flame-engine/flame

- README.md
- doc/gamepad.md
- lib/flame.dart
- lib/gamepad.dart
This PR adds an initial gamepad support on Flame.
Only Android is supported on this PR, I don`t think iOs support will be possible only using the resources provided by flutter, therefore some native code will be needed.
On Android all keys except the axes are supported, which I guess will also require native code.
> Initial Gamepad support

- CHANGELOG.md
- lib/game.dart
- pubspec.yaml
I had an issue where when switching between two different game widgets, the widget would not change. e.g.
* _onGameOver is a method called when the user finishes that minigame
```dart
class GamePageState extends State<GamePage> {
int _nextGame = 0;
MyBaseGame _currentGame;
List<String> games = <String>['Game1', 'Game2'];
@override
void initState() {
super.initState();
_currentGame = _genGame(games[_nextGame++]);
}
void _onGameOver(double seconds) {
if (_nextGame >= games.length) {
// Do something
} else {
setState(() {
_currentGame = _genGame(games[_nextGame++]);
});
}
}
MyBaseGame _genGame(String gameName) {
switch (gameName) {
case 'Game1':
return Game1(onGameOver: _onGameOver);
case 'Game2':
return Game2(onGameOver: _onGameOver);
default:
throw UnimplementedError();
}
}
@override …
```
> Fix widget change

- lib/animation.dart
This PR fixes the following error when using `Animation.spriteList`
```
Dart Error: Unhandled exception:
type 'MappedListIterable<Sprite, Frame>' is not a subtype of type 'List<Frame>'
```
> Fix type error

- lib/animation.dart
Disclaimer: Hello! This is my first PR to this repository, hope it is useful.
I was implementing [flame-example](https://github.com/luanpotter/flame-example) with the latest release of Flame (0.9.4), and the `Animation.lifeTime` property doesn't exists anymore. I tried swapping with the `.clock` property, but I think it changed semantics to count the elapsed time since last frame, so I ended up creating another property, `.ellapsed`, to indicate how long (in seconds) an animation has been running. This allows flame-example to work again.
> Add elapsed time to Animation

- pubspec.yaml
Avoiding conflict with other packages (in my specific case, `cached_network_image`)
> Bump synchronized to 2.1.0

- .travis.yml
- README.md
- pubspec.yaml
This PR updates flutter_svg to its latest version, those breaking changes that were on flutter's master channel has already landed on dev channel, so we can now upgrade it.
This also fixes the package version, and flutter version requirement on pubspec for the develop branch, which was still outdated. And updates the README with information regarding Flame's version requirement.
> Upgrading flutter_svg and fixing version on pubspec for developer branch

- CHANGELOG.md
- README.md
- lib/svg.dart
- pubspec.yaml
Both svg and flare examples worked like a charm.
> Downgrading Flame support to stable channel (1.5.4-hotfix.2)

- README.md
- lib/svg.dart
- pubspec.yaml
This PR updates Flame to work with the latest Flutter stable version.
> Updating Flame to support last stable version (1.7.8+hotfix.2)

- doc/README.md
- doc/box2d.md
This may not be the optimal documentation for box2d, but it tries to at least fill the gap of no Docs at all.
Solves #47
> Adding a simple doc for box2d on Flame

- CHANGELOG.md
- lib/components/animation_component.dart
Apparently the new `destroyOnFinish` flag was breaking when an `AnimationComponent` was created by the `empty` constructor.
> AnimationComponent.empty was breaking

- README.md
- doc/animation_widget_article/article.md
- doc/audio.md
- doc/components.md
- doc/game.md
- doc/images.md
- doc/palette.md
Since Dart 2 the `new` keyword is no longer needed since it is implicit.
> Remove new keyword from docs examples

- CHANGELOG.md
- doc/images.md
- lib/components/animation_component.dart
- lib/components/component.dart
- lib/sprite.dart
- lib/util.dart
This is a simple PR that adds a new parameter to the renders methods of the Sprite class.
Although the Sprite class already have a paint attribute, sometimes you may want to change it just for a single render, in my opinion having a parameter for that is more convenient than setting the attribute, rendering the sprite and reseting the attribute.
You can see an usage of this need on this feature: https://github.com/fireslime/bounce_box/commit/a638e6f1bfb4722f062dea09e0c8a6c6cd2570a9#diff-d02dcf32571d773232d836d3c98753e1R46
I wanted to use a color filter to make some sprites darker like you can see on the following image:
> Adding override paint method to Sprite

- FAQ.md
This PR adds another section to the FAQ and to begin it, adds some info about the change on Flutter that broke some of our examples.
> Adding Common exceptions section to FAQ

- doc/util.md
While I was reading the [util documentation](https://github.com/Felithium/flame/blob/master/doc/util.md) I saw an error in the timer examples. In both examples ```MyGame``` extends ```MyGame```, but ```MyGame``` should probably inherit from ```Game```. (or maybe ```BaseGame```?)
```dart
...
class MyGame extends MyGame {
...
```
changed to
```dart
...
class MyGame extends Game {
...
```
<br>
While I was at it I fixed the **imports**. Now the code can by executed right away after copying.
<br>
When you run the **'Interval example'** you will see the following:
But nothing is changing. I doubt that is the intended behaviour. Correct me if I am wrong.
**Edit: Fixed it by updating the timer object.**
<br>
When I run the **'Countdown example'** it works as intended but the displayed time does …
> added missing imports & fixed inheritance in timer examples

- CHANGELOG.md
- FAQ.md
- README.md
- doc/examples/gestures/.gitignore
- doc/examples/gestures/.metadata
- doc/examples/gestures/README.md
- doc/examples/gestures/lib/main.dart
- doc/examples/gestures/pubspec.yaml
- doc/input.md
- lib/game.dart
- lib/gestures.dart
- lib/util.dart
This is WIP, on this PR I am proposing a new way of handling Gestures on Flame game, and deprecate the old method, which was leading to problems. Hopefully, this can solve #174 #164 #157 and #156 
If this gets approved, I will add all the others detectors provided by the GestureDector widget, not only the tap.
A note about the container: I had some problems with the `GestureDetector` when the game was not in a Container, and when inside a Container, if the Container had no background color, some detectors, like the pan, did not worked, not idea why, so, to keep the old behaviour, I set the background color to black.
> New gesture detector api

- lib/components/text_component.dart
As per issue #213 the `TextComponent` is currently not optimized properly and it does a text layout on every frame render. This PR optimizes the component by only doing layouts when the text or the config changes.
> TextComponent optimization

- lib/components/animation_component.dart
Because the default type of a property is dynamic, an error will be prompted when assigning an int type.
```
type 'int' is not a subtype of type 'double'
```
> amend type for width and height property

- lib/components/composed_component.dart
Today when I used `FlareComponent` to create a Flare animation, the console prompts the following error log.
```
════════ Exception caught by rendering library ════════
The following NoSuchMethodError was thrown during paint():
The method 'render' was called on null.
Receiver: null
Tried calling: render(Instance of 'Canvas', x: 0.0, y: 0.0)
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      FlareComponent.render (package:flame/components/flare_component.dart:35:21)
#2      ComposedComponent._renderComponent (package:flame/components/composed_component.dart:55:7)
#3      ComposedComponent.render.<anonymous closure> (package:flame/components/composed_component.dart:47:34)
#4      IterableMixin.forEach …
```
> Check if the component has been successfully loaded before rendering

- CHANGELOG.md
- doc/examples/with_widgets_overlay/lib/example_game.dart
- doc/examples/with_widgets_overlay/lib/main.dart
- doc/examples/with_widgets_overlay/lib/main_dynamic_game.dart
- doc/examples/with_widgets_overlay/pubspec.yaml
- lib/game/widget_builder.dart
Widget Overlay was missing its key, so the State was been reused over many number of instances, which was causing a lot of issues when multiple game isntances were used.
Fixes #265
> Fixing Widget Overlay usage over many game instances

- CHANGELOG.md
- lib/game/game.dart
When using `BaseGame#addLater`, `onMount` on Component was not called, causing problematic behaviours.
> Fixing addLater component lifecycle

- lib/game/game.dart
- lib/game/game_loop.dart
I added a `GameLoop` class which abstracts the game loop from `GameRenderBox`, to clean things up a bit.
Functionwise it should be the same. I do now check for `running` instead of `attached` in `GameLoop._tick`, but i think it should work the same.
A callback is passed for updates.
> Added game loop abstraction for GameRenderBox

- CHANGELOG.md
- lib/game/game_loop.dart
- lib/game/game_render_box.dart
Simplify the `GameLoop` class using a [Ticker](https://api.flutter.dev/flutter/scheduler/Ticker-class.html).
I believe it's essentially doing the same as before as it is an abstraction on `SchedulerBinding.scheduleFrameCallback`.
But please do some testing..
> Simplify GameLoop using a Ticker

- CHANGELOG.md
- lib/game/base_game.dart
This fixes a bug happening on the current version of BGUG. Components may try to access gameRef inside the resize method and it could sometimes file.
> Fixes games trying to use gameRef inside the resize function

- CHANGELOG.md
- docs/examples/animations/.gitignore
- docs/examples/aseprite/.gitignore
- docs/examples/aseprite/lib/main.dart
- lib/assets_cache.dart
Adding a simple method to load binary files from the assets, and caching it, I need this for the the Fire Atlas package, as the atlases will be exported in a binary format to save space.
> Adding AssetsCache.readBinaryFile

- CHANGELOG.md
- doc/examples/gestures/lib/main.dart
- doc/examples/gestures/lib/main_tapables.dart
- doc/input.md
- lib/components/mixins/tapable.dart
- lib/game/base_game.dart
- lib/game/widget_builder.dart
- lib/gestures.dart
- test/composed_component_test.dart
Tapable components support was causing some issues. Since it made BaseGame use the `MultiTouchTapDetector` it was preventing any other simple detector to work on BaseGame, as multi touch detectors always wins the arena over single touch detectors.
In addition to that, it caused conflicts if the user used the `MultiTouchTapDetector` mixin on the base game class, causing a lot of confusion.
Now, `Tapable` support on BaseGame is enable by the `HasTapableComponents` mixin, and it is directly hooked on the widget builder class, so no more conflicts exists, and the developer can use both `Tapable` components, and have `MultiTouchTapDetector` events on their game.
Fixes #199
If something is unclear, please submit the PR anyways and ask about what you …
> Fixing Tapable conflicts

- CHANGELOG.md
- pubspec.yaml
The previous version of Flutter SVG apparently doesn't work with flutter web for some reason.
> Upgrade Flutter SVG to fix for flame web

- CHANGELOG.md
- lib/box2d/box2d_component.dart
Box2DComponent doesn't currently respect render priority, this is a quick fix for it.
> Fix Box2DComponent render priority

- .github/workflows/test.yml
- CHANGELOG.md
- doc/examples/.gitignore
- doc/examples/with_widgets_overlay/lib/main_dynamic_game.dart
- lib/components/tiled_component.dart
- lib/svg.dart
- pubspec.yaml
Upgrade tiled and flutter_svg dependencies.
> Upgrade tiled and flutter_svg dependencies.

- scripts/lint.sh
- test/has_game_ref_test.dart
- test/resizable_test.dart
This PR changes the linter script to have a more consistent result when the it is ran on the CI and on our own development machines.
I was also going to change the flutter format to the dart format command, but they seems to be removing the deprecating warning from the command, so I decided to keep it, more here: https://github.com/flutter/flutter/pull/58817
Also, apparently, flutter analyze is very smart, and it will find issues inside the `docs/examples folder`, so it is faster now and we don't need to detect which example were changed.
> Moving to flutter analyze instead of dartanalayzer, which was causing confusion

- CHANGELOG.md
- doc/effects.md
- doc/examples/effects/combined_effects/lib/main.dart
- lib/effects/combined_effect.dart
- lib/effects/effects.dart
- lib/effects/move_effect.dart
- lib/effects/rotate_effect.dart
- lib/effects/scale_effect.dart
- lib/effects/sequence_effect.dart
Introduces an onComplete callback for effects
Fixes #336 
>  onComplete callback for effects

- doc/examples/cleanup.sh
Improving the cleanup script to also delete the .dart_tools folder. Though apparently small this really stacks up with the number of examples we have, and this will free a few hundred MBs in total.
> Improve cleanup script to shed a few hundred MBs

- CHANGELOG.md
- lib/game/base_game.dart
Add mustCallSuper to BaseGame. All implementations of Base Game should at some point call the super of render and update to make sure the components are rendered/updated.
Fixes #431 
> Add mustCallSuper to BaseGame

- CHANGELOG.md
- doc/debug.md
- lib/fps.dart
- lib/fps_counter.dart
- lib/game/base_game.dart
Moved the FPS code to its own mixin so people can use it with the `Game` class instead of having to extend from `BaseGame` when they dont use components.
> Move fps to mixin

- CHANGELOG.md
- doc/examples/particles/lib/main.dart
- lib/images.dart
Flame image autoloading and caching was loading an image into the memory multiples times when it was called in sequence, for example, on the following code
```dart
Random r = Random();
int objectCount = 100;
while (objectCount-- > 0) {
add(
// TestComponent is a SpriteComponent where is sprite is autoloaded by flame (i.e: super.square(100, 'ember.png'));
TestComponent()
..x = screenSize.width * r.nextDouble()
..y = screenSize.height * r.nextDouble()
..anchor = Anchor.center
);
}
```
This would make the fetch to memory been called 100 times, since the async load had not finished yet when the next iteration happens.
This PR fixes that, now, it is called only once.
This don't fixes the current perfomance issue we are facing on 1.20.x, but this is a nice, small fix so flame don't put things …
> Improving image autoloading

- doc/examples/cleanup.sh
The cleanup script wasn't cleaning the nested examples we have.
Just the effects example folder is 1.2 GB w/o cleanup.
This might be a bit aggressive as it would delete folders called build, test, inside the srcs of examples but I think that will never be a problem since examples are very small.
> Fix cleanup

- CHANGELOG.md
- lib/fps_counter.dart
- lib/game/game.dart
- lib/game/game_render_box.dart
Changed the way the FPS gets calculated, instead of using the delta values from the update loop I am using `WidgetsBinding.instance.addTimingsCallback`, Flutter calls this with a list of `FrameTiming` which we can use to calculate the FPS value. 
This does mean that it is no longer required to return `true` in `recordFPS` because the values will always get recorded by Flutter. It also means that `recordDt()` will no longer have any purpose, but I kept it in, in case someone is using it for something else. 
Quite from the Discord:
> Well I do think it is more accurate. For instance in my 3D game I noticed the flame FPS sometimes dropped to 29.90 and then back to 60 within a single frame. Which is strange for that to happen in a single frame. With my variant I can see it dropping to 48 and …
> Improved the accuracy of the `FPSCounter` by using Flutter's internal frame timings.

- CHANGELOG.md
- README.md
- doc/box2d.md
- pubspec.yaml
Remove Box2D as a dependency of Flame.
It is based on the vector2d-unification2 branch, so that needs to be merged first.
> Remove Box2D dependency

- lib/game/game_render_box.dart
We are calling an intentionally deprecated method to avoid a breaking change on the develop for the FPS improvement. But that has broke our CI build. I am adding an ignore on that line as we can't fix this otherwise without adding a breaking change. This will be automatically solved on v1 when we remove all the deprecated methods.
> Fixing linter on develop

- CHANGELOG.md
- FAQ.md
- doc/examples/debug/lib/main.dart
- doc/examples/joystick/lib/player.dart
- lib/components/component.dart
- lib/components/joystick/joystick_component.dart
- lib/components/mixins/resizable.dart
- lib/components/parallax_component.dart
- lib/components/position_component.dart
- lib/components/text_box_component.dart
- lib/game/base_game.dart
- test/components/composed_component_test.dart
- test/components/resizable_test.dart
There is a confusion between what is a component size and a game viewport size. 
`PositionComponent` now has the size property, that obviously refers to the size of the component not the size fo the game viewport. 
Ant then we have `Resizable`, a (should be) mixin for components that keeps track of the game viewport size by storing its value on a also named `size` property. 
Using `PositionComponent` alongside `Resizable` leads to a bug. 
Solution proposed:
- Make clear that `.resize` on components are about the game viewport size, not about the component size. Renaming it to `onGameResize`.
- Make `Resizable` have a gameSize property instead of `size`.
- Remove the concern of having
> Fix resizable conflict

- CHANGELOG.md
- doc/effects.md
- doc/examples/effects/sequence_effect/lib/main.dart
- lib/components/component.dart
- lib/components/position_component.dart
- lib/effects/combined_effect.dart
- lib/effects/effects.dart
- lib/effects/move_effect.dart
- lib/effects/sequence_effect.dart
Currently we only support effects for `PositionComponent`, but in theory an effect can run on any component, this PR generalizes the API so it opens up that possibility.
> Generalize effects so that they can be used on all components

- CHANGELOG.md
- doc/effects.md
- doc/examples/effects/combined_effects/lib/main.dart
- doc/examples/effects/infinite_effects/lib/main.dart
- doc/examples/effects/sequence_effect/lib/main.dart
- doc/examples/effects/simple/lib/main_move.dart
- lib/components/component.dart
- lib/components/position_component.dart
- lib/effects/combined_effect.dart
- lib/effects/effects.dart
- lib/effects/move_effect.dart
- lib/effects/sequence_effect.dart
There are some general bug fixes for the effects, but the main thing is that the MoveEffect now takes a list of Vector2 that it goes through, instead of just one position.
Fixes #395
> Use a Vector2 path for MoveEffect

- CHANGELOG.md
- doc/effects.md
- doc/examples/effects/combined_effects/lib/main.dart
- doc/examples/effects/infinite_effects/lib/main.dart
- doc/examples/effects/sequence_effect/lib/main.dart
- doc/examples/effects/simple/lib/main_move.dart
- doc/examples/joystick/lib/player.dart
- doc/examples/particles/lib/main.dart
- lib/components/component.dart
- lib/components/joystick/joystick_component.dart
- lib/components/particle_component.dart
- lib/components/position_component.dart
- lib/components/sprite_batch_component.dart
- lib/components/timer_component.dart
- lib/effects/combined_effect.dart
- lib/effects/effects.dart
- lib/effects/move_effect.dart
- lib/effects/rotate_effect.dart
- lib/effects/sequence_effect.dart
Fixes two effects bugs, one with the relative rotation ending in the wrong angle and one with the `CombinedEffect` resulting in NPE when using it inside a `SequenceEffect`.
Also contains:
* Generalize effects so that they can be used on all components #484 
* Use a Vector2 path for MoveEffect #482 
Fixes #463
> Fix effects bugs, use Vector2 path for MoveEffect and generalize effects

- .github/workflows/test.yml
- CHANGELOG.md
- doc/examples/animation_widget/lib/main.dart
- doc/examples/isometric/lib/main.dart
- lib/components/isometric_tile_map_component.dart
- lib/components/sprite_animation_component.dart
- lib/components/sprite_component.dart
- lib/nine_tile_box.dart
- lib/sprite.dart
- lib/sprite_animation.dart
- lib/spritesheet.dart
- lib/widgets/nine_tile_box.dart
- lib/widgets/sprite_widget.dart
Fixes the issue with Sprite crashing in the constructor if it doesn't get the optional position argument.
(Also converts size to Vector2 where it makes sense)
> Utilize Vector2 for Sprite

- analysis_options.yaml
- lib/components/joystick/joystick_action.dart
- lib/components/mixins/resizable.dart
- lib/components/parallax_component.dart
- lib/components/position_component.dart
- lib/components/sprite_animation_component.dart
- lib/components/sprite_component.dart
- lib/components/text_box_component.dart
- lib/components/timer_component.dart
- lib/effects/combined_effect.dart
- lib/effects/rotate_effect.dart
- lib/extensions/offset.dart
- lib/extensions/rect.dart
- lib/extensions/size.dart
- lib/extensions/vector2.dart
- lib/game/game.dart
- lib/gestures.dart
- lib/keyboard.dart
- lib/layer/layer.dart
- lib/particles/animation_particle.dart
- lib/particles/image_particle.dart
- lib/sprite_batch.dart
- lib/spritesheet.dart
- lib/text_config.dart
- lib/widgets/animation_widget.dart
- lib/widgets/sprite_widget.dart
This is a followup to @spydon 's comment here: https://github.com/flame-engine/flame/pull/469#discussion_r492371603
I updated my plugin to standardize `./foo` imports into `foo`.
Would be good to have a linter rule for imports so we don't get so much inconsistency, specially between relative/absolute imports that cause hard to debug problems.
> Followup fix imports with new version of vscode-dart-import

- CHANGELOG.md
- lib/extensions/vector2.dart
Exports the whole vector_math library so that the users won't have troubles with doing the imports.
Fixes #507
> Export the full vector math library

- CHANGELOG.md
- doc/text.md
- lib/text_config.dart
Add lineHeight property to textConfig (pass through to https://api.flutter.dev/flutter/painting/TextStyle/height.html) so people can specify lineHeight. 
Example:
without property
with property with value 1.5
> Add lineHeight property to TextConfig

- CHANGELOG.md
- doc/game.md
- lib/game/base_game.dart
- lib/game/game.dart
- lib/game/game_render_box.dart
- test/components/resizable_test.dart
Rename resize method on the Game to onResize.
Fixes #517 
> Rename resize method on the Game to onResize

- CHANGELOG.md
- example/lib/main.dart
- lib/components/position_component.dart
- lib/game/base_game.dart
- test/base_game_test.dart
- test/components/composed_component_test.dart
Suggested simplification of BaseGame.
I don't think the user needs to be aware from the names of the methods that the components aren't added/removed directly, and if they need to modify the components list directly they can still easily do so.
> Simplify BaseGame interactions

- CHANGELOG.md
- doc/components.md
- doc/examples/animations/lib/main.dart
- doc/images.md
- doc/particles.md
- lib/components/component.dart
- lib/components/joystick/joystick_component.dart
- lib/components/parallax_component.dart
- lib/components/particle_component.dart
- lib/components/position_component.dart
- lib/components/sprite_animation_component.dart
- lib/components/timer_component.dart
- lib/game/base_game.dart
- lib/particle.dart
- test/base_game_test.dart
I think it is a bit confusing for the user to have `destroy` returning a boolean to mark it for removal, since destroy is a verb.
This change also unifies that there is no difference in whether `onRemove` (`onDestroy` before) is called if the component is removed from within or from the `BaseGame` instance.
> Unify naming standard for removal of components

- lib/game/widget_builder.dart
When applying advanced gesture detectors on `WidgetBuilder` we create a duplicated code and never do anything with the `child` param on  `_applyAdvancedGesturesDetectors`. This PR fixes that
> Fix advanced gesture detector duplicated code

- lib/game/embedded_game_widget.dart
`EmbeddedGameWidget` has a size attribute that is never used nor set. 
> Remove unused size field on Embedded widget

- CHANGELOG.md
- lib/components/position_component.dart
In web debug stoke not worked. strokeWidth required. See flutter/flutter#49328
Bug fix (non-breaking change which fixes an issue)
> fix _debugPaint stroke width for web

- lib/game/game_render_box.dart
- lib/game/widget_builder.dart
We have this unused offset field on our game render box, this PR removes it.
> Remove unused offset

- lib/assets/assets_cache.dart
This simplifies AssetsCache code a bit.
The code is extracted from #549 in an attempt to make the null safety changeset smaller.
> 🚨 Use constructors in classes inherited from `_Asset`

- CHANGELOG.md
- doc/components.md
- doc/examples/gestures/lib/main_overlapping_tapables.dart
- doc/examples/gestures/lib/main_tapables.dart
- doc/images.md
- doc/text.md
- lib/components/base_component.dart
- lib/components/component.dart
- lib/components/mixins/tapable.dart
- lib/components/particle_component.dart
- lib/components/position_component.dart
- lib/effects/effects.dart
- lib/effects/effects_handler.dart
- test/base_game_test.dart
- test/components/composed_component_test.dart
- test/components/position_component_test.dart
This is a work in progress and I'm happily taking in comments to improve it, or scrap it.
It changes the way that we propagate to children.
The events (now the different tap functions) return a boolean so that the user can choose if the event should propagate further or not.
> Take angle into account for taps and propagate to children differently

- CHANGELOG.md
- doc/examples/layers/lib/main.dart
- doc/examples/sprites/lib/main_base64.dart
- doc/util.md
- lib/components/isometric_tile_map_component.dart
- lib/components/joystick/joystick_action.dart
- lib/components/joystick/joystick_directional.dart
- lib/components/joystick/joystick_utils.dart
- lib/particles/animation_particle.dart
- lib/particles/sprite_particle.dart
- lib/sprite.dart
- lib/util.dart
- lib/widgets/nine_tile_box.dart
- lib/widgets/sprite_button.dart
We had quite a few methods for rendering Sprites. I unified them all into a single signature with good parameters.
Also made Flame.util methods related to rendering more consistent and useful.
Also some small refactorings on Joystick stuff to use the new render methods more easily.
> Unify multiple render methods on Sprite

- CHANGELOG.md
- lib/sprite_animation.dart
When creating SpriteAnimationComponent from SpriteAnimationData, the SpriteAnimationData.loop is not passed out to SpriteAnimationComponent. As a result, if you specify SpriteAnimationData.loop=false, you will still see the animation loops in apps.
> Passing SpriteAnimationData.loop out when constructing SpriteAnimationComponent

- CHANGELOG.md
- lib/effects/effects.dart
Right now an effect resets all the properties of a position component when it is done, it should only reset the once it has affected.
For example a ScaleEffect will reset the position of the PositionComponent when it is done.
> Effect shouldn't affect non-used properties

- CHANGELOG.md
- lib/effects/combined_effect.dart
- lib/effects/effects.dart
- lib/effects/move_effect.dart
- lib/effects/rotate_effect.dart
- lib/effects/scale_effect.dart
- lib/effects/sequence_effect.dart
Forgot that in the cases where isAlternating = true, endPosition and originalPosition will be the same
> Explicitly set what the effect modifies

- CHANGELOG.md
- lib/game/game_render_box.dart
Flutter 1.25+ added a new method on RenderBox that needs to be implemented, this PR adds the method.
Flutter stable still don't have that new method, but since it was a method addition, flutter stable will continue to work fine, we just may get some lint warning when this version leave a pre release.
Either way, this change was tested on both stable and beta channel
> Fixing Game Render Box for flutter >= 1.25

- CHANGELOG.md
- lib/components/base_component.dart
This adds the compare function to the children getter on `BaseComponent` as it throws a TypeError since Components are not themselves comparable without that. I didn't log an issue for it since this is a simple change.
> Fix issue in BaseComponent where addChild results in a TypeError

- .github/workflows/test.yml
- CHANGELOG.md
Since the develop branches don't exist anymore, remove the reference to them in the github workflow file.
> Remove develop branches from test

- CHANGELOG.md
- lib/components/base_component.dart
The BaseComponent children getter should return an immutable data structure.
> BaseComponent should return immutable chlidren iterable

- CHANGELOG.md
- lib/game/game_widget.dart
I think errors should not be swallowed, that is a really bad practice. I was very against this when we first discussed, but now that I fell ill of the consequence myself (and took me longer than it should to realize what was going on), I have become vehemently against.
onLoad exceptions should be re-thrown.
This is what it looks like with this change:
You still get the option to provide an error handler but now the handler is aware of what the error was. If you do not, the exception is re-thrown as anyone would except.
Before if a handler was not provided (and it was optional) the exception was completely swallowed and not logged, seem, expressed anywhere. And you got a black screen from an empty game. Also even if you wanted to add a custom handler you would not know what went wrong, …
> Improve error handling for onLoad

- CHANGELOG.md
- lib/components/base_component.dart
BaseComponent never actually removes children marked for removal, so calling `child.remove()` has no effect.
> BaseComponent removes children marked as shouldRemove during update

- CHANGELOG.md
- lib/sprite_animation.dart
While porting the aseprite example to our new [examples repo](https://github.com/flame-engine/flame_example/blob/master/lib/examples/aseprite.dart) I noticed that one wasn't work; this should fix it.
> Fix aseprite constructor bug

- CHANGELOG.md
- lib/timer.dart
Non-repeating Timers never fire their callback. This is making Particle lifespans (which use a Timer internally) not ever fire their end callback, so Particles with a lifespan never auto-remove.
> Ensure non-repeating Timer callback fires

- CHANGELOG.md
- doc/debug.md
- doc/examples/composability/lib/main.dart
- doc/examples/debug/lib/main.dart
- doc/examples/particles/lib/main.dart
- lib/game/base_game.dart
Allows for simpler activation mid-game, and also follow the standard we have for `BaseComponent`.
> Debug mode to be variable on BaseGame

- README.md
Very small change, the current readme is pointing to rc4 instead of rc5.
We should do a latest tag that it can point on instead.
> Update README to point at rc5

- CHANGELOG.md
- doc/examples/widgets/lib/main.dart
Changed `parseAnchor` in `examples/widgets` to throw an exception instead of returning null when it cannot parse an anchor name
Fixes #607 
> 👌 Throw exception from `parseAnchor` in `examples/widgets` instead of returning null

- CHANGELOG.md
- doc/examples/animations/lib/main.dart
- doc/examples/aseprite/lib/main.dart
- doc/examples/render_flip/lib/main.dart
- doc/examples/spritesheet/lib/main.dart
- lib/components/sprite_animation_component.dart
- lib/components/sprite_component.dart
SpriteComponent and SpriteAnimationComponent had a similar behavior on allowing an empty initialization, which is very useful because allows the component to load itself using it's `onLoad` method. But they had the constructors using different patterns. This PR simple makes both component follow a similar pattern so it will be easier for the user to use.
After this proposal is accepted I intend on doing a similar thing on all of our components that requires assets, like Parallax, SpriteBatch, etc.
> Making SpriteComponent and SpriteAnimationComponent follow the same standard for empty constructors

- CHANGELOG.md
- lib/components/joystick/joystick_action.dart
Improved code a bit to utilize `Offset` support for `+` and `-` operators.
Fixes #606 
> 👌 Use `Offset` type directly in `JoystickAction.update` calculations

- CHANGELOG.md
- lib/src/components/base_component.dart
- lib/src/components/position_component.dart
- test/components/composed_component_test.dart
Since the children aren't positioned in an absolute manner their gesture detection was off, this is fixed by taking the parent into account recursively.
Fixes #635 
> Fix gesture detection on children

- CHANGELOG.md
- doc/game.md
- lib/src/game/game_widget.dart
> Added a `required` to GameWidget and updated the docs

- CHANGELOG.md
- doc/examples/sprite_batch/lib/main_auto_loading.dart
- doc/images.md
- lib/src/components/sprite_batch_component.dart
Making SpriteBatchComponent constructor be more in the standard followed by SpriteComponent and SpriteAnimationComponent allowing a better use of the onLoad method on the component
> Adapting SpriteBatchComponent constructors to other components

- CHANGELOG.md
- doc/examples/timer/lib/main.dart
Flutter has deprecated RaisedButton, so this PR just changes our timer example to use the ElevatedButton instead.
> Migrate RaisedButton -> ElevatedButton

- CHANGELOG.md
- lib/extensions.dart
- lib/image_composition.dart
- lib/src/extensions/color.dart
- lib/src/extensions/image.dart
Follow up PR from https://github.com/flame-engine/flame/pull/646#discussion_r569535816, introducing an image extension and color extension.
I also added a few methods that I personally use, so if any of those are deemed unnecessary in the context of Flame then I am okay with removing them.
> Added Color and Image extensions

- CHANGELOG.md
- lib/src/game/base_game.dart
- lib/src/game/game.dart
- test/base_game_test.dart
- test/components/composed_component_test.dart
- test/components/has_game_ref_test.dart
- test/components/resizable_test.dart
- test/effects/effect_test_utils.dart
Flame could present weird issues when `size` or components which needed the `size` were added on the game constructor.
This PR fixes that by making a verification and failing the execution with a meaningful message.
I haven't gone through all the example to verify if all of then are working correctly to this new verification, but I think it is not worth since we are migrating all the examples.
Fixes #658
> Preventing errors caused by the premature use of size property on game

- CHANGELOG.md
- lib/src/anchor.dart
- test/anchor_test.dart
Anchor should really be an enum, but sadly enums in dart are not as sophisticated as java, so we need a class. However dealing with it was not easy because there was no standard way to treat it like a bounded collection of items, so I am adding some common enum helper methods to Anchor to make that integration easier.
> Make the anchor class look more like an enum

- CHANGELOG.md
- lib/src/anchor.dart
- lib/src/components/position_component.dart
- lib/src/sprite.dart
- lib/src/widgets/sprite_widget.dart
- test/anchor_test.dart
Enables so that the user can define the anchor, not just use our predefined values.
Fixes #674 
> Enable user-defined Anchors

- CHANGELOG.md
- lib/src/components/sprite_component.dart
The children should be rendered after the parent is rendered.
#678 
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
> Fix children render order

- CHANGELOG.md
- lib/src/components/sprite_component.dart
This reverts commit 53f155f1a721bad7875c1ee619294069101f9823.
Since `prepareCanvas` is run from super, we can't simply move super down.
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-re …
> Revert "Fix children render order (#682)"

- CHANGELOG.md
- lib/src/components/base_component.dart
- lib/src/components/component.dart
- lib/src/game/base_game.dart
The parent is today rendered after the children, which clearly is not what you want.
This fixes this by handling rendering of `BaseComponent` slightly different.
#678 
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
> Fix order of parent -> children rendering

- CHANGELOG.md
- lib/src/components/sprite_component.dart
Add `srcPosition` and `srcSize` for `SpriteComponent.fromImage()`, so we can create a `SpriteComponent` with part of an image.
fixes #697 
> #697 - Add srcPosition and srcSize for SpriteComponent

- CHANGELOG.md
- lib/src/components/mixins/hitbox.dart
- lib/src/geometry/collision_detection.dart
The bounding rectangle wasn't cached and it was more expensive to calculate it than necessary. 
> Cache and enlarge bounding rectangle

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/anchor.dart
- packages/flame/lib/src/components/mixins/hitbox.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/geometry/polygon.dart
- packages/flame/lib/src/geometry/shape.dart
- packages/flame/test/components/position_component_test.dart
The default hitbox had a degradation where the input rectangle was off if the anchor wasn't centered
#705
> Fix default hitbox with other anchor than center

- packages/flame/lib/src/game/camera.dart
- packages/flame/test/game/camera_and_viewport_test.dart
Found this bug on camera where if it's not following a component it doesn't respect relative offset, and therefore move doesn't work.
> Fix camera when not following component

- packages/flame/lib/src/game/game_widget.dart
As I mentioned back on the examples migration, the scroll example didn't work. I did some investigating and turns out the bug was incorrect component composition. According to my testing this now works (and also works alongside other detectors like mouse move).
> Fix scroll detector that did not work before

- packages/flame/lib/src/components/isometric_tile_map_component.dart
We decided on a convention as to index the matrix as `matrix[j][i]`; however the `containsBlock` method was using the wrong convention. This fixes it.
> Fix inconsistency on IsometricTileMap

- doc/util.md
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/extensions/canvas.dart
- packages/flame/test/extensions/canvas_test.dart
Specially for debugging, it can be useful to render a single point on the canvas. This adds a simple method to our Canvas extension that takes in a Vector2 and a size, and draws a square with length size. You can also customize the color (default magenta).
> Add a renderPoint extension method on Canvas

- doc/text.md
- examples/lib/stories/camera_and_viewport/follow_object.dart
- examples/lib/stories/collision_detection/multiple_shapes.dart
- examples/lib/stories/components/debug.dart
- examples/lib/stories/rendering/text.dart
- examples/lib/stories/utils/particles.dart
- examples/lib/stories/utils/timer.dart
- examples/lib/stories/utils/timer_component.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/components.dart
- packages/flame/lib/game.dart
- packages/flame/lib/src/components/base_component.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/lib/src/components/text_component.dart
- packages/flame/lib/src/text.dart
This PR does two things:
- Create an abstraction for text rendering on the framework, with this abstraction we can now easily introduce more ways of rendering text on Flame and we can still use the same components with different methods of text rendering.
- Rename the `TextConfig` class to `TextPaint`: I always found it a little confusing that our class for rendering text was named `TextConfig` since it is not only a text configuration, but also a text renderer. I choose `TextPaint` for the new name because that implementation is quite tied to the Flutter's `TextPainter` class, that name was also inspired by the Flutter's duo classes `CustomPainter` and `CustomPaint`.
The most importante part of this PR is the abstraction, the renaming is a proposal, let me know what you think of the …
> Abstracting text API to enable custom renderers

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/base_component.dart
- packages/flame/test/components/composed_component_test.dart
The children should have the same debugMode as their parent, at least initially.
This also fixes the composability example.
> Same debugMode for children as for parent

- doc/collision_detection.md
- examples/lib/stories/collision_detection/collision_detection.dart
- examples/lib/stories/collision_detection/multiple_shapes.dart
- examples/pubspec.yaml
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/mixins/collidable.dart
- packages/flame/lib/src/components/mixins/hitbox.dart
- packages/flame/lib/src/geometry/collision_detection.dart
- packages/flame/lib/src/geometry/shape.dart
- packages/flame/pubspec.yaml
- packages/flame/test/components/collidable_type_test.dart
- packages/flame/test/components/collision_callback_test.dart
Calls `onCollisionEnd` on `Collidable` and `HitboxShape` once a collision is over.
> onCollisionEnd callbacks for Collidable and HitboxShape

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/text_component.dart
Fix anchor for rendered text in `TextComponent`.
The text renderer currently defaults to `topLeft` even though the component has another anchor.
#815 
> Fix anchor for rendered text in TextComponent

- doc/util.md
- packages/flame/CHANGELOG.md
- packages/flame/lib/extensions.dart
- packages/flame/lib/src/extensions/rect.dart
- packages/flame/lib/src/extensions/rectangle.dart
- packages/flame/test/extensions/rect_test.dart
Add support to math.Rectangle to our extensions.
`tiled` uses Rectangles because it is Flutter agnostic, and Rect comes from dart:ui which is only bundled for Flutter.
But in general, I think it's useful to provide converters, similar to how we can easily convert to and from (size, position, offset, dimension) on flutter as vectors. …
> Add support to math.Rectangle to our extensions

- packages/flame/test/components/composed_component_test.dart
- packages/flame/test/effects/effect_test_utils.dart
- packages/flame/test/extensions/vector2_test.dart
- packages/flame/test/util/expect_double.dart
- packages/flame/test/util/expect_vector2.dart
Refactor tests to use expectVector2 and expectDouble.
This fixes a TODO
> Refactor tests to use expectVector2 and expectDouble

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/text_component.dart
- packages/flame/lib/src/game/base_game.dart
- packages/flame/test/components/composed_component_test.dart
- packages/flame/test/text_test.dart
This fixes 3 bugs:
* debug mode is not propagated to children of non-Position components
* size property of TextComponent was not correctly set
* anchor property was being incorrectly passed along to text renderer
> Fix a couple bugs with Text and debugMode

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/shape_component.dart
Add `anchor` for `ShapeComponent` constructor, so we can easily set the anchor.
> Add anchor for ShapeComponent constructor

- examples/.gitignore
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/game_loop.dart
- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/lib/src/game/game_widget/game_widget.dart
Some improvements on our render object widget. 
- Made game loop call dispose on the ticker on detach. 
- Made the render object a repaint boundary, avoid an entire screen that contains a GameWidget to repaint every frame.
- Made the render object itself as expanded enabling the removal of that `RenderConstrainedBox` …
> Add some render box updates

- packages/flame/lib/src/game/game_render_box.dart
Prevent assertion error and make the render object be sized by itself. Not by the parent. 
> Make render object not be sized by parents anymore

- doc/components.md
- packages/flame/CHANGELOG.md
The docs for the `SpriteAnimationComponent` tried to pass a list of futures instead of the materialized result.
https://stackoverflow.com/questions/68265898/the-argument-type-listfuturesprite-cant-be-assigned-to-the-parameter-type/68267088#68267088 …
> Fix SpriteAnimationComponent docs

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/camera.dart
- packages/flame/test/game/camera_and_viewport_test.dart
This PR was initially because I thought that the camera didn't return to its original position after a shake (was reported on discord), but it seems that it is. I fixed some small things (so that we don't create new vectors every tick where it is not needed and renamed shake amount to shake duration) and added a test to ensure that the camera does return to its original position. …
> Rename camera shake amount to duration

- doc/components.md
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/base_component.dart
- packages/flame/lib/src/components/component_set.dart
Since for Forge2D we have to flip the canvas back after the render of a parent is done an empty `postRender` method is added to `BaseComponent` which is overridden by `BodyComponent` in an upcomming PR.
> Add `BaseComponent.postRender`

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/base_component.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame_forge2d/CHANGELOG.md
- packages/flame_forge2d/lib/body_component.dart
Since we now have `postRender` let's follow that standard and rename `prepareCanvas` to `preRender`.
> Rename `prepareCanvas` to `preRender`

- doc/components.md
- packages/flame/CHANGELOG.md
- packages/flame_forge2d/CHANGELOG.md
- packages/flame_forge2d/example/lib/balls.dart
- packages/flame_forge2d/example/lib/composition_sample.dart
- packages/flame_forge2d/example/lib/main.dart
- packages/flame_forge2d/example/lib/position_body_sample.dart
- packages/flame_forge2d/lib/body_component.dart
- packages/flame_forge2d/lib/forge2d_game.dart
- packages/flame_forge2d/pubspec.yaml
Since the `BodyComponent` is flipping the y-axis with basically `canvas.scale(1, -1)` in `prepareCanvas` it needs to be flipped back afterwards so that normal Flame components can be added as children.
> Flip back the canvas Y-axis after render of BodyComponent

- examples/lib/stories/camera_and_viewport/camera_and_viewport.dart
- examples/lib/stories/camera_and_viewport/coordinate_systems.dart
- examples/lib/stories/camera_and_viewport/coordinate_systems.dart.bak
- examples/web/index.html
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/game.dart
- packages/flame/lib/src/gestures/events.dart
- packages/flame/test/components/composed_component_test.dart
- packages/flame/test/util/mock_gesture_events.dart
This fixes the Drag events having incorrect coordinates. Allow me to explain the course of operations for the fix, so the PR makes sense:
1. the root issue is that Flutter pulls a short straw on us. I pointed this out as one argument to do our wraps and tried to explain again on the related issue: local coords are not always available for drag events; from the docs:
```
/// The local position in the coordinate system of the event receiver at
/// which the pointer contacted the screen.
///
/// Defaults to [globalPosition] if not specified in the constructor.
final Offset localPosition;
```
note that they always exist for taps. not sure when drags have it or not, but definitely it's a very common issue.
2. I noticed that we are assuming local as src of truth and converting global; should be …
> Fix coordinate systems and add example

- examples/lib/stories/parallax/component.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/parallax_component.dart
Fix parallax fullscreen bug when game is resized. Before if the game was zoomed out the parallax would be minimized when the game was resized.
- [xj] I am willing to follow-up on review comments in a timely manner.
> Fix parallax fullscreen bug when game is resized

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/input/hud_margin_component.dart
- packages/flame/lib/src/components/mixins/collidable.dart
- packages/flame_forge2d/CHANGELOG.md
- packages/flame_forge2d/lib/position_body_component.dart
- packages/flame_forge2d/lib/sprite_body_component.dart
Add generics to components with `HasGameRef` so that they can be extended and have another `with HasGameRef` on the top level that uses a more specific game than `BaseGame`.
> Generics on components with gameRef

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/test/components/sprite_animation_component_test.dart
Adds a simple attribute to pause the animation component
> Adding playing attribute to animation component

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/test/components/sprite_component_test.dart
When `SpriteComponent` is created without the `size:` parameter, it infers its size from the size of the source image. However, if the source image is a sprite sheet and the user passes `srcSize:`  and `srcPosition:`, then `srcSize` is a much better guess for the sprite's render size.
> SpriteComponent falls back to srcSize instead of image.size

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/sprite_animation.dart
- packages/flame/test/components/sprite_animation_component_test.dart
The code in `SpriteAnimation` used to exit early when it found itself on the last frame with `loop=false`. The new behavior will wait until the last animation frame is ready to roll over to the next frame before deciding to officially stop the animation and call the `onComplete` callback.
Closes #895
> #895 Fix truncated last frame of SpriteAnimation

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/assets/images.dart
To simplify loading all image assets in the specified (or default) path into the cache.
> Function to load all images in prefixed path

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/test/components/sprite_component_test.dart
I noticed that for some reason, if we don't provide an explicit `size` for a `SpriteComponent`, it fallbacks to null. I think there is no reason not to fallback to the `Sprite` original size, if present. Thoughts?
> Default sprite component size to sprite size

- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/test/components/text_box_component_test.dart
Given the new way we use change notifiers for the `size` property to compute transform matrices, it means that the naive way in which `TextBoxComponent` carelessly overwrote that field broke the integration, meaning that the transformations weren't updated properly. This fixes that by actually setting the size and recomputing when needed. Added a test & tested with the example app. …
> Fix TextBoxComponent size computation

- packages/flame/lib/src/test_helpers/mock_canvas.dart
- packages/flame/test/game/camera_and_viewport_test.dart
Due to [this bug](https://github.com/flame-engine/flame-analyze-action/pull/1), we ended up introducing terrible mistakes in our codebase. This will fixes all existing issues in preparation for the action fix to be deployed.
> Fix severe formatting issues across the codebase

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/mixins/collidable.dart
Fix issue that was reported on discord with draggables not being removed properly.
It happened since `parent` had already been set to null at the stage where we were supposed to find the parent with `HasDraggables` and remove it from its list.
> Fix issue with draggables not being removed properly

- packages/flame/CHANGELOG.md
- packages/flame/pubspec.yaml
Users in discord chat (https://discord.com/channels/509714518008528896/516639688581316629/889504224159862834) are reporting compilation errors using older versions of the Flutter SDK. Constrain the Flutter SDK version in the pubspec so that users can clearly see they need to use at least Flutter 2.5.x (which is currently stable).
> increase flutter environment constraint to be at least 2.5.0

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component_set.dart
- packages/flame/lib/src/components/mixins/has_collidables.dart
- packages/flame/lib/src/effects/effects.dart
- packages/flame/test/effects/effect_test_utils.dart
It is no longer necessary to call `ComponentSet.register<T>()` before being able to use `ComponentSet.query<T>()`. The list of components matching `T` will be computed on demand. Note that this does not result in performance degradation, since the amount of work needed to construct the filtered list is the same in both cases. In fact, this approach provides a minor performance benefit in case some of the elements are removed from the ComponentSet before querying, or some type gets queried only on a fraction of the ComponentSets.
> No need to pre-register types in ComponentSet

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/flame_game.dart
- packages/flame_forge2d/CHANGELOG.md
- packages/flame_forge2d/lib/forge2d_game.dart
Since Forge2DGame needs to use another camera we need the possibility to pass in another camera than the default one.
> Possibility to pass in a Camera to FlameGame

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/lib/src/game/game_widget/game_widget.dart
- packages/flame/test/game/game_widget/game_widget_lifecycle_test.dart
Stop running onRemove during onResize (which caused `parent` to be nulled out, causing several issues)
https://github.com/flame-engine/flame/issues/967
https://github.com/flame-engine/flame/issues/977
> Stop running onRemove during resize

- examples/lib/stories/utils/timer_component.dart
- packages/flame/CHANGELOG.md
Clarified `TimerComponent` such that the timers are not rendered on top of each other on double tap.
> clarified TimerComponent example

- examples/lib/stories/camera_and_viewport/follow_object.dart
- examples/lib/stories/collision_detection/circles.dart
- examples/lib/stories/collision_detection/multiple_shapes.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/mixins/collidable.dart
- packages/flame/lib/src/components/mixins/hitbox.dart
- packages/flame/test/components/collidable_type_test.dart
- packages/flame/test/components/collision_callback_test.dart
- packages/flame/test/components/mixins/has_collidable_test.dart
- packages/flame/test/components/position_component_test.dart
- packages/flame_bloc/example/lib/src/game/components/bullet.dart
- packages/flame_bloc/example/lib/src/game/components/enemy.dart
- packages/flame_bloc/example/lib/src/game/components/player.dart
Since you add hitboxes to a component that has the `Hitbox` mixin, it is a weird name for that mixin.
So therefore I'm renaming it to `HasHitboxes` instead, which is in line with many of our other mixins too.l
> Rename Hitbox mixin to HasHitboxes

- examples/lib/stories/utils/timer_component.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/timer.dart
Since `shouldRemove` was overridden it wasn't possible to manually remove the component.
- [xj] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage. …
> Possibility to manually remove `TimerComponent`

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/input/hud_margin_component.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/test/components/hud_margin_component_test.dart
Before the position was only updated from the margin on creation, so when the window was resized the buttons didn't keep the margin to the right/bottom if they had that set. …
> Fix `HudMarginComponent` `onGameResize` bug

- doc/components.md
- examples/lib/stories/widgets/custom_painter_component.dart
- examples/lib/stories/widgets/widgets.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/components.dart
- packages/flame/lib/src/components/custom_painter_component.dart
- packages/flame/test/components/custom_painter_component_test.dart
Adds `CustomPainterComponent`, a component which can help sharing custom rendering logic between Flutter widgets and a Flame game.
https://user-images.githubusercontent.com/835641/139759709-b3b252b9-607c-4cb2-919d-9a9fc008d14e.mov
- [ x I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
Solves: #1028  …
> Adding CustomPainterComponent

- doc/collision_detection.md
- doc/gesture-input.md
- packages/flame/lib/src/components/mixins/collidable.dart
- packages/flame/test/components/mixins/has_collidable_test.dart
Following #1060, this PR fixes the remaining cases where the name `Hitbox` was still used in the docs / error messages.
> Rename Hitbox -> HasHitboxes in the docs

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/lib/src/game/projector.dart
- packages/flame/lib/src/gestures/events.dart
- packages/flame/test/game/projections_test.dart
- packages/flame_forge2d/lib/forge2d_game.dart
I still need to write up an example to showcase this, and maybe some test.
But hopefully this PR is a good starting point for understanding the issue.
Currently we combine both projectos on game (viewport & camera). And say that game `is a Projector`. but for hud elements we ignore that, while we would want to ignore the camera only, and still apply the viewport. So instead I make the game `has` 2 projectors, that way we can use the appropriated one when desired. also change the events to expose both (viewport only, and both). I didn't see any use to expose camera only.
> Fix events + isHud

- doc/components.md
- doc/gesture-input.md
- doc/keyboard-input.md
Apparently we still had some mentions of `BaseComponent` in the docs.
> Remove `BaseComponent` from docs

- examples/lib/stories/sprites/spritesheet.dart
This PR only introduces an example from `createAnimationWithVariableStepTimes`.
This PR is related with [this](https://github.com/flame-engine/flame/pull/1018) PR
https://user-images.githubusercontent.com/29265526/140622016-78207568-fe01-4610-936e-21541bc675f0.mov
> Adding example from sprite animation with variable step time

- examples/lib/stories/effects/effects.dart
- examples/lib/stories/effects/move_effect_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/effects2/move_effect.dart
- packages/flame/test/effects2/move_effect_test.dart
Added new `MoveEffect` class based on `Transform2DEffect`. Compared to the original `MoveEffect`, these are some differences:
- `MoveEffect.to` implements movement towards a specific point in the world;
- `MoveEffect.by` is a relative motion that changes the position of a component by the given offset;
- `MoveEffect.along` is for moving the component along an arbitrary path (which includes curved paths too);
- multiple move effects can be applied to a component at the same time.
Added new example in the Dashbook demonstrating different kinds of move effects.
https://user-images.githubusercontent.com/744771/140383592-36a9c090-f6f8-40a9-804e-cb405d29d89d.mp4
Replaces #1031
> Move effects

- packages/flame/test/components/hoverable_test.dart
- packages/flame/test/components/hud_margin_component_test.dart
- packages/flame/test/components/joystick_component_test.dart
- packages/flame/test/components/mixins/has_collidable_test.dart
- packages/flame/test/components/priority_test.dart
- packages/flame/test/effects2/effect_test.dart
- packages/flame/test/effects2/transform2d_effect_test.dart
- packages/flame/test/game/game_widget/game_widget_drag_test.dart
- packages/flame/test/game/game_widget/game_widget_pause_test.dart
- packages/flame/test/game/game_widget/game_widget_tap_test.dart
- packages/flame/test/game/game_widget/game_widget_test.dart
- packages/flame_bloc/test/flame_bloc_game_test.dart
- packages/flame_test/example/test/flame_test_test.dart
- packages/flame_test/lib/src/flame_test.dart
<details>
<summary> ~~first proposal~~ </summary>
Proposal: make the createGame provider for the `flameTest` optional.
Advantages: cleaner, simpler for most use cases.
Disadvantages: not as type safe because if converts a compile error to a runtime error if T != Game (and dart doesn't have overloading).
Other option would be to create a new method where T===FlameGame and it calls this one (but would need to have a different name).
</details>
So I came up with a better idea. It came to me that from all the parameters required to run a test, there are two types:
* name and actually test -> these are of course always unique per test. can't have a test with duped name or code
* everything else -> these most commonly have a single value, if not for the entire application, at least for a set of …
> Improved testing API

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/test/game/base_game_test.dart
Fixes a typo in an error message ("ot" should be "or").
> Fix typo in error message

- packages/flame/lib/src/components/text_box_component.dart
Documentation fixes. For `dismissDelay` property the doc said the default was 9, whereas in fact it was 0, so fixed that as well.
> Fix typos & grammar in TextBoxComponent docs

- doc/collision_detection.md
- doc/components.md
- doc/text.md
- examples/lib/commons/square_component.dart
- examples/lib/stories/camera_and_viewport/follow_object.dart
- examples/lib/stories/collision_detection/circles.dart
- examples/lib/stories/collision_detection/collidable_animation.dart
- examples/lib/stories/collision_detection/collision_detection.dart
- examples/lib/stories/collision_detection/multiple_shapes.dart
- examples/lib/stories/collision_detection/only_shapes.dart
- examples/lib/stories/collision_detection/simple_shapes.dart
- examples/lib/stories/effects/move_effect.dart
- examples/lib/stories/effects/move_effect_example.dart
- examples/lib/stories/effects/remove_effect_example.dart
- examples/lib/stories/input/joystick.dart
- examples/lib/stories/input/joystick_advanced.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/mixins/hitbox.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/components/shape_component.dart
- packages/flame/lib/src/extensions/vector2.dart
- packages/flame/lib/src/geometry/circle.dart
- packages/flame/lib/src/geometry/line_segment.dart
- packages/flame/lib/src/geometry/polygon.dart
- packages/flame/lib/src/geometry/shape.dart
- packages/flame/test/components/joystick_component_test.dart
- packages/flame/test/components/shape_component_test.dart
- packages/flame/test/game/base_game_test.dart
- packages/flame_rive/example/lib/main.dart
The hitboxes didn't take the full ancestor tree of the parent component into consideration, now they do (except for multiple scales).
> `ShapeComponent` and `Hitbox` to take transform of parents full ancestor tree into consideration

- .gitignore
Following the discussion in #1092, this PR adds `Makefile` to the `.gitignore` file, so that developers who want to, can have one, without having to commit it to the project.
> Added Makefile to .gitignore

- doc/_sphinx/conf.py
- doc/collision_detection.md
- doc/components.md
- doc/other-inputs.md
- doc/oxygen.md
- doc/widgets.md
This fixes all the warnings that were produced when generating the documentation:
```
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:72: WARNING: 'myst' reference target not found: #Shapes
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:113: WARNING: 'myst' reference target not found: #ScreenCollidable
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:169: WARNING: 'myst' reference target not found: #Polygon
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:169: WARNING: 'myst' reference target not found: #Rectangle
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:169: WARNING: 'myst' reference target not found: #Circle
/Users/stpasha/github/st-pasha/flame/doc/collision_detection.md:185: WARNING: 'myst' reference …
```
> Fix documentation warnings

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame_forge2d/lib/body_component.dart
Methods `preRender()` and `postRender()` needlessly complicate Flame's pipeline, and can actually be removed without loss of functionality and with a gain to simplicity. Specifically, if a class currently overrides `preRender/postRender`, that class can replace both methods with
```dart
@override
void renderTree(Canvas canvas) {
... preRender code
super.renderTree(canvas);
... postRender code
}
``` 
I have currently marked the two methods as deprecated, however if any project is currently uses them, they will not lose any functionality, and will only see a warning. It is up to the team whether we want to:
- keep them deprecated until the version 1.0; or
- remove the deprecated status, allowing external users to keep using them without any warnings; or
Before you create this PR confirm …
> Deprecate preRender/postRender

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/position_component.dart
- packages/flame/test/components/position_component_test.dart
Since it wasn't taken into regard whether it was already flipped or not before if changed position when trying to flip back.
> Fix `flipHorizontallyAroundCenter` and `flipVerticallyAroundCenter`

- examples/lib/stories/effects/effects.dart
- examples/lib/stories/effects/old_size_effect_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/effects2/component_effect.dart
- packages/flame/lib/src/effects2/size_effect.dart
- packages/flame/lib/src/effects2/transform2d_effect.dart
- packages/flame/test/effects2/size_effect_test.dart
- packages/flame/test/effects2/transform2d_effect_test.dart
Since the `Transform2DEffect` could be used here I created a more general `ComponentEffect`.
> Added the `SizeEffect` and a general `ComponentEffect`

- examples/lib/stories/effects/effects.dart
- examples/lib/stories/effects/old_opacity_effect_example.dart
- examples/lib/stories/effects/opacity_effect_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/mixins/has_paint.dart
- packages/flame/lib/src/effects2/component_effect.dart
- packages/flame/lib/src/effects2/opacity_effect.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
- packages/flame/test/effects2/opacity_effect_test.dart
- packages/flame_test/lib/src/expect_double.dart
The `OpacityEffect` is a bit tricky to compose since the opacity only is stored in 8 bits, so it can get pretty big numeric discrepancies, so we have to accumulate the rounding errors.  …
> `OpacityEffect` in the new effects engine

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/camera/viewport.dart
I am porting Gravity Runner (aka Gravitational Waves) to the latest Flame.
I think it will be very good to have a fully functional, complete big game example before release.
Most of it was painless or even deleting stuff that we had incorporated from GR to Flame (like camera, viewport, etc).
However, I did come out with a list of things that were easier to do before. So I am putting out a few PRs.
This adds an option to the viewport for noClip. …
> Add a noClip option to fixed viewport

- doc/other-inputs.md
- examples/lib/stories/input/joystick_advanced_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/input.dart
- packages/flame/lib/src/components/input/button_component.dart
- packages/flame/lib/src/components/input/hud_button_component.dart
- packages/flame/lib/src/components/input/sprite_button_component.dart
- packages/flame/test/effects2/opacity_effect_test.dart
Since we have a `HudButtonComponent` I'm adding this one for consistency.
If you haven't used the `HudButtonComponent` it is simply two `PositionComponent`s, one that shows when the button is pressed and one that shows otherwise.
https://user-images.githubusercontent.com/744771/143618565-4e4df42a-4fed-4248-9a6d-770151386d66.mp4
[issue database]: …
> Added a ButtonComponent

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/game/camera/camera_wrapper.dart
- packages/flame/pubspec.yaml
- packages/flame/test/components/position_component_test.dart
- packages/flame/test/game/camera_and_viewport_test.dart
- packages/flame/test/game/component_rendering_test.dart
[I am porting](https://github.com/bluefireteam/gravitational_waves/pull/4) Gravity Runner (aka Gravitational Waves) to the latest Flame.
I think it will be very good to have a fully functional, complete big game example before release.
Most of it was painless or even deleting stuff that we had incorporated from GR to Flame (like camera, viewport, etc).
However, I did come out with a list of things that were easier to do before. So I am putting out a few PRs.
And also I found this bug where component rendering order was not respected for isHud components.
This fixes that but in order to add a test I am modifying `canvas_test` to better test save/restore: https://github.com/bluefireteam/canvas_test/pull/3
Before you create this PR confirm that it meets all requirements listed below by …
> Fix render order of components and add tests

- examples/lib/stories/camera_and_viewport/follow_component_example.dart
- examples/lib/stories/collision_detection/circles_example.dart
- examples/lib/stories/collision_detection/collidable_animation_example.dart
- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- examples/lib/stories/components/composability_example.dart
- examples/lib/stories/components/debug_example.dart
- examples/lib/stories/input/joystick_player.dart
- examples/lib/stories/rendering/particles_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/input/joystick_component.dart
- packages/flame/lib/src/components/parallax_component.dart
- packages/flame/lib/src/components/particle_component.dart
- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/lib/src/components/timer_component.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/test/components/composed_component_test.dart
- packages/flame/test/game/base_game_test.dart
- packages/flame/test/game/flame_game_test.dart
- packages/flame_bloc/example/lib/src/game/components/bullet.dart
- packages/flame_bloc/example/lib/src/game/components/enemy.dart
- packages/flame_bloc/example/lib/src/game/components/player.dart
- packages/flame_flare/lib/src/flare_actor_component.dart
- packages/flame_flare/lib/src/flare_particle.dart
- packages/flame_forge2d/example/lib/balls.dart
- packages/flame_forge2d/lib/position_body_component.dart
- packages/flame_rive/lib/src/rive_component.dart
- packages/flame_test/lib/src/flame_test.dart
Since we have `renderTree`, this PR introduces `updateTree`.
I'm not fully happy with the solution, but it is better than changing `GameRenderBox` to call `updateTree` and `renderTree`.
Any other ideas of how to solve this is appreciated.
Fixes #1115 
> Introduce updateTree

- doc/_sphinx/styles/custom.css
- doc/other-inputs.md
Navigation buttons at the bottom of the page will now be rendered correctly. This was broken by a style change in an upstream library `sphinx-book-theme`.
> Documentation style fixes

- examples/lib/stories/collision_detection/circles_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/src/geometry/circle.dart
Since the `HitboxCircle` multiplies with the scale, when the component is flipped it can get a negative radius.
> Fix `HitboxCircle` on flip

- packages/flame_test/CHANGELOG.md
- packages/flame_test/lib/src/flame_test.dart
- packages/flame_test/test/flame_async_test.dart
Fixes an issue where our test framework sometimes finished abruptly, without running the whole test when there were too many futures on it.
> Fixing tests with multiple futures finishing abruptly

- packages/flame/CHANGELOG.md
- packages/flame/lib/src/effects/scale_effect.dart
- packages/flame/test/effects/scale_effect_test.dart
This PR makes `ScaleEffect.by` multiplicative. That is, `ScaleEffect.by(Vector2.all(2))` will increase the size of the target by a factor of 2 instead of adding +2 to the target's current scale vector.
The reason for this change is because this is how we usually think about scaling:
- make this component twice larger;
- make it 10 times smaller;
- make it 50% taller while at the same time 30% more narrow;
- flip the component horizontally (but gradually)
All these descriptions require the new scale to be a certain factor of the previous scale (especially if the target is flipped, and hence has a negative scale in one of the directions).
[Flame …
> Make ScaleEffect.by multiplicative

- examples/lib/stories/effects/move_effect_example.dart
- packages/flame/CHANGELOG.md
- packages/flame/lib/effects.dart
- packages/flame/lib/src/effects/move_along_path_effect.dart
- packages/flame/lib/src/effects/move_effect.dart
- packages/flame/test/effects/move_along_path_effect_test.dart
- packages/flame/test/effects/move_effect_test.dart
- `MoveEffect.along` converted into a separate class `MoveAlongPathEffect`
- Added flag `absolute`, to create an effect that moves the target along an absolutely positioned path
- Added flag `oriented` to allow the target to keep its orientation aligned with the direction of the path
- The example updated to use oriented path
> MoveAlongPathEffect

- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/mixins/draggable.dart
- packages/flame/lib/src/components/mixins/hoverable.dart
- packages/flame/lib/src/components/mixins/tappable.dart
- packages/flame/lib/src/game/mixins/keyboard.dart
- packages/flame/test/components/composed_component_test.dart
Since the children weren't reversed in `propagateToChildren` the events were not first passed to the last added component.
In `OrderedSet` we now cache the reversed set, so it is a slightly less impact than it should have been to have reversed here than before.
Fixes #1175
Closes #949 
> Fix propagation order

- examples/lib/stories/camera_and_viewport/fixed_resolution_example.dart
- examples/lib/stories/input/input.dart
- examples/lib/stories/parallax/parallax.dart
- examples/lib/stories/rendering/rendering.dart
- examples/lib/stories/sprites/sprites.dart
- examples/lib/stories/system/system.dart
- examples/lib/stories/widgets/custom_painter_example.dart
- packages/flame/lib/src/effects/color_effect.dart
- packages/flame/test/effects/color_effect_test.dart
Flutter has a bug (fixed on master, but not in stable) where the color filter can't be passed 0.
Also fixed some broken links in the examples.
https://github.com/flutter/flutter/issues/89433
https://github.com/flutter/flutter/issues/77258
> Work around Flutter bug for `ColorEffect` and fix broken links

- doc/_sphinx/styles/custom.css
Noted by @spydon, our docs' side menu was changing its size on hover when viewed within a browser window large enough that there was no scrollbar. This PR fixes the problem.
> style: Prevent docs side menu from changing size

- doc/text.md
Usage examples were out of sync with `TextComponent` and `TextBoxComponent`. Input string is now a named parameters for both these components. This PR fixes that.
- (NA) My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- (NA) I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- (NA) I have added a description of the change under `[next]` in `CHANGELOG.md`.
NA
[issue database]: …
> fix: Make string input a named parameter in example code

- packages/flame/lib/src/parallax.dart
Updates to Parallax to allow overriding of the filterQuality parameter passed to the paintImage method from render.
This allows the client to specify the override as such:
`   var img = await loadParallaxImage('background.png',
filterQuality: FilterQuality.none,
);`
Change is not ideal as the paintImage method supplies the default value of FilterQuality.low, and doesn't allow a null parameter, meaning the same value has to be defaulted  as a non-nullable field of the ParallaxRenderer.
`        filterQuality = filterQuality ?? FilterQuality.low;`
> feat: Adding filterQuality override to parallax

- doc/effects.md
- examples/lib/stories/effects/scale_effect_example.dart
- packages/flame/lib/effects.dart
- packages/flame/lib/src/effects/controllers/effect_controller.dart
- packages/flame/lib/src/effects/controllers/infinite_effect_controller.dart
- packages/flame/lib/src/effects/controllers/random_effect_controller.dart
- packages/flame/test/effects/controllers/random_effect_controller_test.dart
Add `RandomEffectController` -- a controller that makes the duration of some other effect controller random. This could be useful if the user wants to inject some amount of unpredictability into the effect.
> feat: Add RandomEffectController

- doc/effects.md
- packages/flame/lib/src/effects/effect.dart
- packages/flame/test/effects/effect_test.dart
`Effect.onFinish` is now a property that can be directly set by the user. This allows an alternative way to chain multiple effects, and to perform some special action when an effect completes.
Previously, `Effect.onFinish()` was a method, and the only way to use it was to subclass a particular effect and create an overridden `.onFinish` method -- which is very cumbersome.
Note the asymmetry between `onStart()` and `onFinish()`: the first still remains an overridable method. This is because there are many effects that are interested in performing a custom action at start, and for them using a callback function would be more difficult. At the same time, there doesn't appear to be a clear use case when the user would want to provide a custom action at the start of an event.
> feat: Effect.onComplete callback as an alternative to onFinish()

- examples/pubspec.yaml
- packages/flame/example/pubspec.yaml
- packages/flame_audio/example/pubspec.yaml
- packages/flame_bloc/example/pubspec.yaml
- packages/flame_fire_atlas/example/pubspec.yaml
- packages/flame_forge2d/example/pubspec.yaml
- packages/flame_oxygen/example/pubspec.yaml
- packages/flame_rive/example/pubspec.yaml
- packages/flame_svg/example/pubspec.yaml
- packages/flame_test/example/pubspec.yaml
- packages/flame_test/example/test/flame_test_test.dart
- packages/flame_test/example/test/main_test.dart
- packages/flame_tiled/example/pubspec.yaml
- tutorials/space_shooter/pubspec.yaml
This PR renames some of the internal (non-published) packages within Flame, ensuring that they all have unique and predictable names. The reason for this change is that when melos runs its action across all packages, and then reports a problem in one of the packages, it uses the name of the package in the report. Thus, if the name is non-unique like `example`, it is impossible to tell where the problem was.
> chore: Ensure unique names for all flame sub-packages

- packages/flame/lib/src/components/input/joystick_component.dart
Apparently the priority was missing from the `JoystickComponent`.
Fixes #1226
> fix: Add missing `priority` argument for `JoystickComponent`

- packages/flame/example/lib/main.dart
- packages/flame/example/pubspec.yaml
- packages/flame/lib/src/components/mixins/tappable.dart
- packages/flame/lib/src/game/game_widget/game_widget.dart
- packages/flame/lib/src/game/game_widget/gestures.dart
- packages/flame/test/game/detectors_test.dart
Most gesture detectors work together now, except for the `PanDetector` or `ScaleDetector` together with the `MultiTouchDragDetector`. Maybe even the `ScaleDetector` will work with the `MultiTouchDragDetector`, will have to try.
Also simplified the example game a little bit. …
> fix: Allow most basic and advanced gesture detectors together

- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/component_set.dart
The `Component.children` property can now be null.
The reasoning is simple: most of the components in the game tree are leaf nodes, and don't have any children. For these components carrying around a `ComponentSet` object is wasteful.
> perf: Allow components to have null children

- README.md
- melos.yaml
Examples and tutorials were missing from the list of packages in the melos config file, which prevented melos from running lints in those packages.
Also added Melos badge to the readme file, in case we want to show it.
> chore: Add missing packages to melos.yaml

- melos.yaml
Added new command `melos run coverage` to generate the standard test coverage report.
> chore: Add coverage script to melos.yaml

- packages/flame/lib/src/game/game_widget/game_widget.dart
The code in `loaderFuture` can be simplified using `async`.
> refactor: Simplify GameWidgetState.loaderFuture

- .github/pull_request_template.md
Correct conventional commit type (doc -> docs) in the pull request template.
> docs: Correct conventional commit type (doc -> docs)

- packages/flame/lib/src/components/component.dart
- packages/flame/test/components/component_test.dart
Since `prepareComponent` can be called multiple times for non-root children we need to make sure that it is only called once.
Fixes #1235
> fix: `prepareComponent` should never run again on a prepared component

- examples/lib/stories/camera_and_viewport/camera_and_viewport.dart
- examples/lib/stories/camera_and_viewport/coordinate_systems_example.dart
- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/base_future_builder.dart
- packages/flame/lib/src/widgets/nine_tile_box.dart
- packages/flame/lib/src/widgets/sprite_button.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
- packages/flame_forge2d/example/lib/main.dart
- packages/flame_forge2d/example/lib/widget_sample.dart
- packages/flame_lint/lib/analysis_options.yaml
- packages/flame_test/example/lib/game.dart
This:
- Add new rule `use_if_null_to_convert_nulls_to_bools` to `flame_lint` (no violations)
- Add new rule `use_key_in_widget_constructors` (several violations)
- Fix violations
- Exclude generated files from flame_lint (we don't have any on this repo but when using on games often there are)
I believe this is *not* a breaking change because it just adds optional arguments to constructors, but if it is, we can reconsider this PR. …
> refactor: Add a few more rules to flame_lint, including use_key_in_widget_constructors

- packages/flame/lib/src/components/input/hud_margin_component.dart
- packages/flame/test/components/hud_margin_component_test.dart
This fixes so that the `HudMarginComponent` uses the size of the viewport instead of the zoomed size from the game.
> fix: HudMarginComponent positioning on zoom

- packages/flame_forge2d/lib/forge2d_camera.dart
- packages/flame_forge2d/test/position_test.dart
While projecting world coordinates, Forge2DCamera was modifying the original input vector. This change makes sure that the input vector is cloned before modifying it.
Fixes #1254 
> fix: Clone input vector before projecting it

- doc/collision_detection.md
- packages/flame/lib/src/components/mixins/collidable.dart
- packages/flame/lib/src/geometry/collision_detection.dart
- packages/flame/lib/src/geometry/shape.dart
- packages/flame/test/components/collision_callback_test.dart
Introduces `onCollsionStart` for `Collidable` and `HitboxShape`, which is called only once when the collision starts.
> feat: `onCollisionStart` for `Collidable` and `HitboxShape`

- doc/gesture-input.md
This PR fixes following issues:
- Explanation for advanced detectors had a typo saying "MultiTouchDragDetector and MultiTouchDragDetector". It should have been "**MultiTouchTapDetector** and MultiTouchDragDetector"
- Link for `GestureDectector` was ill-formatted
- Overridden methods from mixins were renaming input parameter from `info` to `event`
- 2nd parameter for `onDragStart` was shown as `Vector2` instead of `DragStartInfo`
NA
[issue …
> docs: Fix some typos and correct some snippets in gesture-input

- packages/flame_tiled/lib/src/tiled_component.dart
There was no way to set priority of TiledComponent while construction. This change exposes that property.
NA
> feat: Expose priority for TiledComponent

- doc/components.md
- packages/flame/lib/src/components/component_set.dart
In some situations where you don't know whether you need to use `children.query` or not it will be a performance hit to be forced to `register` the query, since when `children.register` is called the set is initialized, even though the children set might never be used. …
> feat: Turn off `strictMode` for children

- packages/flame/lib/src/components/mixins/draggable.dart
- packages/flame/test/components/draggable_test.dart
A typo in `handleDragCanceled` caused the proper event handler `onDragCancel` to never be called.
- [NA] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [NA] I have updated/added relevant examples in `examples`.
Fixes #1276 
> fix: Typo in handleDragCanceled() callback

- packages/flame/lib/src/components/text_box_component.dart
TextBoxComponent used to decide whether to redraw text or not based on whether the text length is different from the `_previousChar` value. Thus, when replacing text with another text that has the same length, the component failed to update its cached image.
Fixes #1277
> fix: TextBoxComponent did not redraw when changing text to another string with the same length

- doc/other-inputs.md
- packages/flame/lib/src/components/input/hud_button_component.dart
This PR adds an `onReleased` callback to HudButtonComponent which will be called when button is released.
Fixes #1290  …
> feat: Add onReleased callback for HudButtonComponent

- doc/components.md
Updated the docs to use `flipHorizontally()` and `flipVertically()` instead of `renderFlipX` and `renderFlipY`.
Fixes #1303 
[Conventional …
> docs: Replace renderFlip properties with flipxxx methods

- packages/flame/lib/src/components/sprite_component.dart
Adding the paint argument which exists in the normal `SpriteComponent` constructor to the named `SpriteComponent.fromImage` constructor.
> fix: Add missing paint argument to `SpriteComponent.fromImage`

- packages/flame/lib/src/game/game_render_box.dart
The documentation of `RenderBox` says the following:
```dart
/// When implementing a [RenderBox] subclass, one must make a choice. Does it
/// size itself exclusively based on the constraints, or does it use any other
/// information in sizing itself? An example of sizing purely based on the
/// constraints would be growing to fit the parent.
///
/// Sizing purely based on the constraints allows the system to make some
/// significant optimizations. Classes that use this approach should override
/// [sizedByParent] to return true, and then override [computeDryLayout] to
/// compute the [Size] using nothing but the constraints, e.g.:
```
This PR changes `GameRenderBox` to adhere to this advice and set `sizedByParent` to true. 
- (NA) I have updated/added tests for ALL new/updated/fixed …
> refactor: Resize logic in GameRenderBox

- doc/images.md
- packages/flame/lib/src/assets/images.dart
- packages/flame/test/images_cache_test.dart
Disposes the images when they are removed or when the image cache is cleared.
Closes #1309
> fix: Properly dispose images when cache is cleared

- packages/flame_bloc/CHANGELOG.md
- packages/flame_bloc/pubspec.yaml
> feat: publish flame bloc

- examples/lib/stories/system/without_flamegame_example.dart
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/lib/src/game/mixins/loadable.dart
Mixin `Loadable` no longer declares method `onGameResize()`. Instead, this method is now defined by classes `Component` and `Game` separately (which they were already doing before).
Resizing has nothing to do with loading, so it is not proper to declare this method inside `Loadable`. I presume it existed there by accident.  …
> refactor: Loadable no longer declares onGameResize

- packages/flame_bloc/README.md
the example should be 
```dart
class ExampleGame extends FlameBlocGame {
void selectWeapon() {
read<InventoryBloc>.add(WeaponSelected('axe'));
}
}
```
not
```dart
class ExampleGame example FlameBlocGame {
void selectWeapon() {
read<InventoryBloc>.add(WeaponSelected('axe'));
}
}
```
*Replace this paragraph with a description of what this PR is doing. 
If you're modifying existing behavior, describe the existing behavior, how this PR is changing it,
and what motivated the change. If this is a breaking change, specify explicitly which APIs have been
changed.*
Does your PR require Flame users to manually update their …
> docs: Fix typo in flame_bloc readme

- packages/flame_svg/example/lib/main.dart
- packages/flame_svg/example/pubspec.yaml
- packages/flame_svg/lib/svg_component.dart
- packages/flame_svg/pubspec.yaml
SvgComponent lacked a default constructor and had a non nullable instance of the svg, which didn't allowed it to be lazy loaded on the `onLoad` method and was not consistent with the rest of Flame components. This PRs simply add the default constructor to address that. …
> feat: adding default constructor on SvgComponent

- packages/flame_svg/lib/svg.dart
SVG rendering was affect subsequent renderings due to lack of saving and restoring context. …
> fix: preventing svg rendering from affecting other renderings

- packages/flame_tiled/lib/src/flame_tsx_provider.dart
- packages/flame_tiled/lib/src/renderable_tile_map.dart
- packages/flame_tiled/pubspec.yaml
- packages/flame_tiled/test/assets/tiles/external_tileset_1.tsx
- packages/flame_tiled/test/tiled_test.dart
This is an update to adhere to the new TiledMap.parseTmx contract that will be introduced with: https://github.com/flame-engine/tiled.dart/pull/37/files. The contract update was made to fix the issue raised in https://github.com/flame-engine/tiled.dart/issues/35.
The parser was updated to take a list of external tileset TsxProviders. The parser now expects a list of loaded external tileset data for each external tileset. See other PR for more details on the fix in the tiled repo.
To adhere to this new contract, this fix pre-loads each external tileset referenced in the .tmx file and passes in a list of the corresponding TsxProviders.
While not technically a breaking change, if anyone is subclassing FlameTsxProvider or using directly, the logic is changing when parsing Tilesets, and this …
> !fix: fix multiple external tilesets

- packages/flame/lib/src/components/parallax_component.dart
I think we forgot to set this back to this after we changed from the `isHud` logic.
(It kind of is a breaking change, but the current way is not what was intended so this is more of a bug fix).
> fix: `ParallaxComponent` should have static `positionType`

- doc/effects.md
- examples/lib/stories/effects/move_effect_example.dart
- packages/flame/lib/effects.dart
- packages/flame/lib/src/effects/controllers/noise_effect_controller.dart
- packages/flame/test/effects/controllers/noise_effect_controller_test.dart
Added `NoiseEffectController`, which can be used to implement various shake effects.
Closes #396 
> feat: Added NoiseEffectController

- packages/flame/pubspec.yaml
- packages/flame_test/pubspec.yaml
Today, `package:flame` and `package:flame_test` depend on `vector_math`. However, the upstream Flutter SDK already depends on this package: https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L15. Thus pub get will resolve both dependencies to a single package (and version solving fail if they are not compatible, which is why I suspect Flame uses such a wide version constraint).
This PR simplifies things by just removing the dependency from the pubspec's altogether. I ran `pub get` on both repos and there was no diff to the pubspec.lock, and the example app built and ran fine.
Does your PR …
> fix: remove vector_math dependency

- doc/_sphinx/scripts/versions.js
- doc/_sphinx/theme/flames.css
- Prevent version entries in the menu dropdown from wrapping to 2 lines.
- Stop blur event from interfering with the click events in the menu.
> fix: Menu dropdown in the docs

- examples/pubspec.yaml
- packages/flame/lib/src/cache/memory_cache.dart
- packages/flame_svg/lib/svg.dart
- packages/flame_svg/lib/svg_component.dart
- packages/flame_svg/pubspec.yaml
- packages/flame_svg/test/svg_component_test.dart
Fixes Flame SVG perfomance by caching it in an image. …
> fix: flame svg perfomance

- packages/flame/lib/src/sprite_animation.dart
- packages/flame/test/sprite_animation_test.dart
- packages/flame/test/spritesheet_test.dart
`SpriteAnimation` class now ensures that all animation frames have positive durations. If not, the `update()` method would go into an infinite loop.
Current constructors in SpriteAnimation converted into factory constructors so that validity checks can all be made in a single place.
Also make sure that non-looping single-frame `SpriteAnimation` works correctly and calls the `onComplete` callback after the frame ends.
Closes #1372
Closes #1379 …
> fix: Step time in SpriteAnimation must be positive

- packages/flame_forge2d/lib/sprite_body_component.dart
Gives you the option to set the priority directly when creating the component.
> feat: Add missing optional priority to SpriteBodyComponent

- packages/flame_forge2d/example/lib/balls.dart
- packages/flame_forge2d/example/lib/blob_sample.dart
- packages/flame_forge2d/example/lib/boundaries.dart
- packages/flame_forge2d/example/lib/circle_stress_sample.dart
- packages/flame_forge2d/example/lib/composition_sample.dart
- packages/flame_forge2d/example/lib/contact_callbacks_sample.dart
- packages/flame_forge2d/example/lib/domino_sample.dart
- packages/flame_forge2d/example/lib/draggable_sample.dart
- packages/flame_forge2d/example/lib/joint_sample.dart
- packages/flame_forge2d/example/lib/mouse_joint_sample.dart
- packages/flame_forge2d/example/lib/position_body_sample.dart
- packages/flame_forge2d/example/lib/raycast_sample.dart
- packages/flame_forge2d/example/lib/sprite_body_sample.dart
- packages/flame_forge2d/example/lib/tappable_sample.dart
- packages/flame_forge2d/example/lib/widget_sample.dart
- packages/flame_forge2d/lib/flame_forge2d.dart
Adds exports for all `flame_forge2d` content to the `flame_forge2d.dart` barrel file. 
This will clean up Forge2D imports when using the package so only one import is necessary:
`import 'package:flame_forge2d/flame_forge2d.dart';`
**Users with strict linter rules may see warnings to remove unnecessary imports, but it won't break functionality**
> chore(flame_forge2d): export all files in barrel file

- packages/flame_forge2d/example/lib/balls.dart
- packages/flame_forge2d/lib/contact_callbacks.dart
Make begin and end methods optionally overridable when extending ContactCallback.
Also updates examples that were implementing empty methods.
Aims to resolve #1414.
> feat: Make ContactCallback begin end methods optional overrides

- packages/flame_forge2d/lib/position_body_component.dart
`PositionBodyComponent` had its `onMount` method declared as `async`, even though it wasn't needed since there are no async operations on that method.
This not only was unnecessary, but it was preventing other mixins (like `BlocComponent`) that have their own onMount method to be used alongside this component.
> fix: PositionBodyComponent had an async onMount, without needing

- doc/flame/collision_detection.md
- examples/lib/stories/collision_detection/collidable_animation_example.dart
- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- examples/lib/stories/input/gesture_hitboxes_example.dart
- packages/flame/lib/src/collisions/collision_callbacks.dart
- packages/flame/lib/src/collisions/collision_detection.dart
- packages/flame/lib/src/collisions/hitboxes/hitbox.dart
- packages/flame/lib/src/collisions/hitboxes/polygon_hitbox.dart
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
- packages/flame/lib/src/collisions/sweep.dart
- packages/flame/test/collision_detection/collidable_type_test.dart
- packages/flame/test/collision_detection/collision_test_helpers.dart
- packages/flame_bloc/example/lib/src/game/components/enemy.dart
`relatve` - > `relative`
`CollidableType` -> `CollisionType`
Paint for hitboxes should be `debugPaint`.
> fix: Fix collision detection comments and typo

- packages/flame/lib/src/components/component.dart
Currently, `Component.debugPaint` uses `strokeWidth = 1`. However, this "1" is not 1 pixel, but rather 1 unit of the game coordinate system. So, if the game uses large zoom level by default, the wireframes will become too thick; and if the game uses small zoom, the wireframes will be barely visible. Setting `strokWidth = 0` produces "hairline width" rectangles of consistent appearance regardless of the zoom level. …
> fix: Use strokeWidth=0 in debug mode

- packages/flame/lib/src/experimental/viewfinder.dart
- packages/flame/test/experimental/viewfinder_test.dart
Camera's aim was incorrect in games with zoom≠1.
> fix: CameraComponent's behavior under zoom

- packages/flame/lib/src/assets/images.dart
- packages/flame/test/assets/images_test.dart
> feat: allowing changing of the images prefix and allowing empty prefixes

- packages/flame/lib/src/assets/images.dart
- packages/flame/test/assets/images_test.dart
- Setter for `Images.prefix` now allows to set to an empty string.
- Added doc-string for the `.prefix` property.
> fix: Setting images.prefix to empty string

- packages/flame_forge2d/lib/body_component.dart
- packages/flame_forge2d/lib/position_body_component.dart
Since debug rendering now renders on top of everything (since ages), `BodyComponent` shouldn't hijack the debug render method for its normal rendering.
> fix: Don't use debug rendering by default in BodyComponent

- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_batch_component.dart
Added the missing @mustCallSuper tags in 3 sprite components to provide proper linting.  PR request per this thread: https://discordapp.com/channels/509714518008528896/516639688581316629/952199344679964742
None
> fix: `@mustCallSuper` missing on components

- doc/flame/camera_and_viewport.md
- doc/other_modules/forge2d.md
- packages/flame_forge2d/example/lib/camera_sample.dart
- packages/flame_forge2d/example/lib/composition_sample.dart
- packages/flame_forge2d/example/lib/position_body_sample.dart
- packages/flame_forge2d/example/lib/sprite_body_sample.dart
- packages/flame_forge2d/lib/body_component.dart
- packages/flame_forge2d/lib/flame_forge2d.dart
- packages/flame_forge2d/lib/forge2d_camera.dart
- packages/flame_forge2d/lib/forge2d_game.dart
- packages/flame_forge2d/lib/position_body_component.dart
- packages/flame_forge2d/lib/sprite_body_component.dart
Since `BodyComponent` now works when having `PositionComponent` children, the ugly `PositionBodyComponent` hack can be deprecated.
(It will be breaking once the deprecated classes are removed though).
> feat: `BodyComponent` can properly have normal Flame component children

- doc/flame/components.md
- doc/flame/game.md
- packages/flame/lib/src/components/component.dart
- packages/flame/test/components/priority_test.dart
Allows setting the priority directly by having a setter that checks whether the component has a parent or not.
> feat: Add setter to priority

- doc/flame/game.md
We were missing docs about `backgroundColor`.
> docs: Add `backgroundColor()` docs

- doc/flame/game.md
The Widget Overlay docs was out of date and was missing the `Game` argument.
> docs: Widget overlay documentation is out of date

- doc/flame/camera_component.md
- examples/lib/stories/camera_and_viewport/camera_and_viewport.dart
- examples/lib/stories/camera_and_viewport/camera_component_example.dart
- examples/lib/stories/camera_and_viewport/camera_component_properties_example.dart
- packages/flame/lib/src/experimental/camera_component.dart
- packages/flame/lib/src/experimental/fixed_size_viewport.dart
- packages/flame/lib/src/experimental/viewfinder.dart
- packages/flame/lib/src/experimental/viewport.dart
- packages/flame/test/experimental/viewfinder_test.dart
The `.anchor` property allows to designate a specific point within the viewport as being the "logical center" of the viewport -- this is the point where the viewfinder's focus will be placed at. This is similar to the `relativeOffset` property of the old `Camera`.
Also: slightly simplified the rendering logic of `CameraComponent` by merging the multiple rendering methods.
> feat: Added .anchor property to CameraComponent.Viewfinder

- doc/flame/other/util.md
- packages/flame/lib/src/assets/images.dart
- packages/flame/lib/src/extensions/rect.dart
- Deprecating `fromBounds` in favor of better named `getBounds`.
- Deprecating `fromVector2Center` in favor of `fromCenter`, as it won't be blocking on the `Rect.fromCenter` constructor.
> feat: Deprecating Rect methods

- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/geometry/circle_component.dart
- packages/flame/lib/src/geometry/polygon_component.dart
- packages/flame/test/components/composed_component_test.dart
`debugMode` wasn't propagating properly from the parent component to it's descendants.
If you for example added a component `a` to a component `b` first, and then added `b` to `c` which had `debugMode = true`, `a` would not have `debugMode = true`. But if `a` was added to `b` after it was added to `c`, then `a` would have `debugMode = true`.
This also fixes the `debugMode` for `HitboxShape`s.
> fix: `debugMode` should be inherited from parent when mounted

- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/position_component.dart
Since `whereType` can be used just as efficiently on `ancestors` and since `descendants` didn't implement generics, it should be removed from `ancestors`.
Since it wasn't released yet it's not a breaking change.
#1456 
> fix: Remove generics from ancestors

- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/test/components/component_test.dart
* `propagateToChildren` is supposed to visit components in the order opposite of how they were rendered. However, there was a bug that when called with `includeSelf=true`, the root of the tree will be visited first instead of last.
* Also, there was a bug where, in case of a game-in-game structure, the children of the nested game would be traversed twice.
* Added flag `bool reversed = false` to the `descendants()` method. …
> fix: Component.propagateToChildren() order of traversal

- packages/flame/lib/src/components/component.dart
- packages/flame/test/components/component_test.dart
Adds a simple new method on `Component` to enable easy and safe way to recover the first child of a given type, basically a convenience method for `children.whereType<T>.first`.
> feat: adding Component.lastChild and Component.firstChild

- packages/flame/lib/src/components/component.dart
- packages/flame/test/game/flame_game_test.dart
Fix the case when a FlameGame is being added into another FlameGame.
Closes #1474 
> fix: Game-in-Game now works correctly again

- packages/flame/lib/src/geometry/circle_component.dart
Adds the possibility to set the `radius` in a `CircleComponent`.
> feat: Add setter for CircleComponent.radius

- doc/_sphinx/extensions/flutter_app.py
The `..flutter-app` directive in the documentation system now takes into account the `PUBLISH_PATH` environment variable, which can be used to specify that the documentation will reside at a path different from the root.
> doc: Take PUBLISH_PATH into account when building docs

- doc/_sphinx/extensions/flutter_app.css
- doc/_sphinx/extensions/flutter_app.js
- doc/_sphinx/extensions/flutter_app.py
- doc/tutorials/bare_flame_game.md
- doc/tutorials/klondike/step2.md
The `..flutter-app` directive now also supports the `"code"` mode, which produces button that will show code listing for all files in the compiled app.
Looks like this:
> doc: Flutter-app directive can now also show the listings of code

- packages/flame/lib/src/components/mixins/has_game_ref.dart
- packages/flame/test/components/has_game_ref_test.dart
> feat: adding HasGameRef.mockGameRef

- packages/flame/lib/effects.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/effects/provider_interfaces.dart
- packages/flame/lib/src/effects/rotate_effect.dart
- packages/flame/lib/src/experimental/viewfinder.dart
- packages/flame/test/experimental/viewfinder_test.dart
- Added interface `AngleProvider`, which is currently implemented by `PositionComponent` and `Viewfinder`;
- The `RotateEffect`s are now targeting any component with an `AngleProvider`.
> feat: Camera's Viewfinder can now be affected by rotation effects

- packages/flame_test/lib/flame_test.dart
- packages/flame_test/lib/src/close_to_aabb.dart
- packages/flame_test/test/close_to_aabb_test.dart
A convenience function for testing that an Aabb is close to the value that you'd expect.
> feat: Added flame_test function closeToAabb()

- .github/workflows/cicd.yml
- .github/workflows/title-validation.yml
Since a merge doesn't have a PR title (and it is already confirmed).
> chore: Title validation shouldn't run on merge

- packages/flame_oxygen/lib/src/component/size_component.dart
The width setter in Oxygen's SizeComponent is obviously incorrect.
> fix: Fix width setter in Oxygen's SizeComponent

- doc/flame/effects.md
- packages/flame/lib/src/effects/move_along_path_effect.dart
- packages/flame/test/effects/move_along_path_effect_test.dart
- The `MoveAlongPathEffect` is now derived from the `MoveEffect` base class, and can be given an explicit `target`.
- The effect can now be applied to any `PositionProvider`.
- An exception will be thrown if `oriented: true` flag is given, but the target is not an `AngleProvider`.
> feat: MoveAlongPathEffect can now be applied to any PositionProvider

- packages/flame/lib/src/anchor.dart
Comparing hashcodes may return that two different Anchors are equal with a small probability. This has now been fixed.
> fix: Anchor equality operator is now more reliable

- packages/flame_forge2d/example/lib/mouse_joint_sample.dart
Found a functional bug in Forge2d samplecode: `mouse_joint_sample.dart`
- [ x] No, this is *not* a breaking change.
https://stackoverflow.com/questions/71928016/mousejoint-gets-less-and-less-reactive/71938577#71938577
> fix: MouseJoint gets less and less reactive(#1558)

- doc/flame/effects.md
- packages/flame/lib/effects.dart
- packages/flame/lib/src/anchor.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/effects/anchor_by_effect.dart
- packages/flame/lib/src/effects/anchor_effect.dart
- packages/flame/lib/src/effects/anchor_to_effect.dart
- packages/flame/lib/src/effects/provider_interfaces.dart
- packages/flame/lib/src/experimental/viewfinder.dart
- packages/flame/test/effects/anchor_by_effect_test.dart
- packages/flame/test/effects/anchor_to_effect_test.dart
- Added `AnchorProvider` interface, currently implemented by `PositionComponent` and `Viewfinder`.
- Added `AnchorToEffect` and `AnchorByEffect` that can be applied to a target which is an `AnchorProvider`.
> feat: Added AnchorToEffect and AnchorByEffect

- doc/flame/components.md
- packages/flame/lib/src/sprite_animation.dart
- packages/flame/test/sprite_animation_test.dart
Adds `completed` future that completes whenever the animation completes.
Similar to how we have `loaded` and `mounted` on `Component`.
Reasoning:
- The `onCompleted` can be overridden whereas with `completed` you can add multiple "callbacks"
(that overriding issue is what raised the issue on the widget in the first place)
- In some scenarios, the API `completed` is easier to test and read over `onCompleted`
#1543 
> feat: included `completed` to `SpriteAnimation`

- doc/flame/camera_component.md
- packages/flame/lib/experimental.dart
- packages/flame/lib/src/effects/provider_interfaces.dart
- packages/flame/lib/src/experimental/camera_component.dart
- packages/flame/lib/src/experimental/follow_behavior.dart
- packages/flame/test/experimental/camera_component_test.dart
- packages/flame/test/experimental/follow_behavior_test.dart
- Created `FollowBehavior` which can be attached to any component and cause that component to follow the given target;
- Added `CameraComponent` methods `follow()`, `stopFollowing()`, and `moveTo()` which are similar to the existing `Camera` methods.
Still needed: tests, docs and examples.
> feat: Added FollowBehavior and ability for the new Camera to follow a component

- packages/flame/lib/src/particles/accelerated_particle.dart
- packages/flame/lib/src/particles/moving_particle.dart
Remove creation of new `Vector2` objects in `AcceleratedParticle` and `MovingParticle`.
> fix: Optimize AcceleratedParticle and MovingParticle

- packages/flame/lib/src/sprite_animation.dart
Sorry I didn't double check this error in yesterday's pr due to my oversight, because the index starts from 0, and the calculated length should be incremented by 1。
> fix: correctly calculating frame length

- packages/flame/lib/src/components/isometric_tile_map_component.dart
- packages/flame/test/components/isometric_tile_map_component_test.dart
Taking scale in consideration when getting a block from IsometricTileMapComponent. This will allow for scaled maps to return the correct block. 
> fix: Isometric tile map component uses scale when getting block from position

- packages/flame/lib/collisions.dart
Expose the forgotten `CompositeHitbox`.
> fix: Expose `CompositeHitbox`

- packages/flame_bloc/example/lib/src/game.dart
- packages/flame_bloc/example/lib/src/game/components/player.dart
- packages/flame_bloc/example/lib/src/game/game.dart
- packages/flame_bloc/lib/flame_bloc.dart
- packages/flame_bloc/lib/src/flame_bloc_listener.dart
- packages/flame_bloc/lib/src/flame_bloc_listener_component.dart
- packages/flame_bloc/test/flame_bloc_game_test.dart
- packages/flame_bloc/test/src/flame_bloc_listener_component_test.dart
- packages/flame_bloc/test/src/flame_bloc_listener_test.dart
- feat(flame_bloc): add FlameBlocListenerComponent
This change allows developers to have components which can listen to multiple blocs and also aligns more closely with other components like the FlameBlocProvider. We can still keep the FlameBlocListener mixin if you'd like but if we decide to remove the mixin we can rename this to just `FlameBlocListener`.
```dart
class GameStatsController extends Component
with
HasGameRef<SpaceShooterGame>,
FlameBlocListener<GameStatsBloc, GameStatsState> {
@override
bool listenWhen(GameStatsState? previousState, GameStatsState newState) {
return previousState?.status != newState.status &&
newState.status == GameStatus.initial;
}
@override
void onNewState(GameStatsState state) {
gameRef.children.removeWhere((element) => element is EnemyComponent);
}
} …
```
> feat(flame_bloc): add FlameBlocListenerComponent

- packages/flame_bloc/lib/src/flame_bloc_listenable.dart
- packages/flame_bloc/lib/src/flame_bloc_listener.dart
- packages/flame_bloc/pubspec.yaml
- packages/flame_bloc/test/src/flame_bloc_listenable_test.dart
- packages/flame_bloc/test/src/flame_bloc_listener_test.dart
- feat(flame_bloc): add optional bloc parameter to FlameBlocListener
- this enables developers to manage bloc instances without providing them to the component tree and improves the performance by avoiding having to perform ancestor lookups
- in addition it aligns with the existing BlocListener API in flutter_bloc
> feat(flame_bloc): add optional bloc parameter to FlameBlocListener

- packages/flame/lib/src/components/mixins/parent_is_a.dart
In https://github.com/flame-engine/flame/pull/1566 the `mustCallSuper` was forgotten after the refactor back to the original solution.
> fix: `ParentIsA` missing `mustCallSuper`

- packages/flame/lib/src/components/component.dart
Over time, the Component class became quite disorganized.
In this PR I move around various methods/properties of the `Component` class so that methods that perform related functions would be next to each other; classifying them into several named regions.
Also, updated doc-comment for the class, because that was obviously long overdue.
No functions/methods/properties were removed or modified. …
> refactor: Organize Component class

- packages/flame/lib/src/components/component.dart
- packages/flame/test/assets/images_test.dart
- packages/flame/test/cache/memory_cache_test.dart
- packages/flame/test/collisions/collision_callback_benchmark.dart
- packages/flame/test/collisions/collision_callback_test.dart
- packages/flame/test/collisions/collision_passthrough_test.dart
- packages/flame/test/collisions/collision_test_helpers.dart
- packages/flame/test/collisions/collision_type_test.dart
- packages/flame/test/components/mixins/has_paint_test.dart
- packages/flame/test/components/mixins/parent_is_a_test.dart
- Modernize various tests (helper classes made private, proper name of test groups, use testWithFlameGame where appropriate, test for assert failure messages);
- For some tests improved coverage;
- Fixed bug with `ParentIsA` mixin, where wrong parent triggered a TypeCast error instead of an assertion error. The corresponding test couldn't catch this because it tried to call `onMount` manually instead of actually mounting the component, and the error was thrown before the mounting stage.
WIP for #1351 …
> refactor: Improve tests

- packages/flame/lib/src/collisions/hitboxes/rectangle_hitbox.dart
- packages/flame/lib/src/geometry/rectangle_component.dart
The `RectangleHitbox` should shrink to bounds when the relative constructor is used, just like for the `PolygonComponent`.
> fix: RectangleHitbox should shrink to bounds

- doc/flame/components.md
- doc/flame/other/debug.md
- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- examples/lib/stories/components/debug_example.dart
- examples/lib/stories/rendering/particles_example.dart
- packages/flame/lib/components.dart
- packages/flame/lib/src/components/fps_component.dart
- packages/flame/lib/src/components/fps_text_component.dart
- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/lib/src/game/mixins/fps_counter.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/test/components/fps_component_test.dart
- packages/flame_oxygen/example/lib/main.dart
- packages/flame_oxygen/example/lib/system/debug_system.dart
This PR adds two components:
- `FpsComponent` which calculates the current FPS within a window.
- `FpsTextComponent` which renders the current FPS on the screen using a `TextComponent`.
Will add docs and tests if you think it looks like a good idea.
Related to #1582 
> feat: Add `FpsComponent` and `FpsTextComponent`

- packages/flame/lib/assets.dart
- packages/flame/lib/cache.dart
- packages/flame/lib/src/cache/assets_cache.dart
- packages/flame/lib/src/cache/images.dart
- packages/flame/lib/src/components/parallax_component.dart
- packages/flame/lib/src/flame.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/lib/src/parallax.dart
- packages/flame/lib/src/sprite.dart
- packages/flame/lib/src/sprite_animation.dart
- packages/flame/lib/src/sprite_batch.dart
- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/nine_tile_box.dart
- packages/flame/lib/src/widgets/sprite_button.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
- packages/flame/test/cache/images_test.dart
- packages/flame/test/components/parallax_test.dart
- packages/flame_fire_atlas/lib/flame_fire_atlas.dart
- packages/flame_fire_atlas/test/flame_fire_atlas_test.dart
- packages/flame_svg/lib/svg.dart
Adds an optional argument to `Images.load` that lets you specify the key that the `Image` will have in the cache.
Also adds `Images.contains` to check whether a key exists in the cache.
> feat: Optional key for Images.load

- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/lib/src/game/mixins/fps_counter.dart
- packages/flame/lib/src/game/mixins/game.dart
This technically speaking is a breaking change, but since we are already planning on deprecating the `FPSCounter` the team has internally decided to turn the `fps()` method into a copy of the functionality from #1595 so that we can remove the method `onTimingsCallback` already so Flutter 3.0 users wont have any warnings. This method is either not used or a really small portion of people are using it, compared to the `FPSCounter`. 
> feat!: remove `onTimingsCallback` for Flutter 3.0

- packages/flame_lint/pubspec.yaml
Flutter 3 doesn't like the old danalyzer dependency:
```
flame_lint 0.0.1
'-- dartdoc 4.1.0
|-- analyzer 2.8.0
```
which leads to the following error, when executing `melos bootstrap`:
```
[audioplayers]: ERR : Rename failed, path = 'C:\hostedtoolcache\windows\flutter\3.0.0-stable\x64\.pub-cache\_temp\dir1cbe5ff7' (OS Error: Cannot create a file when that file already exists.
```
While `dir1cbe5ff7` is the temporary folder for `flame_lint`
We can also consider remove `dartdocs` dependency completely, if its not needed elsewhere.
Plz also consider publishing soon, as `audioplayers` Merge-Requests depend on it.
Just currently occurs in windows tests for audioplayers, when calling `melos bootstrap` …
> fix(flame_lint): Upgrade dartdoc (upgrade analyzer transitive dependency)

- examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart
> fix: Broken links for flame_forge2d examples

- packages/flame/lib/src/components/parallax_component.dart
Since the parallax won't update otherwise (or even be rendered to its initial position).
> fix: `ParallaxComponent.update` mustCallSuper

- packages/flame/lib/extensions.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/lib/src/extensions/picture_extension.dart
- packages/flame/lib/src/image_composition.dart
- packages/flame/lib/src/sprite_batch.dart
- packages/flame_tiled/test/tiled_test.dart
When using `PictureRecorder`, the `Picture` object that it creates needs to be properly disposed after it is no longer used.
> fix: Avoid leaks when using PictureRecorders

- doc/README.md
- doc/flame/components.md
- doc/flame/effects.md
- doc/flame/inputs/gesture-input.md
- doc/flame/inputs/keyboard-input.md
- doc/flame/inputs/other-inputs.md
- doc/flame/other/widgets.md
- doc/flame/rendering/images.md
- doc/flame/rendering/layers.md
- doc/flame/rendering/text.md
- doc/flame_audio/audio.md
- doc/flame_forge2d/flame_forge2d.md
- doc/flame_forge2d/forge2d.md
- doc/index.md
Some links still remain broken after #1663, as reported by linkcheck. This PR fixes all of them, except these 5:
- https://examples.flame-engine.org/#/Collision%20Detection_Circles
- https://examples.flame-engine.org/#/Collision%20Detection_Shapes%20without%20components
- https://examples.flame-engine.org/#/Collision%20Detection_Multiple%20shapes
- https://examples.flame-engine.org/#/Rendering_Isometric%20Tile%20Map
- https://examples.flame-engine.org/#/Controls_Joystick
Some of these links are actually working, but the script cannot verify that without executing javascript. Not sure what to do about these -- perhaps either the example page needs to be updated so that it lists which links it has; or we directly include these examples into the docs page?
- [-] I have updated/added tests …
> docs: Fix remaining broken and redirected links

- packages/flame/lib/src/game/game_widget/game_widget.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/test/game/game_widget/game_widget_test.dart
Make sure that subscription to `GameStateChange` events is properly updated when the `game:` property of a `GameWidget` changes.
Closes #1658
> fix: Subscription for events when game changes in GameWidget

- packages/flame/lib/src/components/component.dart
- packages/flame/test/components/component_lifecycle_test.dart
`changeParent` should be allowed even when the current parent is null.
> feat: Allow changing parent from null parent

- packages/flame/lib/src/components/component.dart
- packages/flame/lib/src/components/component_set.dart
This was a planned move once we'd switch to Dart 2.15; and we're already on 2.16 since #1617.
> refactor: Deprecate ComponentSet.createDefault()

- packages/flame/lib/src/game/game_widget/game_widget.dart
We were planning to make this change once we upgrade min Dart version to 2.16; which we finally did in #1617.
> feat: Keep stacktrace when rethrowing an error from GameWidget

- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/lib/src/experimental/geometry/shapes/polygon.dart
- packages/flame/lib/src/geometry/line_segment.dart
In some places in code we used patterns like `fold(0, (a, b) => a + b)`, which can be replaced with a simple `.sum` from the Iterable extension.
> refactor: Replace some usages of fold<> with .sum

- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/base_future_builder.dart
- packages/flame/lib/src/widgets/nine_tile_box.dart
- packages/flame/lib/src/widgets/sprite_button.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
- packages/flame/test/widgets/nine_tile_box_widget_test.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
- packages/flame/test/widgets/sprite_button_test.dart
- packages/flame/test/widgets/sprite_widget_test.dart
At first, In #1667, I was planning to change only `SpriteWidget` to be able to remove showing LoadingBuilder when non-future sprite was passed.
But after some digging, I found that BaseFutureBuilder causes the loading because it only accepts Future as a parameter.
And `BaseFutureBuilder` are the very base of all image-related widgets such as NineTileBoxWidget, SpriteAnimationWidget, ... etc.
So the key point of this change should allow BaseFutureBuilder to FutureOr as a parameter and split the build function according to the parameter type.
After #1645, the Default constructor of SpriteButton can pass Future<Sprite> but its constructor is not consistent with other image-related widgets.
Plus, type of `FutureOr<List<Sprite>> _buttonsFuture` only compatible with `Future<List<Sprite>>` but …
> feat!: Add ability to render without loading on image related widgets

- packages/flame/lib/events.dart
- packages/flame/lib/input.dart
- packages/flame/lib/src/events/flame_drag_adapter.dart
- packages/flame/lib/src/events/game_mixins/multi_touch_drag_detector.dart
- packages/flame/lib/src/events/interfaces/multi_drag_listener.dart
- packages/flame/lib/src/game/game_widget/gestures.dart
- packages/flame/lib/src/game/mixins/game.dart
- packages/flame/lib/src/game/mixins/has_draggables.dart
- packages/flame/lib/src/gestures/detectors.dart
Created `MultiDragListener` abstract class, which allows us to simplify code in `gestures.dart`.
> refactor: Added MultiDragListener - common API between HasDraggables and MultiTouchDragDetector

- doc/flame/effects.md
- examples/games/padracing/lib/padracing_game.dart
- packages/flame/lib/src/effects/anchor_by_effect.dart
- packages/flame/lib/src/effects/anchor_effect.dart
- packages/flame/lib/src/effects/anchor_to_effect.dart
- packages/flame/lib/src/effects/color_effect.dart
- packages/flame/lib/src/effects/component_effect.dart
- packages/flame/lib/src/effects/effect.dart
- packages/flame/lib/src/effects/move_along_path_effect.dart
- packages/flame/lib/src/effects/move_by_effect.dart
- packages/flame/lib/src/effects/move_effect.dart
- packages/flame/lib/src/effects/move_to_effect.dart
- packages/flame/lib/src/effects/opacity_effect.dart
- packages/flame/lib/src/effects/remove_effect.dart
- packages/flame/lib/src/effects/rotate_effect.dart
- packages/flame/lib/src/effects/scale_effect.dart
- packages/flame/lib/src/effects/sequence_effect.dart
- packages/flame/lib/src/effects/size_effect.dart
- packages/flame/lib/src/effects/transform2d_effect.dart
- packages/flame/test/effects/effect_test.dart
Adding `onComplete` as optional parameter to all the effects and deprecating `onFinishCallback`.
- [NA] I have updated/added tests for ALL new/updated/fixed functionality.
- [NA] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [NA] I have updated/added relevant examples in `examples`.
Fixes #1683
> refactor: Add onComplete as optional parameter

- doc/flame/components.md
Changed docs for Parallax component. Since Parallax component already has a HasGameRef mixin, it's not possible to add the mixin again.
> docs: fix incorrect gameref on `ParallaxComponent`

- packages/flame_test/lib/src/flame_test.dart
Add test options to enclosing test function on `flame_test`.
This allows users to skip or tag individual tests.
> feat: add options to flame test

- examples/lib/stories/input/joystick_player.dart
- packages/flame/lib/components.dart
- packages/flame/lib/src/components/input/button_component.dart
- packages/flame/lib/src/components/input/hud_button_component.dart
- packages/flame/lib/src/components/mixins/component_viewport_margin.dart
- packages/flame/lib/src/components/mixins/viewport_margin.dart
- packages/flame/test/components/button_component_test.dart
- packages/flame/test/components/hud_button_component_test.dart
- packages/flame/test/game/flame_game_test.dart
- packages/flame_test/lib/src/mock_gesture_events.dart
Created a mixin to handle the margin to the viewport, mostly to remove the code duplication in `ButtonComponent` and `HudButtonComponent`, but it can also be useful in other cases when you don't want to wrap your component in `HudMarginComponent`.
Once the new camera system is in place this will of course have to be replaced.
> feat: Callbacks in `HudButtonComponent` constructor and `ViewportMargin` mixin to avoid code duplication

- packages/flame/pubspec.yaml
- packages/flame_bloc/pubspec.yaml
- packages/flame_fire_atlas/pubspec.yaml
- packages/flame_svg/pubspec.yaml
When running `melos bootstrap`, I realized flame was loading a very old mocktail version that actually has an issue with they dart version constraint:
```
[luan@aurora flame]$ melos bootstrap
melos bootstrap
└> /home/luan/projects/gamedev/flame/flame
Running "flutter pub get" in workspace packages...
Note: this may take a while in large workspaces such as this one.
✓ examples
└> examples
- flame
└> packages/flame
└> Failed to install.
Running "flutter pub get" in flame...                           
Error on line 8, column 8 of /home/luan/.pub-cache/hosted/pub.dartlang.org/mocktail-0.1.2/pubspec.yaml: Invalid version constraint: Expected version number after ">=" in ">=2.12-0-0 <3.0.0", got "2.12-0-0 <3.0.0".
╷
8 │   sdk: ">=2.12-0-0 <3.0.0"
│        ^^^^^^^^^^^^^^^^^^^
╵
pub get failed …
```
> refactor: Update and guarantee consistency on mocktail dev dependency version across repo

- packages/flame/lib/src/game/camera/camera.dart
Add warning about very large numbers on the camera class
Fixes https://github.com/flame-engine/flame/issues/1126
> docs: Add warning about very large numbers on the camera class

- examples/lib/main.dart
- packages/flame/test/components/button_component_test.dart
- packages/flame/test/components/hud_button_component_test.dart
- packages/flame/test/components/hud_margin_component_test.dart
- packages/flame/test/components/sprite_animation_component_test.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
- packages/flame/test/components/sprite_component_test.dart
- packages/flame/test/components/sprite_group_component_test.dart
- packages/flame/test/game/game_widget/game_widget_keyboard_test.dart
- packages/flame/test/widgets/nine_tile_box_widget_test.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
- packages/flame/test/widgets/sprite_button_test.dart
- packages/flame/test/widgets/sprite_widget_test.dart
- packages/flame_audio/example/lib/main.dart
- packages/flame_fire_atlas/example/lib/main.dart
- packages/flame_forge2d/example/lib/main.dart
- packages/flame_lint/lib/analysis_options.yaml
- Fix warnings raised by the `avoid_void_async` lint rule;
- Remove rule `use_enums`, which is not available in Dart 2.16
> chore: Fix some of the remaining lint problems

- packages/flame/lib/src/game/camera/camera.dart
Turns out we have two ways of accessing camera position: `position` is for the outside, it creates a copy. This method was already non-static and accessing `_position` via this, so I just removed both parameters to make it less confusing.
> refactor: Remove unecessary copy operation on Camera

- packages/flame/lib/src/game/game_widget/game_widget.dart
- packages/flame/lib/src/game/game_widget/gestures.dart
- packages/flame/lib/src/gestures/detectors.dart
The "basic" gesture detectors widget was creating a `RawGestureDetector` underneath, which resulted in two nested `RawGestureDetectors`, each with its own gesture arena.
This refactor combines the two gesture detectors into a single one.
> refactor: Merge basic and advanced gesture detectors in GameWidget

- packages/flame_bloc/lib/src/flame_bloc_listenable.dart
- packages/flame_bloc/test/src/flame_bloc_listenable_test.dart
This PR adds a getter to the `FlameBlocListenable` mixin. This getter will allow to use `FlameBlocListenable` as a standalone mixin to react to new states via `onNewState()`, access the current `state`, and also add events to the listenable Bloc via the `bloc` property.
Currently a workaround to give components this functionality is to use `FlameBlocListenable` and `FlameBlocReader` in parallel.
Fixes https://github.com/flame-engine/flame/issues/1694
> feat: adding bloc getter to FlameBlocListenable mixin

- doc/flame/game_widget.md
The return type of [GameWidget docs](https://docs.flame-engine.org/1.2.0/flame/game_widget.html) should be `Widget` instead of `void`
Fixes #1735
> docs: Return Widget instead of void in the game_widget.md

- packages/flame/lib/src/experimental/camera_component.dart
- packages/flame/lib/src/experimental/world.dart
- packages/flame/test/experimental/camera_component_test.dart
The `componentsAtPoint` function allows us to find a component located at a specific position. Usually it is applied to the top-level Game, but there are instances when it could also be useful to apply this function to the `World` component. This PR enables such functionality.
> fix: World component can now be queried with `componentsAtPoint`

- packages/flame_lint/README.md
Fix dangerous typo on flame_lint docs
> docs: Fix dangerous typo on flame_lint docs

- packages/flame/lib/src/game/game.dart
- packages/flame/test/_resources/custom_flame_game.dart
- packages/flame/test/game/active_overlays_test.dart
The problem was that the variable `_ActiveOverlays._game` was assigned too late, and as a result the request to refresh the widget was silently dropped.
Closes #1757 
> fix: Overlays can now be properly added during onLoad

- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
Currently, `AnimationWidget` is using a millisecond of the current second as elapsed time since the last frame.
It is dangerous because when the last frame occurs at end of the second and the current frame at the start of the second.
```
e.g. 
Last frame: 08:00:00.990
Current frame: 08:00:01.006
```
When the above situation occurs, `dt` became 0 and the SpriteAnimation does not update.
Changed to using elapsed time as subtraction of `microsecondsSinceEpoch` between frames.
Fixes https://github.com/flame-engine/flame/issues/1765 …
> fix: Change AnimationWidget to use epoch time 

- doc/_sphinx/extensions/flutter_app.css
- doc/_sphinx/extensions/flutter_app.py
- doc/_sphinx/theme/flames.css
- doc/development/documentation.md
Additional mode "infobox" allows Flutter widgets to be inserted into the generated documentation site as wikipedia-style infoboxes floating on the right. This is useful for presenting content to the user up-front without sacrificing the flow of the exposition. For example, currently the [Tap Events demo](https://docs.flame-engine.org/main/flame/inputs/tap-events.html#demo) is "hidden" in the middle of a long page.
We believe that presenting the content in this way would make the user more excited to read about it.
This is …
> docs: Added ability to create infobox-style widgets in the documentation

- packages/flame/lib/src/extensions/vector2.dart
- packages/flame/test/extensions/vector2_test.dart
Adding `projection`, `ìnvert` and `inverted` to the vector extension.
> feat: Add vector projection and inversion

- packages/flame/lib/src/components/sprite_component.dart
Missing `children` argument on the named constructor.
> feat: add `children` argument to `SpriteComponent.fromImage`

- README.md
- i18n/README-ES.md
- i18n/README-JA.md
- i18n/README-PL.md
- i18n/README-RU.md
- i18n/README-ZH.md
The images path under sponsors has a relative path from the repository, which are being changed to absolute path (starting with https)
There are no breaking changes for this PR. The only changes are the image path changes in README (and translations) which now point to the images actual path in web
The other 3 checks are not required.
Fixes #1795 
> docs: replace images in README with absolute path

- doc/_sphinx/conf.py
- doc/_sphinx/scripts/menu-expand.js
add an event listener to the docs site to listen everytime on load, then
expand the first expandable section ("flame") if the current page is
home page.
This PR includes a new js file that handles every load of the documentation site to auto expand flame section when in home page (the main index page) and leaves as it is in the other pages.
The other small change makes this file include in the build.
The other 3 checks are not required.
Fixes #1773 
> docs: auto expand flame section on documentation home page

- doc/_sphinx/conf.py
- doc/_sphinx/scripts/menu-expand.js
add an event listener to the docs site to listen everytime on load, then
expand the first expandable section ("flame") if the current page is
home page.
> docs: Auto expand flame section on documentation home page (#1823)

- packages/flame/lib/src/components/input/joystick_component.dart
JoystickComponent inherits from HudMarginComponent, and HudMarginComponent positionType= Viewport, so the delta here should use viewport
> fix: JoystickComponent drags using the delta Viewport 

- packages/flame/lib/src/widgets/sprite_button.dart
This PR fixes an issue in which the `SpriteButton` appears as pressed when the user cancelled its press by dragging its finger away from the `SpriteButton`, releasing it outside.
Fixes #1843
> fix: SpriteButton tap cancellation

- doc/flame/collision_detection.md
- packages/flame/lib/src/collisions/collision_detection.dart
- packages/flame/lib/src/collisions/standard_collision_detection.dart
- packages/flame/test/collisions/collision_detection_test.dart
A lot of the time it is useful to be able to ignore certain hitboxes, if you are for example casting rays from within the hitbox of one of your components. This PR adds this functionality to `raycast`, `raycastAll` and `raytrace`.
> feat: Possibility to ignore hitboxes for ray casting

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
- packages/flame_bloc/example/lib/src/game/game.dart
Since `removeWhere` will be removed from the `ComponentSet` in #1877 we should expose it on the component.
> feat: Add `removeWhere` to `Component`

- packages/flame/lib/src/components/core/component_set.dart
These methods should never have been exposed, since you bypass the component lifecycle with them.
For most methods `Component` has the corresponding methods directly on it already.
For example, instead of using `component.children.addAll` you should do `component.addAll`.
Depends on #1878 
> fix!: Make all `ComponentSet` modifications internal

- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/sprite_painter.dart
As-Is
`SpriteAnimationWidget` is re-rendering even if the frame index is not changed. This wastes the resource.
To-Be
`SpriteAnimationWidget` now only re-renders(call setState) only when the frame index is changed.
Additionally, the `canvas.renderRotated` is called in `SpritePainter` even though the rotation angle is 0. I think it is not needed. …
> perf: SpriteAnimationWidget will re-render only when needed

- packages/flame/lib/src/particles/composed_particle.dart
- packages/flame/test/particles/composed_particle_test.dart
Existing behavior: `ComposedParticle` takes `lifespan` and `children` as a constructor argument. At the construction time `lifespan` is propagated to all child particles. 
New behavior: `ComposedParticle` has an extra optional parameter `applyLifespanToChildren`. If set to `true` then existing behavior is preserved and all child particles will be assigned the lifespan of `ComposedParticle`, if set to `false` child particles will keep their original lifespan. If a particle lifecycle ends before `ComposedParticle` ends then it is removed from children.
`applyLifespanToChildren` is set to `true` by default for backward compatibility. 
<strike>Please note, that this is a proposal. I will update the docs and examples if the approach is approved.</strike>
[x] No, this is not a breaking change. …
> feat: Allow children of `ComposedParticle` to have varied lifespan

- packages/flame_tiled/lib/src/tiled_component.dart
- packages/flame_tiled/test/tiled_test.dart
Update `TiledComponent` to extend `PositionComponent` instead of `Component`. With some quirks:
1. Size is computed from the Map and not settable. I've made these operations fail silently for now.
2. Width and Height setters by proxy are ignored.
3. Scale does work
I do not believe this is breaking, since tests are still passing. It is only adding functionality to TiledComponent.
Fixes #1890
> feat: Tiled component is positionable

- README.md
Cleans up the readme by removing the "Getting started" section, since that is already covered in the "Documentation" section.
> docs: Clean up readme to avoid repetitions

- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
Since the `hitboxParent` will be needed from outside of the hitbox, protected is removed and turned into a getter instead.
Related to #1894 
> fix: Expose hitboxParent from Hitbox

- packages/flame/lib/src/components/input/sprite_button_component.dart
This PR makes the internal button state of `SpriteButtonComponent` public. This will make it easier for users to manually change the button state, if needed, by change the value of `current`. One use case discussed on discord was to make the button appear visually pressed on press on a key.
Closes #1940
> feat: Make _ButtonState public for SpriteButtonComponent

- packages/flame_forge2d/lib/forge2d_camera.dart
This PR adds the optional named parameter useCenterOfMass to followBodyComponent. It defaults to false so no breaking changes. Setting true allows camera following that does not "wobble" when an otherwise stationary BodyComponent (with an offset centre of mass) rotates.
Also removed reference to component anchor in documentation/comments since BodyComponent does not use an anchor.
Closes #1947 
> feat: Allow followBodyComponent to follow centre of mass (#1947)

- packages/flame/lib/src/collisions/broadphase/quadtree/has_quadtree_collision_detection.dart
- packages/flame/lib/src/collisions/collision_callbacks.dart
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
`onComponentTypeCheck` was only supported for components but not for hitboxes, because ShapeHitbox implements `GenericCollisionCallbacks` instead `CollisionCallbacks`.
Specifying `onComponentTypeCheck` for individual hitboxes might be useful in cases where `Component` have hitboxes for collisions and also some utility hitboxes (for example, to check available directions for pathfinding). Colliding between this two types of hitboxes should not lead to movement restrictions and so on. But without `onComponentTypeCheck` in `ShapeHitbox` we can not to perform such check.
> feat: onComponentTypeCheck support for ShapeHitbox

- .gitignore
- melos.yaml
`melos doc-xyz` commands were not working on Windows as `SOURCEDIR` was not properly getting set. I tried changing it to use `set SOURCEDIR="$MELOS_ROOT_PATH/doc"` and `set SOURCEDIR="%MELOS_ROOT_PATH%/doc"`, but both didn't work. As `SOURCEDIR` isn't really necessary to be set for the commands to work, this PR remove that variable and directly using `$MELOS_ROOT_PATH/doc` in its place.
Additionally, this PR also adds `.venv` (a common folder storing virtual env) to gitignore.
NA …
> fix: Melos sphinx scripts windows

- doc/_sphinx/Makefile
- doc/development/documentation.md
If we don't ignore the build directories it will build multiple times unnecessarily when doing the live build.
Also tried to solve the "spaces in path" problem, but that is blocked by this:
https://github.com/ipython/ipython/pull/13765
> fix: Ignore the build directories for sphinx builds

- doc/development/documentation.md
Fix several errors reported during documentation build.
Generally speaking,
``````
```foo
``````
would be interpreted as a code block with the language `foo`; while
``````
```{foo}
``````
would be interpreted as a Sphinx directive `.. foo`.
> docs: Fix documentation markup errors

- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/lib/src/events/component_mixins/tap_callbacks.dart
- 🐛 Event component_mixins missing `@mustCallSuper` added
> fix: EventComponentMixins missing `@mustCallSuper` added

- doc/_sphinx/theme/flames.css
the language tag for code blocks used to move along with scroll of code. Now, with this commit, the tag will be fixed at the top and doesn't move with scroll
This commit makes a few css style changes in order that the language tags for code blocks in documentation site remains same even when horizontally scrolled.
Along with the above, this commit adds right padding to the code as to not come under the language tag when reaching the end.
Screenrecording:
https://user-images.githubusercontent.com/40348358/194294111-2d966f9e-2600-45b6-ab25-b15bf9d57770.mov
- [-] I have updated/added relevant examples in `examples` or …
> docs: make the language tag non moving in code blocks

- packages/flame/test/events/component_mixins/drag_callbacks_test.dart
- packages/flame/test/events/component_mixins/tap_callbacks_test.dart
- packages/flame/test/events/game_mixins/multi_touch_drag_detector_test.dart
- packages/flame/test/events/game_mixins/multi_touch_tap_detector_test.dart
- 🐛 fix: #2017: Unit tests for event mixins
-  Unit and Widget tests for Event Mixin
- `DragCallbacks`
- `TapCallbacks`
- `MultiTouchDragDetector`
- `MultiTouchTapDetector`
Closes #2017 
- I will add more widget test in next PR
> test: Unit tests for event mixins - `DragCallbacks` and `TapCallbacks`

- packages/flame/test/events/component_mixins/drag_callbacks_test.dart
- packages/flame/test/events/component_mixins/tap_callbacks_test.dart
- packages/flame/test/events/game_mixins/multi_touch_tap_detector_test.dart
- packages/flame_test/lib/flame_test.dart
- packages/flame_test/lib/src/mock_tap_drag_events.dart
- 🚨 Widget test for `DragCallbacks` and `TapCallbacks`
- Added some common function in separate file for common use case
- Minor test case description changed for `MultiTouchTapDetector`
- Added some common function in 1 file, not sure it's breaking change or not
> test: Widget tests for Event Mixins - `DragCallbacks` and `TapCallbacks`

- doc/development/contributing.md
- doc/development/development.md
As discussed in #2045, this PR makes the CONTRIBUTING doc also visible from the main documentation site.
> docs: Link CONTRIBUTING file into the docs

- packages/flame/lib/src/components/mixins/has_paint.dart
- packages/flame/test/effects/opacity_effect_test.dart
When applying OpacityEffect to a specific `paintId`, the paint at that id was accidently getting replaced with the default `paint`. This PR makes sure that color from the provided `paintId` is used while modifying `alpha` and `opacity` in `HasPaint` mixin.
Closes #2055
> fix: OpacityEffect custom paint override

- packages/flame/lib/src/geometry/polygon_component.dart
- packages/flame/lib/src/geometry/shape_intersections.dart
PolygonComponent used to modify the contents of the _vertices list passed to it by offsetting them all by _topLeft. This prevented the user from using the same vertices list again, such as in another call to PolygonComponent. This PR stops PolygonComponent from directly modifying the list vectors and instead add the _topLeft offset where needed within internal code.
This is a breaking change since PolygonComponent's .vertices getter will now return the original, unmodified vertices rather than with the offset added.
Yes, to obtain the previous values of PolygonComponent .vertices subtract the polygon's top-left point vector from all vectors in the list returned the new output. …
> fix!: PolygonComponent no longer modifies _vertices

- doc/flame/effects.md
- doc/flame/examples/lib/move_along_path_effect.dart
- doc/flame/examples/lib/move_by_effect.dart
This commit fixes the interactive examples of move effect (by and along path). The were not coming to their original position. This commit fixes the flower to come to original position when clicked 2nd time.
This also arranges the code in multi line for the move effects in documentation.
Screen Recordings:
https://user-images.githubusercontent.com/40348358/194905713-3265a3a3-0557-4153-93dc-a81314087720.mov
https://user-images.githubusercontent.com/40348358/194905753-405e673c-0f19-4e19-b200-9e5835ff6d20.mov
Not …
> docs: fix move effect interactive examples reset

- packages/flame_rive/lib/src/rive_component.dart
- packages/flame_rive/test/flame_rive_test.dart
Fixed null exception when no artboard with specified name is exists and added necessary test.
Closes #2043 
> fix: [flame_rive] fixed null exception when no artboard with specified name is exists

- doc/_sphinx/Makefile
Previously it didn't work properly with the live examples.
Closes #2079
> docs: Fix documentation auto re-build

- doc/development/documentation.md
- melos.yaml
This commit replaces the `melos doc-build-live` with `melos doc-serve`.
This also changes documentation for this while removing the mention of `make` commands in the documentation.
The users doesn't need to update anything. The only thing is that, when building documentation locally, the command `melos doc-build-live` won't work and instead have to use `melos doc-serve`
- [-] No, this PR is not a breaking change.
Closes #2075 
> docs!: replace doc-build-live with doc-serve

- doc/flame/effects.md
- doc/flame/examples/lib/main.dart
- doc/flame/examples/lib/size_by_effect.dart
- doc/flame/examples/lib/size_to_effect.dart
Doc examples for SizeEffect.to and SizeEffect.by.
I used the Ember because the Flower gave script errors when trying to size.
Closes #1952
> docs: Interactive SizeEffect examples in doc.

- packages/flame/lib/src/cache/memory_cache.dart
- packages/flame/test/cache/memory_cache_test.dart
- packages/flame_svg/lib/svg.dart
- packages/flame_svg/test/_resources/android.svg
- packages/flame_svg/test/svg_test.dart
<details>
<summary>Run this minimal example:</summary>
```
import 'package:flame/game.dart';
import 'package:flame_svg/flame_svg.dart';
import 'package:flutter/material.dart';
void main() {
final game = MyGame();
runApp(
MaterialApp(
home: Scaffold(
floatingActionButton: FloatingActionButton(
onPressed: game.removeSvgs,
),
body: GameWidget(
game: game,
),
),
),
);
}
class MyGame extends FlameGame {
late Svg svgInstance;
void removeSvgs() {
removeAll(children.query<SvgComponent>());
}
@override
Future<void> onLoad() async {
await super.onLoad();
svgInstance = await loadSvg('android.svg');
addAll(
List.generate(
2,
(index) => SvgComponent(
svg: svgInstance,
position: Vector2.all(100 + index * 100),
size: Vector2.all(100 + index * 100),
),
),
);
}
}
```
</details>
Tap on the floating action …
> fix: Exception when having multiple calls to dispose() function of a Svg instance

- CONTRIBUTING.md
> docs: Fix broken links to style guide and test writing guide

- doc/flame/camera_component.md
- packages/flame/lib/src/experimental/world.dart
With this `World` can make use of the `children` argument to `Component`.
> feat: Add children to `World` constructor

- .github/workflows/gh-pages.yml
This should trigger the documentation build to run, so that we don't have to trigger it manually.
> ci: Trigger docs build on merge

- doc/_sphinx/conf.py
- doc/bridge_packages/flame_tiled/flame_tiled.md
- doc/bridge_packages/flame_tiled/layers.md
- doc/bridge_packages/flame_tiled/tiled.md
Some of the formatting was broken, so this PR fixes that.
Also enabled some new features of MyST that were added recently.
> docs: Formatting clean up in the flame_tiled docs

- examples/README.md
Noticed the `examples` folder README was a bit outdated:
1. it was still linked to the old repo build
2. it still mentioned v1 migration
I also improved punctuation.
> docs: Fix examples folder README

- examples/lib/stories/animations/animations.dart
- examples/lib/stories/animations/benchmark_example.dart
This adds an example so that you can test how many `SpriteAnimationComponent`s that you can add before starting to drop FPS on the platform that you are running the examples on.
It adds 100 embers per tap.
> docs: SpriteAnimation benchmark example

- doc/flame/effects.md
- packages/flame/lib/src/effects/glow_effect.dart
This PR marks the recently added `GlowEffect` as experimental, indicating that we will likely need to change its API soon.
> chore: Mark GlowEffect as experimental

- packages/flame_jenny/jenny/lib/src/parse/tokenize.dart
- packages/flame_jenny/jenny/test/parse/tokenize_test.dart
The whitespace will now be trimmed at the end of expressions like
```
Line1 #foo
Line2 // bar
Line3\s+
```
> feat(jenny): Trim whitespace at the end of dialogue lines

- packages/flame_jenny/jenny/lib/src/parse/parse.dart
- packages/flame_jenny/jenny/lib/src/variable_storage.dart
- packages/flame_jenny/jenny/test/structure/commands/set_command_test.dart
The `<<set>>` command is used to modify existing variables.
> feat(jenny): Added the <<set>> command

- doc/flame/diagrams/component.md
The text on the abstract classes wasn't readable on the old one and loadable doesn't exist anymore, this is the new one:
> docs: Fix component diagram text styling

- packages/flame/lib/src/components/input/button_component.dart
- packages/flame/lib/src/components/input/hud_button_component.dart
- packages/flame/test/components/button_component_test.dart
- packages/flame/test/components/hud_button_component_test.dart
Adds `onCancelled` to `ButtonComponent` and `HudButtonComponent`
https://github.com/flame-engine/flame/issues/2191#issuecomment-1328051507
> feat: add onCancelled to ButtonComponent and HudButtonComponent

- .github/workflows/gh-pages.yml
Instead of the curl command, it uses the integrated [gh cli tool](https://cli.github.com/).
The workflow ID corresponds to the flame-docs-site's gh-pages.yml. 
You can get the workflow id running the gh tool on your computer, via
gh workflow list  -R flame-engine/flame-docs-site
This pr assumes that a personal access token, `docs_token`, can access the flame-docs-site repository and trigger workflows.
> fix: Build flame-docs-site on push

- .github/workflows/gh-pages.yml
Since we're getting this error message when trying to use `gh`, I tried adding the `gh_token`.
```
Run gh workflow run 13757924 -R flame-engine/flame-docs-site
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
Error: Process completed with exit code 4.
```
> ci: Try adding GH_TOKEN too

- packages/flame/lib/src/particles/image_particle.dart
Since it is very bad to create paint-objects in the render loop this PR moves out the paint object and lets the user set the paint object manually.
> fix: Re-use paint object in ImageParticle

- .github/cspell.json
This prevents the same typo happening again.
Followup for #2225.
> docs: Add "teh" as a flag word in spellchecker

- doc/_sphinx/extensions/yarn_lexer.py
- doc/_sphinx/theme/flames.css
- doc/other_modules/jenny/language/commands/commands.md
- doc/other_modules/jenny/language/commands/user_defined_commands.md
- doc/other_modules/jenny/runtime/command_storage.md
- doc/other_modules/jenny/runtime/index.md
- doc/other_modules/jenny/runtime/user_defined_command.md
- doc/other_modules/jenny/runtime/yarn_project.md
- packages/flame_jenny/jenny/analysis_options.yaml
- packages/flame_jenny/jenny/lib/src/command_storage.dart
- packages/flame_jenny/jenny/lib/src/structure/commands/user_defined_command.dart
- packages/flame_jenny/jenny/lib/src/structure/line_content.dart
- packages/flame_jenny/jenny/test/command_storage_test.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
- packages/flame_jenny/jenny/test/dialogue_view_test.dart
- packages/flame_jenny/jenny/test/structure/commands/user_defined_command_test.dart
- packages/flame_jenny/jenny/test/test_scenario.dart
- Class `UserDefinedCommand` now exposes `argumentString` and `arguments` properties, allowing them to be queried in a DialogueView;
- Make sure the arguments of a user-defined command are computed only once per invocation;
- Added documentation for user-defined commands;
- `addDialogueCommand` renamed into `addOrphanedCommand`.
Closes #2217
> feat: Arguments of a UserDefinedCommand are now accessible

- .github/workflows/title-validation.yml
This (hopefully) fixes bad configuration for title validator, pushed in PR #2227.
Looks like the title validator is configured to always use the configuration from main instead of the current branch, which means we can only know if it works after pushing it to main:
> Also if you change the configuration in a PR, the changes will not be reflected for the current PR – only subsequent ones after the changes are in the main branch.
> ci: Fix title validator

- .github/workflows/title-validation.yml
- doc/other_modules/jenny/runtime/dialogue_runner.md
- doc/other_modules/jenny/runtime/dialogue_view.md
- packages/flame_jenny/jenny/lib/src/dialogue_runner.dart
- packages/flame_jenny/jenny/lib/src/dialogue_view.dart
- packages/flame_jenny/jenny/lib/src/structure/commands/jump_command.dart
- packages/flame_jenny/jenny/lib/src/structure/commands/stop_command.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
- packages/flame_jenny/jenny/test/dialogue_view_test.dart
- packages/flame_jenny/jenny/test/structure/commands/jump_command_test.dart
- packages/flame_jenny/jenny/test/structure/commands/user_defined_command_test.dart
- packages/flame_jenny/jenny/test/structure/expressions/functions/visit_count_test.dart
- packages/flame_jenny/jenny/test/test_scenario.dart
- The `onNodeFinish` event is a counterpart to `onNodeStart`.
- This also fixes a small bug where node visit count was not properly incremented if the node was exited via a `<<stop>>`.
- The `DialogueRunner.runNode()` method renamed into `startDialogue()`.
Closes #2215
> feat: Added DialogueView.onNodeFinish event

- doc/flame/components.md
- examples/lib/stories/bridge_libraries/flame_isolate/simple_isolate_example.dart
- examples/lib/stories/camera_and_viewport/camera_component_example.dart
- examples/lib/stories/collision_detection/bouncing_ball_example.dart
- examples/lib/stories/collision_detection/raycast_max_distance_example.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/game/game.dart
- packages/flame_isolate/example/lib/brains/worker_overmind_hud.dart
- packages/flame_isolate/example/lib/units/actions/movable.dart
- packages/flame_lottie/example/pubspec.yaml
- packages/flame_rive/example/lib/main.dart
Before this PR, the return type of `onLoad()` was `Future<void>?`, after this PR the return type is `FutureOr<void>` -- both for classes `Component` and `Game`. 
Reasons:
- The use of `FutureOr` is more idiomatic in Dart, this class was specifically created in order to be used in situations like ours.
- This makes learning Flame easier for beginners, since you no longer need to explain what asynchronous programming is from the start (and `onLoad()` is one of the first methods the user encounters in Flame).
- The code can be cleaner in case when `onLoad` doesn't need to be async. 
With new approach, the `onLoad()` method can be overridden as either
```dart
@override
Future<void> onLoad() async { ... }
```
or
```dart
@override
void onLoad() { ... }
```
Of course, it can also be overridden …
> refactor!: The method `onLoad()` now returns `FutureOr<void>`

- doc/other_modules/jenny/runtime/dialogue_view.md
- packages/flame_jenny/jenny/lib/src/dialogue_runner.dart
- packages/flame_jenny/jenny/lib/src/dialogue_view.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
Previously, `onDialogueChoice` was returning a never-completing future, which is both more error-prone, and prevents a use-case where a dialogue view would perform some async action without ultimately making a selection.
Closes #2216
> feat: OnDialogueChoice now returns null by default

- doc/other_modules/jenny/language/commands/commands.md
- doc/other_modules/jenny/language/commands/jump.md
- doc/other_modules/jenny/language/commands/visit.md
- packages/flame_jenny/jenny/lib/src/command_storage.dart
- packages/flame_jenny/jenny/lib/src/dialogue_runner.dart
- packages/flame_jenny/jenny/lib/src/parse/parse.dart
- packages/flame_jenny/jenny/lib/src/parse/token.dart
- packages/flame_jenny/jenny/lib/src/parse/tokenize.dart
- packages/flame_jenny/jenny/lib/src/structure/commands/visit_command.dart
- packages/flame_jenny/jenny/test/dialogue_view_test.dart
- packages/flame_jenny/jenny/test/parse/token_test.dart
- packages/flame_jenny/jenny/test/structure/commands/jump_command_test.dart
- packages/flame_jenny/jenny/test/structure/commands/visit_command_test.dart
The functionality of the `<<visit Target>>` command is that the dialogue runner will temporarily suspend execution of the current node and start executing Target, but then once that finishes it will resume executing the original node.
> feat: Added command <<visit>>

- doc/bridge_packages/flame_forge2d/forge2d.md
Forge2D/Box2D doesn't have a concept of nested bodies and all bodies should live on a top level in the physics world. However, it's hard to know this for people who stat with Forge2d right away. It would be nice to have it clearly mentioned in the documentations.
Closes #2240
> docs: BodyComponents should not be nested

- doc/README.md
> docs: Fix broken markdown on docs readme file

- doc/_sphinx/scripts/versions.js
- doc/_sphinx/theme/flames.css
- doc/_sphinx/theme/layout.html
See details on issue #2214
Basically, we want to make users more aware they are looking at old version of the docs.
Fixes #2214
> docs: Add warning to version-specific docunmentation pages

- packages/flame/example/lib/main.dart
We shouldn't teach our users to create new `Rect` objects in `render`.
Also switching to `onTapDown` since `onTapUp` won't trigger if you move the mouse since it'll be a drag event instead.
> docs: Update example to not create Rect objects

- .github/ISSUE_TEMPLATE/1_bug.md
Adds a link to https://zapp.run/edit/flame-zh006agh106 in the issue template, since Flame is already set up in there it is incredibly easy to share and run MREs from there.
> docs: Add Flame Zapp link to bug issue template

- doc/_sphinx/extensions/yarn_lexer.py
- doc/other_modules/jenny/language/expressions/functions/functions.md
- doc/other_modules/jenny/language/expressions/functions/misc.md
- packages/flame_jenny/jenny/lib/src/structure/expressions/functions/_common.dart
- packages/flame_jenny/jenny/lib/src/structure/expressions/functions/if.dart
- packages/flame_jenny/jenny/test/structure/expressions/functions/if_test.dart
The `if()` function can be used in place of a ternary-if operator.
Closes #2239
> feat: Added if() built-in function in Jenny

- packages/flame/lib/src/sprite.dart
This creates two new private vector2 objects that can be re-used inside of `Sprite.render` so that we don't have to create new objects in there.
> perf: Avoid Vector2 creation in `Sprite.render`

- doc/other_modules/jenny/language/language.md
- doc/other_modules/jenny/language/markup.md
- packages/flame_jenny/jenny/lib/src/parse/tokenize.dart
- packages/flame_jenny/jenny/test/structure/dialogue_line_test.dart
Added documentation for the markup syntax in Jenny.
- Fixed a small bug with spaces surrounding a self-closing markup tag.
Closes #2235
> docs: Documentation for markup in Jenny

- doc/_sphinx/theme/flames.css
Currently if you navigate to any inner page on the documentation site, say https://docs.flame-engine.org/main/tutorials/platformer/step_5.html, then the menus on the left that are currently collapsed can be expanded, but those that are already expanded cannot be collapsed (try clicking on the arrow next to "Tutorials" or "Ember Quest"). This PR fixes that.
Hopefully not.
> style: Properly collapse left-side menu on the docs site

- doc/_sphinx/extensions/yarn_lexer.py
- doc/other_modules/jenny/language/commands/character.md
- doc/other_modules/jenny/language/commands/commands.md
- doc/other_modules/jenny/language/lines.md
- doc/other_modules/jenny/runtime/character.md
- doc/other_modules/jenny/runtime/character_storage.md
- doc/other_modules/jenny/runtime/dialogue_line.md
- doc/other_modules/jenny/runtime/dialogue_option.md
- doc/other_modules/jenny/runtime/index.md
- doc/other_modules/jenny/runtime/yarn_project.md
- packages/flame_jenny/jenny/lib/jenny.dart
- packages/flame_jenny/jenny/lib/src/character.dart
- packages/flame_jenny/jenny/lib/src/character_storage.dart
- packages/flame_jenny/jenny/lib/src/parse/parse.dart
- packages/flame_jenny/jenny/lib/src/parse/token.dart
- packages/flame_jenny/jenny/lib/src/parse/tokenize.dart
- packages/flame_jenny/jenny/lib/src/structure/commands/character_command.dart
- packages/flame_jenny/jenny/lib/src/structure/dialogue_line.dart
- packages/flame_jenny/jenny/lib/src/structure/dialogue_option.dart
- packages/flame_jenny/jenny/lib/src/yarn_project.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
- packages/flame_jenny/jenny/test/parse/parse_test.dart
- packages/flame_jenny/jenny/test/parse/token_test.dart
- packages/flame_jenny/jenny/test/structure/commands/character_command_test.dart
- packages/flame_jenny/jenny/test/structure/commands/set_command_test.dart
- packages/flame_jenny/jenny/test/structure/dialogue_line_test.dart
- packages/flame_jenny/jenny/test/structure/dialogue_option_test.dart
- packages/flame_jenny/jenny/test/test_scenario.dart
The new command allows pre-declaring the characters that will be seen in the yarn scripts, and provides a place to store any additional information associated with each character.
The `DialogueLine.character` property now returns a `Character` object, instead of a `String`.
Closes #2273
> feat: Added the <<character>> command to Jenny

- packages/flame_bloc/lib/src/flame_multi_bloc_provider.dart
- packages/flame_bloc/test/src/flame_multi_bloc_provider_test.dart
- packages/flame_test/lib/src/flame_test.dart
We overrode the `add()` method in the `FlameMultiBlocProvider` to handle a new functionality (add the new component to the last provider). We need to apply this functionality to the `remove()` method too. I just overrode the `remove()` method to apply that functionality.
In this way, both of `add()` and `remove()` methods work consistently.
> fix: Override `remove()` method to fix the functionality issue in the `FlameMultiBlocProvider`

- melos.yaml
This fixes the following warning when running our CI workflows:
```
[!] The "format" command is deprecated and will be removed in a future version of
Flutter. Please use the "dart format" sub-command instead, which takes all of the
same command-line arguments as "flutter format".
```
> ci: Replace "flutter format" with "dart format" in Melos scripts

- doc/_sphinx/requirements.txt
- doc/development/documentation.md
- melos.yaml
* The purpose of this new command is to make it easier to install things needed for doc development.
* Also added `jinja2` into the requirements file -- currently it is installed manually by the doc-publish script (https://github.com/flame-engine/flame-docs-site/blob/main/publish.sh#L58)
> ci: Added Melos command "doc-setup"

- packages/flame/lib/src/collisions/broadphase/broadphase.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/quad_tree_broadphase.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/quadtree_collision_detection.dart
- packages/flame/lib/src/collisions/broadphase/sweep/sweep.dart
- packages/flame/lib/src/collisions/collision_detection.dart
`items` variable from core `Broadphase` class is replaced to abstract getter. Also methods for adding and removing items are added. All this together allows to preserve backward compatibility and allow broadphase / collision detection  developer to specify own algorithm of adding/removing hitboxes and algorithm of accessing a full list of hitboxes.
Closes #2283
> refactor: Remove "items" variable from core Broadphase class.

- packages/flame_audio/pubspec.yaml
Bump to the latest audioplayers since the older version breakes in Flutter v3.7.0
> chore: Bump audioplayers in flame_audio

- packages/flame/lib/src/collisions/broadphase/quadtree/quad_tree_broadphase.dart
The QuadTreeBroadphase._broadphaseCheckCache did not get cleared from removed items and keeps dead components until clear() will be called explicitly.
> fix: Removed component does not deleted from _broadphaseCheckCache

- packages/flame/lib/src/cache/images.dart
- packages/flame/test/cache/images_test.dart
I've recently discovered that the `painting.dart` library from flutter has a nicer API for the `decodeImageFromList` than `dart:ui`.
This PR changes to use the one from `painting.dart` to simplify a little bit this class.
> refactor: Simplify how images.dart decodes images

- packages/flame/test/components/position_component_test.dart
In the test, the component was not properly added to a game instance, and as a result its hitbox was never mounted. In addition, the hitbox polygon used negative coordinates, which caused to be outside of the parent shape, which was counterintuitive.
> test: Fix a test for a component with hitboxes

- .github/.cspell/flame_dictionary.txt
- .github/.cspell/gamedev_dictionary.txt
- doc/bridge_packages/flame_svg/svg.md
- doc/flame/effects.md
- doc/other_modules/jenny/language/commands/declare.md
- doc/tutorials/platformer/step_3.md
- examples/games/trex/lib/trex_game.dart
- packages/flame/lib/src/text/formatters/sprite_font_text_formatter.dart
- packages/flame_bloc/example/lib/src/inventory/view/inventory.dart
I am on a crusade to improve our spellchecking. I have a big PR that I am now going to break down into very small chunks to for review.
This one I am fixing actual typos that made it despite our current settings. Hopefully this one won't be controversial (yet).
> docs: Fix actual typos that made into our dictionary

- packages/flame_jenny/jenny/lib/src/parse/parse.dart
> style: Remove unused typedef in jenny's parser

- packages/flame/test/components/component_test.dart
- packages/flame/test/custom_component.dart
Since we started using ComponentTreeRoot, the children of an unmounted component are stored in its `children` container -- which means the components added during `onLoad` are now accessible during `onMount` via `children` (even though they are still unmounted).
This PR adds a test for that.
Closes #1945
> test: Added test for accessing children in onMount

- .github/.cspell/flame_dictionary.txt
- packages/flame_flare/README.md
I am on a crusade to improve our spellchecking. I have a big PR that I am now going to break down into very small chunks to for review.
This is another hopefully not controversial one - broken links referencing the old Fire Slime.
Updating the links means we no longer need that word in our dictionary file.
> docs: Update broken fireslime references

- .github/.cspell/gamedev_dictionary.txt
- .github/cspell.json
- .github/workflows/spell_checker.yml
- packages/flame/lib/src/extensions/color.dart
- packages/flame/lib/src/extensions/paint.dart
I am on a crusade to improve our spellchecking. I have a big PR that I am now going to break down into very small chunks to for review.
[zwaldowski's cspell-action](https://github.com/zwaldowski/cspell-action) has been deprecated in favor of streetsidesoftware/cspell-action.
This PR:
* updates to use the new recommended cspell action
* update to use checkout v3, because why not
* fixes a few violations the new action caught
Note: I think we should make a distinction between things that should be in a dictionary (e.g. `AABB`, a standard industry acronym that we expect people to know what it is) and specific edge-cases/ignore rules for specific parts of specific files (e.g. something like `fccc` which is meaningless outside of the very specific context in which it is used). For the latter, …
> docs: Update cspell github action and configuration

- packages/flame/lib/src/components/text_box_component.dart
…t" error #2143
Error was happening because cachedImage.dispose(); was called multiple times on the same object.
https://github.com/flame-engine/flame/issues/2143
Closes #2143
> fix: TextBoxComponent's boxConfig timePerChar generates "Optimized Out" error

- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/lib/src/game/game_widget/game_widget.dart
- packages/flame/test/game/flame_game_test.dart
- packages/flame/test/game/game_render_box_test.dart
Closes: https://github.com/flame-engine/flame/issues/2340
> feat: Allow people to opt-out on repaint boundary

- doc/_sphinx/extensions/dart_domain.py
- doc/flame/game_widget.md
- packages/flame/lib/src/game/game_widget/game_widget.dart
Use the `dartdoc` directive for the `GameWidget` class, allowing us to keep the documentation in the code and on the site in sync.
> docs: Refactor documentation for GameWidget

- packages/flame_rive/example/pubspec.yaml
- packages/flame_rive/lib/src/rive_component.dart
- packages/flame_rive/pubspec.yaml
- packages/flame_rive/test/flame_rive_test.dart
0.10.2: 
Performance improvement: No longer drawing components with an opacity of 0.
Updated example, see "Skinning Demo".
Support for negative speeds on linear animations when played back in state machines.
Support for overriding speed on animation states.
> chore: Update rive package to 0.10.2

- examples/lib/stories/components/components.dart
Current source code links for `Component Notifier` and `Component Notifier (with provider)` return 404, this PR fixes it.
> docs: Fix broken links in Component Notifier examples

- doc/flame/components.md
Seems to have been some confusion about the anchor from the one that wrote these docs, the sentence that described the code was wrong.
https://stackoverflow.com/questions/75493256/confusion-on-anchor-argument-of-position-component
> docs: Small anchor confusion in the components doc

- doc/flame/components.md
- examples/lib/stories/components/priority_example.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/core/component_set.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/lib/src/components/router_component.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/test/components/priority_test.dart
- packages/flame/test/custom_component.dart
This PR ensures that all component rebalancing operations are resolved from a single location, after the `update` stage but before the `render` stage (thus, components may get reordered during the update, and these changes will go into effect during the rendering step on the same game tick).
This also fixes the problem where the child changing the priorities of its parent would cause a ConcurrentModificationError.
A number of methods that were used to handle rebalancing are now marked as deprecated. From the user's perspective, the only API they should be using is the `.priority` setter.
Closes #2263 …
> refactor: Component rebalancing is now performed via a global queue

- packages/flame/test/events/game_mixins/multi_touch_tap_detector_test.dart
This is a cleanup identified on this issue: https://github.com/flame-engine/flame/issues/2308
Using an amazing unused-code tooling
Now, since Flame is a public API, unused code might not be trivial - it might just mean untested code.
This one was a no-brainer -- the variable was clearly replaced by specific counters during the writing of the test and forgotten there:
```
int nOnTapDown = 0;
int nOnLongTapDown = 0;
int nOnTapUp = 0;
int nOnTap = 0;
int nOnTapCancel = 0;
```
It wasn't even increment and the taps are already thoroughly tested more granularly.
> refactor: Remove unused variable "tapTimes" from multi_touch_tap_detector_test.dart

- packages/flame/test/components/component_test.dart
This is a cleanup identified on this issue: https://github.com/flame-engine/flame/issues/2308
Using an amazing unused-code tooling
Now, since Flame is a public API, unused code might not be trivial - it might just mean untested code.
In this case, the unused code is in the tests, which likely means it is indeed necessary.
I tried to infer the intent of the author here, and even considered adding the names of the components to the events, but the events are already always per component, so that was meaningless. I also thought it might be a missing toString, that they would wish to show the component name for debugging purposes, but I didn't see any asserts/logs on the component objects themselves (just the events).
So I concluded there is no reason to keep this field, but lmk if anyone …
> refactor: Use variable name on toString in component_test.dart

- packages/flame_bloc/example/lib/src/game_stats/bloc/game_stats_bloc.dart
- packages/flame_bloc/example/lib/src/game_stats/bloc/game_stats_event.dart
This is a cleanup identified on this issue: https://github.com/flame-engine/flame/issues/2308
Using an amazing unused-code tooling
Now, since Flame is a public API, unused code might not be trivial - it might just mean untested code.
Since this an example package, it definitely should never have unused code.
In this case, the constructor wasn't being used, but upon deeper investigation, that was because this particular event wasn't ever fired at all.
So I removed it entirely. If this was supposed to be fired somewhere by the example, please lmk and I can add the missing firing.
But as far as I can see, the event serves no purpose in this example. …
> refactor: Remove unused event "ScoreEventCleared" from flame_block example

- packages/flame/lib/src/components/input/hud_margin_component.dart
- packages/flame/test/components/joystick_component_test.dart
When in landscape mode, a Component will need to be repositioned based on the new canvas
dimensions. If a Component has not reached the mounted state when
HudMarginComponent.onGameResize is called, then _updateMargins will not be called, and
the position will not be updated.
This PR removes the check that the Component has reached the mounted state in
HudMarginComponent.onGameResize so that _updateMargins will always be called. …
> fix: Incorrect JoystickComponent position in landscape mode #2387

- doc/_sphinx/extensions/flutter_app.py
- doc/bridge_packages/flame_forge2d/joints.md
Embedded flutter-app joints examples didn't work, because flutter-app script expects the example page to be located in the lib folder of a module. Introduced a new subfolder param, to specify where to find the example page.
Verified joints examples apps and code button on the doc page work; Also verified the same for the effects page.
PR 5/X for #2005
> docs: Fixed linked joints examples

- packages/flame_bloc/README.md
- packages/flame_fire_atlas/README.md
- packages/flame_flare/README.md
- packages/flame_forge2d/README.md
- packages/flame_isolate/README.md
- packages/flame_jenny/README.md
- packages/flame_lint/README.md
- packages/flame_lottie/README.md
- packages/flame_oxygen/README.md
- packages/flame_rive/README.md
- packages/flame_svg/README.md
- packages/flame_test/README.md
- packages/flame_tiled/README.md
Apparently my previous change broke a lot of the README files because I used markdown on the HTML-only zone. It started all right but at some point after I started testing I accidentally switched.
The backticks also don't work well with links, so I removed them.
> docs: Fix non-markdown section of README files

- packages/flame_tiled/README.md
Fix broken image link on flame_tiled pub.
Sadly the repo relative link works on GitHub but not on pub.
This replaces it with an equivalent githubusercontent URL.
This is how it is done by other packages and recommended on Stack Overflow according to my research (but open to other better solutions).
I also made the image a bit bigger bc it was small and hard to see (to me).
> docs: Fix broken image link on flame_tiled pub

- doc/flame/collision_detection.md
- examples/.gitignore
- examples/lib/stories/collision_detection/collision_detection.dart
- examples/lib/stories/collision_detection/multiple_worlds_example.dart
- packages/flame/lib/src/collisions/has_collision_detection.dart
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/collisions/collision_callback_benchmark_test.dart
- packages/flame/test/collisions/collision_callback_test.dart
- packages/flame/test/collisions/collision_detection_test.dart
- packages/flame/test/collisions/collision_test_helpers.dart
- pubspec.lock
This change makes it possible to have the collision detection system further down in the tree than on the `FlameGame`, this enables you to have collision detection on the `World` component for example. 
Today it doesn't work if you have several worlds where the components are overlapping across the worlds, since the hitboxes live on top level.
So now you can use a `World` like this:
```dart
class CollisionDetectionWorld extends World with HasCollisionDetection {}
```
and all hitboxes added in there will only react with other hitboxes added to that world.
> feat: Change `HasCollisionDetection` to be on `Component`

- packages/flame/lib/src/components/input/button_component.dart
- packages/flame/test/components/hud_button_component_test.dart
Since it should be possible to set `button` and `buttonDown` in `onLoad` they shouldn't be final.
> fix: Buttons in ButtonComponents should not be final

- examples/games/padracing/lib/padracing_game.dart
The map with active keymaps should be cleared and not the maps in the map.
This made the game not taking input properly after restart.
Closes #2414 
> fix: Fix key input to work after restart

- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/test/components/text_box_component_test.dart
Initially the calculation of lines and updating accordingly ignores the case for a new line escape characters.
This PR changes how we calculate and update lines when checking for bounds.
**Before:**
When a text that contains `\n` character is given to the TextBox for example `Hello \n World`. It doesn't consider the new line and just appends the `\n` to the same line. This increases the lineHeight for that particular word (and won't be updated in this case). But, instead when there is a text `\nHello World`, then the initial lineHeight itself is twice than what it actually is.
So, the main problem here is that we are not considering (ignoring) the `\n` characters.
This can be solved by checking for any new lines in the split word (From `split(' ')`) by using `split('\n')` and adding the …
> fix: TextBoxComponent rendering for new line

- packages/flame/lib/src/effects/move_along_path_effect.dart
- packages/flame/test/effects/move_along_path_effect_test.dart
Updated `MoveAlongPathEffect` class to ensure target angle is initiated when oriented is set to true for either absolute or non-absolute paths.
Not that I know of but flame team would be best placed to say yes/no to this.
> fix: Update MoveAlongPathEffect

- doc/_sphinx/theme/flames.css
when overflow-y, the scroll will be enabled on hover that makes us scroll through the contents and click what's below
Initially, the contents section (the right side nav) doesn't scroll when overflow. This PR adds the functionality to scroll when it overflows vertically.
Working video:
https://user-images.githubusercontent.com/40348358/227519288-805ae943-0c23-4220-8224-fec168bae599.mov
This commit had some complications like having to compromise with having shrink width. It doesn't much shrink, but does slightly does.
Before this PR:
After this PR:
But, I am thinking this can be considered as the readability isn't effected much as this sidebar only is visible when there is enough space (more width).
- [-] I have …
> feat: Add scroll to right side nav

- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/test/components/sprite_component_test.dart
This PR adds an `autoResize` parameter to `SpriteComponent` using which users will be able to control if the component should auto-resize on sprite change to match the sprite's `srcSize`. Some important design decisions about `autoResize`:
- It is mutually exclusive with `size` while construction: This means, if `size` is non-null while construction of `SpriteComponent`, `autoResize` cannot be true. This allows use-cases where one might want to render a sprite at a different size than its original size. If an user is setting the size explicitly, we can leave it up to them to handle resizing in such cases. 
- It is optional: If an user does not set this parameter while construction, it will be auto-populated depending upon if a `size` is provided or not.
Closes #2419
> fix: Auto-resize `SpriteComponent` on sprite change

- doc/flame/examples/lib/main.dart
- doc/flame/examples/lib/time_scale.dart
- doc/flame/other/util.md
- examples/lib/stories/components/components.dart
- examples/lib/stories/components/time_scale_example.dart
- packages/flame/lib/components.dart
- packages/flame/lib/src/components/mixins/has_time_scale.dart
- packages/flame/test/components/mixins/has_time_scale_test.dart
This PR adds a new mixin on `Component`. When attached to a component, it allows scaling the delta time of that component as well as all its children by a non-negative factor. The idea is to allows slowing down or speeding up the gameplay by change the scaling factor.
Note: This approach works only for framerate independent game logic. Code in `update()` that is not dependent on delta time will remain unaffected by time scale.
Here are few examples:
https://user-images.githubusercontent.com/33748002/227756636-ee00405a-2d6a-4751-91a3-2b78a522e723.mp4
https://user-images.githubusercontent.com/33748002/227756645-bc570e6b-4985-4d51-8f1a-5f2cbaef99c6.mp4
Closes #2392
> feat: Add `HasTimeScale` mixin

- doc/bridge_packages/flame_svg/svg.md
Error in flame_svg code snippets in documentation causing issues in IDE
update code snippets for [flame_svg docs](https://docs.flame-engine.org/1.6.0/bridge_packages/flame_svg/svg.html#how-to-use-flame-svg)
Closes #2432
> docs: Error in flame_svg code snippets in documentation

- doc/bridge_packages/flame_svg/svg.md
- doc/flame/camera_and_viewport.md
- doc/flame/collision_detection.md
- doc/flame/components.md
- doc/other_modules/jenny/runtime/command_storage.md
- doc/tutorials/klondike/step4.md
docs: Some `@overrides` for the `onLoad()` function are missing in the code snippets
missing `@overrides` are added in the corresponding code snippets.
Closes #2446
> docs: Some @overrides for the onLoad() function are missing

- doc/bridge_packages/flame_audio/flame_audio.md
- doc/bridge_packages/flame_forge2d/flame_forge2d.md
Remove `:hidden:` from `flame_audio.md` & `flame_forge2d.md` files.
Closes #2445
> docs: Hidden toctree details for flame_audio & flame_forge2d

- examples/lib/main.dart
- examples/lib/stories/image/image.dart
- examples/lib/stories/image/resize.dart
- examples/pubspec.yaml
- packages/flame/lib/src/extensions/image.dart
- packages/flame/test/extensions/image_extension_test.dart
Adds a helper method to `ImageExtension` to make it easier to resize an image.
> feat: Adding ImageExtension.resize

- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
- packages/flame/test/components/sprite_animation_component_test.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
This PR extends `autoResize` to `SpriteAnimationComponent` and `SpriteAnimationGroupComponent`  similar to what was done in #2430 and #2442. 
Additionally, this PR also adds `playing` property to `SpriteAnimationGroupComponent`. If it is desired to make this appear as a separate entry in the changlog, I can move this change to a separate PR as it is completely unrelated to the auto-resize changes.
NA
> feat: Add `autoResize` for `SpriteAnimationComponent` and `SpriteAnimationGroupComponent`

- packages/flame/lib/src/camera/viewports/fixed_aspect_ratio_viewport.dart
- packages/flame/lib/src/camera/viewports/max_viewport.dart
- packages/flame/test/camera/viewfinder_test.dart
- packages/flame/test/camera/viewports/max_viewport_test.dart
#2317 removed the call to `onGameResize` before `onLoad` and since the viewports relied on that for setting their sizes you couldn't change for example the `viewfinder.visibleGameSize` before the `CameraComponent` had been mounted (since `onGameResize` is called right before `onMount`).
I'm not super happy with the solution, so I'm open to any suggestions.
Closes #2426 
> fix: Set size of viewports in `onLoad`

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
This is needed since it'll get a `ConcurrentModificationException` in some cases otherwise, like in the test added for example.
Closes #2424 
> fix: Materialize list in `Component.removeWhere`

- README.md
Standardize sizes of the different contributing badges on README.md to 200 pixels width.
Sadly the height and style are still different, but that is beyond my capabilities.
Also adds a star emoji to the star pledge, and slightly improve wording.
Before:
Now:
> docs: Standardize sizes of the different contributing badges on README.md

- doc/_sphinx/conf.py
Add sphinx copy button configurations in `conf.py`
Closes #2463
> docs: Add sphinx copy button configurations in conf.py

- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
- packages/flame/test/components/sprite_animation_component_test.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
- packages/flame/test/components/sprite_component_test.dart
- packages/flame/test/components/sprite_group_component_test.dart
This PR fixes a regression introduced in Flame 1.7.0 and discussed in [this thread on discord](https://discord.com/channels/509714518008528896/1092822070280327330).
The whole idea is to detect if size is being modified by some external call apart from the `autoResize`ing code and stop auto-resize from that point onwards.
NA
> fix: Stop auto-resizing on external size change in sprite based components

- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
Fixes a mistake made in auto-resize disabling logic submitted via #2467 
NA
> fix: A mistake in auto-resizing disabling logic

- doc/flame/examples/lib/drag_events.dart
- doc/tutorials/klondike/app/lib/step4/components/card.dart
- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- examples/lib/stories/input/draggables_example.dart
- packages/flame/lib/src/components/input/joystick_component.dart
- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/test/events/component_mixins/drag_callbacks_test.dart
- packages/flame/test/events/flame_game_mixins/has_draggable_components_test.dart
Adding a `isDragged` state for `DragCallbacks` mixin. This was available in the `Draggable` mixin.
NA
> feat: Add `isDragged` in `DragCallbacks` mixin

- examples/lib/stories/components/game_in_game_example.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
Since we now have a setter directly for `parent`, `changeParent` is no longer needed.
> feat: Deprecate Component.changeParent

- packages/flame/lib/src/components/core/recycled_queue.dart
Implementing and extending the iterable interface/mixin at the same time breaks Flame in the current beta channel (3.10...).
This PR removes the implementation of the interface to get flame ready for the next flutter release.
> fix: RecycleQueue cannot extends and implements Iterable at the same time

- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
- packages/flame/test/components/sprite_animation_component_test.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
- packages/flame/test/components/sprite_component_test.dart
- packages/flame/test/components/sprite_group_component_test.dart
Checks the size before modifying and skips if it hasn't changed.
Closes #2488
> fix: Modify size only if changed while auto-resizing

- packages/flame/lib/src/game/mixins/has_tappables.dart
`HasTappables` also needs the same full implementation in `mount` as `HasTappableComponents` has for `Tappable` to work properly.
It seems to work the same without this too, so there is something that I'm missing.
> fix: Fill in mount implementation in `HasTappables`

- doc/_sphinx/scripts/versions.js
After the #2345 change we also have to consider "latest" as the latest version, so that we don't show a warning box for that.
> docs: Consider "latest" as the latest version

- packages/flame_audio/lib/bgm.dart
The `AudioPlayer` should not be disposed when it should be continued to be used, it should be `release`d.
https://github.com/bluefireteam/audioplayers/issues/1475
> fix: Release instead of dispose audioplayer in play

- doc/flame/components.md
- doc/flame/examples/lib/anchor.dart
- doc/flame/examples/lib/main.dart
This PR add an interactive example to show the parent child relationship when their anchors are changed. It also elaborates the same in written docs as well.
https://user-images.githubusercontent.com/33748002/235361268-7636d25c-5c07-4124-9ce5-de9485b0fb1b.mp4
Closes #2510
> docs: Add interactive example for `Anchor`

- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/sprite_button.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
To make it consistent with the other constructors, all builders should be settable from the default constructor.
> fix: Move `errorBuilder` and `loadingBuilder` to constructors

- doc/tutorials/klondike/step4.md
It just removes a deprecated line that is in the tutorial for building a Klondike game. The final code does not have it and it is no longer necessary to have it in the `KlondikeGame` class.
No, just docs.
> docs: Remove deprecated mixin from klondike tutorial

- .github/workflows/cicd.yml
- packages/flame_rive/example/lib/main.dart
- packages/flame_rive/example/pubspec.yaml
- packages/flame_rive/lib/src/rive_component.dart
- packages/flame_rive/pubspec.yaml
Avoid creation of unnecessary objects for RiveComponent and simplifies the example.
> fix: Avoid creation of unnecessary objects for RiveComponent

- doc/flame/collision_detection.md
- packages/flame/lib/src/collisions/collision_callbacks.dart
@mustCallSuper is very strict requirement. This is true only for hitboxes and internal engine's logic, but unnecessary for other, "client-side" game components.
When overriding `onComponentTypeCheck` for component you can simple return true or false and this would not break anything.
> fix: Remove `mustCallSuper` from `onComponentTypeCheck`

- packages/flame/lib/src/experimental/geometry/shapes/rectangle.dart
- packages/flame/test/experimental/geometry/shapes/rectangle_test.dart
Add useful methods to Rectangle class:
* a fromCenter constructor
* an `area` getter
* edges and vertices
* intersections with Line Segment
* toRect()
> feat: Add useful methods to Rectangle class

- packages/flame_tiled/lib/src/flame_tsx_provider.dart
- packages/flame_tiled/lib/src/renderable_layers/image_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/renderable_layer.dart
- packages/flame_tiled/lib/src/renderable_tile_map.dart
Add images and bundle to the named parameters for the creation of a tiled map.
No
\-
Closes #2568
> feat: Add option for a custom image and asset loader

- doc/tutorials/klondike/step3.md
In the tutorial, the code that relies on `Rank` uses the `.fromInt` constructor, not `.of`
- [x ] I have followed the [Contributor Guide] when preparing my PR.
- [+] I have updated/added relevant examples in `examples` or `docs`.
> fix: Update step3.md to use correct constructor name

- doc/flame/components.md
- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/parallax.dart
- packages/flame/lib/src/particles/sprite_animation_particle.dart
- packages/flame/lib/src/sprite_animation.dart
- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/test/components/sprite_animation_component_test.dart
- packages/flame/test/sprite_animation_ticker_test.dart
- packages/flame/test/spritesheet_test.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
This PR marks `SpriteAnimation.ticker()` as deprecated with `SpriteAnimation.createTicker()` as a replacement. This is done to make it more clear that calling that method creates a new ticker. Also, the docs for `SpriteAnimationGroupComponent` are updated with code snippet showing how to access and use the callbacks from tickers of each animation state.
N/A
> fix: Animation ticker readability improvements

- doc/bridge_packages/flame_tiled/flame_tiled.md
- packages/flame_tiled/lib/src/tile_atlas.dart
- packages/flame_tiled/test/tile_atlas_test.dart
Possibility to clear TiledAtlas cache. This is required after `Flame.images.clearCache()` call. 
Closes #2585
> feat: TiledAtlas.clearCache function

- examples/lib/stories/parallax/advanced_parallax_example.dart
- examples/lib/stories/parallax/animation_parallax_example.dart
- examples/lib/stories/parallax/basic_parallax_example.dart
- examples/lib/stories/parallax/component_parallax_example.dart
- examples/lib/stories/parallax/no_fcs_parallax_example.dart
- examples/lib/stories/parallax/sandbox_layer_parallax_example.dart
- packages/flame/lib/src/components/parallax_component.dart
- packages/flame/lib/src/parallax.dart
The Parallax already supported filter quality, but the loader methods were missing parameters for it to be passed to the loaded instances, making it impossible (unless manually loading) to set a filter quality in a parallax.
By setting a filter quality to none (which on flutter means that the next neighbour algorithm will be user) on pixel art sprites we can keep the crisp look that that style of art demands.
Before my change:
https://github.com/flame-engine/flame/assets/835641/1e11943c-2939-4fcf-829d-024fa199aa2e
After:
https://github.com/flame-engine/flame/assets/835641/3af2039b-5a4c-4614-9d68-886eb5dcdb66
[CHANGELOG]: …
> feat: Adding filterQuality arguments to Parallax load methods

- packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/has_draggable_components.dart
- packages/flame/lib/src/events/flame_game_mixins/has_tappable_components.dart
- packages/flame/lib/src/events/messages/double_tap_down_event.dart
- packages/flame/lib/src/events/messages/drag_start_event.dart
- packages/flame/lib/src/events/messages/drag_update_event.dart
- packages/flame/lib/src/events/messages/position_event.dart
- packages/flame/lib/src/events/messages/tap_down_event.dart
- packages/flame/lib/src/events/messages/tap_up_event.dart
- packages/flame/test/events/component_mixins/drag_callbacks_test.dart
- packages/flame/test/events/component_mixins/tap_callbacks_test.dart
- packages/flame_test/lib/src/mock_tap_drag_events.dart
This PR makes the `PositionEvent` class take a `Game` instance as a required parameter. The game is the used
to convert `canvasPosition` lazily as it is done in `EventPosition`.
As a result, i had to change several constructor calls to include the game, and make a breaking change in the `flame_test` package for all the `create[...]Events` functions. This may not be the best solution, but it is the easiest. Feel free to share your opinion and improvement ideas.
The `create[...]Events` functions in the `flame_test` package changed their signature.
You now have to pass in the game as the required `game` named parameter. …
> fix!: Convert PositionEvent.canvasPosition to local coordinates

- doc/flame/collision_detection.md
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
- packages/flame/test/collisions/collision_callback_test.dart
See #2590 
Added `triggersParentCollision` variable to `ShapeHitbox` class to prevent propogating `onCollision*` events to parent component
Closes #2590
> feat: Option to prevent propagating collision events from ShapeHitbox to _hitboxParent

- doc/flame/other/util.md
- packages/flame/lib/src/experimental/geometry/shapes/rectangle.dart
- packages/flame/lib/src/extensions/rect.dart
- packages/flame/test/experimental/geometry/shapes/rectangle_test.dart
- packages/flame/test/extensions/rect_test.dart
Add a `Rectangle.fromLTWH` and `Rect.toFlameRectangle` utility methods to more easily create and convert between different rectangle represenations.
Extracted from our [lightrunners code](https://github.com/flame-engine/lightrunners/blob/eb2e91a29c7271e7f6bf7c8d25922d994adfc00b/lib/utils/triangle2.dart#L107).
> feat: Add Rectangle.fromLTWH and Rect.toFlameRectangle utility methods

- packages/flame/lib/src/geometry/line.dart
- packages/flame/lib/src/geometry/line_segment.dart
- packages/flame/test/geometry/line_segment_test.dart
Add a `LineSegment.midpoint` utility getter.
Extracted from our [lightrunners code](https://github.com/flame-engine/lightrunners/blob/eb2e91a29c7271e7f6bf7c8d25922d994adfc00b/lib/utils/triangle2.dart#L107).
> feat: Add a midpoint getter to LineSegment

- packages/flame/lib/src/experimental/geometry/shapes/circle.dart
- packages/flame/test/experimental/geometry/shapes/circle_test.dart
Add a `Circle.fromPoints` utility method to (maybe) create Circles that intersect three given points.
Extracted from our [lightrunners code](https://github.com/flame-engine/lightrunners/blob/eb2e91a29c7271e7f6bf7c8d25922d994adfc00b/lib/utils/triangle2.dart#L107).
> feat: Add a Circle.fromPoints utility method

- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/test/components/text_box_component_test.dart
`TextBoxConfig.dismissDelay` was being ignored, now it removed the component once it is finished and the delay has passed, like intended.
> fix: TextBoxConfig dismissDelay to not be ignored

- doc/README.md
Apparently someone thought they should run `pub get` in their terminal instead of `flutter pub get`. Though it's called "Pub: Get Packages" in the VS Code command pallete.
This changed `pub get` to `flutter pub get` in the installation guide (https://docs.flame-engine.org/latest/).
Closes #2609
> docs: Adds more clarity to `pub get`

- packages/flame/lib/src/components/input/hud_margin_component.dart
In a project where we wrapped the `JoystickComponent` into it's own `Component` to separate concerns resizing the window (or hot reloading) would throw an exception leading to a red screen.
The `HudMarginComponent` currently expects the parent to be either a `FlameGame` or `ReadOnlySizeProvider`, which throws an exception when our wrapped `Joystick` class is neither.
With the help of @spydon, we came to the conclusion that this fix should work and not break other cases.
No related issue, I can open one if needed.
> fix: Only use pre-set ReadonlySizeProvider for sizing in HudMarginComponent

- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/test/camera/viewports/fixed_size_viewport_test.dart
`CameraComponent` can now stare at nothingness because its world reference can be null now.
`CameraComponent.world` is now nullable. While accessing it, make sure to perform null checks if it can be null in your case. Otherwise, if you are sure that the world is non-null perform unconditional using `CameraComponent.world!`.
Closes #2614
> feat!: Make world nullable in `CameraComponent`

- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/test/camera/camera_component_test.dart
- packages/flame/test/camera/viewports/fixed_size_viewport_test.dart
`CameraComponent.canSee` wasn't performing any kind of sanity checks on the given components world or mounted-ness. This PR adds these checks to correctly return false if the component is not mounted or if the optional world is not the same as camera's current target world.
NA
> feat: Add optional world input to `CameraComponent.canSee`

- doc/flame/collision_detection.md
- packages/flame/lib/src/collisions/broadphase/broadphase.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/has_quadtree_collision_detection.dart
- packages/flame/lib/src/collisions/has_collision_detection.dart
This is adding a bit more precise language and more context to API docs of `HasCollisionDetection`, `Broadphase` and `HasQuadTreeCollisionDetection`.
Closes #2622 (imho)
> docs: Add more guidance to collision detection algorithm choices

- examples/.metadata
- examples/test/main_test.dart
- packages/flame/lib/collisions.dart
- packages/flame/lib/src/collisions/broadphase/broadphase.dart
- packages/flame/lib/src/collisions/broadphase/prospect_pool.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/has_quadtree_collision_detection.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/quad_tree_broadphase.dart
- packages/flame/lib/src/collisions/broadphase/quadtree/quadtree_collision_detection.dart
- packages/flame/lib/src/collisions/broadphase/sweep/sweep.dart
- packages/flame/lib/src/collisions/collision_detection.dart
- packages/flame/test/collisions/collision_callback_test.dart
- packages/flame/test/collisions/collision_test_helpers.dart
- packages/flame_lint/lib/analysis_options.yaml
This change introduces a very simple pool for `CollisionProspect`s so that those objects don't have to be re-created each tick.
It means that the `CollisionProspect` needs to be mutable though, so the code becomes a little bit harder to read since sets can't be used anymore.
If you are depending on that the query method returns a set instead of an iterable you have to accommodate for that change, or do `toSet`, but the latter might not be reliable depending on how you use the set afterwards, since the objects are now mutable.
> perf!: Pool `CollisionProspect`s and remove some list creations from the collision detection

- doc/tutorials/klondike/step3.md
- doc/tutorials/klondike/step4.md
I have just finished steps 1-4 of the Klondike tutorial and noticed a couple of minor things that look to be outdated with the current dart / flame versions.
When following this step the analyser hightlight this rule [unnecessary_late](https://dart.dev/tools/linter-rules/unnecessary_late) (introduced in Dart 2.16.0) which states:
> Top-level and static variables with initializers are already evaluated lazily as if they are marked late.
I updated the notes around why the laziness is important so the reader can still understand the reasoning.
Looking through the `DragCallbacks` mixin I found that `onDragStart()` and `onDragEnd()` both set a private `_isDragged` flag that acts the same as the `_isDragging` local flag created in the tutorial. This was added in …
> docs: Minor updates to steps 3 & 4 in Klondike tutorial

- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/lib/src/events/component_mixins/double_tap_callbacks.dart
- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/lib/src/events/component_mixins/tap_callbacks.dart
- packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/has_draggable_components.dart
- packages/flame/lib/src/events/flame_game_mixins/has_tappable_components.dart
This uses the `ComponentKey` API to register and unregister dispatchers, so that we don't have to create unnecessary dispatcher components that are removed directly in `onMount` if there already is a dispatcher or the same type added.
This also opens up for registering components to the dispatchers so that we don't have to go through the whole tree to deliver events which it does currently.
> fix: Use `ComponentKey`s to keep track of dispatchers

- packages/flame_tiled/lib/src/renderable_layers/group_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/image_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/object_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/renderable_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/hexagonal_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/isometric_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/orthogonal_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/staggered_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/tile_layer.dart
This makes it possible to pass in `FilterQuality` to the `TiledComponent` and to the layers, since `PaintImage` defaults to `FilterQuality.low`.
> feat: Possiblity to pass in FilterQuality to tiled layers

- packages/flame/lib/src/sprite_animation_ticker.dart
- packages/flame/test/sprite_animation_ticker_test.dart
I was running this code:
```dart
void attack() async {
print('Attack started');
current = PlayerState.attack;
final attackTicker = animationTicker!;
await attackTicker.completed;
print('Attack ticker completed');
attackTicker.reset();
current = PlayerState.idle;
}
```
and `attackTicker.completed` would get stuck as permanently completed after the first completion.
The closest issue I can find is https://github.com/flame-engine/flame/issues/2584 which uses the `ticker.onComplete` function and ran into a problem because of creating a new ticker. This PR concerns the `ticker.completed` …
> fix: Reset _completeCompleter in ticker

- packages/flame/lib/src/text/nodes/block_node.dart
- packages/flame/lib/src/text/nodes/column_node.dart
- packages/flame/lib/src/text/nodes/document_node.dart
- packages/flame/lib/src/text/nodes/header_node.dart
- packages/flame/lib/src/text/nodes/text_node.dart
Improve comments and documentation for text-rendering Nodes
Super-specify return types whenever possible
Minor refactorings to improve legibility
> docs: Improve comments and documentation for text-rendering Nodes

- doc/flame/components.md
- doc/flame/rendering/images.md
- doc/flame/rendering/particles.md
Remove outdated references to the flame_flare package from our docs
> docs: Remove outdated references to the flame_flare package from our docs

- packages/flame/lib/src/sprite_animation_ticker.dart
- packages/flame/test/sprite_animation_ticker_test.dart
Based on the Discord discussion and consultation with @ufrshubham, this PR adds the ability to pause a `SpriteAnimationTicker`.
> feat: Add `pause` and `isPaused` to SpriteAnimationTicker

- packages/flame/lib/src/text/formatters/sprite_font_text_formatter.dart
Add a class-level doc comment to `SpriteFontTextFormatter`, analogous to `TextPainterTextFormatter`.
Also, super-specify the return type of the `format` method to facilitate understanding (again, this makes it more aligned with its twin `TextPainterTextFormatter`). 
> docs: Improve documentation around SpriteFontTextFormatter

- .github/pull_request_template.md
Update PR template so "Migration instructions" is after the breaking change checkbox.
I believe that was where it was intended to be, but please assess if this makes sense.
> docs: Update PR template so "Migration instructions" is after the breaking change checkbox

- doc/flame/diagrams/component.md
Update components diagram on the docs to be simpler.
It seems we no longer have any abstract classes to note (other than the abstract concept of "Effects").
I feel right now the colouring (while pretty) is just "highlighting" the effects node on the graph for no particular reason.
I think it would be simpler and more immediate to understand if we remove this distinction on this diagram.
Just a thought, though. Hard to assess what will be clearer to someone not so familiar with the concepts.
Current version:
New version:
``` mermaid
graph TD
%% Config %%
classDef default fill:#282828,stroke:#F6BE00;
%% Nodes %%
Component(Component)
Misc("
TimerComponent
ParticleComponent
SpriteBatchComponent
")
Effects("Effects<br/>(See the effects section)")
Game(Game)
FlameGame(FlameGame) …
```
> docs: Update components diagram on the docs to be simpler [Proposal]

- packages/flame/lib/effects.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/input/hud_margin_component.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/effects/provider_interfaces.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/lib/src/layout/align_component.dart
- packages/flame_forge2d/lib/body_component.dart
- packages/flame_forge2d/test/body_component_test.dart
Currently, the implementation of the `absoluteAngle` getter in `PositionComponent` only takes into account `PositionComponent` ancestors. The implementation simply runs through the whole hierarchy summing up the relative angles.
This gives a wrong result with Forge2D because `BodyComponent`s have angles too: in the common situation where a `PositionComponent` (e.g. a `SpriteComponent`) is the child of a `BodyComponent`, the `BodyComponent`'s rotation is ignored when computing the `absoluteAngle`.
The fix simply introduces a new minimal interface `HasAngle` that both `PositionComponent` and `BodyComponent` implement (`PositionComponent` implements it automatically via `AngleProvider`), and reimplements `absoluteAngle` so that it considers all ancestors with an angle and not just the …
> fix: Absolute angle takes into account BodyComponent ancestors too

- packages/flame_jenny/jenny/test/test_scenario.dart
- packages/flame_lint/lib/analysis_options_with_dcm.yaml
Enable new DCM rule: avoid-cascade-after-if-null
Reference: https://dcm.dev/docs/rules/common/avoid-cascade-after-if-null/
> refactor: Enable new DCM rule: avoid-cascade-after-if-null

- CONTRIBUTING.md
Extend the contributing guidelines with more usable markdown suggestions.
In particular suggest the `Rewrap` VS-code extension since the existing tooling cannot fix laborious markdown line length issues.
> docs: Extend the contributing guidelines with more usable markdown suggestions

- .github/workflows/cicd.yml
The issue with GitHub killing out test pipeline might be due to the running on the latest ubuntu image, this commit tries to use the older one (which I read could be a solution somewhere...)
> ci: Try to use ubuntu-20.04 for tests

- doc/bridge_packages/flame_tiled/flame_tiled.md
- doc/flame/components.md
- packages/flame_tiled/lib/src/rectangle_bin_packer.dart
- packages/flame_tiled/lib/src/renderable_tile_map.dart
- packages/flame_tiled/lib/src/tile_atlas.dart
- packages/flame_tiled/lib/src/tiled_component.dart
- packages/flame_tiled/test/rectangle_bin_packer_test.dart
This PR add the ability for users to override the max size of `TiledAtlas` used by `TiledComponent` for packing all the images of all the tilesets used by a tilemap. The overrides can be used if one is sure that their target platform can handle huge textures.
It also adds an assert for cases when the `RectangleBinPacker` runs out of space. This is done to help users find the problem quickly.
Closes #2619
> feat: Expose atlas limits for `TiledComponent`

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/position_component_test.dart
Since you might want to set `debugCoordinatesPrecision` without having to override it, it is better to have it as a variable than a getter.
> fix: Make `debugCoordinatesPrecision` into a variable instead of a getter

- doc/other_modules/jenny/runtime/character_storage.md
- packages/flame_jenny/jenny/lib/src/character_storage.dart
- packages/flame_jenny/jenny/test/character_storage_test.dart
Allow characters to be removed from character storage, or character storage to be cleared.
This is useful in large games where each scene may have different sets of characters. They can be cleared between scenes, and new characters loaded.
Relates to #2686 which will be split to multiple PRs to keep them manageable :) 
> feat(flame_jenny): Allow removal of characters

- doc/other_modules/jenny/runtime/variable_storage.md
- packages/flame_jenny/jenny/lib/src/variable_storage.dart
- packages/flame_jenny/jenny/test/variable_storage_test.dart
Allow variables to be removed from variable storage, or variable storage to be cleared.
It's not usual to do this, but could be useful in large games where each scene may have its own set of variables. They can be cleared between scenes.  Another use-case is for implementing a 'save game' feature. The variables can be cleared, and a new set of variables loaded in from a save game.
It's important to note that Jenny uses variable storage to retain the node visit counts (the number of times the player has visited each node). This has been taken into account in the `clear` method, which allows the user to retain the node visit counts.
Relates to #2686 which will be split to multiple PRs to keep them manageable :)  …
> feat(flame_jenny): Allow removal of variables

- doc/tutorials/klondike/app/lib/step4/components/card.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/mixins/has_game_ref.dart
- packages/flame/lib/src/components/mixins/notifier.dart
- packages/flame/lib/src/events/component_mixins/double_tap_callbacks.dart
- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/lib/src/events/component_mixins/tap_callbacks.dart
- packages/flame/lib/src/experimental/has_game_reference.dart
- packages/flame/test/experimental/has_game_reference_test.dart
- packages/flame_test/lib/src/flame_test.dart
It doesn't make any sense for `HasGameReference` to have `Game` as a base instead of `FlameGame` since the mixin is `on Component` and clearly in a component tree context, so this PR sets the base to be `FlameGame` (like `HasGameRef`).
It kind of is a breaking change, but I can not imagine anyone using it in a way that this would become breaking for them, so I'm counting it as a non-breaking change.
> fix: HasGameReference should default to FlameGame

- packages/flame/lib/src/game/game_render_box.dart
- packages/flame/test/game/game_widget/game_widget_lifecycle_test.dart
Since we are requiring a SDK higher than when the instance could be null we don't need to do the ambiguate call anymore.
> fix: Ambiguation is not needed in render box anymore

- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/lib/src/camera/viewfinder.dart
- packages/flame/lib/src/camera/viewport.dart
- packages/flame/lib/src/game/transform2d.dart
- packages/flame/test/camera/camera_component_test.dart
Add `globalToLocal` and `localToGlobal` methods to viewport, viewfinder and camera.
> feat: Add globalToLocal and localToGlobal methods to viewport, viewfinder and camera

- packages/flame_lint/lib/analysis_options_with_dcm.yaml
Enable DCM rule: avoid-collection-methods-with-unrelated-types
Reference: https://dcm.dev/docs/rules/common/avoid-collection-methods-with-unrelated-types/
Hopefully we don't have any violations as-is, because this would be pretty bad.
> chore: Enable DCM rule: avoid-collection-methods-with-unrelated-types

- CONTRIBUTING.md
- doc/development/style_guide.md
- examples/games/padracing/scripts/merge_files.sh
`flutter format` will generate a deprecation warning:
```
The "format" command is deprecated. Please use the "dart format" sub-command instead, which has the same command-line usage as "flutter format".
```
It should be replaced with `dart format`.
Have updated two places in the docs, and in a shell script (please verify this one for me!)
> docs: Replace flutter format with dart format

- packages/flame/test/game/game_widget/game_widget_pause_test.dart
Just adds a test that makes sure that the dt that has passed when a game is paused is not accumulated.
#2642 
> test: Test so that paused gameloop doesn't count dt

- doc/_sphinx/Makefile
- doc/flame/diagrams/flame_game_life_cycle.md
- doc/flame/game.md
The `FlameGame` lifecycle diagram is incorrect.  The lifecycle for a `FlameGame` is as follows:
```
onGameResize
onLoad
onMount
render
update
onRemove
onGameResize
onLoad
onMount
render
update
```
Note in particular the `onGameResize` is before `onLoad` and the `render` and `update` are reversed.  Because they are different, this PR creates a new lifecycle diagram that is not shared with `Component`.  It also fixes the `Component` lifecycle diagram to be consistent with the `FlameGame` lifecycle diagram formatting and terms.  
- [x ] I have followed the [Contributor Guide] when preparing my PR.
- [] I have updated/added tests for ALL new/updated/fixed functionality.
- [] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [] I have updated/added …
> fix: Correct FlameGame lifecycle diagram and description

- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/events/component_mixins/double_tap_callbacks.dart
- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/lib/src/events/component_mixins/pointer_move_callbacks.dart
- packages/flame/lib/src/events/component_mixins/tap_callbacks.dart
- packages/flame/test/components/component_test.dart
Since registering detectors won't work on a non-root game we have to register the dispatchers on the root game.
> fix: Use root game for gestures

- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/test/components/component_test.dart
This PR no longer treats it as an invalid action to add a child to a parent even if it already has a parent, it simply triggers a move instead, which makes it possible to simplify the logic.
> fix: Allow moving to a new parent in the same tick

- packages/flame/lib/src/game/game.dart
Since the widget wasn't refreshed when a new mouse detector was added it only worked if for example `HoverCallbacks` components were added directly in the game's `onLoad`.
Closes #2760
> fix: Correctly refreshes the widget after new mouse detector

- doc/bridge_packages/flame_forge2d/forge2d.md
- doc/bridge_packages/flame_forge2d/joints.md
- examples/lib/stories/bridge_libraries/flame_forge2d/flame_forge2d.dart
- packages/flame_forge2d/README.md
Some links were not converted when we renamed a directory from forge2d to flame_forge2d.
> chore: Fix some broken flame_forge2d links

- packages/flame/lib/src/collisions/broadphase/quadtree/has_quadtree_collision_detection.dart
- packages/flame/lib/src/game/mixins/keyboard.dart
Since FlameGame now takes in `W extends World` the mixins that are `on FlameGame` needs to be able to take in the same generics.
Later the `HasKeyboardHandlerComponents` wont be necessary, but let's do this intermediary step.
Closes #2761
> fix: Add necessary generics on mixins on FlameGame

- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/test/components/text_box_component_test.dart
Fix `TextBoxComponent` alignment bug
The `anchor` is the anchor of the text box component itself.
It has nothing to do with the alignment of the text within the box.
The position computed for rendering the text on the above lines is assuming `topLeft` anchor for the text.
* [discord thread](https://discord.com/channels/509714518008528896/516639688581316629/1157552876936233031)
> fix: Fix TextBoxComponent alignment bug

- examples/lib/stories/camera_and_viewport/follow_component_example.dart
- examples/lib/stories/components/clip_component_example.dart
- examples/lib/stories/components/components_notifier_provider_example.dart
- examples/lib/stories/components/spawn_component_example.dart
- examples/lib/stories/rendering/rich_text_example.dart
- packages/flame/example/lib/main.dart
- packages/flame_audio/example/lib/main.dart
- packages/flame_isolate/example/lib/game_map/game_map.dart
I was playing around with the rule [avoid-global-state](https://dcm.dev/docs/rules/common/avoid-global-state/)
While I don't think we should enable it, because we do have several totally legitimate cases of what the rule considers global state, it did help me find any current cases where the things just _should_ be final constants.
So this PR will mark semantically final variables as final (or const) proper, exclusively on examples (no violations on actual src code are legit).
> refactor: Mark semantically final variables as final (or const) proper [DCM]

- packages/flame/lib/src/effects/controllers/zigzag_effect_controller.dart
- packages/flame/lib/src/game/game_widget/gesture_detector_builder.dart
- packages/flame/test/effects/controllers/sequence_effect_controller_test.dart
- packages/flame_jenny/jenny/lib/src/structure/expressions/expression.dart
- packages/flame_jenny/jenny/lib/src/variable_storage.dart
I was playing around with the rule [avoid-nested-conditional-expressions](https://dcm.dev/docs/rules/common/avoid-nested-conditional-expressions/).
While I philosophically agree with the rule, sadly Dart's new switch-as-an-expression, while a much-needed improvement, still pales in comparison to Kotlin's powerful `when`, which makes it impossible to convert all cases of nested ternaries into something actually better. In some cases, given the tools that Dart provides, I think nested ternary is the best option.
Notwithstanding, I used the rule to catch many cases where the new switch expression can be used to vastly simplify our codebase, making it much more readable. …
> refactor: Avoid nested conditional expressions whenever possible [DCM]

- doc/bridge_packages/flame_forge2d/forge2d.md
- packages/flame_forge2d/example/lib/main.dart
- packages/flame_forge2d/lib/body_component.dart
- packages/flame_forge2d/test/body_component_test.dart
This change introduces a way to create `BodyDef` and `FixtureDef`s as early as in constructor - or even earlier. This allows to pass position and other body/fixture related parameters to constructor, and not have them stick around as `this.initialThis` or `this.initialThat`.
For example:
```
class OffroadWheel extends BodyComponent {
OffroadWheel(
Vector2 initialPosition,
double radius,
) : super(
bodyDef: BodyDef(position: initialPosition), type: BodyType.dynamic),
fixtureDef: FixtureDef(CircleShape()..radius = radius),
);
}
```
I added `fixtureDef` constructor argument for convenience.
[CHANGELOG]: …
> feat: Allow for bodyDef and fixtureDefs to be prepared earlier

- packages/flame/lib/src/layout/align_component.dart
At the moment, I have removed the additional check, because an object deleted outside its parent may not be checked and the reference is not reset in the onChildrenChanged method
> fix: AlignComponent set child (remove compare)

- .github/workflows/cicd.yml
- doc/flame/examples/pubspec.yaml
- doc/tutorials/bare_flame_game.md
- examples/games/rogue_shooter/pubspec.yaml
- examples/games/trex/pubspec.yaml
- examples/pubspec.yaml
- packages/flame/example/pubspec.yaml
- packages/flame/pubspec.yaml
- packages/flame_audio/pubspec.yaml
- packages/flame_fire_atlas/pubspec.yaml
- packages/flame_forge2d/example/pubspec.yaml
- packages/flame_forge2d/pubspec.yaml
- packages/flame_jenny/pubspec.yaml
- packages/flame_lottie/pubspec.yaml
- packages/flame_markdown/pubspec.yaml
- packages/flame_noise/pubspec.yaml
- packages/flame_oxygen/pubspec.yaml
- packages/flame_rive/pubspec.yaml
- packages/flame_spine/pubspec.yaml
- packages/flame_test/pubspec.yaml
- packages/flame_tiled/pubspec.yaml
Due to [this](https://docs.flutter.dev/release/breaking-changes/add-applifecyclestate-hidden) breaking change we have to bump our lowest supported Flutter version to 3.13.
This PR also adds so that we both analyze with the latest stable flutter version and our lowest supported one.
Closes #2778 
Simply upgrade to a stable version equal to or greater than Flutter 3.13 by running `flutter upgrade`.
> chore: Bump to Flutter 3.13

- .github/workflows/cicd.yml
- .github/workflows/gh-pages.yml
Sets the min flutter version in the CI from env and moves to the stable melos version for the gh pages build.
> ci: Sets the min flutter version from env

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
ComponentKey for children components were not getting unregistered when the sub-tree was removed from the game. As a result:
- same key couldn't be reused
- components with such keys couldn't be readded once removed
- component with such keys were not being garbage collected (didn't actually verify this one though)
> fix: Un-register component keys down the component tree

- packages/flame_svg/lib/svg.dart
When rendering the SVG for the first time, on devices with pixelRatio > 1, the image is rendered bigger. Only subsequent renders that utilize `_imageCache` are rendering the SVG properly.
Tested on screens with pixelRatio=1 (LG, 2560x1080) and =2 (MacBook Pro M1)
> fix: Do not render SVGs bigger than requested when pixelRatio > 1 and no match in _imageCache

- examples/games/padracing/lib/lap_line.dart
- examples/games/rogue_shooter/lib/main.dart
- packages/flame/lib/src/components/parallax_component.dart
- packages/flame/lib/src/image_composition.dart
- packages/flame/lib/src/sprite.dart
- packages/flame/test/cache/assets_cache_test.dart
- packages/flame/test/cache/memory_cache_test.dart
- packages/flame/test/components/text_box_component_test.dart
- packages/flame/test/game/mixins/single_game_instance_test.dart
- packages/flame/test/particles/curved_particle_test.dart
- packages/flame/test/sprite_animation_ticker_test.dart
- packages/flame/test/spritesheet_test.dart
- packages/flame_audio/lib/flame_audio.dart
- packages/flame_fire_atlas/lib/flame_fire_atlas.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
- packages/flame_jenny/jenny/test/structure/commands/jump_command_test.dart
- packages/flame_jenny/jenny/test/structure/commands/visit_command_test.dart
- packages/flame_jenny/jenny/test/structure/expressions/functions/dice_test.dart
- packages/flame_jenny/jenny/test/structure/expressions/functions/random_range_test.dart
- packages/flame_lottie/example/lib/main.dart
- packages/flame_rive/test/flame_rive_test.dart
- packages/flame_test/lib/src/test_flame_game.dart
- packages/flame_tiled/lib/src/renderable_tile_map.dart
- packages/flame_tiled/test/tile_atlas_test.dart
- packages/flame_tiled/test/tiled_test.dart
Proposal: remove unnecessary 'async' keyword across the codebase.
This is following the DCM rule [avoid-redundant-async](https://dcm.dev/docs/rules/common/avoid-redundant-async)
Sadly we cannot enable the rule, as it has 3 false positives (cc @incendial if you wanna take a look!)
> refactor: Remove unnecessary 'async' keyword across the codebase [DCM]

- doc/flame/structure.md
- packages/flame/lib/src/cache/assets_cache.dart
- packages/flame/lib/src/cache/images.dart
- packages/flame/test/cache/assets_cache_test.dart
- packages/flame/test/cache/images_test.dart
- packages/flame_tiled/lib/src/tiled_component.dart
- packages/flame_tiled/test/tile_atlas_test.dart
- packages/flame_tiled/test/tiled_test.dart
Previously, `Images` and `AssetsCache` would always try to fetch assets from the `rootBundle`.
With this PR, we can have instances of those classes that uses a custom `AssetsBundle`. When this gets merged, we could consider refactoring flame_network_assets to  use this new feature and allow Flame users to use the same API
to load both local and network assets.
> feat: AssetsBundle can be customized in Images and AssetsCache.

- packages/flame/lib/camera.dart
- packages/flame/lib/src/camera/camera_component.dart
The `CameraComponent.withFixedResolution` was a factory but can easily be a redirect constructor, allowing developers to use it when they extend the `CameraComponent`. On top of that the `FixedResolutionViewport` was not being exported so if a developer wanted to have a custom camera with a `FixedResolutionViewport` there was no way to do so unless they imported from `src/` or copied the code, both are bad practices 😄 
> fix(flame): Export `FixedResolutionViewport` and make `withFixedResolution` a redirect constructor

- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/position_component.dart
Right now the debug texts (certain coordinates of components) use 12px size, but `zoom: 10` turns that into `120px`. This PR fixes that, debug informations are displayed using 12px size font, regardless of zoom.
> fix: Do not scale debug texts with zoom

- packages/flame/lib/src/collisions/collision_passthrough.dart
- packages/flame/test/collisions/collision_passthrough_test.dart
In `CollisionPassthrough`, while searching for an ancestor with `CollisionCallbacks` mixin, `firstWhere` was used. This was causing it to fail when no such ancestor was found. But having a passthrough parent is not necessary, at least rest of the code wasn't designed on that assumption. So this PR replaced `firstWhere` with `firstWhereOrNull` allowing the passthrough to be null.
This was discovered in one of the [discord discussions](https://discord.com/channels/509714518008528896/516639688581316629/1163600349643411467). …
> fix: Allow null passthrough parent

- packages/flame_jenny/jenny/lib/src/parse/parse.dart
- packages/flame_jenny/jenny/lib/src/structure/dialogue_line.dart
- packages/flame_jenny/jenny/test/dialogue_runner_test.dart
According to the YarnSpinner Documentation the tag "#lastline" should be added on each line bevore a choice.
https://docs.yarnspinner.dev/getting-started/writing-in-yarn/tags-metadata#special-tags
This PR does this.
> feat: Added lastline before choice

- doc/tutorials/klondike/app/lib/step2/klondike_game.dart
- doc/tutorials/klondike/app/lib/step3/klondike_game.dart
Previously, as part of Issue #2798, I fixed the Klondike Tutorial app's step4 executable to use the Flame 1.9.x `world` and `camera` built-in objects and described the new code in the Step 2 tutorial, where it first appears in the discussion. However, the Step 2 and Step 3 tutorial texts have options to execute code and those did not include the new code. Accordingly, I have cloned the relevant code into `app/lib/step2/klondike_game.dart` and `app/lib/step3/klondike_game.dart`. I have also checked that there are no `*.md` files to be updated. The `step2.md` tutorial file covers Issue #2799 AFAICS.
- [-] I have …
> fix: Finishing touches to use v1.9.x+ world and camera and complete Issue #2799

- .github/.cspell/gamedev_dictionary.txt
- doc/README.md
Use `flutter pub add` instead of munging the `pubspec.yaml` file for adding `flame` as a dependency
> docs: Use `flutter pub add` to add `flame` dependency

- packages/flame/lib/src/game/flame_game.dart
- packages/flame/test/game/flame_game_test.dart
Currently setting a new `FlameGame.camera` can cause `camera.world` to no long match `game.world`, which I think it's safe to assume is never desirable.
This PR sets the `camera.world` to the game's `world` when setting a new Camera, this matches what happens when a new World is set on the game (`world.camera` is set automatically).
> fix: Setting world on FlameGame camera setter

- doc/flame/rendering/particles.md
- packages/flame/lib/src/particles/particle.dart
- packages/flame/lib/src/particles/scaling_particle.dart
- packages/flame/test/particles/scaling_particle_test.dart
Added a ScalingParticle class that lerp between 1 and a given scale, a shorthand in the Particle class called scaling and updated the docs. Also exposed a getter for the lifespan property in the Particle class.
> feat: Scaling particle feature

- .github/ISSUE_TEMPLATE/bug_report.yml
- examples/games/padracing/lib/tire.dart
- examples/lib/stories/bridge_libraries/flame_forge2d/animated_body_example.dart
- examples/lib/stories/bridge_libraries/flame_forge2d/blob_example.dart
- examples/lib/stories/bridge_libraries/flame_forge2d/sprite_body_example.dart
- examples/lib/stories/bridge_libraries/flame_forge2d/utils/balls.dart
- examples/lib/stories/bridge_libraries/flame_forge2d/widget_example.dart
- melos.yaml
- packages/flame_forge2d/example/lib/main.dart
- packages/flame_forge2d/lib/forge2d_game.dart
- packages/flame_forge2d/lib/forge2d_world.dart
- packages/flame_forge2d/pubspec.yaml
- pubspec.yaml
Bumps forge2d to 0.12.2
Migration instructions:
The gravity and bullet are now field setters and getters, so if you before had `setGravity(Vector2(0, -10))` then you now do `gravity = Vector2(0, -10);` and if you previously had `body.setBullet(true);` you now do `body.isBullet = true;`.
> chore: Bump Forge2D to 0.12.2

- packages/flame_tiled/lib/flame_tiled.dart
- packages/flame_tiled/lib/src/renderable_layers/renderable_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/hexagonal_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/isometric_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/orthogonal_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/staggered_tile_layer.dart
- packages/flame_tiled/lib/src/renderable_layers/tile_layers/tile_layer.dart
- packages/flame_tiled/lib/src/renderable_tile_map.dart
- packages/flame_tiled/lib/src/tile_atlas.dart
- packages/flame_tiled/lib/src/tiled_component.dart
Creates a configuration in Flame Tiled that allows developers to use custom paint objects which can be useful when we need to render tilesets that require a different Paint configuration other than the default one. Like low rez pixel art tilesets which benefits from using filterQuality.none
> feat: Adding way to configure a layer paint in flame tiled

- .github/workflows/cicd.yml
Bump the `melos-action` to v3, where only yaml is used instead of separate scripts.
> ci: Bump melos-action to v3

- packages/flame/lib/src/sprite_batch.dart
After a chat with the flutter team responsible for the rendering engine, I've learned that we don't need to pass a blend mode and colors for the `drawAtlas` call is those colors/blending will not generate any real change in the rendered result.
On `SpriteBatch` by default we add a full transparent color for all the rects in the batch, that blending makes no difference in the final rendered call since it is a transparent color, so we were adding unnecessary processing in the calls.
This PR changes `SpriteBatch` in a way that is had no default blending color and it will just pass those colors to `drawAtlas` if the developer has explicit informed a default color or a color in the render.
I made a quick benchmark and this optimization is minor, but still noticeable. To make it easier to …
> feat: Optimization in sprite batch

- examples/lib/stories/input/hover_callbacks_example.dart
Fix Hover Callbacks so the tap used in the example respects the zoom.
The example happens to use a tap event to create new squares. However, since the tap event is bound to the Game instead of the World, had it had any zoom applied (which it didn't), or any other camera transform, the squares would have been created on the wrong place. This sends a bad example to new users and can cause confusion.
> docs: Fix Hover Callbacks so the tap used in the example respects the zoom

- examples/lib/stories/input/tap_callbacks_example.dart
Use world on tap_callbacks_example. We should just standardize all examples to use the world unless there is a reason not to, in order to avoid confusing users.
> fix: Use world on tap_callbacks_example

- packages/flame/lib/src/camera/viewfinder.dart
- packages/flame/lib/src/camera/viewport.dart
Make `Viewfinder` and `Viewport` comply with `CoordinateTransform` interface; they already perform the coordinate transform operation but didn't technically implement then interface.
> docs: Make Viewfinder and Viewport comply with CoordinateTransform interface

- examples/lib/stories/input/drag_callbacks_example.dart
- examples/lib/stories/input/input.dart
- examples/lib/stories/input/overlapping_tap_callbacks_example.dart
Fix naming of drag- and tap-callbacks examples
> docs: Fix naming of drag- and tap-callbacks examples

- doc/flame/examples/lib/main.dart
Add an ad-hoc index page with routing links to all examples within doc/flame/examples.
Before, it would just show a cryptic error message that would require checking the code to understand how to access a specific one.
These examples are used with route pre-set within the docs so they are not normally accessed by users directly, however this is helpful when you refactor something and wish to double-check the examples still work.
Obviously it could be improved further, but this already helps finding what you seek quickly.
> docs: Add index page with routing links to doc/flame/examples

- .github/.cspell/words_dictionary.txt
- examples/games/trex/lib/trex_game.dart
Update t-rex game to use `TapCallbacks` instead of `TapDetector`,  in anticipation of [deprecating the latter](https://github.com/flame-engine/flame/pull/2886).
Also update the term high score to avoid a dictionary entry.
Tested by running the game.
> docs: Update t-rex game to use TapCallbacks

- doc/tutorials/klondike/app/lib/step5/components/card.dart
- doc/tutorials/klondike/app/lib/step5/components/tableau_pile.dart
- doc/tutorials/klondike/app/lib/step5/klondike_world.dart
When the cards are dealt at the start of a Klondike Step 5 game there are multiple occurrences of unrealistic behaviors:
- Several cards being dealt may come from the middle of the Stock Pile,
- Cards that are dealt early can be seen moving in front of cards that are dealt later.
Each card dealt should be rendered on the top of the Stock Pile and should be seen to come from there. During the deal, later cards dealt are placed on top of earlier ones, so later cards should be seen to move in front of earlier ones when they are travelling from the Stock Pile to their positions in the layout.
- [-] I have updated/added …
> fix: Issue #2889, Klondike Step5, incorrect animation of the deal.

- doc/tutorials/klondike/app/lib/step5/components/card.dart
- doc/tutorials/klondike/app/lib/step5/components/stock_pile.dart
- doc/tutorials/klondike/app/lib/step5/klondike_game.dart
- doc/tutorials/klondike/app/lib/step5/klondike_world.dart
The objective of this fix is to make a tap on a card more positive-feeling for the player and not to disappear silently if it is interpreted as a drag.
It adds a Base Card to make an empty Stock Pile behave as a Card and use the tap and drag logic of the `Card` class. Any attempted drag on a Stock Pile card, including the Base Card, is now changed to a tap in onTapCancel() and the drag is not followed. The Base Card is rendered in outline only and does *not* take part in gameplay.
In other Piles a short drag is either treated as a tap or ignored. Only the Waste and Tableau Piles allow such taps. As before in Klondike Step5, they result in the tapped card moving automatically to its Foundation Pile if it is eligible to "go out".
As before in Klondike Step4 and Step5, all piles except the …
> docs: Klondike Step5, re-work drags and taps

- doc/flame/rendering/text_rendering.md
This changed `=` to `:` when calling named parameter `position`.
> docs: Fix typo in TextComponent sample code

- packages/flame/lib/src/camera/behaviors/bounded_position_behavior.dart
- packages/flame/test/camera/behaviors/bounded_position_behavior_test.dart
The `bounds` setter of `BoundedPositionBehavior` tries to update the target's position when bounds are updated. But it wasn't checking if the target is null. This was causing null exceptions while updating bounds of an unmounted `BoundedPositionBehavior` with null target (as seen in [this failing test case](https://github.com/flame-engine/flame/actions/runs/7231182930/job/19704091006#step:5:1291)). This PR fixes that by checking if the target is null before updating the position.
Closes #2655 
> fix: Allow setting `bounds` while `BoundedPositionBehavior`'s target is null

- packages/flame/lib/src/cache/memory_cache.dart
- packages/flame/test/cache/memory_cache_test.dart
Fixes a logic error which prevented values in `MemoryCache` from being updated when calling `setValue` with a preexisting `key`.
Assuming nobody is expecting the memory cache _not_ to be updatable? This is possible, I just don't think it's very probable.
> fix: Logic error in MemoryCache.setValue()

- packages/flame_riverpod/lib/src/widget.dart
Added missing fields from the GameWidget default constructor to the RiverpodAwareGameWidget constructor.
This PR was already discussed on the Discord server with spydon.
This PR is not a breaking change.
> fix: Add super constructor fields to RiverpodAwareGameWidget

- packages/flame_riverpod/lib/src/widget.dart
The forceRebuild function now has an "isDirty" check to determine whether setState should be called. Previously, setState was uncritically invoked which *could* produce the Flutter framework error that occurs when setState is called while widgets are still being rebuilt. 
The setState call inside ref.watch has been replaced with a call to forceRebuild, and forceRebuild now has checks to prevent setState from being called while a build is in progress. A persistent frame callback has been added to reset supporting flags. 
N/A. Customer reported issue[ via Discord.](https://discord.com/channels/509714518008528896/1186421112217813062/1186908306179100723)  …
> fix: Package flame_riverpod, setState() or markNeedsBuild() called during build.

- CHANGELOG.md
- packages/flame/CHANGELOG.md
- packages/flame/pubspec.yaml
- packages/flame_riverpod/CHANGELOG.md
- packages/flame_riverpod/pubspec.yaml
```
Package Name     Current Version   Updated Version   Update Reason
flame            1.13.0            1.13.1            manual versioning
flame_riverpod   5.1.1             5.1.2             manual versioning
```
> chore(release): Flame v1.13.1

- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
- packages/flame/test/components/sprite_animation_group_component_test.dart
- packages/flame/test/components/sprite_group_component_test.dart
With these new notifiers you can get notified when the current animation or sprite changes in the group components.
The value notifier is not initialized unless the user tries to use it, so it doesn't carry any extra weight on the components.
> feat: Notifier for changing current sprite/animation in group components

- .github/.cspell/gamedev_dictionary.txt
- packages/flame_riverpod/lib/src/consumer.dart
This PR changes the return type of RiverpodComponentMixin.onLoad to match that of Component.onLoad. 
This resolves #2961 which describes an error preventing use of RiverpodComponentMixin on Component subclasses that return a Future in their implementation of onLoad due to a signature mismatch. 
Closes #2961.
> fix: Change return type of RiverpodComponentMixin.onLoad to FutureOr<void>

- packages/flame/lib/src/collisions/collision_detection.dart
- packages/flame/lib/src/collisions/standard_collision_detection.dart
- packages/flame/test/collisions/collision_detection_test.dart
Adds a new argument callback to all `raycast*` methods that lets the user ignore hitboxes dynamically. The callback is called with every prospective hitbox, and the hitbox is only considered when the callback returns `true`.
This is faster, in the general case, than the current `ignoreHitboxes` aproach. And it lets the developer have dynamic rules about what the rays collide with. (For example, a line-of-fire raycast should take friendlies into account, but could easily ignore other enemies that get in the way.)
For people who just _use_ raycasts, this is not a breaking change.
People who extend `CollisionDetection` will need to support the new argument. I'd say this is pretty rare but not unheard of.
If you have your own custom collision detection logic (a class implementing or extending …
> feat: Add a hitboxFilter argument to raycast()

- packages/flame/lib/src/geometry/polygon_component.dart
- packages/flame/test/components/shape_component_test.dart
Previously, the `PolygonComponent.containsPoint()` and `.containsLocalPoint()` functions consisted of duplicate code that checked whether a given point lies within a convex polygon. They didn't function properly with concave polygons.
I created a new `_containsPoint()` function that is called from both functions to reduce redundancies. This new function uses a different approach to figure out whether a point lies within a polygon, which should also work for concave polygons, or even polygons with holes. The algorithm is vaguely explained within code comments, and is visualized in this post: https://stackoverflow.com/a/218081/5008997
[CHANGELOG]: …
> fix: Updated PolygonComponent.containsPoint to account for concave polygons

- packages/flame/lib/src/components/core/component.dart
- packages/flame_riverpod/lib/src/consumer.dart
- packages/flame_riverpod/lib/src/widget.dart
Since the user might want to use the `ComponentKey` after it has been assigned it should be made public.
It also updates `Consumer.key` to `Consumer.widgetKey` in flame_riverpod to avoid a name clash. (Slightly breaking)
If you are using `consumer.key` from flame_riverpod you have to now use `consumer.widgetKey` instead.
Closes #2985
> feat: Make `Component.key` public

- .github/.cspell/gamedev_dictionary.txt
- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/test/camera/camera_component_test.dart
When camera is following a component and trying to follow another target I got an exception:
```
dart:core                                              Iterable.forEach
package:flame/src/camera/camera_component.dart 326:25  CameraComponent.stop
package:flame/src/camera/camera_component.dart 309:5   CameraComponent.follow
test/camera/camera_component_test.dart 69:14           main.<fn>.<fn>
package:flame_test/src/test_flame_game.dart 80:21      testWithGame.<fn>
Concurrent modification during iteration: _Set len:0.
```
Copying viewfinder children before iterating through it and removing child from parent does the trick, as we are not iterating through the same list as we are removing items from, but rather a copy of it.
I tried to use camera from `game` provided in the test but it is AFAIK …
> fix: CameraComponent no longer throws Concurrent modification on stop

- doc/tutorials/klondike/step2.md
missing the 
import 'package:flame/flame.dart';
for this step
> docs: Add missing import in klondike tutorial

- packages/flame/lib/src/components/input/sprite_button_component.dart
- packages/flame/test/components/input/sprite_button_component_test.dart
Previously if you replaced a sprite in a `SpriteButtonComponent` with `component.button = ...` it didn't update the button visually since the `sprites` map wasn't updated, this PR solves that.
> fix: Properly update sprites in SpriteButtonComponent

- packages/flame/lib/src/components/core/component_key.dart
- packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/multi_drag_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/multi_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/pointer_move_dispatcher.dart
- packages/flame/test/extensions/_help.dart
- packages/flame/test/extensions/matrix4_test.dart
- packages/flame_lint/lib/analysis_options.yaml
- packages/flame_lint/lib/analysis_options_with_dcm.yaml
Fix warnings and lint issues across the codebase.
This includes:
* equals should now be Object instead of dynamic (and thus we don't need _help.dart anymore)
* the `always_require_non_null_named_parameters` lint rule is removed
* the `avoid-banned-imports` rule from DCM actually doesn't do anything unless configured
> chore: Fix warnings and lint issues across the codebase

- examples/lib/stories/input/joystick_advanced_example.dart
- packages/flame/lib/src/components/input/joystick_component.dart
- packages/flame/test/components/joystick_component_test.dart
The margins of the `JoystickComponent` weren't set properly, this PR fixes that.
> fix: Set margins of `JoystickComponent` properly

- packages/flame/lib/src/geometry/polygon_component.dart
- packages/flame/test/components/shape_component_test.dart
If the vertices in the `PolygonComponent` weren't starting at 0,0 they got the wrong hitbox, but rendered correctly.
This PR fixes that.
Closes: #3031
> fix: Vertices in `PolygonComponent` should subtract vertices positioning

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
Adding a child component to a parent which is in `removing` state, caused the lifecycle processing to go into a cyclic dependency when the parent is re-added. It happens because, while processing the lifecycle events, child's add event causes itself and the parent to get added to the blocked list. As a result of this, when the parent's add event is processed next, it gets skipped due to being in the blocked list.
This PR makes sure that the child does not get enqueued when parent is about to be removed.
NA
> fix: Check for removing state while adding a child

- packages/flame/lib/src/widgets/sprite_widget.dart
The unused fields of "SpriteWidget", "srcPosition" and "srcSize" and their matching parameter in the default constructor has been removed.
If SpriteWidget is used, remove the parameter srcPosition and srcSize as they have not been used in the default constructor.
(This does not belong to SpriteWidget.asset())
Closes #3071 
> fix!: Removed unused parameters from SpriteWidget

- packages/flame_riverpod/example/pubspec.yaml
- packages/flame_riverpod/lib/src/widget.dart
Changes to how support for manual listeners is implemented in flutter_riverpod 2.5.1 (released 4 days ago) have affected flame_riverpod - specifically, the implementation of ProviderSubscription. 
This PR updates the implementation of manual listeners in flame_riverpod in the same manner that flutter_riverpod has. 
No one has reported this as an issue yet. Evidence of the problem is[ visible on pub.dev](https://pub.dev/packages/flame_riverpod). 
> fix: Resolve breaking changes from Riverpod affecting flame_riverpod

- packages/flame_riverpod/lib/src/consumer.dart
Assignment of the game property on Components using RiverpodComponentMixin was being performed inside the onLoad method, meaning if components were unmounted and mounted once again, attempts to invoke callbacks to the GameWidget's build method would throw an exception. 
This functionality has been moved to the onMount method, where it always should have been.
Closes #3025
> fix: Resolve logic error with assignment of ComponentRef's game property in flame_riverpod

- packages/flame_forge2d/lib/forge2d_game.dart
- packages/flame_forge2d/test/forge2d_game_test.dart
`Forge2dGame` overrides the world's gravity even when a gravity vector is not provided to it. This causes the world to use the default gravity.
NA
> fix: Null gravity override by Forge2dGame

- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/extensions/vector2.dart
- packages/flame/test/extensions/vector2_test.dart
Adds a `toString` override for `PositionComponent` so that one can see all its properties easily.
> feat: Add PositionComponent.toString

- examples/lib/stories/collision_detection/collision_detection.dart
- examples/lib/stories/collision_detection/rays_in_shape_example.dart
- packages/flame/lib/src/collisions/hitboxes/circle_hitbox.dart
- packages/flame/test/collisions/collision_detection_test.dart
Previously some rays that originated outside of the `CircleHitbox` were counted as inside, this solves that and adds an example of how to use the `isInsideHitbox` functionality (thanks to @wurzelsand). 
Closes #3063 
> fix: CircleHitbox should properly detect when ray is outside

- doc/flame/rendering/text_rendering.md
- packages/flame/lib/src/components/scroll_text_box_component.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/test/components/scroll_text_box_component_test.dart
- packages/flame/test/components/text_box_component_test.dart
Implemented a callback function to notify when all text is displayed.
Removed unnecessary code.
Fixes #3088 
> feat: Add onFinished callback to ScrollTextBoxComponent

- doc/flame/collision_detection.md
- doc/flame/components.md
- doc/flame/inputs/other_inputs.md
- examples/pubspec.yaml
- packages/flame_forge2d/example/pubspec.yaml
This PR upgrades the `dashbook` to the latest version in the examples. After upgrading, the links related to this are also being updated in the docs. It also removes `dashbook` from dependencies of examples in `forge2d` as it no longer uses it.
Some parts of #2895 (like `5` and `6`) are fixed
Closes #2790
Has a one line conflict with #3072 in `other_inputs.md` (should not be much of an issue)
[CHANGELOG]: …
> docs: Upgrade dashbook version

- packages/flame/lib/src/text/renderers/text_paint.dart
- packages/flame/lib/src/text/styles/inline_text_style.dart
- packages/flame/test/text/text_paint_test.dart
Add ability to convert between `TextPaint` and `InlineTextStyle`.
The opposite is already possible with `asTextRenderer`, which this exposes.
> feat: Add ability to convert between TextPaint and InlineTextStyle

- .github/.cspell/flame_dictionary.txt
- packages/flame/lib/src/components/text_element_component.dart
- packages/flame/lib/src/text/elements/group_element.dart
- packages/flame/lib/src/text/elements/inline_text_element.dart
- packages/flame/lib/src/text/elements/rect_element.dart
- packages/flame/lib/src/text/elements/rrect_element.dart
- packages/flame/lib/src/text/elements/text_element.dart
- packages/flame/test/components/element_component_test.dart
- packages/flame/test/text/text_element_test.dart
Add accessor to determine a `TextElement` size.
Currently, there is no way to figure out the actual size of a `TextElement`.
This is quite important as the element will have the lines laid out and broken down, so we need a way to determine the height of the resulting bounding box.
Before:
After:
> feat: Add accessor to determine a TextElement size

- packages/flame/lib/src/camera/viewports/fixed_resolution_viewport.dart
Updates the dartdocs of `FixedResolutionViewport` since it has an accidental copy paste from another viewport.
Closes #3131
> docs: Update the dartdocs for `FixedResolutionViewport`

- packages/flame_3d/README.md
- packages/flame_3d/example/.gitignore
Fix minor nits on flame_3d, namely:
* fix wrong bash command on the readme file
* add missing git ignore to the example
This was extracted directly from @wolfenrain 's [bigger PR](https://github.com/flame-engine/flame/pull/3085), making it easier to merge later.
> feat(flame_3d): Fix minor nits on flame_3d

- doc/tutorials/platformer/app/lib/ember_quest.dart
- packages/flame/lib/src/widgets/base_future_builder.dart
- packages/flame/test/components/scroll_text_box_component_test.dart
- packages/flame/test/components/text_box_component_test.dart
- packages/flame/test/effects/controllers/effect_controller_test.dart
- packages/flame/test/extensions/canvas_test.dart
- packages/flame_bloc/pubspec.yaml
- packages/flame_lint/lib/analysis_options.yaml
- packages/flame_lint/pubspec.yaml
Expand flame_lint to respect required pub.dev checks.
We are currently losing pub points due to lint violations:
Turns out `flame_lint` does not respect lints/core which is being enforced now by pub.
This adds that as a dependency on `flame_lint`, updates `flutter_lint` for the packages that use that, and fix all existing violations (luckily very few).
This change will ensure that us and everyone else who uses `flame_lint` get all the points they deserve on pub. We can consider expanding to `lints/recommended` in the future, but that is definitely not a requirement at this stage (and a much bigger change).
[CHANGELOG]: …
> feat: Expand flame_lint to respect required pub.dev checks

- examples/lib/stories/rendering/isometric_tile_map_example.dart
- examples/lib/stories/rendering/rendering.dart
- packages/flame/lib/src/components/isometric_tile_map_component.dart
- packages/flame/test/components/isometric_tile_map_component_test.dart
Update IsometricTileMapComponent to have better defined position and size.
Before, the isometric component "zero" would be the center of the 0,0 block.
However, that does not play nicely with our component system if you want to know the size (i.e. bounding box) of a component.
This changes so that the 0,0 of the component is the 0,0 of the AABB around the isometric tiles. Then, it also computes the size of the component accordingly.
This also changes the example to allow toggling between half and full size more easily.
In our example, this is what it looks like:
The example still shows how to compute the previous origin (the purple dot) if you want to.
With full size blocks:
I also [updated isomash](https://github.com/luanpotter/isomash/pull/1) to check if more complex functionality plays …
> fix!: Update IsometricTileMapComponent to have better defined position and size

- doc/flame/examples/lib/router.dart
- doc/flame/examples/lib/value_route.dart
- doc/flame/router.md
Fixes #3143 
In the future we should probably add another boolean that controls whether the events should be able to pass through the route or not, independent on whether the route below is rendered or not.
> docs: Add background to `ValueRoute` example that captures events

- packages/flame/lib/src/text/renderers/text_paint.dart
- packages/flame/lib/src/text/styles/inline_text_style.dart
- packages/flame/test/text/text_paint_test.dart
Add missing parameters to `InlineTextStyle`, such as `height` and `shadows`.
Without this, it is not possible to configure such parameters in the new text rendering pipeline. Since the other parameters are 1:1 to Flutter's `TextStyle`, these missing fields seem to have been just an oversight.
However, it does make me question why are we copying the values from Flutter's class. I don't see why we could not just replace all these fields with a single `TextStyle` field. In fact, we could just make `TextPaint` extend `FlameTextStyle` and get rid of `InlineTextStyle` altogether. Either way, these can be followups.
[CHANGELOG]: …
> feat: Add missing parameters to InlineTextStyle

- examples/lib/stories/rendering/rendering.dart
- examples/lib/stories/rendering/rich_text_example.dart
- packages/flame/lib/src/text/nodes/text_block_node.dart
- packages/flame/lib/src/text/styles/block_style.dart
Support text align on new text rendering pipeline.
I am re-using Flutter's `TextAlign` enum for simplicity; however, it has extra constants we don't quite need. It has `start` and `end` that for us are synonyms of `left` and `right` because the text rendering pipeline does not support rtl text directions. It also has `justify` which this PR does not support as it is much more involved (though we could support later).
The other options were to either make a new enum, use a double from 0 to 1, or use the anchor class (but only take the horizontal component - vertically it doesn't make sense as it is always exactly line height). Of those options, I believe re-using the enum is cleaner.
That being said, this does touch on a crucial point that I am noticing: it seems we are rebuilding a lot of …
> feat: Support text align on new text rendering pipeline

- packages/flame/lib/src/components/input/advanced_button_component.dart
- packages/flame/test/components/advanced_button_component_test.dart
- packages/flame/test/components/toogle_button_component_test.dart
Add `onReleased` action which will be called within `onTapUp`. That fixed some scenarios which require the pressed action to be called after the user taps up the button.
For example, `AdvancedButtonComponent` doesn't show the `downSkin` if the action of `onPressed` changes the router to another page. That is because the router is changed before the `downSkin` is shown as the `onPressed` action is called in `onTapDown`.
Fixes #3150
> feat: Add `onReleased` action to `AdvancedButtonComponent` which will be called within `onTapUp`

- .github/.cspell/dart_dictionary.txt
- .github/.cspell/gamedev_dictionary.txt
- .github/.cspell/words_dictionary.txt
- .github/workflows/spell_checker.yml
This PR pin down the cspell version to 8.8.2. This will avoid random cspell check failures caused because of cspell updates.
NA
> chore: Pin cspell to 8.8.2

- packages/flame/lib/effects.dart
- packages/flame/lib/src/effects/controllers/delayed_effect_controller.dart
- packages/flame/lib/src/effects/controllers/infinite_effect_controller.dart
- packages/flame/lib/src/effects/controllers/mixins/has_single_child_effect_controller.dart
- packages/flame/lib/src/effects/controllers/random_effect_controller.dart
- packages/flame/lib/src/effects/controllers/repeated_effect_controller.dart
- packages/flame/lib/src/effects/controllers/speed_effect_controller.dart
- packages/flame/test/effects/controllers/mixins/has_single_child_effect_controller_test.dart
`DelayedEffectController` was not calling `setToStart` on its child, causing it to not behave as expected when used with `InfiniteEffectController`. This was reported by a discord member [in this message](https://discord.com/channels/509714518008528896/516639688581316629/1242258377766080666).
This PR introduces a `HasSingleChildEffectController` mixin which can be added to any effect controller that wraps a single child effect controller. This mixin makes sure that the `setToStart`, `setToEnd` and `onMount` methods always get invoked on the child controllers.
NA
> fix: Invoke `setToStart` on child effect controller of wrapping effect controllers

- packages/flame/lib/src/camera/behaviors/bounded_position_behavior.dart
- packages/flame/lib/src/camera/behaviors/follow_behavior.dart
- packages/flame/lib/src/camera/behaviors/viewport_aware_bounds_behavior.dart
- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/lib/src/camera/viewfinder.dart
- packages/flame/lib/src/camera/viewport.dart
- packages/flame/lib/src/camera/world.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/lib/src/components/input/keyboard_listener_component.dart
- packages/flame/lib/src/effects/anchor_by_effect.dart
- packages/flame/lib/src/effects/anchor_effect.dart
- packages/flame/lib/src/effects/anchor_to_effect.dart
- packages/flame/lib/src/effects/color_effect.dart
- packages/flame/lib/src/effects/component_effect.dart
- packages/flame/lib/src/effects/effect.dart
- packages/flame/lib/src/effects/glow_effect.dart
- packages/flame/lib/src/effects/move_along_path_effect.dart
- packages/flame/lib/src/effects/move_by_effect.dart
- packages/flame/lib/src/effects/move_effect.dart
- packages/flame/lib/src/effects/move_to_effect.dart
- packages/flame/lib/src/effects/opacity_effect.dart
- packages/flame/lib/src/effects/remove_effect.dart
- packages/flame/lib/src/effects/rotate_effect.dart
- packages/flame/lib/src/effects/scale_effect.dart
- packages/flame/lib/src/effects/sequence_effect.dart
- packages/flame/lib/src/effects/size_effect.dart
- packages/flame/lib/src/effects/transform2d_effect.dart
- packages/flame/lib/src/geometry/circle_component.dart
> fix: Add key parameters to the rest of the components

- packages/flame/pubspec.yaml
- packages/flame_audio/pubspec.yaml
- packages/flame_behavior_tree/pubspec.yaml
- packages/flame_bloc/pubspec.yaml
- packages/flame_fire_atlas/pubspec.yaml
- packages/flame_forge2d/pubspec.yaml
- packages/flame_isolate/pubspec.yaml
- packages/flame_jenny/jenny/pubspec.yaml
- packages/flame_jenny/pubspec.yaml
- packages/flame_lint/pubspec.yaml
- packages/flame_lottie/pubspec.yaml
- packages/flame_markdown/pubspec.yaml
- packages/flame_network_assets/pubspec.yaml
- packages/flame_noise/pubspec.yaml
- packages/flame_oxygen/pubspec.yaml
- packages/flame_rive/pubspec.yaml
- packages/flame_riverpod/pubspec.yaml
- packages/flame_spine/pubspec.yaml
- packages/flame_splash_screen/pubspec.yaml
- packages/flame_sprite_fusion/pubspec.yaml
- packages/flame_svg/pubspec.yaml
- packages/flame_test/pubspec.yaml
- packages/flame_texturepacker/pubspec.yaml
- packages/flame_tiled/pubspec.yaml
This adds topics to the packages so that they are more easily discoverable through pub.
> chore: Add topics to pubspec files

- packages/flame/lib/src/components/sprite_animation_group_component.dart
Many users try to modify the `SpriteAnimationGroupComponent.animations` map, but that doesn't work since it has to go through the setter, so this PR makes the returned map from the getter unmodifiable.
> fix: Disallow mutatation of `SpriteAnimationGroupComponent.animations`

- packages/flame/lib/src/components/input/sprite_button_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
Many users try to modify the `SpriteGroupComponent.sprites` map, but that doesn't work since it has to go through the setter, so this PR makes the returned map from the getter unmodifiable.
You can either set it by using the setter or set a particular sprite by using the newly created `updateSprite` method.
> fix: Disallow mutatation of `SpriteGroupComponent.sprites`

- packages/flame/lib/src/text/styles/inline_text_style.dart
Add missing background and foreground properties to `InlineTextStyle`.
Note that Flutter also exposes `backgroundColor` and `foregroundColor` as redundant helpers. I think for the sake of keeping things simpler on our end, in particular the merge logic, we can do away with those.
> feat: Add missing background and foreground properties to InlineTextStyle

- README.md
Link contributing doc into the relevant homepage section.
I noticed that we don't actually link our [contributing guide](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md) anywhere on our readme, so I propose we include it on the relevant section.
> docs: Link contributing doc into the relevant homepage section

- packages/flame/lib/src/text/nodes/bold_text_node.dart
- packages/flame/lib/src/text/nodes/code_text_node.dart
- packages/flame/lib/src/text/nodes/group_text_node.dart
- packages/flame/lib/src/text/nodes/inline_text_node.dart
- packages/flame/lib/src/text/nodes/italic_text_node.dart
- packages/flame/lib/src/text/nodes/plain_text_node.dart
Add dartdocs to inline text node classes.
> docs: Add dartdocs to inline text node classes

- packages/flame/lib/src/text/renderers/text_paint.dart
- packages/flame/test/text/text_paint_test.dart
Wire in background and foreground colors in TextPaint.
> fix: Wire in background and foreground colors in TextPaint

- examples/lib/stories/bridge_libraries/flame_forge2d/utils/boxes.dart
This PR makes the `DraggableBox` movement more smooth and predictable by:
1) adjusting `FixtureDef` and `MouseJointDef` parameters
2) setting the `MouseJoint` target to `game.screenToWorld(event.deviceEndPosition)` rather than `event.localEndPosition`
Fixes https://github.com/flame-engine/flame/issues/3203
The comparison recordings are presented below:
<details closed><summary>GearJointExample</summary>
| BEFORE | AFTER |
|----------|----------|
| <video src="https://github.com/flame-engine/flame/assets/30288967/8188ed18-e0aa-4c0f-a6c4-092015ba471c"> | <video src="https://github.com/flame-engine/flame/assets/30288967/2388bf23-ab32-43a8-af88-a974687b6901"> |
</details>
<details closed><summary>PrismaticJointExample</summary>
| BEFORE | AFTER |
|----------|----------|
| <video …
> docs(example): DraggableBox does not follow the cursor smoothly

- packages/flame_3d/example/lib/main.dart
- packages/flame_3d/lib/camera.dart
- packages/flame_3d/lib/core.dart
- packages/flame_3d/lib/extensions.dart
- packages/flame_3d/lib/game.dart
- packages/flame_3d/lib/src/camera/camera_component_3d.dart
- packages/flame_3d/lib/src/components/component_3d.dart
- packages/flame_3d/lib/src/components/mesh_component.dart
- packages/flame_3d/lib/src/extensions/matrix4.dart
- packages/flame_3d/lib/src/resources/mesh/vertex.dart
- packages/flame_3d/pubspec.yaml
- packages/flame_3d/test/vector2_extensions_test.dart
- packages/flame_3d/test/vector3_extensions_test.dart
- packages/flame_3d/test/vector4_extensions_test.dart
Expose vector classes on extensions file.
It is very common that we want to work with vector and matrices even though I don't want to import anything else specific from Flame. This PR allows we to use the extensions file as a base import similar to how it is on normal flame.
> feat: Expose vector classes on core file [flame_3d]

- packages/flame_3d/example/lib/crate.dart
- packages/flame_3d/lib/src/resources/mesh/cuboid_mesh.dart
- packages/flame_3d/lib/src/resources/mesh/mesh.dart
- packages/flame_3d/lib/src/resources/mesh/plane_mesh.dart
- packages/flame_3d/lib/src/resources/mesh/sphere_mesh.dart
- packages/flame_3d/lib/src/resources/mesh/surface.dart
Currently it is quite hard to operate with the `Mesh` class, because the list of surfaces is kept private.
I understand the concern with immutability, and the fact that the `aabb` must be recalculated when anything change.
Sadly I don't think Dart provides us with patterns to fully automate updating the `aabb`.
We need a way to update the meshes, so this is a compromise:
* add a getter to an unmodifiable list
* if the user updates the surfaces within, they are responsible for calling `updateBounds`
* add methods to update or remove elements from the list, which automatically call `updateBounds`
* this allow us to remove the silly "updateMaterial" methods that are used by Defend the Donut
This also adds an `add` method that takes a `Surface` object witch is extremely handy (even though it …
> feat: Make it easier work with the Mesh class [flame_3d]

- doc/flame/rendering/particles.md
- packages/flame/lib/src/particles/particle.dart
- packages/flame/lib/src/particles/scaling_particle.dart
- packages/flame/test/particles/scaling_particle_test.dart
This PR introduces a `curve` parameter to the `ScalingParticle` class. This allows for more flexible and customizable scaling by specifying different curves for scaling transformations. The default curve is set to `Curves.linear`, ensuring backward compatibility.
> feat: Take in super.curve in ScalingParticle

- packages/flame/lib/src/particles/scaled_particle.dart
This PR removed the CurvedParticle inheritance from the ScaledParticle, as the scale did not change over time which also ensures backwardwards compatibility as the Curve essentially did nothing.
> fix: Replace CurvedParticle inheritance with Particle in ScaledParticle

- examples/lib/stories/components/time_scale_example.dart
- examples/lib/stories/system/step_engine_example.dart
- packages/flame/lib/src/components/input/joystick_component.dart
- packages/flame_behavior_tree/behavior_tree/pubspec.yaml
- packages/flame_lint/pubspec.yaml
Update version of lints to comply with new pub requirements.
Turns out we are losing significant pub points due to lint violations:
The root cause was our severely outdated version of core lints used on `flame_lint`.
This updates it and fixes the new rule which forbids accessing parameters that are wildcards.
> fix: Update version of lints to comply with new pub requirements

- packages/flame_behavior_tree/behavior_tree/pubspec.yaml
Fix capitalization of the Dart programming language on pubspec description field
> docs: Fix capitalization of the Dart programming language on pubspec description field

- packages/flame/lib/src/camera/behaviors/follow_behavior.dart
This PR add a temp vector in `FollowBehavior` to avoid creating a new vector every frame for the delta calculations.
NA
> refactor: Use a temp vector for delta calculations of `FollowBehavior`

- packages/flame_texturepacker/lib/src/texture_packer_sprite.dart
TexturePackerSprite creates unnecessary Transform2D and Transform2DDecorator objects when region rotation is set to false. This bloats the TexturePackerSprite object size and causes severe performance issues when using thousands of TexturePackerSprites. This PR wraps the creation of these objects in a region rotation check.
> perf: Optimize `TexturePackerSprite` when sprites do not need to be rotated

- packages/flame_lint/lib/analysis_options_with_dcm.yaml
Enable DCM rule avoid-unnecessary-type-assertions.
More details [here](https://dcm.dev/docs/rules/common/avoid-unnecessary-type-assertions/). Note that we have to ignore mixins otherwise the rule has false positives.
> chore: Enable DCM rule avoid-unnecessary-type-assertions

- packages/flame_lint/lib/analysis_options_with_dcm.yaml
Enable DCM rule avoid-unrelated-type-assertions.
More details [here](https://dcm.dev/docs/rules/common/avoid-unrelated-type-assertions/). Note that we have to ignore mixins otherwise the rule has false positives.
> chore: Enable DCM rule avoid-unrelated-type-assertions

- packages/flame_3d/lib/src/camera/world_3d.dart
- packages/flame_3d/lib/src/game/notifying_quaternion.dart
- packages/flame_3d/lib/src/game/notifying_vector3.dart
- packages/flame_3d/lib/src/game/transform_3d.dart
- packages/flame_3d/lib/src/resources/mesh/vertex.dart
- packages/flame_3d/lib/src/resources/resource.dart
Update imports within flame_3d to not bring in flutter widgets unnecessarily.
I think it is prefer to import things directly when possible, for example:
* import meta instead of flutter
* import Color, Paint, etc from dart:ui
* import flutter foundations instead of widgets
Unless other things from a higher level are already used anyway (like a class that actually uses flutter widgets can keep those imports).
> chore: Update imports within flame_3d to not bring in flutter widgets unnecessarily [flame_3d]

- packages/flame_3d/lib/src/resources/mesh.dart
Add missing export for CylinderMesh
> fix: Add missing export for CylinderMesh [flame_3d]

- packages/flame_3d/example/lib/main.dart
- packages/flame_3d/lib/src/resources/mesh/cuboid_mesh.dart
- packages/flame_3d/lib/src/resources/mesh/surface.dart
- packages/flame_3d/lib/src/resources/mesh/vertex.dart
Add normals to surfaces when not specified.
Not all meshes come with normals.
For example, the provided `SphereMesh` has no normals.
Similarly, some GLTF files come without normals.
Note that this still allows the user to specify their own normals. For example, the `CuboidMesh` uses face normals by default.
However, if the user sets `useFaceNormals` to false, the vertex normals are computed instead.
All objects need normals for lighting purposes. The choice of using face or vertex normal is up to the user, as that will have different consequences.
> feat: Add normals to surfaces when not specified

- packages/flame/lib/src/devtools/connectors/component_tree_connector.dart
- packages/flame/lib/src/devtools/connectors/position_attributes_component_connector.dart
- packages/flame/lib/src/devtools/connectors/position_component_attributes_connector.dart
- packages/flame/lib/src/devtools/dev_tools_connector.dart
- packages/flame/lib/src/devtools/dev_tools_service.dart
- packages/flame_devtools/lib/providers/position_component_attributes_provider.dart
- packages/flame_devtools/lib/repository.dart
- packages/flame_devtools/lib/widgets/component_tree.dart
- packages/flame_devtools/lib/widgets/incremental_number_form_field.dart
- packages/flame_devtools/lib/widgets/position_component_attributes_form.dart
Adds fields to allow developers to change the x, y, width and height of position components from the dev tools.
https://github.com/user-attachments/assets/70f6fe15-488c-4eb2-83bf-6cdc050526d8
> feat: Adding x,y,width and height inputs to position components on Dev Tools

- .github/workflows/cicd.yml
- .github/workflows/gh-pages.yml
- .github/workflows/spell_checker.yml
- doc/flame/platforms.md
Use GitHub Actions checkout@v4 instead of v3.
`v3` is deprecated and giving us warnings:
> chore: Use GitHub Actions checkout@v4 instead of v3

- .github/workflows/cicd.yml
Use GitHub Actions github-action-dart-analyzer@v3 instead of v2.0.0
`v2.0.0` uses deprecated versions of other actions giving us warnings:
> chore: Use GitHub Actions github-action-dart-analyzer@v3 instead of v2.0.0

- .github/workflows/cicd.yml
Use GitHub Actions setup-node@v4 instead of v3.
`v3` is deprecated and giving us warnings:
> chore: Use GitHub Actions setup-node@v4 instead of v3

- packages/flame/example/README.md
Updates a README file.
Closes https://github.com/flame-engine/flame/issues/3286
> docs: Include information about the Flame DevTools extension in example readme

- doc/flame/examples/lib/drag_events.dart
- doc/flame/examples/lib/pointer_events.dart
- doc/flame/examples/lib/ray_cast.dart
- doc/flame/examples/lib/ray_trace.dart
- doc/flame/examples/lib/tap_events.dart
- doc/flame/rendering/particles.md
- examples/games/padracing/lib/lap_line.dart
- examples/games/padracing/lib/trail.dart
- examples/lib/stories/camera_and_viewport/camera_component_properties_example.dart
- examples/lib/stories/camera_and_viewport/fixed_resolution_example.dart
- examples/lib/stories/collision_detection/multiple_shapes_example.dart
- examples/lib/stories/collision_detection/raycast_example.dart
- examples/lib/stories/collision_detection/raycast_light_example.dart
- examples/lib/stories/collision_detection/raytrace_example.dart
- examples/lib/stories/components/keys_example.dart
- examples/lib/stories/effects/opacity_effect_example.dart
- examples/lib/stories/input/overlapping_tap_callbacks_example.dart
- examples/lib/stories/rendering/particles_example.dart
- packages/flame/lib/src/components/mixins/has_paint.dart
- packages/flame/lib/src/effects/color_effect.dart
- packages/flame/lib/src/extensions/color.dart
- packages/flame/lib/src/extensions/image.dart
- packages/flame/lib/src/layers/processors.dart
- packages/flame/lib/src/palette.dart
- packages/flame/test/components/mixins/has_paint_test.dart
- packages/flame/test/effects/opacity_effect_test.dart
- packages/flame/test/extensions/image_extension_test.dart
- packages/flame/test/extensions/paint_test.dart
- packages/flame_isolate/example/lib/terrain/grass.dart
- packages/flame_oxygen/example/lib/system/kawabunga_system.dart
Update usages of Dart UI Color to not use deprecated fields and methods.
On latest main of Flutter these will cause lint errors, [as can be seen here](https://github.com/flame-engine/flame/actions/runs/10814047130/job/29999530293?pr=3282).
Note: I will update the `flame_3d`-specific violations on a followup.
> chore: Update usages of Dart UI Color to not use deprecated fields and methods [flame_3d]

- packages/flame_3d/lib/src/extensions/color.dart
- packages/flame_3d/lib/src/resources/texture/color_texture.dart
> chore: Fix deprecated color methods [flame_3d]

- examples/lib/stories/widgets/paints.dart
- examples/lib/stories/widgets/sprite_animation_widget_example.dart
- examples/lib/stories/widgets/sprite_widget_example.dart
- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/sprite_painter.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
Adds a `Paint` attribute to the `SpriteWidget` and `SpriteAnimationWidget` for an improved API.
> feat: Adding paint attribute to SpriteWidget and SpriteAnimationWidget

- packages/flame/test/text/sprite_font_renderer_test.dart
- packages/flame_sprite_fusion/test/sprite_fusion_tilemap_component_test.dart
- packages/flame_tiled/test/tile_atlas_test.dart
- packages/flame_tiled/test/tiled_test.dart
Skip broken `drawRawAtlas` tests.
This has nothing to do with Flame 3D - just some issue on Flutter main.
In order to facilitate our build, this PR temporarily skips those tests.
That makes our build fully green :)
Obviously this should not be merged into main.
> test: Skip broken drawRawAtlas tests [flame_3d]

- packages/flame_3d/lib/src/extensions/quaternion.dart
- packages/flame_3d/test/quaternion_extensions_test.dart
Improve quaternion slerp logic to avoid NaN edge cases
> fix: Improve quaternion slerp logic to avoid NaN edge cases

- packages/flame/lib/src/camera/behaviors/viewport_aware_bounds_behavior.dart
- packages/flame/lib/src/camera/camera_component.dart
- packages/flame/lib/src/camera/viewfinder.dart
- packages/flame/test/camera/behaviors/viewport_aware_bounds_behavior_test.dart
The behavior for `CameraComponent.setBounds` was not behaving correctly. The viewport-aware behavior was not triggering until a window resize event. All supported bound variants were not respecting the fixed resolution viewport, or in some cases, behaving unpredictably.
The issue was with the fact the viewport-aware behavior component depends on the bounded position component to be in its parent, but was returning `null` during `onMount`. The viewport math was using the logical size instead of the virtual size. I made some math changes to be accurate.
This PR adds new a getter `CameraComponent.considerViewport`. `ViewportAwareBoundsBehavior` is now added as a side effect of mounting `BoundedPositionBehavior` by waiting for the `mounted` future. This guarantees that 
Flames life cycle is …
> fix: ViewportAwareBounds component and lifecycle issues

- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/test/components/component_test.dart
Adds a future that will complete once all lifecycle events have been processed.
If there are no lifecycle events to be processed (`hasLifecycleEvents` is `false`), then this future returns immediately.
This is useful when you modify the component tree (by adding, moving or removing a component) and you want to make sure you react to the changed state, not the current one.
Remember, methods like `Component.add` don't act immediately and instead enqueue their action. This action also cannot be awaited with something like `await world.add(something)` since that future completes _before_ the lifecycle events are processed.
Example usage:
```dart
player.inventory.addAll(enemy.inventory.children);
await game.lifecycleEventsProcessed;
updateUi(player.inventory);
```
Discussed here: …
> feat: Add ComponentTreeRoot.lifecycleEventsProcessed future

- packages/flame/lib/src/components/input/sprite_button_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
Just replaced the null check operator ```!``` with null aware ```?```. 
```void updateSprite(T key, Sprite sprite) {```
```_sprites?[key] = sprite;```
``` _resizeToSprite();```
```}```
the value of ```_sprites``` set on the ```mount()``` method of the ```SpriteButtonComponent``` class
#3293 
> fix: SpriteButtonComponent to initialize sprites in `onLoad`

- examples/lib/stories/system/resize_example.dart
- packages/flame_3d/lib/src/resources/material/material.dart
- packages/flame_3d/lib/src/resources/material/spatial_material.dart
- packages/flame_3d/lib/src/resources/shader.dart
- packages/flame_3d/lib/src/resources/shader/shader.dart
- packages/flame_3d/lib/src/resources/shader/uniform_array.dart
- packages/flame_3d/lib/src/resources/shader/uniform_instance.dart
- packages/flame_3d/lib/src/resources/shader/uniform_sampler.dart
- packages/flame_3d/lib/src/resources/shader/uniform_slot.dart
- packages/flame_3d/lib/src/resources/shader/uniform_value.dart
- packages/flame_3d/test/resources/shader/uniform_binding_test.dart
Refactor shader uniform binding to support shader arrays.
This also decouples the whole shader and uniform byte handling code (that we should definitely test) from the flutter_gpu primitives that are impossible to mock (base native classes).
This adds tests that ensure the arrays are bound as they should - however the underlying flutter_gpu code does not seem to work. See [this PR](https://github.com/flame-engine/flame/pull/3284) for a test of using this to support an arbitrary number of lights.
Either way, we can merge this as is as this refactors the underlying structure to support arrays when ready, and make it more testable as well.
[CHANGELOG]: …
> feat: Refactor shader uniform binding to support shader arrays [flame_3d]

- packages/flame/lib/input.dart
A few time ago I added TapConfig class. It allows us to config the tap timing.
However, it's not exported. This PR fix this problem.
> fix: Export TapConfig to make visible

- melos.yaml
This cleans up the melos `doc-setup` script a bit, if we're lucky it'll make the ci build the docs again.
> ci: Clean-up the doc-setup step

- melos.yaml
- scripts/doc-setup.sh
It needs to use the full root path to find the script.
> ci: Melos root path not needed for running doc setup script

- examples/lib/stories/widgets/nine_tile_box_example_with_animation.dart
- examples/lib/stories/widgets/partial_sprite_widget_example.dart
- examples/lib/stories/widgets/widgets.dart
- packages/flame/lib/src/widgets/animation_widget.dart
- packages/flame/lib/src/widgets/nine_tile_box.dart
- packages/flame/lib/src/widgets/sprite_widget.dart
- packages/flame/test/widgets/nine_tile_box_widget_test.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
- packages/flame/test/widgets/sprite_widget_test.dart
- packages/flame_test/lib/src/mock_image.dart
Fix the flickering in the widgets: `SpriteAnimationWidget`, `SpriteWidget` and `NineTileBoxWidget`.
Closes #3342
> fix: Widgets flickering

- doc/flame/overlays.md
- examples/lib/stories/system/overlays_example.dart
- packages/flame/lib/src/game/overlay_manager.dart
- packages/flame/test/game/overlays_manager_test.dart
To sort overlays we can introduce a priority. 
Let's say my app contains several menus that can be displayed simultaneously, but I want my main menu displayed at first in the stack (at the bottom).
> feat(overlays): Added the 'priority' parameter for overlays

- packages/flame_fire_atlas/lib/flame_fire_atlas.dart
Adding getters and methods to making it easier to copy new selections, which will help the editor to offer more features.
> feat: Adding getters and methods for easier manipulation of selections

- doc/tutorials/space_shooter/step_1.md
I have added the import required for the Canvas component. This tripped me up originally as I was following this example and had to go find out what import to use for the line `void render(Canvas canvas) {`
I did not make an issue since this is an extremely small issue and is regarding documentation and not any real code.
> docs: Update step_1.md to include imports for Canvas

- packages/flame/lib/src/components/clip_component.dart
- packages/flame/lib/src/components/custom_painter_component.dart
- packages/flame/lib/src/components/nine_tile_box_component.dart
- packages/flame/lib/src/components/sprite_animation_component.dart
- packages/flame/lib/src/components/sprite_animation_group_component.dart
- packages/flame/lib/src/components/sprite_component.dart
- packages/flame/lib/src/components/sprite_group_component.dart
- packages/flame/lib/src/geometry/circle_component.dart
I accidentally came across this. `PositionComponent` already implements `SizeProvider` but as it was added later it wasn't cleaned up everywhere.
> fix: Remove extra `implements SizeProvider`s

- packages/flame_console/lib/src/repository/memory_console_repository.dart
- packages/flame_console/lib/src/view/console_view.dart
Since the `MemoryConsoleCommandsRepository` maintains the commands in memory and modifies the its internal list, it can't be const.
> fix(flame_console): MemoryRepository can't be const

- doc/flame/platforms.md
Fixes https://github.com/flame-engine/flame/issues/3364
Merges two variables that mean the same thing into one. (NAME_OF_YOUR_REPOSITORY and YOUR_REPO_NAME)
> docs: Flame Platforms should unify variable for NAME_OF_YOUR_REPOSITORY

- .gitignore
- doc/flame/router.md
- examples/lib/main.dart
- examples/lib/stories/router/router.dart
- examples/lib/stories/router/router_world_example.dart
- packages/flame/lib/game.dart
- packages/flame/lib/src/camera/world.dart
- packages/flame/lib/src/components/router/overlay_route.dart
- packages/flame/lib/src/components/router/route.dart
- packages/flame/lib/src/components/router/router_component.dart
- packages/flame/lib/src/components/router/value_route.dart
- packages/flame/lib/src/components/router/world_route.dart
- packages/flame/test/components/world_route_test.dart
This PR adds the `WorldRoute` which acts as a normal route, but instead of adding a new component (page), it swaps out the world that the camera (either the default camera or an explicitly passed in one) is watching.
[Screencast from 2024-11-23 15-58-35.webm](https://github.com/user-attachments/assets/32165346-eb3d-4b6c-9af9-d200d01d0b2c)
> feat: Add WorldRoute to enable swapping worlds from the RouterComponent

- CHANGELOG.md
Update flame_3d CHANGELOG.md to match main + changes.
This is the second step in merging flame_3d into main. Before we do a final rebase of main back, the last "conflict" is the changelog file (as can be seen [on the temporary PR diff](https://github.com/flame-engine/flame/pull/3377)).
In order to solve this conflict, this does the following steps:
* Collect the changes from flame_3d compared to the current base branch version of main (i.e.: everything that was added to the changelog; this turns out to be two entries for the same day, `2024-09-16`).
* Replace the CHANGELOG.md file with the latest from current main
* Add back the missing entries, but I have doctored the days to be today (`2024-12-10`), in order to not "alter the past". I am happy with keeping the original date, though. No …
> chore: Update flame_3d CHANGELOG.md to match main + changes [flame_3d]

- packages/flame_3d/bin/build_shaders.dart
Make build_shaders script compatible with other platforms
> fix: Make build_shaders script compatible with other platforms [flame_3d]

- packages/flame_3d/lib/src/resources/texture/color_texture.dart
Fix albedo texture binding on shader
> fix: Fix albedo texture binding on shader

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
Fix bug preventing removeAll(children) from be called before mount.
Fixes https://github.com/flame-engine/flame/issues/2933
> fix: Fix bug preventing removeAll(children) from be called before mount

- packages/flame/lib/src/components/input/button_component.dart
- packages/flame/lib/src/components/input/sprite_button_component.dart
If the buttons are extended it doesn't automatically propagate the size from the `button` child component like it does if you pass the button into the constructor. This PR sets that size in `onMount` if the size is zero.
> fix: Set button size in onMount if not set

- packages/flame/lib/src/extensions/image.dart
The image data read back is in a pre-multiplied state. Convert it back to straight alpha before brightening and then premultiply.
This just makes the colors go to white though:
You could alternatively use the HSV color space and increase the Value (brightness); this would be more subtle and keep the colors correct.
> fix: Unmultiply before brightening

- doc/flame/other/other.md
- doc/flame/other/util.md
- packages/flame/lib/src/device.dart
Adds a warning when calling `fullScreen` and the new added method `restoreFullscreen` when used in a desktop platform.
Also adds a brief warning to the docs about some methods in the device class not working outside mobile
> feat: Warning and docs about fullscreen methods outside the mobile platforms

- packages/flame/lib/src/text/common/utils.dart
- packages/flame/lib/src/text/nodes/column_node.dart
- packages/flame/lib/src/text/nodes/document_root.dart
- packages/flame/lib/src/text/nodes/text_block_node.dart
- packages/flame/lib/text.dart
- packages/flame/test/text/text_element_test.dart
- packages/flame/test/text/text_style_test.dart
Add missing export of GroupElement to text.dart
> fix: Add missing export of GroupElement to text.dart

- packages/flame/lib/src/text/nodes/group_text_node.dart
- packages/flame/lib/text.dart
- packages/flame/test/text/text_style_test.dart
Add missing export of GroupTextElement to text.dart
> fix: Add missing export of GroupTextElement to text.dart

- packages/flame_markdown/example/assets/fire_and_ice.md
- packages/flame_markdown/lib/flame_markdown.dart
- packages/flame_markdown/test/flame_markdown_test.dart
Do not encode HTML by default when parsing markdown [flame_markdown].
The Flame text rendering pipeline is not configured to accept HTML encoded sequences, therefore the default behaviour of Flame Markdown doesn't lead to a good result:
With this change:
Of the user can still override it as before.
> fix: Do not encode HTML by default when parsing markdown [flame_markdown]

- .github/.cspell/words_dictionary.txt
- packages/flame/lib/src/text/nodes/strikethrough_text_node.dart
- packages/flame/lib/src/text/styles/document_style.dart
- packages/flame/lib/text.dart
- packages/flame_markdown/example/assets/fire_and_ice.md
- packages/flame_markdown/example/lib/main.dart
- packages/flame_markdown/example/pubspec.yaml
- packages/flame_markdown/lib/flame_markdown.dart
- packages/flame_markdown/test/flame_markdown_test.dart
Add support for strike-through text for flame_markdown, if enabled by the user.
Basically parses the `del` HTMl tag and maps it to a new inline text renderer in Flame's text rendering pipeline.
The style can be controlled with a new property if desired.
In order to parse `~~`-wrapped text into the new node element, the underlying markdown parser must have the strikethrough option enabled (or an equivalent custom option), which can be controlled by the user if providing their own document.
> feat: Add support for strike-through text for flame_markdown

- packages/flame_markdown/test/flame_markdown_test.dart
Enhance tests for flame_markdown to ensure nested styles are propagated.
Specifically adds a second section to each test to assert the element tree (after having asserted the node tree).
And then uses that to add a nested inline style test making sure the "CSS" is propagated and merged correctly.
> test: Enhance tests for flame_markdown to ensure nested styles are propagated

- packages/flame/lib/src/components/spawn_component.dart
- packages/flame/test/components/spawn_component_test.dart
add multiFactory to SpawnComponent to be able to create a list of components for each spawn tick. For backwards compatibility the single component factory is still supported and wrapped internally.
This PR enhances the SpawnComponent to accept a multiFactory which adds a list of components per tick instead of just one.
> feat: Add multiFactory to SpawnComponent

- packages/flame/lib/src/geometry/line_segment.dart
- packages/flame/test/geometry/line_segment_test.dart
feat: Add direction and length getters and constructor to LineSegment
> feat: Add direction and length getters and constructor to LineSegment

- pubspec.yaml
Fix melos/workspace scripts to be able to lint monorepo locally
> fix: Fix melos/workspace scripts to be able to lint monorepo locally

- examples/lib/stories/camera_and_viewport/camera_component_example.dart
This uses the built-in camera in the example, so that people don't create new default cameras accidentally.
> docs: Use built-in camera in example

- packages/flame/lib/src/components/nine_tile_box_component.dart
- packages/flame/lib/src/nine_tile_box.dart
This adds a possibility to override the paint in the `NineTileBox` class which enables `NineTileBoxComponent` to have `HasPaint`, so that opacity and color effects can be used on it.
Fixes: #3430 
> feat: NineTileBoxComponent with HasPaint to enable effects

- packages/flame/benchmark/update_components_benchmark.dart
- packages/flame/lib/src/camera/viewport.dart
- packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
- packages/flame/lib/src/collisions/standard_collision_detection.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/core/component_set.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/lib/src/components/mixins/has_paint.dart
- packages/flame/lib/src/components/position_component.dart
- packages/flame/lib/src/components/text_box_component.dart
- packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart
- packages/flame/lib/src/experimental/geometry/shapes/polygon.dart
- packages/flame/lib/src/game/flame_game.dart
- packages/flame/lib/src/geometry/line_segment.dart
- packages/flame/lib/src/layers/layer.dart
- packages/flame/lib/src/parallax.dart
- packages/flame/lib/src/text/elements/group_element.dart
Replaces uses of `.forEach()` with regular `for` loops. This has significant impact on performance in hot paths such as `Component.updateTree()` and `Component.renderTree()`.
In the graph above, you see 50 runs of `benchmark/update_components_benchmark.dart`. The forEach results are blue, the for-loop results are green. I could see this effect after just replacing the `forEach` calls in `component.dart`. Data [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vRk_yGmLN6o0oqSUWDBh7ODx7B8EIToeahZcZBS3VKHX8AbEnmrgmEqDt98cZLoBjIKQX3MlOc0XwsP/pubhtml).
> Aside for posterity: `for i in {1..50}; do flutter test benchmark/main.dart --no-pub -r silent 2>/dev/null >> benchmarks_for_loop.txt; done`, then get the data from the text file. 
I went ahead and replaced additional `forEach` calls …
> perf: Switch from forEach to regular for-loops for about 30% improvement in raw update performance

- packages/flame_test/lib/flame_test.dart
Simplify and unify syntax used for exports on flame_test.
The file in question only has one public class, which is exported.
This brings it in line with all other exports on the file - the only exception being `test_golden.dart` which does indeed declare other auxiliary public types.
> style: Simplify and unify syntax used for exports on flame_test

- packages/flame_test/lib/flame_test.dart
- packages/flame_test/lib/src/close_to_quaternion.dart
- packages/flame_test/lib/src/close_to_vector.dart
- packages/flame_test/lib/src/close_to_vector3.dart
- packages/flame_test/lib/src/close_to_vector4.dart
- packages/flame_test/lib/src/is_close_to_vector.dart
- packages/flame_test/test/close_to_quaternion_test.dart
- packages/flame_test/test/close_to_vector3_test.dart
- packages/flame_test/test/close_to_vector4_test.dart
- packages/flame_test/test/close_to_vector_test.dart
This creates a generic `CloseToVector` class to be used to power the existing `closeToVector2` and `closeToVector3` and brand-new `closeToVector4` and `closeToQuaternion` matchers. This base class is not exposed (for now; but we could reconsider if demand arises).
> feat: Implement closeToVector4 and closeToQuaternion by extracing a generic CloseToVector base

- packages/flame_3d/lib/src/game/transform_3d.dart
- packages/flame_3d/test/transform_3d_test.dart
Add setFromMatrix4 to Transform3D.
Also add some tests for Transform3D.
> feat: Add setFromMatrix4 to Transform3D

- .github/.cspell/people_usernames.txt
- packages/flame_audio/example/lib/main.dart
- packages/flame_audio/lib/bgm.dart
- packages/flame_audio/lib/flame_audio.dart
- packages/flame_audio/pubspec.yaml
AudioPlayers used to mix their sounds with other audio on the device, which is not the proposed experience on Mobile devices.  So this behavior was changed in AudioPlayers, but it wasn't enforced due to a bug. Obviously this behavior is not wanted for Games as multiple sounds should play simultaneously, so this recovers the old functionality again.
Not sure, if I can test this properly, as it's on a system level. I could ensure the values are set though (?)
I'm actually not sure, if this is breaking, I think it's not, as `audioplayers` used to work like `mixWithOthers` due to a bug, but is not anymore.
No related issues found
[CHANGELOG]: …
> feat(audio): Set audio context AudioContextConfigFocus.mixWithOthers by default

- packages/flame_3d/lib/src/game/transform_3d.dart
This is a minor nit, but it was bugging me that the order of parameters here was mismatched with everywhere else.
This standardizes the order of initializers on `Transform3D`.
> style: Standardize order of initializers on Transform3D

- packages/flame/lib/src/text/nodes/inline_text_node.dart
Fix missing reference on documentation for InlineTextNode
> docs: Fix missing reference on documentation for InlineTextNode

- packages/flame/lib/src/text/nodes/custom_text_node.dart
- packages/flame/lib/src/text/nodes/inline_text_node.dart
- packages/flame/lib/src/text/styles/document_style.dart
- packages/flame/lib/text.dart
- packages/flame_markdown/example/assets/fire_and_ice.md
- packages/flame_markdown/example/lib/main.dart
- packages/flame_markdown/example/pubspec.yaml
- packages/flame_markdown/lib/custom_attribute_syntax.dart
- packages/flame_markdown/lib/flame_markdown.dart
- packages/flame_markdown/test/flame_markdown_test.dart
This is a proposal to extend both our text rendering pipeline and our markdown-parsing capabilities to support more fine-grained styling by leveraging a subset of the extended markdown definition of "custom attributes" (for example, see [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) as an exemplary implementation).
On the markdown side, the syntax will look like this:
```markdown
[This is a custom class]{.my-custom-class}
This word will be [red]{.red} and this one will be [blue]{.blue}.
```
Note that the current implementation only supports specifying the class name and will skip other possible permutations.
On the Flame side, we add a new `customStyles` map to the `DocumentStyle` class, allowing users to provide as many styles as desired.
Example:
Currently, users …
> feat: Support custom attributes syntax to allow for multiple styles in the text rendering pipeline

- .github/workflows/gh-pages.yml
The web-renderer isn't needed anymore, and let's try to use the wasm compiler for the examples by default.
> chore: Remove deprecated gh-pages build argument

- packages/flame_tiled/lib/src/renderable_tile_map.dart
- packages/flame_tiled/test/assets/deleted_layer_map.tmx
- packages/flame_tiled/test/tiled_test.dart
This PR makes sure that `TileData` can be found using `layerIndex` as well as `layerId`.
Use `getTileDataByLayerIndex` instead of `getTileData` to get the `TileData` using layer index.
Closes #3536
> fix!: Add APIs to get TileData by layer index

- doc/bridge_packages/bridge_packages.md
After having some trouble using flamw_console, I realize it actually has documentation, but it was just missing on the menu.
> docs: Add missing flame_console link to docs

- doc/bridge_packages/flame_console/flame_console.md
Fix incorrect class name on flame_console docs.
As far as I can tell, there is no such thing as `ConsoleCommand` at all. At least I could not find it.
As per my testing, I believe this should be `FlameConsoleCommand`.
> docs: Fix incorrect class name on flame_console docs

- packages/flame/lib/src/camera/viewport.dart
- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/camera/viewports/fixed_resolution_viewport_test.dart
Children of `Viewport` were receiving the actual `size` of viewport as input on the `onParentResize` method. In most cases this is fine, but for viewports like `FixedResolutionViewport`, we should be using the `virtualSize`. This PR makes that change.
Closes #3529 
> fix: Use `virtualSize` when calling `onParentResize` on children of `Viewport`

- packages/flame_3d/example/lib/commands/commands.dart
- packages/flame_3d/example/lib/commands/reset_command.dart
- packages/flame_3d/example/lib/components/player.dart
- packages/flame_3d/example/lib/example_game_3d.dart
- packages/flame_3d/example/lib/main.dart
- packages/flame_3d/example/pubspec.yaml
Add flame_console to flame_3d example to enable more complex setups later on.
For now I am only adding one command, reset (which is already bound to R) but this will allow me to add much more complex things without requiring summoning byzantine keybindings.
> feat: Add flame_console to flame_3d example to enable more complex setups

- packages/flame/lib/src/components/core/component.dart
- packages/flame/test/components/component_test.dart
Currently children are not retaining their `parent` while they aren't mounted, even though they haven't been removed from their subtree, but their parent has. This is problematic since the `parent` of the child might need to be accessed in `onRemove` (directly or indirectly). See https://github.com/gnarhard/component_removal_mre for an MRE.
This PR makes sure that the `parent` is always set until the child is itself explicitly removed from its parent.
This is technically a breaking change, but I very much doubt anyone will be affected by it (except that it might solve some people's bugs).
[CHANGELOG]: …
> feat!: Children should retain `parent` after parent is remove from tree

- packages/flame/lib/src/components/core/component.dart
- packages/flame/lib/src/components/core/component_tree_root.dart
- packages/flame/pubspec.yaml
- packages/flame/test/components/component_test.dart
- packages/flame/test/components/priority_test.dart
- packages/flame_3d/pubspec.yaml
This PR updates to ordered_set 8.0.0 and makes sure that `children` are of the `ReadOnlyOrderedSet` type, so that `children.add/remove` isn't directly exposed to the user, since they skip the component lifecycle.
Since we previously had the `ComponentSet` to hide `add/remove` we now had to introduce a new internal getter in the component to make sure that the set only is initialized when it is needed. This was a previous optimization to keep components without children more lightweight.
It also introduces the static `Component.strictQueryMode` variable so that the user can set the `ComponentSetFactory` to only create components sets with strict mode turned on (this functionality also previously lived in the `ComponentSet` class). …
> fix: Only expose `ReadOnlyOrderedset` from `component.children`

- packages/flame/lib/src/components/router/router_component.dart
- packages/flame/test/components/router_component_test.dart
feat: add canPop method to RouterComponent
Adds a new `canPop()` method to the `RouterComponent` class that allows developers to check whether the current route can be safely popped from the navigation stack.
**What this PR adds:**
- `canPop()` method that returns `true` when there are multiple routes in the stack (safe to pop)
**Motivation:**
This method provides a safe way to check if a route can be popped before attempting to pop it, similar to Flutter's `Navigator.canPop()`. This prevents assertion errors that would occur when trying to pop the last remaining route from the router stack. …
> feat: Add canPop to RouterComponent

- packages/flame_3d/example/lib/commands/commands.dart
- packages/flame_3d/example/lib/commands/destroy_command.dart
- packages/flame_3d/example/lib/commands/setup_command.dart
- packages/flame_3d/example/lib/example_game_3d.dart
- packages/flame_3d/example/lib/scenarios/boxes_setup.dart
- packages/flame_3d/example/lib/scenarios/game_setup.dart
This creates a support structure on flame_3d example to allow for different testing scenarios, using commands to easily switch between different setups.
I will followup with other useful commands, such as `spawn` (similar to minecraft) and more. The example can be basically a sandbox to explore several 3d concepts and ideas.
> feat: Add setup command to flame_3d example

- examples/games/trex/lib/background/cloud.dart
- examples/games/trex/lib/background/cloud_manager.dart
- examples/games/trex/lib/obstacle/obstacle.dart
- examples/games/trex/lib/obstacle/obstacle_manager.dart
- examples/games/trex/lib/player.dart
- examples/games/trex/lib/random_extension.dart
- examples/games/trex/lib/trex_game.dart
Use new random extensions to simplify the t-rex example game.
Also make the jump a bit more forgiving to better mimic the chrome version.
> feat: Use new random extensions to simplify the t-rex example game

- examples/lib/stories/components/look_at_example.dart
- packages/flame/benchmark/update_components_benchmark.dart
- packages/flame/lib/src/components/core/component_key.dart
- packages/flame/test/components/position_component_test.dart
- packages/flame/test/widgets/sprite_animation_widget_test.dart
- packages/flame_3d/lib/src/graphics/joints_info.dart
- packages/flame_3d/lib/src/parser/gltf/animation.dart
- packages/flame_3d/lib/src/resources/shader/uniform_array.dart
- packages/flame_3d/lib/src/resources/shader/uniform_instance.dart
- packages/flame_3d/lib/src/resources/shader/uniform_sampler.dart
- packages/flame_3d/lib/src/resources/shader/uniform_value.dart
- packages/flame_markdown/test/flame_markdown_test.dart
Expunge codebase of unholy abbreviations (idx). This prevents further misery to be latched upon @spydon 
> chore: Expunge codebase of unholy abbreviations (idx)

- packages/flame_3d/lib/src/model/model.dart
- packages/flame_3d/lib/src/model/model_node.dart
Use new collection literals on flame_3d, now possible in Dart 3.8
> chore: Use new collection literals on flame_3d

- packages/flame_3d/lib/src/model/model_node.dart
- packages/flame_3d/lib/src/resources/shader/uniform_value.dart
- packages/flame_3d/pubspec.yaml
Add collections library to flame_3d to use the `sortBy` method instead of using `Comparing` from `ordered_set`.
Note: I noticed that while collections is used in a few other packages, versions are not consistent. If this proposal holds, I can followup with version unification.
> refactor: Add collections library to flame_3d

- .github/workflows/cicd.yml
Re-enable melos analyze on CICD following Dart 3.8 migration.
> chore: Re-enable melos analyze on CICD following Dart 3.8 migration

- packages/flame/lib/src/extensions/canvas.dart
- packages/flame/test/extensions/canvas_test.dart
Add renderLine helper to canvas extensions.
> feat: Add renderLine helper to canvas extensions

- packages/flame_3d/lib/components.dart
- packages/flame_3d/test/components/line_3d_test.dart
Expose `Line3D` on `components.dart`
> fix: Expose Line3D on components.dart

- packages/flame_3d/lib/src/graphics/graphics_device.dart
- packages/flame_3d/lib/src/resources/material/material.dart
- packages/flame_3d/lib/src/resources/mesh/surface.dart
Add fallback default material to avoid crashes.
Currently if you don't specify a material on a mesh it will cause a cryptic crash.
Since the parameter is not required, we should add a fallback.
> fix: Add fallback default material to avoid crashes

- packages/flame_3d/lib/src/resources/material/spatial_material.dart
- packages/flame_3d/lib/src/resources/shader/shader.dart
Fix color to byte conversion for shaders.
Why hadn't we noticed this before?
Everything in the example uses the `ColorTexture` to create an in-memory texture with a solid color. That uses a different method to create texture data using one byte per pixel:
```
Uint32List.fromList(
List.filled(
width * height,
// Convert to a 32 bit value representing this color.
(color.a * 255).round() << 24 |
(color.r * 255).round() << 16 |
(color.g * 255).round() << 8 |
(color.b * 255).round(),
),
).buffer.asByteData(),
```
As for the lights, they already used `setColor`, which works. But when setting an albedo color instead of albedo texture, it would have its own method that included an ad-hoc cache. That method was not wiring the bytes in the correct order, causing the issue. I changed it to use …
> fix: Fix color to byte conversion for shaders

- scripts/cspell-run.sh
- scripts/cspell-verify.sh
Update shebang on cspell scripts to be more env agnostic.
This follows standard practices as seen in the [ysap guide](https://style.ysap.sh/):
> Bash is not always located at /bin/bash, so use this line:
> `#!/usr/bin/env bash`
This is also in line with the other scripts on the repo.
> ci: Update shebang on cspell scripts to be more env agnostic

- .github/.cspell/flame_dictionary.txt
- .github/.cspell/gamedev_dictionary.txt
- .github/.cspell/people_usernames.txt
- .github/.cspell/words_dictionary.txt
- scripts/cspell-verify.sh
Fix alphabetization check in cspell verify script; it was using non-bash-compliant code that would not actually work on certain systems; in fact, it was not working on CI, which has caused some drift. This also fixes the dictionaries.
> ci: Fix alphabetization check in cspell verify script

- .github/.cspell/words_dictionary.txt
- scripts/cspell-run.sh
- scripts/cspell-verify.sh
Fix cspell verify script to use the run script.
As part of investigating why the newest cspell version [causes issues](https://github.com/flame-engine/flame/pull/3727) with the verify script, I first notice that we don't run cspell with the correct flags inside the verify script (notably not applying our own config file).
This fixes that by re-using the run script in the verify script, which avoid repetition and future drift.
> ci: Fix cspell verify script to use the run script

- packages/flame/lib/src/components/core/component.dart
This PR removes the sometimes unnecessary creation of a growing list from `addAll`.
> "I'm adding hundreds to thousands of components onto the screen in a short period of time. Switching to .add from .addAll cut down on these CPU-consuming functions:
> 
> _GrowableList.add, _allocateData, _growToNextCapacity, length=
> 
> Even if you're not adding components that need async onLoads, the engine is always instantiating a future list and > adding to it."
Later on we should experiment with list comprehensions and see if they create a statically sized list.
> perf: `addAll` shouldn't create unnecessary growing lists

- .github/workflows/cicd.yml
- packages/flame/lib/src/camera/camera_component.dart
Since we now have shorebird CI we can remove some of our CI steps, more of them will be possible to remove later.
> chore: Remove unnecessary CI steps

- packages/flame/lib/src/events/component_mixins/double_tap_callbacks.dart
- packages/flame/lib/src/events/component_mixins/drag_callbacks.dart
- packages/flame/lib/src/events/component_mixins/hover_callbacks.dart
- packages/flame/lib/src/events/component_mixins/pointer_move_callbacks.dart
- packages/flame/lib/src/events/component_mixins/tap_callbacks.dart
- packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/multi_drag_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/multi_tap_dispatcher.dart
- packages/flame/lib/src/events/flame_game_mixins/pointer_move_dispatcher.dart
- packages/flame/lib/src/events/interfaces/multi_drag_listener.dart
- packages/flame/lib/src/events/interfaces/multi_tap_listener.dart
Re-organize internal event files using the `events.dart` export.
This changes the imports on all files to use the exposed `events.dart` export - this will vastly help us to catch issues of forgetting to expose things. If anything is imported from `src/`, we know it is not exposed by Flame.
This should be absolutely no-op whatsoever - just organizational.
> refactor: Re-organize internal event imports

- packages/flame/lib/src/cache/assets_cache.dart
Instead of converting from string every time a json map is read from the assets cache we store the json map directly.
> fix: Store json maps directly in AssetsCache
