flame-engine/flame

analysis_options.yaml
Use `dartanalyzer .` to check for errors.
=> Strong-mode analysis_options.yaml

lib/components/composed_component.dart
That is what a thought about Composed component''
For example of usage at https://github.com/renancaraujo/trex-flame: 
```dart
class HorizonLine extends PositionComponent with  Resizable, ComposedComponent {
HorizonGround firstGround;
HorizonGround secondGround;
final double bumpThreshold = 0.5;
HorizonLine(Image spriteImage){
Sprite softSprite = Sprite.fromImage(spriteImage,
width: HorizonDimensions.width,
height: HorizonDimensions.height,
y: 104.0,
x: 2.0,
);
Sprite bumpySprite = Sprite.fromImage(spriteImage,
width: HorizonDimensions.width,
height: HorizonDimensions.height,
y: 104.0,
x: 2.0 + HorizonDimensions.width,
);
this.firstGround = HorizonGround(spriteImage, softSprite);
this.secondGround = HorizonGround(spriteImage, bumpySprite);
this..add(firstGround)..add(secondGround);
}
void …
```
=> Composed component 

doc/README.md, doc/text.md, doc/util.md
=> Updating Text docs

lib/flame.dart, lib/game.dart, pubspec.yaml
Deprecating the `new Game().widget` syntax.
=> Game as a Widget

doc/components.md, lib/components/composed_component.dart
=> composed component docs

doc/examples/aseprite/lib/main.dart, doc/examples/text/lib/main.dart, doc/examples/tiled/lib/main.dart, example/lib/main.dart, lib/game.dart
=> Fix widget as game

README.md, pubspec.yaml
Solves https://github.com/luanpotter/flame/issues/74
=> Fixing flutter_svg version to avoid compile problems

README.md
As suggested in https://github.com/luanpotter/flame/pull/83
=> add part 5 from alekhin series to readme

.gitignore, doc/examples/go_desktop/.gitignore, doc/examples/go_desktop/.metadata, doc/examples/go_desktop/README.md, doc/examples/go_desktop/lib/game.dart, doc/examples/go_desktop/lib/main.dart, doc/examples/go_desktop/lib/main_desktop.dart, doc/examples/go_desktop/pubspec.yaml
This PR adds a very simple example of a flame game running on desktop using the go-flutter-desktop library.
=> Adding go desktop example

README.md
This PR adds come cool badge for people to include on their repository and show support to flame.
Solves #95 
Thanks to @impulse
=> Flame badge

CHANGELOG.md, lib/components/component.dart
This PR is just a rebase mirror from #98 
Thanks for the contribution @illiapoplawski !
=> Fixing position component anchor

lib/position.dart
Added operator support for common math functions +,-,*,/. Added utility method to normalize a vector. Added ability to get angle of vector from origin or from another vector. Added ability to rotate a vector by a delta angle rather than just the absolute angle from the origin. Added support for degrees on top of radians for angle methods.
I wasn't sure what was best way to name some of the methods using degrees instead of radians so any feedback is welcome. Also, I like using degrees in certain cases but if you don't find it necessary it's something that I'm willing to remove from this pull request. This is mostly just a collection of methods to simplify more common tasks.
=> Extra functionality in position class for vector rotation, normalization, degrees, and common operators

CHANGELOG.md, doc/examples/timer/.gitignore, doc/examples/timer/.metadata, doc/examples/timer/README.md, doc/examples/timer/lib/main.dart, doc/examples/timer/pubspec.yaml, doc/util.md, lib/time.dart
This PR adds a very simple utility class, to help handling timers and interval events.
Right now I am only adding the concrete Timer class because I am needing this on a project, but this could eventually evolve to be a mixin/component.
=> Adding Timer Class

CHANGELOG.md, doc/examples/animations/lib/main.dart, doc/images.md, lib/components/animation_component.dart
This PR adds a flag on `AnimationComponent` to add the ability for it to be destroyed upon animation completion.
This PR also make some small improvements on the Animation doc.
=> Animation destroy on finish

CHANGELOG.md, doc/examples/animations/lib/main.dart, doc/examples/aseprite/lib/main.dart, doc/examples/sound/lib/main.dart, doc/examples/text/lib/main.dart
This PR fixes all the examples that needed screen size using the workaround found on #81
=> Fixing dimensions problem examples

CHANGELOG.md, lib/time.dart
Just adding a simple utility method to check if the timer is running.
=> Adding Timer#isRunning method

doc/README.md, doc/tiled.md
=> Adding tiled docs

CHANGELOG.md, lib/flame_audio.dart
loop long audio was calling the wrong method from audioplayers.
=> Fixing loopLongAudio

doc/examples/animation_widget/lib/main.dart, doc/images.md, lib/util.dart
I found no gain creating something similar for animations, what we have right now seems to be the best for animations already.
But for Sprites, I found that this is a good solution.
TODO: Still need to update docs.
=> Sprite as widget

doc/game.md, lib/game.dart
Relates to https://github.com/flame-engine/flame/issues/151
=> Updating docs for BaseGame camera to clarify how it works

CHANGELOG.md, lib/util.dart
Avoid errors like the one in #153
=> Prevent multiple completions

doc/README.md, doc/animation_widget_article/article.md, doc/audio.md, doc/box2d.md, doc/debug.md, doc/examples/README.md, doc/examples/audiopool/README.md, doc/examples/sound/lib/main.dart, doc/game.md, doc/images.md, doc/util.md
Fixed some doc typos, maybe turn on the spell checker when writing docs to make it look a bit more professional? :)
=> Correction of typos in the docs

doc/examples/tapeables/README.md, doc/examples/tapeables/lib/main.dart, doc/examples/tapeables/pubspec.yaml, doc/input.md, lib/components/composed_component.dart, lib/components/mixins/tapable.dart, lib/game.dart, test/composed_component_test.dart
Tapeable would be something that you can tape, like with sticky tape, so I suggest we rename it to Tapable. Which also follows the convention for how it is named in other languages and libraries.
=> Tapeable to Tapable

CHANGELOG.md, README.md, doc/README.md, doc/audio.md, doc/bgm.md, lib/bgm.dart, lib/flame.dart
~~This is a work in progress and not ready to be merged. Just putting it out here for review, testing, and further discussion.~~
Edit: Just finished testing and it seems to work. Needs more testing before it's considered ready.
**Edit: I'll mark this one as ready**. Even though I've had enough testing, I encourage people to do more tests though.
=> Looping background music management class

FAQ.md, README.md
This fixes #89.
@erickzanardo I'm sure you have a lot of ideas of what to add to this file, so please let me know and I can improve it :)
=> Adding a FAQ file and link on the README

.gitignore, doc/examples/animation_widget/lib/main.dart, doc/examples/debug/lib/main.dart, doc/examples/flare/lib/main.dart, doc/examples/go_desktop/lib/game.dart, doc/examples/timer/lib/main.dart, example/lib/main.dart, lib/components/component.dart, lib/flare_animation.dart, test/components/component_test.dart
This fixes a lot of warnings and small problems throughout the code.
Let's always keep it clean! :)
=> Fixes and nit-picks

CHANGELOG.md, doc/examples/flare/lib/main.dart, doc/images.md, lib/components/flare_component.dart, lib/flare_animation.dart
While trying to create an example on how to rotate a FlareAnimation to help #179 I realised that FlareAnimation were not following the pattern where base classes does not holds information like position on render method, and that FlareComponent had some problems. This PR address those things.
=> Fixing flare API and rendering 

CHANGELOG.md, doc/examples/timer/lib/main.dart, doc/util.md, lib/components/timer_component.dart
Simple PR to add a wrapper class for the Timer.
=> Adding TimerComponent class

CHANGELOG.md, lib/box2d/box2d_component.dart
Added Box2D ChainShape render function
=> Added Box2D ChainShape render function

CHANGELOG.md, lib/game.dart
Implemented backgroundColor method for overriding the game background
=> Implemented backgroundColor method for overriding the game background

CHANGELOG.md, doc/examples/sound/lib/main.dart, pubspec.yaml
This PR updates AP to the latest version.
@luanpotter please before merging look my comment on the change of the example app sound.
=> Updating AP to 0.13.5

lib/components/text_box_component.dart
Changing the image rendering of text to high quality to ensure sharp edges on rendering
=> Tweaking text box rendering to reduce pixelated text

CHANGELOG.md, doc/README.md, doc/splash_screen.md
=> Add splash screen

CHANGELOG.md, doc/components.md, doc/examples/flare/.gitignore, doc/examples/flare/README.md, doc/examples/flare/lib/main_component.dart, lib/components/flare_component.dart, pubspec.yaml
Solves #202 as well as updates the FlareFlutter dependency.
=> Improving FlareComponent API and updating FlareFlutter dependency

lib/animation.dart, lib/components/animation_component.dart
This PR adds `loop` for `AnimationComponent.sequenced()`.
=> Adding loop for AnimationComponent.sequenced()

lib/bgm.dart, lib/nine_tile_box.dart, lib/svg.dart, lib/text_config.dart, lib/util.dart
Since this didn't change any actual code, added no change to changelog.
=> Fix some typos & docs

doc/input.md
=> Fixing tapable doc

CHANGELOG.md, doc/examples/tapeables/.gitignore, doc/examples/tapeables/lib/main.dart, lib/components/mixins/tapable.dart
=> Fixing Tapable position checking on event handling

CHANGELOG.md, lib/game/game.dart
=> Prevent widgets overlay controller from closing when in debug mode

CHANGELOG.md, doc/examples/keyboard/.gitignore, doc/examples/keyboard/.metadata, doc/examples/keyboard/README.md, doc/examples/keyboard/lib/main.dart, doc/examples/keyboard/pubspec.yaml, doc/input.md, lib/game/game.dart, lib/keyboard.dart
This PR adds a new API for easily enable games to have access to keyboard events, something required for web and desktop games.
=> Adding Keyboard Events API

CHANGELOG.md, doc/box2d.md, doc/examples/box2d/.gitignore, doc/examples/box2d/.metadata, doc/examples/box2d/README.md, doc/examples/box2d/lib/main.dart, doc/examples/box2d/pubspec.yaml, lib/box2d/box2d_game.dart
To simplify control over box2d components and handle them in the same way as other components are handled in the BaseGame.
=> BaseGame extension with Box2D support

CHANGELOG.md, lib/components/animation_component.dart, lib/components/component.dart
Adding paint to AnimationComponent, so it can be repassed to the sprite, useful for doing something like the following red blink effect:
=> Adding Animation#paint

CHANGELOG.md, pubspec.yaml
This enables Audio support for Web
=> Bumping ap

CHANGELOG.md, lib/flame.dart
With the new flutter, FlameBinding had an invalid inheritance (and it has a typo in the class name).
So I was going to fix that, but it seems like it is not needed.
I don't exactly understand what it was for, so please verify.
=> FlameBinding has invalid inheritance

CHANGELOG.md, doc/examples/box2d/lib/main.dart, lib/box2d/box2d_game.dart
Fixes #306 and does it how it should have been made from the beginning.
=> Fix render priority

.github/workflows/test.yml, lib/box2d/box2d_game.dart, lib/components/component.dart, lib/components/flare_component.dart, lib/flame.dart, scripts/lint.sh
Adding linter to build & fix lint issues
=> Adding linter to build & fix lint issues

docs/examples/parallax/lib/main.dart
- added `WidgetsFlutterBinding.ensureInitialized();` in `main()`
- ~I have made corresponding changes to the documentation~
- ~I have added examples for new features in `doc/examples`~
=> Fix parallax example

.github/pull_request_template.md
Just adding an entry in the PR reminder list about the changelog file.
=> Changelog reminder

docs/examples/.gitignore, docs/examples/animation_widget/.gitignore, docs/examples/animations/.gitignore, docs/examples/aseprite/.gitignore, docs/examples/effects/.gitignore, docs/examples/keyboard/.gitignore, docs/examples/particles/.gitignore, docs/examples/sprite_batch/.gitignore, docs/examples/sprites/.gitignore, docs/examples/widgets/.gitignore, docs/examples/with_widgets_overlay/.gitignore
Sevel currently opened PRs are attaching some changes to its examples ignores. This change dismiss the need of that, making future PRs more focused. 
=> fix ignores

doc/examples/spritesheet/lib/main.dart
Run `flutter format` . on develop.
=> Fix format

CHANGELOG.md, doc/effects.md, doc/examples/effects/infinite_effects/lib/main.dart, doc/examples/effects/infinite_effects/lib/square.dart, lib/effects/rotate_effect.dart, lib/effects/rotational_effect.dart
Adds rotational effect as mentioned in #336.
It is based on the infinite effects branch (#329), so that should be merged first.
=> Rotational effect

CHANGELOG.md, doc/examples/README.md, doc/examples/animations/lib/main.dart, doc/examples/box2d/contact_callbacks/lib/boundaries.dart, doc/examples/box2d/contact_callbacks/lib/main.dart, doc/examples/box2d/simple/lib/main.dart, doc/examples/cleanup.sh, doc/examples/sound/lib/main.dart, scripts/lint.sh
Add linter to all examples, fix lint issues and add cleanup script
=> Add linter to all examples, fix lint issues and add cleanup script

CHANGELOG.md, scripts/lint.sh
Only run linting on changed and affected examples.
=> Speed up linting

README-ZH.md
Following `README.md`, updated `README-ZH.md` to 0.22.0
Changed some introduces in the README by comparing version differences.
I think that ` readme` is different from the other features of the project and may need to be kept in the latest version. If submit it to the develop branch, it may always be one version behind.
=> Update `README-ZH` to 0.22.0

CHANGELOG.md, doc/examples/spritesheet/.gitignore, doc/examples/spritesheet/lib/main.dart, doc/examples/spritesheet/pubspec.yaml, lib/spritesheet.dart
Adds new constructor for `SpriteSheet` class, and makes all the the parameters from its constructors required, I don't consider this a breaking change, as they were already required, but didn't had a compilation time error.
Fixes #381
=> Adding SpriteSheet.fromImage

CHANGELOG.md, pubspec.yaml
=> Update tiled dependency

doc/box2d.md
A very small typo fix in the Box2d doc. I know it's nothing but I hope it helps. 
=> minor typo fix

doc/README.md, doc/platforms.md, scripts/lint.sh
Adds a simple section on docs to talk about supported platforms and channel
This PR is targeting master as this is just documentation and is already valid for the current version, I will update develop and v1 once this is merged.
=> Adding platforms and channel doc section

CHANGELOG.md, doc/platforms.md, lib/flame_audio.dart, lib/util.dart
Fixes #361 
~~- [ ] I have added examples for new features in `doc/examples`~~
=> Preventing methods that don't work on web to crash the app

doc/examples/animations/lib/main.dart, doc/examples/aseprite/lib/main.dart, doc/examples/audiopool/lib/main.dart, doc/examples/flare/lib/main.dart, doc/examples/go_desktop/lib/game.dart, doc/examples/keyboard/lib/main.dart, doc/examples/parallax/lib/main.dart, doc/examples/render_flip/lib/main.dart, doc/examples/sound/lib/main.dart, doc/examples/tiled/lib/main.dart, doc/examples/tiled/pubspec.yaml, lib/components/animation_component.dart
Extracted this to a separated PR. This is just making sure all examples are linted & working properly before the refactor. As will have to run every single one later to test. Next PR will be the refactor of files to split component.dart and finally I will have just the composed component removal into a single PR.
=> Composed refactor part 1: Fixes, lint & nits on examples

doc/examples/.gitignore
=> Improvement: Update ignore

CHANGELOG.md, doc/examples/gestures/lib/main_hover.dart, doc/examples/gestures/lib/main_mouse_movement.dart, doc/input.md, lib/game/widget_builder.dart, lib/gestures.dart
Adds "out of the box" support for mouse hover events.
UPDATE:
=> Adding HoverDetector

CHANGELOG.md, lib/bgm.dart
Fixes #436 and improve Bgm code a bit
=> Fixes #436 and improve Bgm code a bit

CHANGELOG.md, doc/examples/gestures/lib/main_scroll.dart, doc/input.md, lib/game/widget_builder.dart, lib/gestures.dart
This pull request is based on #461 and adds `ScrollDetector`. This is useful for detecting mouse scroll wheel inputs or touchpad inputs.
~Creating as a draft since this is based on the `erick.mouse-hover` which in turn is based on `develop`. The draft state can be changed once #461 was merged.~
=> Adding ScrollDetector

CHANGELOG.md, doc/effects.md, doc/examples/effects/simple/lib/square.dart, lib/components/position_component.dart, lib/effects/combined_effect.dart, lib/effects/effects.dart, lib/effects/move_effect.dart, lib/effects/rotate_effect.dart, lib/effects/scale_effect.dart, lib/effects/sequence_effect.dart, test/components/component_test.dart
Gives the user the ability to define whether an effect should be relative or not.
Fixes #398
=> Add isRelative to effects that it makes sense for

CHANGELOG.md, lib/util.dart
Fix this deprecation message. 
[x] Bug fix (non-breaking change which fixes an issue)
=> Fix deprecation message

README.md
Adding disclaimer for contribution
=> Adding disclaimer for contribution

pubspec.yaml
Removing unused dependencies on Flame.
=> Removing unused deps

.github/workflows/test.yml
Our CI was only running on our own branches, when a PR was submitted from a fork, it didn't ran. This PR fixes that.
=> Fixing CI workflow to run on pull requests too

CHANGELOG.md, lib/time.dart
Sometimes we need to just pause because stop resets the timer. This PR adds the pause and resume methods.
=> Adding pause and resume methods to time class

.github/pull_request_template.md
Updates our template to the v1.0.0 branch
=> Updating PR template to the v1 branch

CHANGELOG.md, doc/effects.md, doc/examples/effects/combined_effects/lib/main.dart, doc/examples/effects/sequence_effect/lib/main.dart, lib/components/component.dart, lib/effects/combined_effect.dart, lib/effects/effects.dart, lib/effects/move_effect.dart, lib/effects/rotate_effect.dart, lib/effects/scale_effect.dart, lib/effects/sequence_effect.dart, test/effects/effect_test_utils.dart, test/effects/move_effect_test.dart, test/effects/rotate_effect_test.dart, test/effects/scale_effect_test.dart
=> Pause and resume effects

README-ZH.md
Update README-CN based on newest readme(0.28.0).
We also create a website to share amazing Flame (includes full translation of official documents).
Update Chinese translation(README-ZH.md)
=> Update ReadME translation (Chinese)

CHANGELOG.md, lib/components/parallax_component.dart
Fixing parallax bug due to missing parenthesis.
=> Fix parallax bug

CHANGELOG.md, doc/examples/animation_widget/lib/main.dart, doc/examples/animation_widget/pubspec.yaml, doc/examples/animations/pubspec.yaml, doc/examples/aseprite/pubspec.yaml, doc/examples/debug/pubspec.yaml, doc/examples/effects/combined_effects/pubspec.yaml, doc/examples/effects/infinite_effects/pubspec.yaml, doc/examples/effects/sequence_effect/pubspec.yaml, doc/examples/effects/simple/pubspec.yaml, doc/examples/gestures/pubspec.yaml, doc/examples/go_desktop/pubspec.yaml, doc/examples/isometric/pubspec.yaml, doc/examples/joystick/pubspec.yaml, doc/examples/keyboard/pubspec.yaml, doc/examples/nine_tile_box/pubspec.yaml, doc/examples/parallax/pubspec.yaml, doc/examples/particles/pubspec.yaml, doc/examples/render_flip/pubspec.yaml, doc/examples/sprite_batch/pubspec.yaml, doc/examples/sprites/pubspec.yaml, doc/examples/spritesheet/pubspec.yaml, doc/examples/text/lib/main.dart, doc/examples/text/pubspec.yaml, doc/examples/timer/pubspec.yaml, doc/examples/widgets/pubspec.yaml, doc/examples/with_widgets_overlay/pubspec.yaml, doc/text.md, example/pubspec.yaml, lib/components/text_box_component.dart
* The TextBoxComponent wasn't rendering at all in v1.0.0 so that is fixed.
* Adds full margin options
* Adds option whether the box should be growing or not
Fixes #532 
=> Add TextBoxConfig options and fix TextBoxComponent bugs

.github/workflows/test.yml
Make `test` workflow run only when it is needed.
=> Chore: prevent ci from running twice

.github/pull_request_template.md, CHANGELOG.md, README.md
Updated the PR template to reflect removal of the develop branch
=> Update PR template

lib/extensions/offset.dart, lib/extensions/rect.dart
Found a couple of incorrect imports not following our guidelines.
=> Fix imports to be relative

lib/game/game_widget.dart
Fix bug introduced after game widget.
=> fix tappable

CHANGELOG.md, doc/examples/gestures/lib/main_dragables.dart, doc/input.md, lib/anchor.dart, lib/components/base_component.dart, lib/components/mixins/dragable.dart, lib/components/position_component.dart, lib/game/game_widget.dart, lib/gestures.dart, lib/sprite.dart, lib/widgets/sprite_widget.dart
Like `Tapable`, but for components to handle drags
=> Dragable mixin for components

README-PL.md, README-ZH.md, README.md
=> Update readme with enew logo

CHANGELOG.md, lib/components/base_component.dart, test/components/composed_component_test.dart, test/util/mock_canvas.dart
The rendering and update of the children was lost in the last refactoring.
Fixes #562 
=> Fix children update and rendering

CHANGELOG.md, doc/images.md
Updates SVG documentation to go along with this PR:
https://github.com/flame-engine/flame_svg/pull/2
=> Update SVG documentation

CHANGELOG.md, doc/components.md, lib/components/base_component.dart, lib/components/component.dart, lib/components/mixins/has_async_load.dart, lib/components/parallax_component.dart, lib/game/base_game.dart, test/base_game_test.dart, test/components/composed_component_test.dart
Proposal for enabling components to have async loading
=> Adding Component#onLoad

CHANGELOG.md, doc/components.md, lib/effects/effects_handler.dart
Clarification of how you should implement the render method for `PositionComponent`s.
(Accidentally removed one line that is not needed for effects too).
=> Update PositionComponent docs

CHANGELOG.md, lib/effects/effects_handler.dart, lib/game/base_game.dart
If `game.add` is called in `onMount` you get a `ConcurrentModificationException`.
=> Fix ConcurrentModificationException on add in onMount

CHANGELOG.md, doc/examples/gestures/lib/main_draggables.dart, doc/input.md, lib/components/mixins/draggable.dart, lib/game/game_widget.dart
Apparently Dragable is spelled Draggable...
=> Rename Dragable -> Draggable

doc/util.md
We still had the Position class (replaced by Vector2) on the docs, just removing it.
=> Removing Position from docs

CHANGELOG.md, lib/components/text_box_component.dart
=> Use config defaults for TextBoxComponent

CHANGELOG.md, lib/assets/images.dart
Simply renames `Retreive` to `Retrieve`.
=> Retreive -> Retrieve

.github/FUNDING.yml
I will look into adding github sponsors as well later (got an email about that).
=> Add a funding file with our patreon

README.md
This is what it would look like:
(just a suggestion, not sure if too cluttered)
=> Add a badge with our current RC as well alongside the current stable version

CHANGELOG.md, test/components/composed_component_test.dart
Add test for removal of component children, should be merged after #600 
=> Add test for removal of component children

CHANGELOG.md, doc/examples/effects/infinite_effects/lib/main.dart, doc/examples/gestures/lib/main_multitap_advanced.dart, doc/examples/joystick/lib/player.dart, doc/examples/render_flip/lib/main.dart, doc/examples/widgets/lib/main.dart, lib/components/joystick/joystick_action.dart, lib/components/joystick/joystick_utils.dart, lib/components/sprite_component.dart, lib/components/text_box_component.dart, lib/components/text_component.dart, lib/effects/combined_effect.dart, lib/effects/effects.dart, lib/effects/move_effect.dart, lib/effects/rotate_effect.dart, lib/effects/scale_effect.dart, lib/effects/sequence_effect.dart, lib/flame.dart, lib/game/base_game.dart, lib/game/game_widget.dart, lib/gestures.dart, lib/layers/processors.dart, lib/nine_tile_box.dart, lib/parallax.dart, lib/particles/computed_particle.dart, lib/particles/rotating_particle.dart, lib/sprite.dart, lib/widgets/animation_widget.dart
As suggested by @spydon (https://github.com/flame-engine/flame/pull/549#issuecomment-753447386), backporting some code changes made in the null safety PR (https://github.com/flame-engine/flame/pull/549)
=> 🏷 Backport some code improvements from the `null-safety` branch

CHANGELOG.md, doc/examples/widgets/lib/main.dart, doc/widgets.md
=> Updated the widgets docs

CHANGELOG.md, README.md, doc/README.md, pubspec.yaml
Changes necessary to release v1.0.0-rc6
=> Release v1.0.0-rc6

CHANGELOG.md, doc/examples/debug/lib/main.dart, doc/examples/effects/combined_effects/lib/main.dart, doc/examples/effects/infinite_effects/lib/main.dart, doc/examples/effects/sequence_effect/lib/main.dart, doc/examples/layers/lib/main.dart, doc/examples/parallax/lib/main.dart, doc/examples/parallax/lib/main_advanced.dart, doc/examples/particles/lib/main.dart, doc/util.md, lib/src/device.dart, lib/src/extensions/canvas.dart, lib/src/flame.dart
=> Removing Util.dart and moving its remaining parts to better places

doc/forge2d.md
=> Fix forge2d.md typo

analysis_options.yaml, doc/examples/gestures/lib/main_overlapping_tapables.dart, doc/examples/particles/lib/main.dart, doc/examples/spritesheet/lib/main.dart, doc/examples/text/lib/main.dart, doc/examples/timer/lib/main.dart, doc/examples/widgets/lib/main.dart, lib/image_composition.dart, lib/src/components/joystick/joystick_events.dart, lib/src/components/position_component.dart, lib/src/particles/particle.dart, pubspec.yaml, scripts/lint.sh, test/base_game_test.dart, test/effects/combined_effect_test.dart, test/effects/effect_test_utils.dart, test/effects/sequence_effect_test.dart
This adds checking for trailing commas on our linter.
This should even adds checking on the Editors
=> Adds checking for trailling commas on the project

CHANGELOG.md, lib/src/game/base_game.dart, test/components/draggable.dart, test/components/tapables.dart
=> Add assert to make Draggables are used properly

CHANGELOG.md, doc/examples/nine_tile_box/lib/main.dart, example/lib/main.dart, lib/src/components/joystick/joystick_directional.dart, lib/src/components/mixins/single_child_particle.dart, lib/src/components/parallax_component.dart, lib/src/components/sprite_animation_component.dart, lib/src/game/base_game.dart, lib/src/game/game.dart, lib/src/parallax.dart, lib/src/particles/accelerated_particle.dart
We used to have a mix of `t` and `dt` in the update methods, this PR standardizes the use of `dt`.
#677
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
=> Standardize on dt in update methods

lib/src/components/sprite_animation_component.dart
=> Followups to 667

doc/components.md, doc/examples/sprites/lib/main.dart, example/lib/main.dart, lib/image_composition.dart, lib/src/anchor.dart, lib/src/components/isometric_tile_map_component.dart, lib/src/components/parallax_component.dart, lib/src/components/sprite_animation_component.dart, lib/src/components/sprite_component.dart, lib/src/extensions/image.dart, lib/src/parallax.dart, lib/src/sprite.dart, lib/src/sprite_animation.dart, lib/src/sprite_batch.dart
@pedia 's PR also has benefits down the line in our other packages, like flame_svg, flame_flare need to be updated to support optional position argument as well. Basically every package that adds children to PosComp.
This also fix all the green-green issues from the lint PR.
=> More followups from #667 : Unifying constructor logic + small improvements and docs

lib/src/effects/combined_effect.dart, lib/src/effects/effects.dart, lib/src/effects/move_effect.dart, lib/src/effects/rotate_effect.dart, lib/src/effects/scale_effect.dart, lib/src/effects/sequence_effect.dart, lib/src/game/game_widget.dart, lib/src/game/viewport.dart, lib/src/timer.dart
These are Ericks suggestions from the NS PR
* use VoidCallback instead of void Function()
* remove param since default value is already intersect
=> Second batch of improvements from the Null Safe PR

CHANGELOG.md, example/lib/main.dart
While checking our example app on Flutter 2.0, I have noticed that we had a bug on it 😬
=> Fix example app

CHANGELOG.md, doc/examples/collision_detection/lib/main.dart, doc/examples/collision_detection/lib/main_simple.dart, lib/src/components/mixins/collidable.dart, lib/src/geometry/collision_detection.dart, lib/src/geometry/shape.dart
Rename points to intersectionPoints to make it clearer what they are.
Upon good suggestion from @wolfenrain.
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
=> Rename points -> intersectionPoints

.github/ISSUE_TEMPLATE/1_bug.md, .github/ISSUE_TEMPLATE/2_feature.md, .github/ISSUE_TEMPLATE/3_improvement.md, .github/pull_request_template.md
The content written under `More information` will not be displayed.
No.
=> Update GitHub templates

README.md
=> Reviewing credits

packages/flame/CHANGELOG.md, packages/flame/lib/assets.dart
`Images` and `AssetsCache` were exported and they should so people could have the possibility to control their own caches.
=> Exporting Images and AssetsCache

doc/layers.md
I just fixed a small typo in the docs
=> fixed typo

doc/collision_detection.md, doc/components.md, doc/images.md
This updates the components documentation to reflect the latest version.
I also accidentally fixed some things in other files which will later have more updates in another PR.
=> Documentation update: components

doc/README.md, doc/audio.md, doc/bgm.md
=> Documentation update: audio

examples/lib/commons/square_component.dart, examples/lib/stories/controls/joystick_player.dart, examples/lib/stories/controls/keyboard.dart, examples/lib/stories/controls/mouse_movement.dart, examples/lib/stories/controls/multitap.dart, examples/lib/stories/controls/multitap_advanced.dart, examples/lib/stories/controls/overlapping_tapables.dart, examples/lib/stories/controls/scroll.dart, packages/flame/CHANGELOG.md, packages/flame/example/lib/main.dart, packages/flame/lib/src/components/text_box_component.dart, packages/flame/lib/src/nine_tile_box.dart, packages/flame/lib/src/palette.dart, packages/flame/lib/src/sprite.dart, tutorials/1_basic_square/README.md, tutorials/1_basic_square/code/lib/main.dart
This PR transforms the paint getter into a full method, so it is more clear that a new Paint is created and should be cached.
Also adds more basic colors to BasicPalette.
- [ x I have formatted my code with `./scripts/format.sh` and the Flame analyzer (`./scripts/analyze.sh`) does not report any problems.
=> Transforming PaletteEntry#paint into a full method and adding more colors to BasicPalette

doc/effects.md
=> Documentation update: effects

.github/pull_request_template.md, CONTRIBUTING.md, FAQ.md, README.md, doc/collision_detection.md, doc/components.md, doc/debug.md, doc/effects.md, doc/forge2d.md, doc/game.md, doc/images.md, doc/input.md, doc/layers.md, doc/palette.md, doc/platforms.md, doc/splash_screen.md, doc/summary.md, doc/text.md, doc/tiled.md, doc/util.md, doc/widgets.md, examples/README.md, packages/flame/CHANGELOG.md, packages/flame/lib/src/extensions/rect.dart, tutorials/1_basic_square/README.md
Update documentation for some different things.
=> Documentation update: other

examples/lib/commons/square_component.dart, examples/lib/stories/animations/basic.dart, examples/lib/stories/controls/draggables.dart, examples/lib/stories/effects/combined_effect.dart, examples/lib/stories/effects/infinite_effect.dart, examples/lib/stories/effects/move_effect.dart, examples/lib/stories/effects/rotate_effect.dart, examples/lib/stories/effects/scale_effect.dart, examples/lib/stories/effects/sequence_effect.dart, examples/lib/stories/rendering/text.dart, examples/lib/stories/tile_maps/isometric_tile_map.dart, examples/lib/stories/utils/camera_and_viewport.dart, packages/flame/CHANGELOG.md, packages/flame/example/lib/main.dart, packages/flame/lib/src/components/parallax_component.dart, packages/flame/lib/src/components/position_component.dart, packages/flame/lib/src/effects/move_effect.dart, packages/flame/lib/src/effects/scale_effect.dart, packages/flame/lib/src/game/camera.dart, packages/flame/test/components/component_test.dart, packages/flame/test/components/composed_component_test.dart, packages/flame/test/components/position_component_test.dart, packages/flame/test/components/resizable_test.dart, packages/flame/test/effects/effect_test_utils.dart, packages/flame/test/effects/sequence_effect_test.dart, packages/flame/test/game/camera_and_viewport_test.dart
Since this PR makes position and size final camera can follow the position vector directly instead of checking it in the component for every tick. If you later want to have an external path or something that you update with a vector2 you can make the camera follow that instead of a component.
This also adds `onPositionUpdate` for the Camera since it is needed for the Forge2D viewport so that it can update its `ViewportTransform.center`. …
=> Follow a Vector2 in Camera and add onPositionUpdate

doc/structure.md, packages/flame/CHANGELOG.md, packages/flame/lib/src/assets/assets_cache.dart, packages/flame/lib/src/assets/images.dart
Fixing https://github.com/flame-engine/flame/issues/715
=> Make prefix configurable for image and asset loading

packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart
With this method it will be less code duplication when fixing the viewport for `flame_forge2d`.
=> Add followVector2 method to Camera

examples/lib/stories/components/composability.dart, examples/lib/stories/components/debug.dart, examples/lib/stories/controls/draggables.dart, examples/lib/stories/parallax/component.dart, examples/lib/stories/sprites/spritebatch_auto_load.dart, examples/lib/stories/utils/camera_and_viewport.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/base_component.dart, packages/flame/lib/src/components/joystick/joystick_action.dart, packages/flame/lib/src/components/joystick/joystick_directional.dart, packages/flame/lib/src/components/mixins/has_game_ref.dart, packages/flame/test/components/has_game_ref_test.dart
See https://github.com/flame-engine/flame/issues/706
https://github.com/flame-engine/flame/issues/706
=> Make gameRef late

examples/lib/stories/controls/scroll.dart, packages/flame/CHANGELOG.md
Removed the TODO now that example works. Also updated it to fix a few bugs it had in of itself.
=> Fix scroll example now that the scroll detector works

doc/collision_detection.md, doc/components.md, examples/lib/main.dart, examples/lib/stories/collision_detection/circles.dart, examples/lib/stories/collision_detection/collision_detection.dart, examples/lib/stories/collision_detection/multiple_shapes.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/mixins/hitbox.dart, packages/flame/lib/src/extensions/rect.dart, packages/flame/lib/src/geometry/shape.dart
The collision detection examples were previously accidentally removed, this brings them back and fixes a bug that was introduced too.
=> Bring back collision detection example

.github/workflows/gh-pages.yml, README.md, examples/pubspec.yaml, examples/web/index.html, packages/flame/CHANGELOG.md
This PR implements an action to auto deploy our examples on gh pages
=> Configuring ghpages action for examples

README.md, packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
=> bumping versions rc9

packages/flame/CHANGELOG.md, tutorials/1_basic_square/README.md
This pull request updates the README.md for 1_basic_square so that the Flame version matches the example code
#753 tutorials/1_basic_square/README.md version incompatible with paint()
=> #753 - Update 1 basic square tutorial

examples/web/index.html
New page will be on `examples.flame-engine.org` so this base ref is now causing issues.
=> Fix github examples deploy

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/mixins/collidable.dart, packages/flame/lib/src/components/mixins/hitbox.dart, packages/flame/lib/src/geometry/polygon.dart
The polygon (and therefore also rectangle) collisions were not properly checked.
#759 
=> Fix bounding box check in collision detection

doc/README.md
Update the docs to have a correct link to the tutorials page.
N/A
=> [docs] Update tutorials link on README.md

examples/web/CNAME
Adding the CNAME file to the examples web folder, so we don't need to recreate it every time that the examples is deployed.
=> Adding CNAME to examples/web folder to make this config persistent

examples/lib/stories/utils/camera_and_viewport.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart, packages/flame/test/game/camera_and_viewport_test.dart, packages/flame/test/game/projections_test.dart
This:
* Addresses the TODO to change the camera public APIs to take Anchors for relativePositions.
* Adds a couple more useful methods to camera
=> Improve camera

examples/lib/stories/collision_detection/collision_detection.dart, examples/lib/stories/collision_detection/multiple_shapes.dart, examples/lib/stories/collision_detection/only_shapes.dart, packages/flame/CHANGELOG.md, packages/flame/lib/components.dart, packages/flame/lib/src/anchor.dart, packages/flame/lib/src/components/mixins/collidable.dart, packages/flame/lib/src/components/mixins/hitbox.dart, packages/flame/lib/src/components/position_component.dart, packages/flame/lib/src/components/shape_component.dart, packages/flame/lib/src/extensions/vector2.dart, packages/flame/lib/src/game/camera.dart, packages/flame/lib/src/geometry/circle.dart, packages/flame/lib/src/geometry/polygon.dart, packages/flame/lib/src/geometry/rectangle.dart, packages/flame/lib/src/geometry/shape.dart, packages/flame/lib/src/geometry/shape_intersections.dart, packages/flame/lib/src/sprite_batch.dart, packages/flame/test/anchor_test.dart, packages/flame/test/components/position_component_test.dart, packages/flame/test/extensions/vector2_test.dart
- Fixes some bugs with angles in the collision detection system.
- Caches some of the frequent Vector2 calculations in Shape
- Fixes rendering of shapes that aren't HitboxShape
#759 
=> Fix collision detection and rendering of local shape angles

examples/README.md
Update to the new link in the examples readme.
#783 
=> Fix link in examples readme

doc/input.md, examples/lib/stories/controls/controls.dart, examples/lib/stories/controls/hoverables.dart, packages/flame/CHANGELOG.md, packages/flame/lib/components.dart, packages/flame/lib/src/components/mixins/hoverable.dart, packages/flame/lib/src/game/base_game.dart, packages/flame/lib/src/game/game_widget/gestures.dart, packages/flame/test/anchor_test.dart, packages/flame/test/components/draggable_test.dart, packages/flame/test/components/hoverable_test.dart, packages/flame/test/components/tapables_test.dart
Analogous to Tapables and Draggables.
=> Add hoverables

README.md, packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
Update pubspec, changelog and readme to `1.0.0-releasecandidate.11`,
=> Release rc11

examples/lib/commons/commons.dart, packages/flame/CHANGELOG.md
Simply updates the old master link to main.
=> Fix link to code in examples

packages/flame_audio/CHANGELOG.md, packages/flame_audio/pubspec.yaml
Bump flame audio version for release
=> Bump flame audio version for release

packages/flame_svg/CHANGELOG.md, packages/flame_svg/pubspec.yaml
We no longer have to use the null-safety prerelease for `flame_svg`
Someone asked for this on discord.
=> Upgrade flutter_svg

.github/workflows/cicd.yml
Fix Github actions to run on the new master branch
=> Fix Github actions to run on the new master branch

i18n/README-ZH.md
Update README in Chinese. Following the style guide that Chinese documents usually use. Few things were updated in this change:
* Words correct/improve.
* Remove a user group link since it's nothing official.
The typography guide is based on [中文文案排版指南 (Chinese Typography Guide)](https://github.com/cfug/flutter.cn/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%88%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97-(Chinese-Typography-Guide)) .
A maintainer in the [CFUG (Chinese Flutter User Group)](https://github.com/cfug) Localization team. Reviewed over 200 articles translation in Chinese. Also a Flutter GitHub member.
Please let me know if the doc needs update in the future, and I'm glad I can help with it.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> 📝 Update README in Chinese

packages/flame_svg/pubspec.yaml
Update pubspec.yaml for flame_svg with correct link
=> Update pubspec.yaml for flame_svg with correct link

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/text_box_component.dart, packages/flame/lib/src/components/text_component.dart, packages/flame/lib/src/text.dart, packages/flame/test/text_test.dart
Assuming you have an arbitrary TextComponent, that got it's painter (which stands in as a config) via a parameter, and you want to modify some property, you cannot do that in a generic way. This adds a couple functions to facilitate such operations; also, it makes text component type safe by defining what implementation of text renderer it uses as a generic parameter. …
=> Make it possible to work with the new Text inheritance chain

packages/flame/CHANGELOG.md, packages/flame/lib/src/extensions/canvas.dart
=> Fix renderRotated

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/mixins/has_collidables.dart, packages/flame/lib/src/game/base_game.dart, packages/flame/pubspec.yaml
This is a initial step to unify addLater and removeLater between BaseGame and BaseComponent.
I noticed there is some Collidables code that was run in between the operations I want to extract.
However it seems that that can be vastly simplified using the brand new QOS.
@spydon lmk if that makes sense. I believe the only reason it was there was to keep the copy list consistent. now QOS keeps track of all cache lists for you. tests passed and the examples seems to run exactly as intended.
[issue database]: …
=> Refactor base game to use QueryableOrderedSet for Collidables

packages/flame_audio/example/pubspec.yaml, packages/flame_audio/pubspec.yaml, packages/flame_fire_atlas/example/lib/main.dart, packages/flame_fire_atlas/example/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_svg/CHANGELOG.md, packages/flame_svg/example/pubspec.yaml, packages/flame_svg/lib/svg_component.dart, packages/flame_svg/pubspec.yaml, scripts/publish.sh
* Sets the flame dependency for bridge packages to relative
* Introducing a publish script that we can use until a better solution if figured out
```
Example:
Which package do you want to publish?
-------------------------------------
1	flame
2	flame_audio
3	flame_svg
4	flame_fire_atlas
Enter a number: 3
You have chosen to publish flame_svg, is this correct? (y/N): y
The current version is 1.0.0-rc4, enter new version: 1.0.0-rc5
Is 1.0.0-rc5 the version you want to publish? (y/N) y
Publishing flame_svg 1.0.0-rc5 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   |-- assets
|   |   '-- android.svg
|   |-- lib
|   |   '-- main.dart
|   '-- …
```
=> Relative flame paths for bridge packages

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/base_component.dart, packages/flame/lib/src/components/text_box_component.dart, packages/flame/test/components/composed_component_test.dart, packages/flame/test/components/position_component_test.dart
1. Slightly improve docs for text box component since I was there
2. Slightly refactor code for text box component since I was there
3. Fix bug on text box component where gameSize was used instead of size, incorrectly
4. Remove gameSize altogether from TBC because it was not needed at all
5. Rescue a dumb user (i.e. me) from doing a wrong PEMDAS when adding children to non-has-game-ref parents with an error message.
See notes on PR for possible followups. …
=> Fix a couple gnarly bugs

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/shape_component.dart, packages/flame/lib/src/geometry/polygon.dart, packages/flame/lib/src/geometry/shape.dart
Fix rendering of polygons in `ShapeComponent`
=> Fix rendering of polygons in ShapeComponent

doc/summary.md
Add tutorials link to the sidebar of the site's docs section.
=> Add link to docs summary

examples/lib/stories/animations/basic.dart, examples/lib/stories/camera_and_viewport/zoom.dart, examples/lib/stories/collision_detection/circles.dart, examples/lib/stories/collision_detection/multiple_shapes.dart, examples/lib/stories/collision_detection/only_shapes.dart, examples/lib/stories/components/priority.dart, examples/lib/stories/controls/draggables.dart, examples/lib/stories/controls/hoverables.dart, examples/lib/stories/controls/mouse_movement.dart, examples/lib/stories/controls/multitap.dart, examples/lib/stories/controls/multitap_advanced.dart, examples/lib/stories/controls/scroll.dart, examples/lib/stories/effects/combined_effect.dart, examples/lib/stories/effects/infinite_effect.dart, examples/lib/stories/effects/move_effect.dart, examples/lib/stories/effects/sequence_effect.dart, examples/lib/stories/tile_maps/isometric_tile_map.dart, packages/flame/CHANGELOG.md, packages/flame/example/lib/main.dart, packages/flame/lib/src/components/base_component.dart, packages/flame/lib/src/components/joystick/joystick_action.dart, packages/flame/lib/src/components/joystick/joystick_directional.dart, packages/flame/lib/src/components/mixins/draggable.dart, packages/flame/lib/src/components/mixins/hoverable.dart, packages/flame/lib/src/components/mixins/tapable.dart, packages/flame/lib/src/gestures/detectors.dart, packages/flame/test/components/draggable_test.dart, packages/flame/test/components/hoverable_test.dart, tutorials/2_sprite_animations_gestures/code/lib/main.dart
The events are currently always passed as game coordinates to `Tapable`, `Draggable` and `Hoverable`.
With this PR we take that into consideration.
It also does some small changes to `Hoverable` to follow the standard of the other ones.
**You only have to look at the first commit if you want to see actual changes! In the second commit I just rename all remaining fields to info since we had a mix of event and info.**
*Replace this paragraph with a list of issues related to this PR from the [issue database]. Indicate, which of …
=> Fix gestures when isHud = true and camera is transformed

packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart, packages/flame/test/game/camera_and_viewport_test.dart
Fixes the camera so that it takes offset into consideration when zooming.
=> Fix camera zoom with offset

packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/README.md, packages/flame_forge2d/lib/body_component.dart, packages/flame_forge2d/pubspec.yaml
Fixes https://github.com/flame-engine/flame_forge2d/issues/42
https://github.com/flame-engine/flame_forge2d/issues/42
=> Publish flame forge2d 0.7.3 releasecandidate.12

examples/lib/stories/controls/joystick_player.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/joystick/joystick_action.dart, packages/flame/lib/src/components/joystick/joystick_component.dart
Make the JoystickPlayer a PositionComponent
=> Make the JoystickPlayer a PositionComponent

doc/forge2d.md
=> Update forge2d docs

STYLEGUIDE.md, doc/input.md, examples/lib/stories/camera_and_viewport/follow_object.dart, examples/lib/stories/collision_detection/only_shapes.dart, examples/lib/stories/components/priority.dart, examples/lib/stories/controls/controls.dart, examples/lib/stories/controls/overlapping_tappables.dart, examples/lib/stories/controls/tappables.dart, packages/flame/CHANGELOG.md, packages/flame/lib/components.dart, packages/flame/lib/src/components/mixins/tappable.dart, packages/flame/lib/src/game/base_game.dart, packages/flame/lib/src/game/game_widget/gestures.dart, packages/flame/test/components/composed_component_test.dart, packages/flame/test/components/tapables_test.dart, packages/flame/test/game/base_game_test.dart, packages/flame_forge2d/example/lib/main.dart, packages/flame_forge2d/example/lib/tappable_sample.dart, tutorials/2_sprite_animations_gestures/README.md
Since apparently `Tapable` isn't the correct word, let's rename it back to `Tappable` like it used to be a year ago until I changed it to the wrong one. 😅
#863 
=> Rename Tapable to Tappable

packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart
I think a quite normal usecase will be to set intensity per shake, so here I move the intensity variable to the `shake` method as an optional argument.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process. I also make the related 
=> Move intensity to Camera.shake

examples/lib/stories/camera_and_viewport/camera_and_viewport.dart, examples/lib/stories/camera_and_viewport/fixed_resolution.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/viewport.dart, packages/flame/test/game/camera_and_viewport_test.dart
Just like with the camera, use matrix transformations in the `FixedResolutionViewport`.
I couldn't come up with a way to get the `clipRect` call into the transform matrix, so that one is still separate. …
=> Use matrix transformations in FixedResolutionViewport

packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/pubspec.yaml
Publish flame_forge2d-0.8.0-releasecandidate.13
=> Publish flame_forge2d-0.8.0-releasecandidate.13

examples/lib/stories/camera_and_viewport/fixed_resolution.dart, examples/lib/stories/camera_and_viewport/follow_object.dart, examples/lib/stories/camera_and_viewport/zoom.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart, packages/flame/test/game/camera_and_viewport_test.dart
Rename Camera.cameraSpeed to Camera.speed, since it is implicit that the speed is for the camera.
=> Rename Camera.cameraSpeed to Camera.speed

doc/collision_detection.md, examples/lib/stories/camera_and_viewport/follow_object.dart, examples/lib/stories/collision_detection/circles.dart, examples/lib/stories/collision_detection/multiple_shapes.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/mixins/collidable.dart, packages/flame/lib/src/components/mixins/hitbox.dart, packages/flame/lib/src/components/position_component.dart, packages/flame/lib/src/geometry/collision_detection.dart, packages/flame/test/components/collidable_type_test.dart, packages/flame/test/components/collision_callback_test.dart, packages/flame/test/components/position_component_test.dart
It is more clear that it is a hitbox that is added if the method is called `addHitbox`.
=> Rename `addShape` to `addHitbox`

packages/flame/lib/src/game/game_widget/game_widget.dart, packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/example/lib/balls.dart, packages/flame_forge2d/example/lib/blob_sample.dart, packages/flame_forge2d/example/lib/joint_sample.dart, packages/flame_forge2d/example/lib/main.dart, packages/flame_forge2d/example/lib/widget_sample.dart
An example of how to tie forge2d to widgets.
=> forge2d widget sample

STYLEGUIDE.md
This is a proposal to better organize the styleguide's sections and subsections, moving some stuff around, removing the use of bullet items when not needed, etc.
There is no significant content change proposed (yet).
=> Improve STYLEGUIDE

doc/components.md, doc/images.md, examples/lib/stories/sprites/sprite_group.dart, examples/lib/stories/sprites/sprites.dart, packages/flame/CHANGELOG.md, packages/flame/lib/components.dart, packages/flame/lib/src/components/sprite_group_component.dart, packages/flame/test/components/sprite_group_component_test.dart
Adding SpriteGroupComponent
https://user-images.githubusercontent.com/835641/127781143-f931bc22-a437-4b3d-b23c-03f8d5eec51d.mov
=> Adding SpriteGroupComponent

doc/debug.md, examples/lib/stories/collision_detection/multiple_shapes.dart, examples/lib/stories/components/debug.dart, examples/lib/stories/utils/particles.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/base_game.dart
Removes a tiiiiny bit of clutter, which can just as easily be added on your game class when you need it.
=> Remove FPSCounter from BaseGame

packages/flame/CHANGELOG.md, packages/flame/lib/src/game/notifying_vector2.dart, packages/flame/lib/src/game/transform2d.dart, packages/flame/test/game/notifying_vector2_test.dart, packages/flame/test/game/transform2d_test.dart
New class `Transform2D` whose purpose is to describe a compound 2d transform: a combination of translation, rotation, reflection, and scaling.
This class is intended to be used in `PositionComponent`, and also possibly in `Camera` and `PositionComponentEffect`.
WIP for #904
=> Transform2D class

doc/camera_and_viewport.md, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/camera.dart
Updated the `Camera` docs by adding a section about how to use it with a `Game` class structure.
Also found a minor bug where when following the worldBounds would be reset when none was given. As the value is "optional" it should only be set when not nill. …
=> Updated Camera docs to reflect usage with Game class

packages/flame/CHANGELOG.md, packages/flame/lib/src/test_helpers/random_test.dart, packages/flame/test/effects/combined_effect_test.dart, packages/flame/test/effects/effect_test_utils.dart, packages/flame/test/effects/move_effect_test.dart, packages/flame/test/effects/rotate_effect_test.dart, packages/flame/test/effects/scale_effect_test.dart, packages/flame/test/effects/sequence_effect_test.dart, packages/flame/test/effects/size_effect_test.dart
- Added two functions to help with the randomized unit testing: `testRandom()` and `testWidgetsRandom()`. The purpose of these functions is to make the randomized tests reproducible.
- Refactored all effects tests to use these functions. 
WIP for #915
=> Reproducible random tests

packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/lib/body_component.dart
This PR makes it easier to use the render function of `BodyComponent` with the flame coordinate system
=> body rendering

README.md, i18n/README-ES.md
*This PR takes into account the suggestions that the previous one received.*
- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- [ x] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [ x] I updated/added relevant documentation (doc comments with `///`) and updated/added examples in `doc/examples`.
- [ x] I have formatted my code with …
=> 919 - Spanish Readme

packages/flame_oxygen/CHANGELOG.md, packages/flame_oxygen/pubspec.yaml, scripts/publish.sh
=> Publish flame_oxygen-0.1.0-releasecandidate.13

packages/flame/lib/src/game/game_widget/game_widget.dart, packages/flame/lib/src/game/mixins/keyboard.dart, packages/flame/test/game/game_widget/game_widget_keyboard_test.dart, packages/flame/test/game/mixins/keyboard_test.dart
Keyboard API wasn't working anymore for some reason. This PR fixes it.
=> Fix keyboard handlers

.github/workflows/gh-pages.yml, examples/web/index.html
Either we do this, or we remove the `baseHref` from the underlying flutter-gh-pages action.
=> Fix base href for the gh-pages action

packages/flame_test/CHANGELOG.md, packages/flame_test/pubspec.yaml
=> Publish flame_test 0.1.0-releasecandidate.13

packages/flame_test/CHANGELOG.md, packages/flame_test/pubspec.yaml
Publish flame_test 0.1.1-releasecandidate.13
=> Publish flame_test 0.1.1-releasecandidate.13

packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
Publish Flame 1.0.0-releasecandidate.14
=> Publish Flame 1.0.0-releasecandidate.14

packages/flame_test/CHANGELOG.md, packages/flame_test/pubspec.yaml
=> Publish flame_test-0.1.1-releasecandidate.14

examples/lib/stories/widgets/sprite_widget.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/widgets/sprite_painter.dart, packages/flame/lib/src/widgets/sprite_widget.dart
Add option to rotate `SpriteWidget`
=> Add option to rotate SpriteWidget

doc/_sphinx/styles/custom.css
The logo was too big, causing the menu to have a horizontal scroll.
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>
=> Fix logo styling on docs

packages/flame_test/CHANGELOG.md, packages/flame_test/pubspec.yaml
=> Publish flame_test-1.0.0-releasecandidate.15

doc/keyboard-input.md
Just found this when using the docs
=> Fix small detail on our keyboard docs

packages/flame_lint/pubspec.yaml, scripts/publish.sh
needed to publish https://pub.dev/packages/flame_lint
=> Make the publish script work with packages without example

doc/platforms.md
Some instructions on how to use github pages to deploy a web game.
=> docs: some steps to use gh pages

doc/game.md, examples/lib/main.dart, examples/lib/stories/system/pause_resume_game.dart, examples/lib/stories/system/system.dart, examples/lib/stories/widgets/overlay.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/game/game_loop.dart, packages/flame/lib/src/game/game_render_box.dart, packages/flame/lib/src/game/mixins/game.dart, packages/flame/test/game/game_widget/game_widget_pause_test.dart
This PR fixes a bug that we identified during the game jam. Where once a game was paused, if it's `GameWidget` had a rebuild (could be a screen resize, or an overlay addition for example). The game would start running again, even though we had paused it before.
That happened because every rebuild, we attach the game to a new render box, and on the render box we automatically started the game if the `runOnCreation` variable was set to true.
This PR address that by renaming the `runOnCreation` variable to `paused` (so it can be used both upon creation and on runtime) and used to control the running state internally.
Example showcasing:
https://user-images.githubusercontent.com/835641/139753821-c95a010d-1768-439c-b2fb-4bc91a5597d9.mov
Does your PR require Flame users to manually update their …
=> Fixing Flame pause and resume engine features

examples/lib/stories/camera_and_viewport/follow_object.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/custom_painter_component.dart, packages/flame/lib/src/components/input/hud_button_component.dart, packages/flame/lib/src/components/input/hud_margin_component.dart, packages/flame/lib/src/components/isometric_tile_map_component.dart, packages/flame/lib/src/components/nine_tile_box_component.dart, packages/flame/lib/src/components/parallax_component.dart, packages/flame/lib/src/components/position_component.dart, packages/flame/lib/src/components/sprite_animation_component.dart, packages/flame/lib/src/components/sprite_animation_group_component.dart, packages/flame/lib/src/components/sprite_component.dart, packages/flame/lib/src/components/sprite_group_component.dart, packages/flame/lib/src/components/text_box_component.dart, packages/flame/lib/src/components/text_component.dart
This PR makes sure that all components that extend `PositionComponent` take in all the arguments that `PositionComponent` accepts.
It also simplifies some named constructors and factories. …
=> Streamline `PositionComponent` constructors

.github/pull_request_template.md
Since the scripts doesn't exist anymore I changed that checkbox.
=> Update PR template by removing script references

doc/components.md
Change to the correct image in the component docs.
Super minor change, shouldn't need changelog entry.
=> Change to the correct image in the component docs

examples/lib/stories/tile_maps/isometric_tile_map.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/isometric_tile_map_component.dart, packages/flame/test/components/isometric_tile_map_component_test.dart
Upon working a bit on heeve I thought of a couple improvements to the tile map api to make it clearer.
=> Improvements to isometric tilemaps

packages/flame_tiled/analysis_options.yaml, packages/flame_tiled/example/analysis_options.yaml, packages/flame_tiled/example/lib/main.dart, packages/flame_tiled/lib/src/flame_tsx_provider.dart, packages/flame_tiled/lib/src/renderable_tile_map.dart, packages/flame_tiled/lib/src/simple_flips.dart, packages/flame_tiled/lib/src/tiled_component.dart
=> Adding dartdocs to flame tiled

doc/components.md, examples/lib/stories/input/joystick_advanced.dart, examples/lib/stories/parallax/advanced.dart, examples/lib/stories/parallax/animation.dart, examples/lib/stories/parallax/sandbox_layer.dart, examples/lib/stories/rendering/text.dart, examples/lib/stories/sprites/spritebatch.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/components/nine_tile_box_component.dart, packages/flame/lib/src/components/parallax_component.dart, packages/flame/lib/src/components/sprite_batch_component.dart, packages/flame/lib/src/components/sprite_component.dart, packages/flame/lib/src/components/sprite_group_component.dart, packages/flame/lib/src/components/text_box_component.dart, packages/flame/lib/src/components/text_component.dart, packages/flame/lib/src/parallax.dart, packages/flame/test/components/text_box_component_test.dart, packages/flame/test/game/base_game_test.dart, packages/flame/test/text_test.dart, packages/flame_forge2d/example/lib/composition_sample.dart
When extending a `PositionComponent` you usually want to initialize everything in `onLoad` instead of the constructor, this adds that possibility to all components that didn't have it before. …
=> Possibility to initialize all `PositionComponent`s from `onLoad`

packages/flame_audio/analysis_options.yaml, packages/flame_audio/example/analysis_options.yaml, packages/flame_audio/example/lib/main.dart, packages/flame_audio/lib/audio_pool.dart, packages/flame_audio/lib/bgm.dart, packages/flame_audio/lib/flame_audio.dart
Adding dartdoc to flame_audio.
=> Adding dartdoc to flame_audio

examples/lib/stories/collision_detection/multiple_shapes.dart, examples/lib/stories/effects/rotate_effect_example.dart, examples/lib/stories/system/system.dart, examples/lib/stories/tile_maps/tile_maps.dart, packages/flame/lib/src/components/input/joystick_component.dart, packages/flame/lib/src/components/parallax_component.dart, packages/flame/lib/src/effects2/standard_effect_controller.dart, packages/flame/lib/src/effects2/transform2d_effect.dart, packages/flame/lib/src/particles/particle.dart, packages/flame/lib/src/sprite_batch.dart, packages/flame/test/components/hoverable_test.dart, packages/flame/test/game/camera_and_viewport_test.dart, packages/flame/test/game/projections_test.dart, packages/flame_fire_atlas/example/lib/main.dart, packages/flame_forge2d/lib/position_body_component.dart, packages/flame_lint/lib/analysis_options.yaml
* Remove the prefer_mixin rule as per discussed here #993
* Add some more lint rules (not exhaustive; just some we already mostly follow and I don't think are any controversial)
=> Add some new lint rules

packages/flame_fire_atlas/analysis_options.yaml, packages/flame_fire_atlas/example/analysis_options.yaml, packages/flame_fire_atlas/example/lib/main.dart, packages/flame_fire_atlas/lib/flame_fire_atlas.dart
Adds dartdoc to fire atlas package.
=> Adding dartdoc to flame_fire_atlas

examples/lib/stories/camera_and_viewport/follow_component_example.dart, examples/lib/stories/effects/effects.dart, examples/lib/stories/effects/old_scale_effect_example.dart, packages/flame/CHANGELOG.md, packages/flame/lib/src/effects2/scale_effect.dart, packages/flame/test/effects2/scale_effect_test.dart
Refactored `ScaleEffect` to the new effects engine
=> Refactored `ScaleEffect` to the new effects engine

packages/flame/lib/src/components/isometric_tile_map_component.dart, packages/flame/test/components/isometric_tile_map_component_test.dart
Followup on the previous PR, just fixing a bug.
This image will make everything immediately clear:
=> Luan.fix center isometric

doc/particles.md
Updated the documentation link to new location
Not an known issue.
=> Changed link to new particle example location

doc/particles.md
Removed "particle:" key. replaced ..asComponent with ParticleComponent.
No document issue relation found
=> Align code examples with examples

packages/flame_oxygen/CHANGELOG.md, packages/flame_oxygen/pubspec.yaml
Publish flame_oxygen-0.1.0-releasecandidate.17
=> Publish flame_oxygen-0.1.0-releasecandidate.17

packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/pubspec.yaml
Publish flame_forge2d-0.8.2-releasecandidate.17
=> Publish flame_forge2d-0.8.2-releasecandidate.17

packages/flame_rive/CHANGELOG.md, packages/flame_rive/pubspec.yaml
Publish flame_rive-1.0.0-releasecandidate.2
#1141
=> Publish flame_rive-1.0.0-releasecandidate.2

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/input/hud_margin_component.dart
Fixed both margin and position when using a Viewport.
Credits to @spydon for debugging and fixing this with me.
=> Fixed calculations in HudMarginComponent

packages/flame/CHANGELOG.md, packages/flame/lib/src/device.dart
Forcing portrait and landscape is now supported on web
=> Forcing portrait and landscape is now supported on web

packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
Publish flame-1.0.0-releasecandidate.18
=> Publish flame-1.0.0-releasecandidate.18

packages/flame/CHANGELOG.md, packages/flame/lib/src/components/parallax_component.dart, packages/flame/lib/src/parallax.dart, packages/flame/test/components/parallax_test.dart
Fix parallax loading with different loading times
#1154 
=> Fix parallax loading with different loading times

doc/_sphinx/requirements.txt
Added `sphinxcontrib-mermaid` to the requirements file for our docs website. The package is used for generating diagrams / flowcharts / etc.
=> Add sphinxcontrib-mermaid to the requirements file

doc/components.md, examples/lib/stories/input/joystick_advanced_example.dart, packages/flame/CHANGELOG.md, packages/flame/lib/components.dart, packages/flame/lib/src/components/component.dart, packages/flame/lib/src/components/coordinate_system.dart, packages/flame/lib/src/components/input/hud_margin_component.dart, packages/flame/lib/src/components/positioning_type.dart, packages/flame/lib/src/game/camera/camera.dart, packages/flame/lib/src/game/camera/camera_wrapper.dart, packages/flame/lib/src/game/camera/viewport.dart, packages/flame/lib/src/game/mixins/game.dart, packages/flame/lib/src/gestures/events.dart, packages/flame/test/game/camera_and_viewport_test.dart, packages/flame/test/game/component_rendering_test.dart
=> respectCamera and respectViewport proposal: coordinate system enum

doc/effects.md, examples/lib/stories/effects/color_effect_example.dart, examples/lib/stories/effects/effects.dart, packages/flame/CHANGELOG.md, packages/flame/lib/effects.dart, packages/flame/lib/src/components/mixins/has_paint.dart, packages/flame/lib/src/effects/color_effect.dart, packages/flame/test/components/mixins/has_paint_test.dart, packages/flame/test/effects/color_effect_test.dart
Adds the color effect on the new effects system
=> Implementing ColorEffect on the new effects system

packages/flame/test/effects/opacity_effect_test.dart
Bump epsilon of long opacity effect test until we fix it properly.
=> Bump epsilon of long opacity effect test

packages/flame/pubspec.yaml
=> Add collection

packages/flame/pubspec.yaml, packages/flame_test/CHANGELOG.md, packages/flame_test/pubspec.yaml
=> Publish flame test 1.0.0

packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
=> Update Flame version to 1.0.0

packages/flame_test/CHANGELOG.md, packages/flame_test/example/pubspec.yaml, packages/flame_test/pubspec.yaml
=> Publish flame test 1.0.1

packages/flame_audio/CHANGELOG.md, packages/flame_audio/example/pubspec.yaml, packages/flame_audio/pubspec.yaml
=> Publish flame audio 1.0.0

packages/flame_flare/CHANGELOG.md, packages/flame_flare/pubspec.yaml, packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/pubspec.yaml
=>  Publish flame flare 1.0.0

packages/flame_bloc/CHANGELOG.md, packages/flame_bloc/example/pubspec.yaml, packages/flame_bloc/pubspec.yaml
=> Publish flame bloc 1.0.0 

packages/flame_oxygen/CHANGELOG.md, packages/flame_oxygen/pubspec.yaml
=> Publish flame oxygen 0.1.1

packages/flame_rive/CHANGELOG.md, packages/flame_rive/pubspec.yaml
=> Publish flame rive 1.0.0

packages/flame_svg/CHANGELOG.md, packages/flame_svg/pubspec.yaml
=> Publish flame svg 1.0.0

packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/pubspec.yaml
=> Publish flame tiled 1.0.0

README.md
*The flame_lint link at README.md fixed.*
*None*
=> docs: fix faulty `flame_lint` link in README.md

packages/flame_tiled/README.md
Adds feroult to the list of contributors.
=> docs: Update contributions to flame_tiled

i18n/README-ZH.md
Improves the mandarin README. A few things need to be mentioned:
* Replaced all `pub.dev` to `pub.flutter-io.cn`, which is our official mirror.
* Two of our localized sites were moved into the "Other resources" part, with an **unofficial** tag.
* Mentioned that *Highlighted community tutorials* might not be able to access due to network limitations.
- (N/A) My PR includes unit or integration tests for *all* changed/updated/fixed behaviors and are passing (See [Contributor Guide]).
- (N/A) My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR …
=> docs: Improve Mandarin README

i18n/README-ES.md
- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] My PR does not decrease the code coverage, or I have __a very special case__ and explained on the PR description why this PR decreases the coverage.
- [ X] I read and followed the [Flame Style Guide].
- [ X] I am willing to follow-up on …
=> docs: #1195-Update-README.md-for-other-languages

.github/pull_request_template.md, CONTRIBUTING.md, melos.yaml, packages/flame/example/analysis_options.yaml
This PR adds Melos and updates the contributing doc accordingly
Closes #1200 
=> build: Add Melos and update contributing doc

README.md
Upon reading our docs in search for a simple, couple-paragraph description of the engine, I figured this section could be improved. In particular we say "Currently" a lot; I don't mean we are not improving and ever evolving and certainly new things will be added, but I proposed we change the tone a bit with v1, being more assertive to describe what we have to offer. I am open to suggestions though, I know it might be silly to focus on a handful of sentences but this is the main description of the engine for anyone new that arrives here, so I think it's important to get them just right.
Does your PR require Flame …
=> doc: Improve Features section, remove the usage of Currently

CONTRIBUTING.md
=> doc: Fix typo on CONTRIBUTING.md

packages/flame_forge2d/example/lib/main.dart, packages/flame_forge2d/example/lib/raycast_sample.dart
This PR adds a new sample in flame_forge2d for Raycast. It contains a sample implementation for finding nearest and farthest fixtures along the casted ray. Here is how it works, two rays (red and blue) are fired from same starting point with mouse position as the target. Red ray always stops at the nearest fixture and blue ray always stop at the farthest fixture. Paint of fixtures are changed depending on which ray hits it. If both rays hit the same fixture, it turns yellow.
https://user-images.githubusercontent.com/33748002/146823360-4e8b30c1-0d0e-44b0-8d25-61a8fb42bc0d.mp4
- (NA) I have updated/added tests for ALL …
=> example: Add Raycast example for flame_forge2d

doc/game.md
the link realises to a web page not found
*Replace this paragraph with a description of what this PR is doing. 
If you're modifying existing behavior, describe the existing behavior, how this PR is changing it,
and what motivated the change. If this is a breaking change, specify explicitly which APIs have been
changed.*
[issue …
=> working example link error?

doc/components.md, packages/flame/lib/src/components/component_set.dart
=> fix: Both places should have `strictMode = false`

examples/lib/stories/input/keyboard_example.dart
*Replace this paragraph with a description of what this PR is doing. 
If you're modifying existing behavior, describe the existing behavior, how this PR is changing it,
and what motivated the change. If this is a breaking change, specify explicitly which APIs have been
changed.*
[issue database]: …
=> docs: Fix keyboard example instructions

packages/flame_tiled/README.md
Fixed a typo in the flame_tiled docs, and then I realized it probably is a good idea to add a warning about the ghost lines too.
=> docs: Update flame_tiled readme

packages/flame_bloc/pubspec.yaml, packages/flame_test/CHANGELOG.md, packages/flame_test/example/pubspec.yaml, packages/flame_test/example/test/main_test.dart, packages/flame_test/pubspec.yaml
Publish new version of flame_test
=> chore(publish): Publish flame_test 1.1.0

doc/components.md, packages/flame_bloc/pubspec.yaml
Add note about `PositionType` and subcomponents
=> docs: Add note about `PositionType` and subcomponents

packages/flame_bloc/example/pubspec.yaml, packages/flame_bloc/pubspec.yaml
Updated the bloc version inside flame bloc to the latest bloc version.
This is a breaking change in terms that the user will need to update their dependency as well, but no code change will be required if they already moved their blocs to the new API.
[Contributor …
=> feat!(flame-bloc): updating flame bloc to bloc 8

doc/components.md
Fix a miss typo on the documentation of components.md
The checks of tests/examples does not make sense for this PR
No issue related
=> docs: Fix a variable declaration on components.md

CHANGELOG.md, packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/pubspec.yaml
=> chore(release): Publish `flame_tiled` 1.2.0

packages/flame_bloc/lib/src/flame_bloc_game.dart
Added Camera optional parameter on FlameBlocGame, so it can be used on super constructor.
=> feat: Optional Camera argument in FlameBlocGame

doc/gesture-input.md, examples/lib/stories/camera_and_viewport/zoom_example.dart, packages/flame/lib/src/gestures/events.dart
Includes events for panning into the scale info events, since in Flutter the `ScaleDetector` is a superset of the `PanDetector`.
=> feat(gestures): Update scale events to contain pan info

packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml
Update rive package to 0.8.1 (now support raster graphics), in pubspec.yaml in flame_rive package.
Fixes  #1270
=> feat: update rive package to 0.8.1 (now support raster graphics)

README.md, i18n/README-ES.md, i18n/README-JA.md, i18n/README-PL.md, i18n/README-RU.md, i18n/README-ZH.md
Added Japanese README. This is a faithful translation of the original README written in English. The meaning is the same as in the original English version, although some words have been added to make it more natural Japanese. In addition, links to the new README have been added to the READMEs in other languages that had already been added.
No issue.
[Flame …
=> docs: Added Japanese README.

CHANGELOG.md, packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/pubspec.yaml
=> chore: publish flame_tiled 1.2.1

doc/components.md
fixed example in section Querying child components
=> `docs:` Update components.md - fixed example in section Querying child components

.github/workflows/gh-pages.yml
=> chore: Initialize melos before building gh pages

examples/pubspec.yaml
Flutter 2.10 introduced some breaking changes that broke dashbook, a new version was released and this PR updates our examples app to this version. …
=> feat: update examples dashbook

CHANGELOG.md, packages/flame_forge2d/CHANGELOG.md, packages/flame_forge2d/pubspec.yaml
- flame_forge2d@0.9.0-releasecandidate.1
*Replace this paragraph with a description of what this PR is doing. 
If you're modifying existing behavior, describe the existing behavior, how this PR is changing it,
and what motivated the change. If this is a breaking change, specify explicitly which APIs have been
changed.*
[issue …
=> chore(release): publish packages

packages/flame_svg/pubspec.yaml
Current flutter_svg version is quite old: ^0.22.0. Updated to latest v1.0.3
=> chore: update flutter_svg version in flame_svg to latest

doc/flame/inputs/gesture-input.md
=> docs: draggable doc fix

doc/flame/collision_detection.md, doc/flame/game.md
=> docs: Fix anchor links in collision detection docs

packages/flame_audio/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_flare/pubspec.yaml, packages/flame_oxygen/pubspec.yaml
Remove publish_to: none where not needed so that those packages will be properly published.
=> chore: Remove publish_to: none where not needed

packages/flame/lib/src/assets/images.dart, packages/flame/lib/src/components/component_set.dart, packages/flame/lib/src/extensions/rect.dart, packages/flame/lib/src/game/game_loop.dart, packages/flame/lib/src/game/mixins/loadable.dart, packages/flame/lib/src/widgets/nine_tile_box.dart, packages/flame_forge2d/lib/position_body_component.dart, packages/flame_svg/lib/svg_component.dart, packages/flame_tiled/lib/src/renderable_tile_map.dart
Adds the correct version that the methods (etc) will be removed in.
=> chore: Add correct removal version to deprecated methods

doc/_sphinx/theme/flames.css, doc/flame/collision_detection.md, doc/flame/components.md, doc/flame/game.md, doc/flame/inputs/gesture-input.md, doc/other_modules/forge2d.md
Also, added an admonition for a "Deprecated" block.
=> fix: Fix warnings/errors in documentation

packages/flame/lib/src/components/component.dart, packages/flame/test/components/component_test.dart
This PR makes it possible to get the descendants of a component
https://github.com/flame-engine/flame/issues/1456#issue-1171350725
=> feat: Added method that returned descendants

packages/flame_forge2d/pubspec.yaml
=> feat: updating forge2d version

doc/flame/rendering/particles.md, examples/lib/stories/rendering/particles_example.dart, examples/lib/stories/rendering/particles_interactive_example.dart, examples/lib/stories/rendering/rendering.dart, packages/flame/lib/components.dart, packages/flame/lib/src/components/particle_component.dart, packages/flame/lib/src/components/particle_system_component.dart, packages/flame/test/components/particle_system_component_test.dart
Adds a new component to handle particles into FCS and deprecates the old one
Solves #1488
=> feat: adding ParticleSystemComponent

packages/flame/lib/src/collisions/broadphase.dart, packages/flame/test/collisions/collision_callback_test.dart
See [this comment](https://github.com/flame-engine/flame/issues/1478#issuecomment-1091453143)
Fixes #1478 
=> fix: Make CollisionProspect's a, b have unordered equality

.github/workflows/cicd.yml
This is the same action that Melos itself uses for PR title validation so it should be solid.
Closes #1370 
=> chore: Add PR title validation

packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml
- Mesh deform support for image assets, including bone binding and skin deformation.
- Fixed an issue with references to missing assets.
- Fixed some warnings.
=> feat: update to Rive 0.8.4

i18n/README-RU.md
https://github.com/flame-engine/flame/issues/1195#issuecomment-1106344807
=> docs: update Russian readme

packages/flame/lib/src/sprite_animation.dart
When using sprite animation, you can control the range of animation display by passing in the two parameters of start and end
=> feat: Add range constructor on SpriteAnimationData

i18n/README-PL.md
Updated Polish readme - current version 1.1.1.
https://github.com/flame-engine/flame/issues/1195#issuecomment-1106344807
Best wishes,
=> docs: Update Polish readme

doc/flame/effects.md, examples/lib/stories/effects/size_effect_example.dart, packages/flame/lib/effects.dart, packages/flame/lib/src/components/nine_tile_box_component.dart, packages/flame/lib/src/components/sprite_animation_component.dart, packages/flame/lib/src/components/sprite_animation_group_component.dart, packages/flame/lib/src/components/sprite_component.dart, packages/flame/lib/src/components/sprite_group_component.dart, packages/flame/lib/src/effects/provider_interfaces.dart, packages/flame/lib/src/effects/size_effect.dart, packages/flame/lib/src/experimental/viewport.dart, packages/flame/lib/src/geometry/circle_component.dart, packages/flame/test/effects/size_effect_test.dart
Similar to all other effects, the `SizeEffect` now targets components implementing `SizeProvider`.
Currently the following classes implement `SizeProvider`:
- `CircleComponent`,
- `Viewport`,
- `NineTileBoxComponent`,
- `SpriteComponent`,
- `SpriteGroupComponent`,
- `SpriteAnimationComponent`,
- `SpriteAnimationGroupComponent`.
Unlike with other effects, `PositionComponent` does NOT implement `SizeProvider`. This is because the components usually don't pay attention to their `size` when rendering, and thus changing their `size` would not create any visual difference, which users assume is a bug. Now this class of bugs will disappear: `SizeEffect` will simply throw an error saying that the target is not a `SizeProvider`.
Breaking change:
- If users have their own components that they …
=> feat!: Size effects will now work only on components implementing SizeProvider

packages/flame/lib/src/sprite_animation.dart, packages/flame/test/sprite_animation_test.dart
Add tests for SpriteAnimationData
=> feat: add SpriteAnimationData tests

.github/workflows/cicd.yml
To speed up the pipeline, allow the test step to run in parallel with the other steps.
=> ci: Run tests in parallel with analyze

melos.yaml, packages/flame/test/experimental/fixed_size_viewport_test.dart, packages/flame/test/sprite_test.dart, packages/flame_test/lib/flame_test.dart, packages/flame_test/lib/src/test_golden.dart, packages/flame_test/test/golden_test.dart
Added new function `testGolden()` that reduces the boilerplate of writing golden tests to a minimum.
=> feat: Add helper function for creating golden tests

packages/flame/lib/src/components/input/hud_button_component.dart
#1646 seems to already be fixed in `main`, this just simplifies the code a bit for it.
#1646 
=> refactor: Simplify HudButtonComponent

doc/README.md, doc/flame/camera_and_viewport.md, doc/flame/components.md, doc/flame/inputs/gesture-input.md, doc/flame/inputs/keyboard-input.md, doc/flame/inputs/other-inputs.md, doc/flame/other/util.md, doc/flame/other/widgets.md, doc/flame/platforms.md, doc/flame/rendering/images.md, doc/flame/rendering/layers.md, doc/flame/rendering/particles.md, doc/flame/rendering/text.md, doc/flame_audio/bgm.md, doc/other_modules/oxygen.md
Fix all the dead links and add two new lines before each new header according to some form of markdown best practices.
=> docs: Dead links and header formatting

doc/flame/collision_detection.md, doc/flame/inputs/other-inputs.md
Fix the last remaining broken example links.
=> docs: Fix the broken example links

packages/flame/lib/src/components/component.dart
These methods can be simplified using the extension `Iterable.firstOrNull` getter.
=> refactor: Simplify Component.firstChild, .lastChild, and .findParent

doc/tutorials/bare_flame_game.md
Updated instructions in the "Bare Flame game" tutorial to account for the current Flutter min version of 2.10.0.
=> docs: Update Flame min version in "bare flame game" tutorial

packages/flame/lib/src/anchor.dart
This method is not used anywhere, and its name doesn't match the function very well.
=> fix: Deprecate Anchor.translate()

examples/games/trex/lib/background/cloud.dart, packages/flame/lib/src/components/component.dart, packages/flame/test/components/particle_system_component_test.dart, packages/flame/test/components/sprite_animation_component_test.dart, packages/flame/test/components/sprite_animation_group_component_test.dart, packages/flame/test/game/flame_game_test.dart
Some of these tests are a bit strange, but that's outside of the scope of this PR.
=> fix: Remove nonVirtual method shouldRemove

packages/flame/example/lib/main.dart
Our main example for the flame package was no longer working due to some changes on the input system, namely the need to manually mark events as handled.
I also removed some pausing logic that I do not think belongs on the main example, that can be a separate topic on the dashbook example. This example should be simple and contain key learning topics.
=> fix: Fix flame package example app

packages/flame_lint/CHANGELOG.md, packages/flame_lint/README.md, packages/flame_lint/pubspec.yaml
Since flame_lint was accidentally missed in the release yesterday.
=> chore: publish flame_lint

.github/workflows/cicd.yml
This caches Flutter between the steps in the pipeline.
=> chore: Cache flutter in pipeline

packages/flame_audio/pubspec.yaml
Update minor version of audioplayers, which fixes a couple bugs
=> chore: Update minor version of audioplayers

examples/lib/stories/games/games.dart
=> fix: Fix broken link for example games code

CHANGELOG.md, packages/flame_rive/CHANGELOG.md, packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml
=> chore(release): Publish flame_rive 1.4.0

doc/_sphinx/requirements.txt, doc/_sphinx/theme/doctools.js
Upgrading `doctools.js` script to the latest version used in Sphinx.
After this change, the search script should work again.
=> docs: Fix search in documentation

examples/pubspec.yaml
Updates the Dashbook version on our examples and update  an example to use its new action API.
=> chore: updating dashbook on examples

examples/games/padracing/lib/main.dart, examples/games/padracing/scripts/merge_files.sh
After a previous update to padracing I forgot to update the script that turns it into a file that can be put into DartPad.
=> fix: Correct the imports for the padracing -> dartpad script

packages/flame/lib/src/game/flame_game.dart
This PR delays the update for camera until all the components are updated to avoid the jitter effect. Here is a comparison of before and after 
https://user-images.githubusercontent.com/33748002/180600607-60aaa756-2128-4ec7-ae81-6362b4fbbab8.mp4
- [NA] I have updated/added tests for ALL new/updated/fixed functionality.
- [NA] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [NA] I have updated/added relevant examples in `examples`.
Fixes #1810 
=> fix: Delay camera update

doc/flame/inputs/gesture-input.md, packages/flame/lib/events.dart, packages/flame/lib/src/game/game_widget/gestures.dart, packages/flame/lib/src/gestures/detectors.dart
This PR will add a new mixin on `Game` to detect tertiary tap (middle mouse button on desktop platforms) inputs.
=> feat: Add tertiary tap detector mixin

doc/flame/other/util.md
=> docs: Fixed incorrect import in timer docs.

doc/flame_forge2d/forge2d.md
=> docs: wrong syntax on forge2d docs.

doc/_sphinx/theme/flames.css
Fix docs bug introduced in #1817
=> docs: Fix disappearing menu in docs

CHANGELOG.md, packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/example/pubspec.yaml, packages/flame_tiled/pubspec.yaml
Bump flame_tiled to 1.7.0 so that it is using tiled 0.8.4
=> chore(release): Publish flame_tiled 1.7.0

CHANGELOG.md, packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/example/pubspec.yaml, packages/flame_tiled/pubspec.yaml
=> chore(release): Publish flame_tiled v1.7.1

doc/other_modules/tiled.md
=> docs: pdate tiled docs example link

packages/flame_forge2d/README.md
Fix broken link in forge2d readme
=> docs: Fix broken link in forge2d readme

examples/lib/stories/input/input.dart
=> docs: fix broken link for Keyboard Input Component

doc/flame/platforms.md
=> docs: itch.io web upload instructions

doc/flame/platforms.md
=> docs: small fix on itch io instructions.

doc/flame/platforms.md
=> docs: Updated itch.io instructions

packages/flame/lib/src/game/game_widget/game_widget.dart
Changes:
- Container for ColoredBox
- Container for SizedBox.shrink 
Rationale:
- Avoid unnecessary checks.
- Be more implicit on the desired effect by using more specific widgets.
- Remove unnecessary checks made by Flutter by not following the above point.
- SizedBox can be const and won't even create a new instance during runtime.
=> refactor: used simpler and more implicit widgets in GameWidget

doc/flame/components.md
Updated docs about priority as we chat at https://github.com/flame-engine/flame/issues/1457#issuecomment-1229249634. I reused the same sentence as @st-pasha as it was easy to understand and I am not a native speaker.
- #1457 
=> docs: more precise `priority` definition

examples/games/padracing/pubspec.yaml, examples/lib/stories/collision_detection/bouncing_ball_example.dart, examples/lib/stories/collision_detection/collision_detection.dart, examples/pubspec.yaml
This PR adds two updates.
1. It updates the flame_forge2d to latest version i.e on pub.dev in examples and padracing projects. 
2. Adds a bouncing ball example in the collision detection examples demonstrating a simple example of collision and bouncing of a ball from the walls around it.
https://user-images.githubusercontent.com/65209850/187041471-77635c70-b75a-4db6-b692-62899014e54f.mov
=> docs: Added bouncing ball example in collision_detection examples and updated flame_forge2d to latest

doc/flame/examples/pubspec.yaml, examples/games/padracing/lib/padracing_widget.dart, examples/games/trex/pubspec.yaml, examples/pubspec.yaml, packages/flame/example/pubspec.yaml, packages/flame/lib/src/cache/images.dart, packages/flame/lib/src/components/isometric_tile_map_component.dart, packages/flame/pubspec.yaml, packages/flame/test/components/keyboard_listener_component_test.dart, packages/flame_audio/pubspec.yaml, packages/flame_bloc/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_flare/example/pubspec.yaml, packages/flame_flare/pubspec.yaml, packages/flame_forge2d/example/pubspec.yaml, packages/flame_forge2d/pubspec.yaml, packages/flame_oxygen/pubspec.yaml, packages/flame_rive/pubspec.yaml, packages/flame_svg/pubspec.yaml, packages/flame_test/pubspec.yaml, packages/flame_tiled/pubspec.yaml
Upgrade the dartdoc version to work with the current flutter version
=> chore: Upgrade the dartdoc version to work with the current flutter version

packages/flame/pubspec.yaml, packages/flame_audio/pubspec.yaml, packages/flame_bloc/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_flare/pubspec.yaml, packages/flame_forge2d/pubspec.yaml, packages/flame_lint/pubspec.yaml, packages/flame_oxygen/pubspec.yaml, packages/flame_rive/pubspec.yaml, packages/flame_svg/pubspec.yaml, packages/flame_test/pubspec.yaml, packages/flame_tiled/pubspec.yaml
Adds the links to our patreon and buy me a coffee in the pubspec files so that pub.dev can show them.
=> chore: Add funding links (patreon + buy me a coffee)

packages/flame/lib/src/collisions/collision_detection.dart, packages/flame/lib/src/collisions/has_collision_detection.dart, packages/flame/lib/src/collisions/standard_collision_detection.dart
This adds generics for the broadphase used in the collision detection.
This should simplify things a bit in #1894.
=> feat: Add broadphase generics to CollisionDetection

packages/flame_bloc/pubspec.yaml
flame_bloc is currently losing points on pub due to a too short description, this PR makes the description longer.
=> chore: Fix flame_bloc pubspec description

packages/flame_tiled/example/pubspec.yaml, packages/flame_tiled/lib/src/renderable_layers/tile_layer.dart, packages/flame_tiled/lib/src/renderable_tile_map.dart, packages/flame_tiled/pubspec.yaml
=> chore: Bump tiled to 0.9.0

doc/_sphinx/requirements.txt
=> docs: Pin doc dependency versions

packages/flame/test/components/input/sprite_button_component_test.dart
- 🐛 fix: #1967 : Unit tests for `SpriteButtonComponent`
Closes #1967 
I haven't added Widget test for the `SpriteButtonComponent`. I will create another PR for Widget test. This will include only Unit test.
=> test: Unit tests for `SpriteButtonComponent`

.github/workflows/cicd.yml, packages/flame/lib/src/events/messages/event.dart
This helps our contributors to see the warnings from the analyzer directly in the PR.
=> ci: Inline analyze warnings

examples/lib/stories/animations/animations.dart, examples/lib/stories/bridge_libraries/audio/audio.dart, examples/lib/stories/collision_detection/collision_detection.dart, examples/lib/stories/input/input.dart, examples/lib/stories/tiled/tiled.dart
=> docs: Fixed broken example links 

doc/_sphinx/theme/flames.css
Just noticed that on mobiles in Examples block, if a link is long, there is an annoying horizontal scrolling:
=> docs: wrap long external links to avoid horizontal scrolling

packages/flame/test/components/input/sprite_button_component_test.dart
- 🚨 Widget test for `SpriteButtonComponent`
=> test: Widget test for `SpriteButtonComponent`

packages/flame_forge2d/test/body_component_test.dart, packages/flame_forge2d/test/forge2d_game_test.dart
- Working on unit test
- 🐛 fix: #2031:  unit test for `Forge2dGame`
Closes #2031
=> test: unit test for `Forge2dGame`

packages/flame/test/game/mixins/has_hoverables_test.dart
- 🚨 Unit test for `HasHoverables`
=> test: Unit test for `HasHoverables`

packages/flame/test/particles/circle_particle_test.dart, packages/flame/test/particles/computed_particle_test.dart, packages/flame/test/particles/curved_particle_test.dart, packages/flame/test/particles/moving_particle_test.dart, packages/flame/test/particles/scaled_particle_test.dart, packages/flame/test/particles/sprite_particle_test.dart
- fix: 🐛 #1966: Unit test for `Particles`
- Closes #1966 
=> test: unit test for particles #1966

CODE_OF_CONDUCT.md
=> docs: Fireslime -> Blue Fire

doc/_sphinx/conf.py, doc/_sphinx/extensions/package.css, doc/_sphinx/extensions/package.py, doc/bridge_packages/bridge_packages.md, doc/other_modules/other_modules.md
The new directive is intended to work as an infocard about one of the Flame's subpackages, and looks more conspicuous than a mere link.
=> docs: Added new directive {package}

.github/.cspell/flame_dictionary.txt, .github/workflows/spell_checker.yml, packages/flame_isolate/example/lib/brains/path_finder.dart
Make the spell check mandatory in the pipeline.
Closes #2158 
=> ci: Make the spell check mandatory

packages/flame_jenny/jenny/pubspec.yaml
=> fix: remove flutter from jenny

doc/README.md, doc/bridge_packages/flame_isolate/isolate.md, doc/tutorials/tutorials.md, examples/lib/stories/bridge_libraries/flame_isolate/isolate.dart
Closes: https://github.com/flame-engine/flame/issues/2169
As discussed, a quick fix to some bad links and while I was in Flame Isolate, fixed some bad grammar.
=> docs:  Fix bad links in docs as well as minor updates

CHANGELOG.md, packages/flame_isolate/CHANGELOG.md
=> chore(release): Publish flame_isolate v0.1.0

.github/workflows/gh-pages.yml
=> ci: Try to build docs with only GH_TOKEN set to PAT

.github/workflows/gh-pages.yml
=> ci: Use curl instead of GH to dispatch job request for docs

.github/workflows/gh-pages.yml
=> ci: Use external action for remote doc build

.github/workflows/gh-pages.yml
=> ci: Add repository line for docs build dispatch

.github/workflows/gh-pages.yml
=> ci: Try triggering doc action from curl

.github/workflows/gh-pages.yml
=> ci: Try using other PAT for docs build

packages/flame/lib/src/spritesheet.dart
Fixed super small typo mentioned in Discord.
=> docs: Teh -> the

doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_5.md
Per the Discord discussion, I have updated the references of "your class" to the proper class name for the file.
=> docs: References to "your class" to use class name

packages/flame_audio/pubspec.yaml
Resolves upstream issue https://github.com/bluefireteam/audioplayers/issues/1194
=> chore: Bump audioplayers to 1.2.0

doc/other_modules/jenny/language/expressions/functions/functions.md, doc/other_modules/jenny/language/expressions/functions/user_defined_functions.md, doc/other_modules/jenny/runtime/command_storage.md, doc/other_modules/jenny/runtime/function_storage.md, doc/other_modules/jenny/runtime/index.md, doc/other_modules/jenny/runtime/yarn_project.md
The documentation for user-defined functions and the `FunctionStorage` class.
Closes #2237
=> docs: Add documentation for user-defined functions in Jenny

packages/flame_jenny/jenny/test/dialogue_runner_test.dart, packages/flame_jenny/jenny/test/dialogue_view_test.dart, packages/flame_jenny/jenny/test/structure/dialogue_option_test.dart
This adds several missing test cases, restoring 100% coverage.
=> test: Added several missing tests for Jenny

doc/flame/game.md
This PR addresses the confusion in https://github.com/flame-engine/flame/issues/2213.  
=> docs: Added note to clarify the use of camera.gameSize in the resize event

doc/flame/camera_component.md, packages/flame/lib/src/camera/camera_component.dart, packages/flame/test/camera/camera_component_test.dart
This PR adds a `moveBy` method to the `CameraComponent` using the `MoveByEffect`, matching the `moveTo` method we already have.
=> feat: Add `moveBy` to `CameraComponent`

packages/flame_jenny/jenny/lib/jenny.dart, packages/flame_jenny/jenny/lib/src/command_storage.dart, packages/flame_jenny/jenny/lib/src/structure/dialogue_line.dart, packages/flame_jenny/jenny/test/dialogue_view_test.dart, packages/flame_jenny/jenny/test/function_storage_test.dart, packages/flame_jenny/jenny/test/structure/commands/declare_command_test.dart, packages/flame_jenny/jenny/test/structure/commands/user_defined_command_test.dart, packages/flame_jenny/jenny/test/structure/dialogue_line_test.dart, packages/flame_jenny/jenny/test/test_scenario.dart, packages/flame_jenny/jenny/test/variable_storage_test.dart
This ensures that all classes that are documented are actually publicly exported by the package.
=> chore: Add missing exports for Jenny

doc/flame/camera_component.md, packages/flame/lib/src/camera/camera_component.dart, packages/flame/test/camera/camera_component_test.dart
Adding `inView` method so developers can more easily check if a given component is visible from a camera point of view.
=> feat: Add a `canSee` method to the `CameraComponent`

.github/workflows/cicd.yml
To be able to get in all our fixes.
=> ci: Pin flutter version until we have done all fixes

packages/flame/lib/src/collisions/broadphase/quadtree/quadtree.dart, packages/flame/lib/src/particles/animation_particle.dart
Found some minor code smells, wont affect any functionality.
=> chore: Clean up minor code smells

CHANGELOG.md, examples/pubspec.yaml, packages/flame_audio/CHANGELOG.md, packages/flame_audio/example/pubspec.yaml, packages/flame_audio/pubspec.yaml
=> chore(release): Publish flame_audio v1.4.0

packages/flame/lib/src/components/route.dart, packages/flame/lib/src/components/router_component.dart, packages/flame/lib/src/particles/sprite_particle.dart, packages/flame/test/components/router_component_test.dart, packages/flame_isolate/example/.metadata
Before when you only had two routes you'd get:
```
Bad state: No element
dart:core                                                  List.last
package:flame/src/components/router_component.dart 260:30  RouterComponent._popWithoutMinimumAssert
package:flame/src/components/router_component.dart 122:7   RouterComponent.pushReplacementNamed
test/components/router_component_test.dart 20:14           main.<fn>.<fn>
```
=> fix: RouterComponent replace methods to correctly handle previous/nextRoute

doc/tutorials/platformer/step_6.md
Remove a typo in the code of tuto
=> docs: Remove a typo in the code of tuto

doc/flame/rendering/particles.md, packages/flame/lib/src/components/mixins/single_child_particle.dart
Saw some old code references, fixed them up.
=> docs: Fix old doc code

.github/workflows/gh-pages.yml
Just bumping to the newest Melos version.
=> ci: Bump Melos in gh-pages

doc/tutorials/platformer/step_3.md
Currently, the platformer tutorial in the Platform Block section of Step 3 tells the reader to declare a variable at the top of the `EmberQuestGame` class and modify update method of the `EmberQuestGame` class.
The screenshot below shows how the explanation tells that the changes should be done in the "platform block".
This PR updates the text to read `PlatformBlock` instead of `EmberQuestGame`.
=> docs: Fix typo in Step 3 of platformer tutorial

doc/flame/inputs/gesture_input.md
Minor indentation fix in the list of gesture detectors.
=> docs: Indentation fix in gesture list

packages/flame/lib/src/timer.dart
As stated in #2357, the field `limit` of the class `Timer` had no reason to be final. By removing this keyword, we make it possible to add more time to a given `Timer` object (so that they can be used as a countdown for example).
Closes #2357.
=> feat: Make `limit` field mutable in the `Timer` class

doc/tutorials/klondike/step2.md
At the *Other classes* session, when it is mentioned that we need to create the `components` sub-directory, the tutorial is guiding us to add it in the root, but on the structure below, it is possible to see that it should be created inside the `libs` folder instead.
It seems to be better to be more explicit in this paragraph.
- [ x] I have followed the [Contributor Guide] when preparing my PR.
- [ x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ x] I have updated/added relevant examples in `examples` or `docs`.
[CHANGELOG]: …
=> docs: Fixing components sub-directory path

CONTRIBUTING.md
Updated activate melos command, to use melos 3.0
#2364
=> docs: Updated activate melos command

doc/_sphinx/requirements.txt
This fixes the regression with that the graphs aren't rendering. Unfortunately they will forever be broken in the v1.6.0 release of the docs now.
Fix comes from here: https://github.com/mgaitan/sphinxcontrib-mermaid/commit/2eaff4220ade181ad9d8e6148f76498c0c0671f2
Closes #2361 
=> docs: Update to latest sphinx-mermaid

.github/.cspell/flame_dictionary.txt, .github/.cspell/gamedev_dictionary.txt
All of a sudden Cypher started failing in the pipeline.
The other two are for #2367
=> docs: Add missing dictionary words

doc/flame/rendering/particles.md, packages/flame/lib/particles.dart, packages/flame/lib/src/particles/sprite_animation_particle.dart, packages/flame/lib/src/particles/sprite_particle.dart
=> feat: Add position and anchor params for Sprite and SpriteAnimation Particles

CONTRIBUTING.md
Clarify required flutter channel on CONTRIBUTING guidelines
=> docs: Clarify required flutter channel on CONTRIBUTING guidelines

CONTRIBUTING.md, pubspec.yaml
Since Melos 3 now is released we don't have to refer to the pre-release version anymore.
=> chore: Update instructions and pubspec to Melos 3

doc/_sphinx/extensions/dart_domain.py
This fixes a problem that we accidentally introduced in a recent PR: the `shell=True` setting requires that the arguments were passed as a single string instead of a list. Passing as a string, in turn, is somewhat problematic because the file names need to be escaped, and there is no utility function to make this escaping cross-platform.
So, instead we'll use the standard `shell=False`, and invoke `dartdoc_json.bat` on Windows instead of simply `dartdoc_json`. Hope this would work. …
=> docs: Do not use shell=True in dart_domain.py

doc/_sphinx/doc-setup.py, melos.yaml
Closes: https://github.com/flame-engine/flame/issues/2398
Finally got the script all figured out, so `melos doc-setup` works on windows.  It should work on Unix as well, but I can't verify.  Its simply scalar fold, color encoding removed, python string literal wrapped in double quotes, and false converted to a bash exit.
=> docs: Fix melos doc setup for windows

examples/.gitignore, examples/lib/main.dart, examples/lib/platform/page_provider.dart, examples/lib/platform/stub_provider.dart, examples/lib/platform/web_provider.dart, examples/pubspec.yaml, examples/test/main_test.dart
Fix build for non-web platforms, by hiding dart:html into platform-specific import.
=> docs: Fix non-web examples

.github/FUNDING.yml, README.md, packages/flame/pubspec.yaml, packages/flame_audio/pubspec.yaml, packages/flame_bloc/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_flare/pubspec.yaml, packages/flame_forge2d/pubspec.yaml, packages/flame_jenny/jenny/pubspec.yaml, packages/flame_jenny/pubspec.yaml, packages/flame_lint/pubspec.yaml, packages/flame_lottie/pubspec.yaml, packages/flame_network_assets/pubspec.yaml, packages/flame_noise/pubspec.yaml, packages/flame_oxygen/pubspec.yaml, packages/flame_rive/pubspec.yaml, packages/flame_studio/pubspec.yaml, packages/flame_svg/pubspec.yaml, packages/flame_test/pubspec.yaml, packages/flame_tiled/pubspec.yaml
This just updates the funding links and adds OpenCollective first everywhere and removing BuyMeACoffee.
=> docs: Update funding links

doc/bridge_packages/flame_forge2d/joints.md, examples/lib/main.dart, examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/forge2d/joints/motor_joint.dart, examples/lib/stories/bridge_libraries/forge2d/joints/pulley_joint.dart, examples/lib/stories/bridge_libraries/forge2d/utils/balls.dart, examples/lib/stories/bridge_libraries/forge2d/utils/boxes.dart
PulleyJoint documentation and example
#2005 
=> docs: PulleyJoint documentation and example

examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart
Update source code urls of forge2d joints in Flame Examples
Closes #2436
=> docs: Update source code urls of forge2d joints in Flame Examples

.github/ISSUE_TEMPLATE/3_improvement.md
Small type that I came around while filling an issue.
=> chore: Small Typo fix in the improvement template issue.

doc/flame/inputs/inputs.md, doc/flame/layout/layout.md
Add [Hardware Keyboard Detector](https://docs.flame-engine.org/main/flame/inputs/hardware_keyboard_detector.html#) in [Inputs](https://docs.flame-engine.org/main/flame/inputs/inputs.html#)
and
[Align Component](https://docs.flame-engine.org/main/flame/layout/align_component.html) in [Layout](https://docs.flame-engine.org/main/flame/layout/layout.html)
Closes #2439
=> docs: Update the side bar menu with the latest additions

doc/bridge_packages/flame_forge2d/forge2d.md, doc/flame/camera_and_viewport.md, doc/flame/rendering/text_rendering.md, doc/flame/router.md, doc/tutorials/platformer/step_2.md, doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_4.md, doc/tutorials/space_shooter/step_2.md
Removed unnecessary `async` from code snippets.
Closes #2449
=> docs: Remove unnecessary async from code snippets

CHANGELOG.md, packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
=> chore(release): Publish Flame v1.7.1

doc/bridge_packages/flame_forge2d/joints.md, examples/lib/main.dart, examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/forge2d/joints/prismatic_joint.dart
PrismaticJoint example and documentation
#2005 
=> docs: PrismaticJoint docs and example

CHANGELOG.md, packages/flame/CHANGELOG.md, packages/flame/pubspec.yaml
Releasing Flame v1.7.2 with two bug fixes.
=> chore(release): Flame v1.7.2

doc/flame/effects.md
Removal of the information concerning effects.reverse() and effects.isReversed in the "Effect" bulletpoint list, as these are outdated and have been removed from the Effect component.
Closes #2475
=> docs: Remove deprecated effects.reverse docs

doc/tutorials/klondike/step1.md
fixing link to bare flame tutorial
=> docs: Fix link in step1.md

CHANGELOG.md, examples/pubspec.yaml, packages/flame_audio/CHANGELOG.md, packages/flame_audio/example/pubspec.yaml, packages/flame_audio/pubspec.yaml
Release flame_audio@2.0.0 which uses audioplayers 4.0.0
=> chore(release): Publish flame_audio 2.0.0

doc/bridge_packages/flame_forge2d/joints.md, examples/lib/main.dart, examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/forge2d/joints/gear_joint.dart
GearJoint docs and example
#2005 
=> docs: Added GearJoint docs and example

packages/flame/pubspec.yaml
Bump the version of `ordered_set` to ensure that users gets the fixed version.
=> feat: Bump ordered_set version

doc/flame/collision_detection.md, doc/flame/examples/lib/ember.dart, doc/tutorials/platformer/app/lib/actors/water_enemy.dart, doc/tutorials/platformer/app/lib/objects/ground_block.dart, doc/tutorials/platformer/app/lib/objects/platform_block.dart, doc/tutorials/platformer/app/lib/objects/star.dart, doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_4.md, examples/games/rogue_shooter/lib/components/enemy_component.dart, examples/lib/stories/collision_detection/quadtree_example.dart, packages/flame/lib/src/collisions/collision_detection.dart, packages/flame/lib/src/collisions/hitboxes/circle_hitbox.dart, packages/flame/lib/src/collisions/hitboxes/polygon_hitbox.dart, packages/flame/lib/src/collisions/hitboxes/rectangle_hitbox.dart, packages/flame_bloc/example/lib/src/game/components/enemy.dart
With this PR we accept the `CollisionType` directly in the constructor.
=> feat: Accept `CollisionType` in hitbox constructor

CHANGELOG.md, examples/pubspec.yaml, packages/flame_audio/CHANGELOG.md, packages/flame_audio/example/pubspec.yaml, packages/flame_audio/pubspec.yaml
=> chore(release): Publish flame_audio 2.0.2

doc/bridge_packages/flame_forge2d/joints.md, examples/lib/main.dart, examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/forge2d/joints/rope_joint.dart, examples/lib/stories/bridge_libraries/forge2d/utils/balls.dart
RopeJoint documentation and example
#2005 
=> docs: RopeJoint documentation and example

CONTRIBUTING.md, doc/_sphinx/theme/flames.css, doc/development/documentation.md, doc/development/style_guide.md, doc/development/testing_guide.md, doc/flame/platforms.md, doc/tutorials/bare_flame_game.md, packages/flame/lib/src/game/game_widget/game_widget.dart, packages/flame_flare/example/README.md
Update content types of some sphinx code snippets.
=> docs: Update content types of sphinx code snippets

doc/bridge_packages/flame_forge2d/joints.md, examples/lib/main.dart, examples/lib/stories/bridge_libraries/forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/forge2d/joints/weld_joint.dart, examples/lib/stories/bridge_libraries/forge2d/utils/boxes.dart
WeldJoint docs and example
#2005 
=> docs: WeldJoint docs and example

doc/tutorials/platformer/step_5.md
The update method should end up with the code in this order, otherwise the velocity is never set to 0. 
Probably obvious but the rest of the steps were precise on where to include these code blocks.
May wanna add this full block to the end of this step as well, I spent a few minutes trying to figure out why it wasn't working propely.
```dart
@override
void update(double dt) {
if (horizontalDirection < 0 && scale.x > 0) {
flipHorizontally();
} else if (horizontalDirection > 0 && scale.x < 0) {
flipHorizontally();
}
// Apply basic gravity
velocity.y += gravity;
// Determine if ember has jumped
if (hasJumped) {
if (isOnGround) {
velocity.y = -jumpSpeed;
isOnGround = false;
}
hasJumped = false;
}
// Prevent ember from jumping to crazy fast as well as descending too fast and
// crashing …
```
=> docs: Enhance "adding the scrolling" section

packages/flame_bloc/lib/src/flame_bloc_listener.dart, packages/flame_bloc/test/src/flame_bloc_listener_test.dart
Adding onInitialState to FlameBlocListener to match the implemented interface.
=> feat: Add onInitialState to FlameBlocListener

CHANGELOG.md, examples/pubspec.yaml, packages/flame_tiled/CHANGELOG.md, packages/flame_tiled/example/pubspec.yaml, packages/flame_tiled/pubspec.yaml
=> chore(release): Publish flame_tiled 1.11.0

packages/flame/lib/src/camera/world.dart, packages/flame/test/camera/world_test.dart
=> feat(flame): Set a default negative priority on the world for general use

CONTRIBUTING.md
Since Melos 3 isn't beta anymore we can point directly to the latest stable release.
=> docs: Update CONTRIBUTING.md to point to latest Melos

doc/tutorials/klondike/step3.md
Update step3.md of Klondike tutorial to give `Card` `isFaceDown` Since that property is used in step 4.
=> docs: Update step3.md of Klondike tutorial to give `Card` `isFaceDown`

packages/flame_forge2d/README.md
=> docs: Fix broken link on flame_forge2d readme

.github/.cspell/flame_dictionary.txt, doc/README.md
Update Nakama link + add Supabase to the docs.
=> docs: Update Nakama link + add Supabase

packages/flame_audio/pubspec.yaml
=> chore: Bump audioplayers to 5.0.0

packages/flame_forge2d/pubspec.yaml
Proper Flame dependency in flame_forge2d
=> fix: Proper Flame dependency in flame_forge2d

examples/games/rogue_shooter/README.md
This updates the rogue shooter readme since there was some confusion in #2640.
Closes #2640 
=> docs: Update README.md of rogue_shooter

doc/flame/diagrams/component.md
Fix component diagram
Broken by https://github.com/flame-engine/flame/commit/f582f4924f05e8fe300f517e3f6ffc553e2d294c
=> docs: Fix component diagram

examples/games/padracing/lib/padracing_game.dart, examples/games/padracing/lib/tire.dart, examples/games/rogue_shooter/lib/components/enemy_component.dart, examples/games/trex/lib/background/cloud.dart, examples/games/trex/lib/random_extension.dart, examples/lib/stories/bridge_libraries/audio/basic_audio_example.dart, examples/lib/stories/input/hardware_keyboard_example.dart, packages/flame/lib/src/components/input/sprite_button_component.dart, packages/flame_studio/lib/src/core/component_tree.dart, packages/flame_studio/lib/src/widgets/toolbar/toolbar_button.dart
Fix a handful of lint issues across the codebase, identified using DCM.
Nothing controversial, I expect; slowly getting these out of the way so we can focus on discussing bigger things.
=> refactor: Fix lint issues across the codebase - Part 2

README.md
Just adds the Flutter favorite logo to the readme.
=> docs: Add Flutter favorite logo to readme

.github/workflows/cicd.yml, melos.yaml
Try if `flutter test` works better in the pipeline. 😥
Maybe spec is using too much resources and gets killed.
=> ci: Try running the test pipeline without spec

.github/workflows/cicd.yml
We aren't even using `melos analyze` in our pipeline, I forgot that.
This makes the infos fatal, so that it fails properly.
=> ci: Fatal-infos should be true for analyze step

packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml
Allow new text feature from Rive.
=> chore: Update rive package to 0.11.16

doc/flame/game.md
Just fixes some docs in `game.md` to remove syntax errors and make it runnable.
Closes #2712 
=> docs: Make game docs runnable

README.md
Updates the list of Bridge packages in the project main README
=> chore: Update bridge package list

packages/flame/lib/src/components/core/component.dart
The `removeFromParent` wasn't going through the public methods on the parent, so overwriting the `remove` would not allow you to detect all removing of children.
=> fix(flame): The `component.removeFromParent` method should use `parent.remove` internally

CONTRIBUTING.md
Add better instructions on how to run cspell locally
=> docs: Add better instructions on how to run cspell locally

packages/flame/lib/src/game/game.dart, packages/flame/lib/src/game/game_widget/game_widget.dart, packages/flame/test/game/flame_game_test.dart
When the init game method is called straight after the app has launched, the lifecycle state from `WidgetsBinding.instance.lifecycleState` often returns `disposed` or `inactive` which causes the engine to stay paused even though the app is foregrounded.
This PR fixes the lifecycle state as `resumed` when the init method is called.
Fixes #2771
=> fix: Hardcode initCurrentGame lifecycle state as resumed

examples/lib/stories/bridge_libraries/flame_forge2d/flame_forge2d.dart, examples/lib/stories/bridge_libraries/flame_lottie/lottie.dart, examples/lib/stories/bridge_libraries/flame_spine/flame_spine.dart
Fixing broken links to issue  #2618
If the PR is breaking, uncomment this header and add instructions for how to migrate from the
currently released version to the new proposed way.
-->
Closes #2618
=> docs: Fix broken links to code in examples

packages/flame_splash_screen/CHANGELOG.md, packages/flame_splash_screen/example/pubspec.yaml, packages/flame_splash_screen/pubspec.yaml
Publish flame_splash_screen 0.2.0
=> chore: Publish flame_splash_screen 0.2.0

packages/flame_tiled/lib/src/renderable_tile_map.dart, packages/flame_tiled/lib/src/tile_atlas.dart
Some classes in flame tiled weren't using the optional Images/AssetsBundle class, this address that.
=> feat: Add overriding of Images and Bundle in all classes

.github/pull_request_template.md
With these new tags we can remove all the things from the PR template that we don't want to be included in the git log.
=> chore: Exclude PR template from Git log

packages/flame/lib/src/camera/viewfinder.dart, packages/flame/lib/src/collisions/hitboxes/screen_hitbox.dart, packages/flame/test/collisions/screen_hibox_test.dart
Resizes the `ScreenHitbox` on zoom changes.
=> fix: Properly resize ScreenHitbox when needed

.gitignore, packages/flame_tiled/example/.gitignore
Change the gitignore to ignore the platform folders of examples
=> chore: Ignoring examples platforms folder

packages/flame_test/lib/src/test_flame_game.dart
There were a few arguments in `test` that wasn't being exposed by `testWithGame` and `testWithFlameGame`.
=> feat: Expose addition test arguments on flame test

doc/tutorials/platformer/step_2.md, doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_5.md, doc/tutorials/platformer/step_6.md
This small PR adjusts:
1.  some `backticks` (`) in the platformer tutorial in order to have a proper highlight of the file names.
2. replaces backslash (`\`) with slash (`/`) in order to be consistent with the other  file paths used in the tutorial.
3. renames the variable `_xOffset` to `xOffset` in order to be consistent with the rest of the code.
[CHANGELOG]: …
=> fix: Adjust platformer tutorial steps

packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml
Description
Allow new features from Rive, like events.
Checklist
I have followed the [Contributor Guide] when preparing my PR.
[-] I have updated/added tests for ALL new/updated/fixed functionality.
[-] I have updated/added relevant documentation in docs and added dartdoc comments with ///.
I have updated/added relevant examples in examples or docs.
Breaking Change?
Yes, this PR is a breaking change.
No, this PR is not a breaking change.
=> chore: Update rive package to 0.12.3

packages/flame_tiled/lib/src/renderable_tile_map.dart, packages/flame_tiled/lib/src/tile_atlas.dart, packages/flame_tiled/lib/src/tiled_component.dart
Flame Tiled uses SpriteBatch under the hood to render its tiles. That API has a flag called `useAtlas` that when false allows rendering to be done through `drawImageRect`s instead of `drawAtlas`.
There were not way to set that through Flame Tiled though. This PR exposes that as an option for the developer.
=> feat: Expose useAtlas on Flame Tiled

packages/flame_tiled/lib/src/tile_atlas.dart
The `useAtlas` configuration was not being propagated correctly in all of the places. This PR fixes that.
=> fix: Configuration useAtlas was not been propagated correctly everywhere

doc/flame/structure.md
Details about the `tiles` folder was missing from the `proposed folder structure` docs, so this PR adds that.
Closes #2859 
=> docs: Add `tiles` folder to structure docs

packages/flame/lib/src/geometry/circle_component.dart, packages/flame/lib/src/geometry/polygon_component.dart, packages/flame/lib/src/geometry/rectangle_component.dart
Some constructors in the shape components were missing, this PR adds them.
=> feat: Adding children argument to all constructors in the shape components

packages/flame/lib/src/effects/sequence_effect.dart
With previous implementation of the `SequenceEffect` didn't allowed developers to extend it and create custom sequence effects. This PR slightly refactors the class so it can now be extended.
=> feat: Allow sequence effect to be extended

packages/flame_tiled/lib/src/tiled_component.dart, packages/flame_tiled/test/tiled_test.dart
Adds a `componentAtlases` in the `TiledComponent` which can be useful for debugging purposes, where the developer will be able to inspect the atlases being used in their game.
=> feat: Exposing atlases for reading in a TiledComponent

packages/flame_tiled/lib/src/tiled_component.dart
Remove duplicated entries from `TiledComponent.atlases`
=> fix: TiledComponent.atlases had duplicated values

doc/tutorials/platformer/step_4.md, doc/tutorials/platformer/step_7.md
Fix EmberQuest tutorial typos described in issue #2869 
Closes #2869 
=> docs: Fix EmberQuest tutorial typos

examples/pubspec.yaml, packages/flame_spine/pubspec.yaml
`spine_flutter` got a new release recently, which fix the issue that the dependency overriding was handling, so this PR removes the dependency override and updates the package.
=> fix: Removing spine flutter overriding

packages/flame/lib/src/components/core/component.dart
Consider viewport scaling into the text paint used in the debug information of components.
Fixes #2881
=> feat: Using viewport scale on debug mode text paint

packages/flame_isolate/pubspec.yaml
Update flame_isolate to point at repository
=> docs: Update flame_isolate to point at repository

packages/flame/lib/src/widgets/animation_widget.dart, packages/flame/test/widgets/sprite_animation_widget_test.dart, packages/flame_riverpod/example/pubspec.yaml, packages/flame_riverpod/pubspec.yaml
`SpriteAnimationWidget` was incorrectly reseting its `animationTicker` everytime it had a change, even if the playing attribute did not change. This PR fixes that.
=> fix: SpriteAnimationWidget was resetting the ticker even when the playing didn't changed

.github/.cspell/gamedev_dictionary.txt, .github/.cspell/words_dictionary.txt, doc/tutorials/platformer/step_1.md, doc/tutorials/platformer/step_2.md, doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_4.md, doc/tutorials/platformer/step_5.md, doc/tutorials/platformer/step_6.md, doc/tutorials/platformer/step_7.md
Updates the  platformer tutorial to Flame v1.11.0
=> docs: Update platformer tutorial to latest Flame

doc/flame/camera_component.md
Added some missing link text in the camera component documentation.
Closes #2908
=> docs: Added missing text to links in camera component documentation

packages/flame/lib/src/components/sprite_animation_component.dart
Just exposed the `children` list from `fromFrameData` constructor.
=> feat: Add `children` to `SpriteAnimationComponent.fromFrameData`

doc/README.md
This PR does two improvements to the README.md in our docs:
- Remove the list of bridge packages and link to the bridge packages section, so we don't need to maintain two lists
- Remove the section about external assets not being in the scope of the Flame since that is not true anymore.
=> docs: Remove list of bridge packages from readme

doc/tutorials/space_shooter/app/lib/main.dart, doc/tutorials/space_shooter/app/lib/step4/main.dart, doc/tutorials/space_shooter/step_4.md
Adds the fourth step of the space shooter tutorial.
=> docs: Adding space shooter tutorial step4

doc/flame/rendering/text_rendering.md
Fix a typo in text_rendering.md file.
=> docs: Fix typo in text_rendering.md

doc/bridge_packages/flame_tiled/flame_tiled.md
=> docs: Adding VGV's article on ghost line issue for tiled

doc/bridge_packages/flame_forge2d/joints.md, doc/flame/camera_component.md, doc/flame/flame.md, doc/flame/inputs/inputs.md, doc/tutorials/klondike/step5.md
This fixes the warnings that sphinx was throwing when building.
It most likely doesn't fix the mermaid rendering though.
=> docs: Fix sphinx warnings

doc/flame/rendering/images.md
This is based on #2939.
Closes #2939 
=> docs: Improvement on animation docs

doc/tutorials/space_shooter/app/lib/step2/main.dart, doc/tutorials/space_shooter/app/lib/step3/main.dart, doc/tutorials/space_shooter/app/lib/step4/main.dart, doc/tutorials/space_shooter/app/lib/step5/main.dart, doc/tutorials/space_shooter/app/lib/step6/main.dart, doc/tutorials/space_shooter/step_2.md, doc/tutorials/space_shooter/step_3.md, doc/tutorials/space_shooter/step_4.md, doc/tutorials/space_shooter/step_5.md, doc/tutorials/space_shooter/step_6.md
This PR improves the Space Shooter Tutorial as a whole by moving the setting of component's attributes from their `onLoad` method, to their constructors.
Once this is merged, I will do two additional follow ups
- Using `SpawnComponent` instead of `TimerComponent` to create bullets
- Adding passive hitboxes to bullets and explaining why.
=> docs: Improving Space Shooter tutorial by moving attributes to constructors

examples/lib/stories/collision_detection/circles_example.dart, packages/flame/lib/src/camera/viewfinder.dart, packages/flame/test/collisions/screen_hibox_test.dart
The `visibleGameSize` should be based on the virtual size of the viewport, otherwise it won't work for `FixedResolutionViewport` for example.
We noticed this when using the `ScreenHitbox` in a world that was looked upon by a camera with a `FixedResolutionViewport`.
=> fix: The `visibleGameSize` should be based on `viewport.virtualSize`

doc/flame/collision_detection.md, doc/tutorials/space_shooter/app/lib/step6/main.dart, doc/tutorials/space_shooter/step_6.md
Improves the collision code of the space shooter tutorial.
=> docs: Improving collision on SpaceShooter tutorial

packages/flame/lib/src/components/spawn_component.dart, packages/flame/test/components/spawn_component_test.dart
`SpawnComponent` didn't had the ability to not auto start. This PR adds a new attribute in order to customize that.
=> feat: Adding ability for a SpawnComponent to not auto start

doc/tutorials/space_shooter/app/lib/step4/main.dart, doc/tutorials/space_shooter/app/lib/step5/main.dart, doc/tutorials/space_shooter/app/lib/step6/main.dart, doc/tutorials/space_shooter/step_4.md
Use a `SpawnComponent` instead of a `TimerComponent` to spawn bullets on the Space Shooter tutorial.
=> docs: SpaceShooter Bullet SpawnComponent

CHANGELOG.md, packages/flame_riverpod/CHANGELOG.md, packages/flame_riverpod/pubspec.yaml
```
Package Name     Current Version   Updated Version   Update Reason
flame_riverpod   5.1.2             5.1.3             manual versioning
```
=> chore(release): Publish flame_riverpod v5.1.3

packages/flame/lib/src/components/mixins/gesture_hitboxes.dart, packages/flame/lib/src/components/position_component.dart, packages/flame/test/components/mixins/gesture_hitboxes_test.dart
Previously the point sent in to `containsLocalPoint` for `GestureHitboxes` didn't take the parent transformation into consideration, this is fixed in this PR.
=> fix: Consider displaced hitboxes in GestureHitboxes mixin

packages/flame/lib/src/collisions/hitboxes/shape_hitbox.dart
To easily be able to spot whether a it is a hitbox that is being drawn in `debugMode = true` it is now yellow instead of purple like the other debug boxes.
=> fix: Set hitbox `debugColor` to yellow

CHANGELOG.md, packages/flame_riverpod/CHANGELOG.md, packages/flame_riverpod/example/pubspec.yaml, packages/flame_riverpod/pubspec.yaml
```
Package Name     Current Version   Updated Version   Update Reason
flame_riverpod   5.1.4             5.1.5             updated with patch changes
```
=> chore(release): Publish flame_riverpod 5.1.5

packages/flame_riverpod/lib/src/consumer.dart
This PR adds a template parameter to the `RiverpodGameMixin` as it is done with all other mixins on `FlameGame` throughout the codebase. This allows to use this mixin on `FlameGame`s that use a different `World` (for example `Forge2DGame` with `Forge2DWorld`). 
I have not created an issue as the solution is straigtforward and this PR implements the solution.
[CHANGELOG]: …
=> fix: Add Template param to RiverpodGameMixin

doc/flame/inputs/other_inputs.md
* Removes `HasDraggables` reference; fixes #2975
* velocity -> relativeDelta
Closes #2975
=> docs: Remove `HasDraggables` in `JoystickComponent` example docs

doc/flame/rendering/images.md
Fix the `SpriteBatch` example URL described in issue https://github.com/flame-engine/flame/issues/2991
Closes https://github.com/flame-engine/flame/issues/2991
=> docs: Add an underscore to SpriteBatch example url

doc/tutorials/space_shooter/step_4.md, doc/tutorials/space_shooter/step_5.md, doc/tutorials/space_shooter/step_6.md
Adds flutter app block to the steps 4, 5 and 6 to the space shooter tutorial, which were missing.
=> docs: Space Shooter Tutorial had flutter app missing in some steps

doc/flame/components.md
Fix typo inside the documentation to avoid confusion. The header should be 'SpriteGroupComponent' instead of 'SpriteGroup'.
=> docs: SpriteGroup -> SpriteGroupComponent

doc/tutorials/space_shooter/app/lib/step4/main.dart, doc/tutorials/space_shooter/app/lib/step5/main.dart, doc/tutorials/space_shooter/app/lib/step6/main.dart, doc/tutorials/space_shooter/step_4.md
=> docs: SpaceShooter tutorial had an issue in its code for the bullet spawn

doc/flame/other/widgets.md
The documentation regarding the widgets are so outdated and it is very confusing for a beginner like me. So, I update them to make it easier for others to follow.
=> docs: Update widgets documentation

.github/ISSUE_TEMPLATE/bug_report.yml
This PR's main aim is to fix the validation errors (seen [here](https://github.com/flame-engine/flame/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml)) within the bug report yaml to make this a valid form based on GitHubs schema.
That being said, the main changes are:
- Ensure each form has a unique ID
- A proposal to change the "affected platforms" from a textarea to a dropdown
- Small phrasing changes, happy to revert if needed.
=> chore: Minor updates to bug_report form

.github/.cspell/dart_dictionary.txt, CHANGELOG.md, examples/pubspec.yaml, packages/flame_svg/CHANGELOG.md, packages/flame_svg/example/pubspec.yaml, packages/flame_svg/pubspec.yaml
```
Package Name   Current Version   Updated Version   Update Reason
flame_svg      1.8.10            1.9.0             updated with minor changes
```
=> chore(release): Publish flame_svg v1.9.0

.github/.cspell/dart_dictionary.txt, packages/flame_tiled/lib/flame_tiled.dart, packages/flame_tiled/lib/src/extensions.dart, packages/flame_tiled/test/extensions_test.dart
This PR adds an extension on `TiledObject` to allow getting the object's `position` and `size` as `Vector2` objects.
NA
=> feat: Add TiledObjectHealpers extension on TiledObject

packages/flame/lib/components.dart, packages/flame/lib/experimental.dart, packages/flame/lib/game.dart, packages/flame/lib/input.dart, packages/flame/lib/sprite.dart, packages/flame_lint/lib/analysis_options.yaml
This is decreasing flame's points on pub
=> chore: Fix `dangling_library_doc_comments`

packages/flame_forge2d/lib/body_component.dart, packages/flame_forge2d/test/body_component_test.dart
The previous solution didn't take the whole transform into consideration, this one does.
Closes: #3039
=> fix: BodyComponent fixtures should test with global point

packages/flame_texturepacker/lib/flame_texturepacker.dart
=> feat(flame_texturepacker): Expose TexturePackerAtlas

packages/flame_tiled/lib/flame_tiled.dart, packages/flame_tiled/lib/src/renderable_layers/tile_layers/tile_layer.dart, packages/flame_tiled/test/tile_atlas_test.dart, packages/flame_tiled/test/tiled_test.dart
`TileAtlas` has a `clearCache` method which the users might need to call from their code. This is recommended in our docs here: https://docs.flame-engine.org/latest/bridge_packages/flame_tiled/flame_tiled.html#clearing-images-cache
NA
=> feat: Export `TileAtlas` from `flame_tiled` package

packages/flame/lib/src/components/mixins/component_viewport_margin.dart
=> fix: FutureOr return type of ComponentViewportMargin.onLoad

packages/flame/lib/src/components/route.dart, packages/flame/test/components/route_test.dart
This PR replaces the `Route.timeSpeed` with `HasTimeScale.timeScale`.
Replace `Route.timeSpeed` with `Route.timeScale`.
NA
=> refactor!: Use HasTimeScale for Route

packages/flame_riverpod/lib/src/widget.dart
This adds implementations of the necessary `ProviderSubscription` getters.
=> fix: Implement necessary `ProviderSubscription` getters

CHANGELOG.md, packages/flame_riverpod/CHANGELOG.md, packages/flame_riverpod/example/pubspec.yaml, packages/flame_riverpod/pubspec.yaml
```
Package Name     Current Version   Updated Version   Update Reason
flame_riverpod   5.3.0             5.4.0             updated with minor changes
```
=> chore: Publish flame_riverpod v5.4.0

packages/flame_network_assets/pubspec.yaml
Updates the http dependency on flame_network_assets
=> feat: Update http dependency on flame_network_assets

packages/flame_oxygen/lib/src/flame_world.dart, packages/flame_oxygen/pubspec.yaml
Updated oxygen dep to v0.3.1 and added call to new method to remove components.
- [-] I have updated/added tests for ALL new/updated/fixed functionality. --> I didn't see any tests for this package
Oxygen issue: [#18](https://github.com/flame-engine/oxygen/issues/18).
=> fix: Updated oxygen dep to v0.3.1 and added removing components

packages/flame/lib/src/components/clip_component.dart
The ClipComponent factory Constructor "circle", "rectangle" and "polygon" are now redirect Constructor while they persist their previous behaviour and syntax.
This allows subclasses of ClipComponent to directly address them.
```dart
/// Examples: 
SubClass.fancyShape() : super.polygon();
Smiley() : super.circle();
```
Closes #3083
=> refactor: Change the ClipComponent factory Constructor to redirect Constructor

examples/lib/stories/bridge_libraries/flame_jenny/commons/commons.dart
The links for the flame_jenny examples were pointing on the wrong URL.
=> docs: Fix broken link to flame_jenny example code

doc/flame/other/debug.md, melos.yaml, packages/flame/.pubignore, packages/flame/lib/devtools.dart, packages/flame/lib/src/devtools/connectors/component_tree_connector.dart, packages/flame/lib/src/devtools/connectors/debug_mode_connector.dart, packages/flame/lib/src/devtools/dev_tools_service.dart, packages/flame_devtools/README.md, packages/flame_devtools/lib/main.dart, packages/flame_devtools/lib/repository.dart, packages/flame_devtools/lib/widgets/component_counter.dart, packages/flame_devtools/lib/widgets/component_tree.dart, packages/flame_devtools/lib/widgets/debug_mode_button.dart, packages/flame_devtools/lib/widgets/game_loop_controls.dart, packages/flame_devtools/pubspec.yaml
This PR creates a devtools extension tab for Flame where you can:
* Turn on `debugMode` for a chosen component or the whole tree
* See the component tree
* Play, pause and step the game loop.
[Screencast from 2024-03-24 22-09-55.webm](https://github.com/flame-engine/flame/assets/744771/82217afb-e096-4375-a892-b59e1be6d7ec)
=> feat: Component tree for the devtools extension tab

packages/flame_texturepacker/README.md, packages/flame_texturepacker/example/lib/main.dart, packages/flame_texturepacker/lib/flame_texturepacker.dart
Originally, the function was named `fromAtlas` because there was another function named `fromJson` that loaded `.json` files.  but since that one is gone, and now every function is loading a `.atlas` it make sense to have `fromAssets` and `fromStorage`
=> refactor: Deprecate `fromAtlas` in favour of `atlasFromAssets` and `atlasFromStorage`

packages/flame/lib/src/game/flame_game.dart
Old typo where `renderTree` should call `render` and not itself when the parent isn't null, since otherwise it will cause an infinite recursion.
=> fix: Call `render` properly from nested `FlameGame`s

doc/bridge_packages/flame_forge2d/joints.md, doc/development/documentation.md, doc/flame/rendering/text_rendering.md, examples/lib/stories/bridge_libraries/flame_isolate/simple_isolate_example.dart, packages/flame/lib/src/camera/camera_component.dart, packages/flame/lib/src/components/sprite_animation_group_component.dart, packages/flame/lib/src/components/sprite_group_component.dart, packages/flame/lib/src/extensions/image.dart, packages/flame/lib/src/parallax.dart
=> chore: Remove repetitive words

doc/flame/effects.md, packages/flame/lib/src/effects/effect.dart, packages/flame/test/effects/effect_test.dart
This PR adds a `completed` future for effects which completes when the effect finishes.
NA
=> feat: Add completed future for effects

melos.yaml, packages/flame_devtools/lib/main.dart, packages/flame_devtools/lib/widgets/component_tree.dart, packages/flame_devtools/lib/widgets/component_tree_model.dart, packages/flame_devtools/pubspec.yaml
This is a refactor to prepare for some new devtools features, like autoreloading the tree and the component.
=> refactor: Use riverpod in devtools components tree

doc/tutorials/klondike/app/lib/main.dart, doc/tutorials/klondike/app/lib/step3/components/card.dart, doc/tutorials/klondike/app/lib/step4/components/card.dart, doc/tutorials/klondike/app/lib/step5/components/card.dart, doc/tutorials/klondike/step3.md, doc/tutorials/platformer/app/lib/ember_quest.dart, doc/tutorials/platformer/step_3.md, doc/tutorials/platformer/step_4.md, doc/tutorials/space_shooter/app/lib/main.dart, examples/games/padracing/lib/game_colors.dart, examples/games/trex/lib/obstacle/obstacle_type.dart, examples/lib/stories/bridge_libraries/flame_isolate/simple_isolate_example.dart, examples/lib/stories/collision_detection/multiple_shapes_example.dart, examples/lib/stories/components/spawn_component_example.dart, examples/lib/stories/input/gesture_hitboxes_example.dart, packages/flame/lib/src/collisions/broadphase/quadtree/quadtree.dart, packages/flame/lib/src/components/core/component_tree_root.dart, packages/flame/lib/src/parallax.dart, packages/flame/test/extensions/image_extension_test.dart, packages/flame_behavior_tree/behavior_tree/lib/src/decorators/inverter.dart, packages/flame_bloc/example/lib/src/game/components/bullet.dart, packages/flame_bloc/example/lib/src/inventory/view/inventory.dart, packages/flame_forge2d/lib/body_component.dart, packages/flame_isolate/example/lib/brains/worker_overmind.dart, packages/flame_jenny/jenny/lib/src/command_storage.dart, packages/flame_jenny/jenny/lib/src/function_storage.dart, packages/flame_markdown/lib/flame_markdown.dart, packages/flame_rive/lib/src/rive_component.dart, packages/flame_tiled/lib/src/renderable_layers/tile_layers/tile_layer.dart
Replaces the switch cases that can be replaces with switch expressions and removes `break;` where it isn't needed.
https://dart.dev/language/branches#switch-statements
=> refactor: Modernize switch; use switch-expressions and no break;

doc/tutorials/space_shooter/step_1.md, doc/tutorials/space_shooter/step_2.md, doc/tutorials/space_shooter/step_3.md, doc/tutorials/space_shooter/step_4.md, doc/tutorials/space_shooter/step_5.md, doc/tutorials/space_shooter/step_6.md
- Fixed typos and grammar
- Rephrased some sentences for brevity purposes
- Added link to next stage (I realise these MD files are probably also used to generate https://docs.flame-engine.org/main/tutorials/space_shooter/space_shooter.html where you add the `prev` and `next` buttons but I think it's useful to have these for those viewing them directly from the GH repo in a web browser)
=> docs: Fix typos and add links to the next tutorial steps

packages/flame_3d/lib/src/extensions/vector2.dart, packages/flame_3d/lib/src/extensions/vector3.dart, packages/flame_3d/lib/src/extensions/vector4.dart, packages/flame_3d/test/vector2_extensions_test.dart, packages/flame_3d/test/vector3_extensions_test.dart, packages/flame_3d/test/vector4_extensions_test.dart
Add helpful extension functions to Vector classes, including tests.
This was extracted directly from @wolfenrain 's [bigger PR](https://github.com/flame-engine/flame/pull/3085), making it easier to merge later.
=> feat(flame_3d): Add helpful extension functions to Vector

doc/flame/components.md
Fix the code in the docs page examples which has IsometricTileset and is not present in the flame to SpriteSheet
Closes #3163
=> docs: Fix IsometricTileMap code

packages/flame_devtools/.metadata, packages/flame_devtools/lib/widgets/component_tree.dart, packages/flame_devtools/pubspec.yaml, packages/flame_devtools/web/index.html
Bumps the devtools dependencies and fixes the `SplitPane` name change.
=> chore: Bump devtools dependencies

packages/flame_bloc/lib/src/flame_bloc_reader.dart
Since you can't chain the mixin if it doesn't call `super.onLoad`, that call was added.
Closes #3164
=> fix: Call `super.onLoad` from `FlameBlockReader`

examples/lib/stories/rendering/rich_text_example.dart, packages/flame/lib/src/text/nodes/code_text_node.dart, packages/flame/lib/src/text/styles/document_style.dart, packages/flame/lib/text.dart, packages/flame_markdown/lib/flame_markdown.dart, packages/flame_markdown/test/flame_markdown_test.dart
Support inline code blocks on markdown rich text.
=> feat: Support inline code blocks on markdown rich text

examples/pubspec.yaml
=> chore: Bump dashbook to 0.1.15

doc/tutorials/space_shooter/step_2.md
There was a small code Error in Step 2 of the Space Shooter Tutorial
```
the onPanUpdate method looked like this 
void onPanUpdate(DragUpdateInfo info) {
player.move(info.delta.global);
}
```
but it should look like this
```
void onPanUpdate(DragUpdateInfo info) {
player.move(info.delta.global);
}
```
Closes #3199
=> docs: Fix step 2 of space shooter tutorial delta values

packages/flame_spine/pubspec.yaml
Update spine_flutter dependency to 4.2.29
Closes #3201
=> chore(deps): Update spine_flutter to latest dependency

packages/flame/lib/src/components/core/component_set.dart, packages/flame/pubspec.yaml
Avoid hard-to-detect bugs by disallowing people to touch the list that they get from `query()`.
=> refactor!: Make query() result an Iterable

doc/flame/other/util.md, packages/flame/lib/src/components/mixins/has_time_scale.dart, packages/flame/test/components/mixins/has_time_scale_test.dart
This PR just adds 2 simple method to easily pause and resume the time scaled component.
NA
=> feat: Add `pause` and `resume` to `HasTimeScale` mixin

doc/flame/components.md
Remove abstract definition of `Component`.
=> docs: Remove abstract definition of Component

doc/flame/components.md
Improve wording on components.md
=> docs: Improve wording on components.md

doc/tutorials/space_shooter/step_2.md
DragUpdateInfo is included in the events package but is not in the docs.
When following the shooter tutorial I had issues cause the DragUpdateInfo was undefined. upon further investigation I found that it was in the event import instead
=> docs: Add events import in space shooter tutorial step_2

examples/lib/stories/bridge_libraries/flame_jenny/jenny.dart
Jenny code links were broken in examples. This PR fixes them.
NA
=> docs: Fix code links for jenny examples

packages/flame_test/lib/flame_test.dart, packages/flame_test/lib/src/close_to_vector3.dart, packages/flame_test/test/close_to_vector3_test.dart
Add a closeToVector3 matcher to flame_test
=> feat: Add a closeToVector3 matcher to flame_test

packages/flame_lint/lib/analysis_options_with_dcm.yaml, packages/flame_texturepacker/lib/src/texture_packer_atlas.dart
Enable DCM rule avoid-throw-in-catch-block
Details [here](https://dcm.dev/docs/rules/common/avoid-throw-in-catch-block/), basically doing so will erase the original stack trace.
This fixes all violations by using `Error.throwWithStackTrace`.
=> chore: Enable DCM rule avoid-throw-in-catch-block

packages/flame_fire_atlas/lib/flame_fire_atlas.dart, packages/flame_fire_atlas/test/flame_fire_atlas_test.dart
Adds a group to selections on Flame Fire Atlas
=> feat: Adding group to flame fire atlas

packages/flame_3d/lib/src/resources/mesh/cylinder_mesh.dart
Add `CylinderMesh` (as seen in defend_the_donut!)
=> feat: Add CylinderMesh [flame_3d]

packages/flame_3d/lib/resources.dart
=> fix: Fix typo on loadTexture

packages/flame_devtools/README.md
=> docs: Small devtools docs fixes

packages/flame_3d/example/pubspec.yaml, packages/flame_3d/pubspec.yaml
Update flame_lint version on flame_3d.
Note that this did not introduce any new violations (running locally):
```
$ melos analyze
└> dart analyze --fatal-infos
└> SUCCES
$ c packages/flame_3d
$ f analyze .
Analyzing flame_3d...
No issues found! (ran in 2.1s)
$ dart format .
Formatted 60 files (0 changed) in 0.32 seconds.
```
=> chore: Update flame_lint version on flame_3d

packages/flame_jenny/jenny/lib/src/parse/tokenize.dart
=> fix: Fix analyze issue on main

packages/flame/lib/src/devtools/connectors/position_component_attributes_connector.dart, packages/flame_devtools/lib/providers/position_component_attributes_provider.dart, packages/flame_devtools/lib/repository.dart, packages/flame_devtools/lib/widgets/incremental_number_form_field.dart, packages/flame_devtools/lib/widgets/position_component_attributes_form.dart
Adds scaling and angle to the dev tools form. Also fix a caching issue that was presenting outdated values to the user.
=> feat: Adding scale and angle to devtools attributes

packages/flame_spine/pubspec.yaml
The link to the homepage for the flame_spine package has a typo in it. This PR fixes the link.
=> docs: Homepage link typo for flame_spine

.github/.cspell/gamedev_dictionary.txt, packages/flame_3d/lib/extensions.dart, packages/flame_3d/lib/src/extensions/quaternion.dart, packages/flame_3d/lib/src/extensions/vector2.dart, packages/flame_3d/lib/src/extensions/vector3.dart, packages/flame_3d/lib/src/extensions/vector4.dart, packages/flame_3d/test/quaternion_extensions_test.dart, packages/flame_3d/test/vector2_extensions_test.dart, packages/flame_3d/test/vector3_extensions_test.dart, packages/flame_3d/test/vector4_extensions_test.dart
Add more useful extensions to VectorN and Quaternion
=> feat: Add more useful extensions to VectorN and Quaternion [flame_3d]

packages/flame_3d/README.md
Update README.md docs to reflect current state of affairs.
=> docs: Update README.md docs to reflect current state of affairs

packages/flame_3d/lib/src/extensions/quaternion.dart
Improve behavior of Quaternion.slerp function.
I wasn't fully happy with the previous implementation, as it introduced yet another "edge case".
It can actually be fixed much nicer by fixing two mistakes on the existing logic:
* consider the abs to check if quaternions are close enough for linear interpolation
* divide by `sin(alpha)` after multiplying the numerator to avoid numerical inaccuracies
Tested extensively with several models and seems to be working flawlessly.
=> fix: Improve behavior of Quaternion.slerp function [flame_3d]

.github/workflows/release-prepare.yml, .github/workflows/release-publish.yml, .github/workflows/release-tag.yml
With this PR we'll be able to publish by running an action from the Actions tab which will create a release PR that we can review and when that PR is merged it will tag all new packages and trigger release workflows for them.
=> ci: Melos publishing from workflow

.github/workflows/release-prepare.yml, .github/workflows/release-publish.yml, .github/workflows/release-tag.yml
This should fetch all history and tags etc, which is needed to properly version and publish.
=> ci: Run release workflows with fetch-depth 0

.github/workflows/release-tag.yml
The `env:` line was on the wrong indentation level.
=> ci: Correct env formatting for run

packages/flame/lib/src/components/sprite_group_component.dart
Now the assertion is slightly clearer for what the user has done wrong when calling the `SpriteGroupComponent.updateSprite` in an instance without an initialized `sprites` map.
=> fix: Clarify `SpriteGroupComponent.updateSprite` assertion

doc/flame/rendering/images.md, packages/flame/lib/src/cache/images.dart, packages/flame/test/cache/images_test.dart, packages/flame_tiled/test/tile_atlas_test.dart
Adds a keys getter in `Images` for retrieving all cache keys
https://github.com/flame-engine/flame/issues/3237
=> feat: Add a getter for images cache keys

packages/flame/lib/src/components/input/sprite_button_component.dart
Since it will be confusing for the user to have to call `super.onLoad` last when they override `onLoad`, we move setting the `sprites` to `onMount`.
=> fix: Set SpriteButtonComponent sprites in `onMount`

.github/workflows/release-tag.yml
This adds the missing permission to the release tag job.
=> ci: Add actions permissions to release tag job

packages/flame/lib/src/components/spawn_component.dart, packages/flame/test/components/spawn_component_test.dart
Adds a new flag on `SpawnComponent` to spawn a component when it is loaded, similar to how we have on `TimerComponent`. 
Its default is set to false to avoid breaking the current behaviour.
=> feat: Adding spawnWhenLoaded flag on SpawnComponent

melos.yaml, scripts/doc-setup.sh
Since there seems to be some problem with the doc setup on the GitHub runners, let's try running it as a separate script.
=> ci: Moved doc setup to separate script

.github/ISSUE_TEMPLATE/bug_report.yml
Fixing a typo I found when submitting a bug.
=> docs: Fix typo in bug report

examples/lib/stories/system/resize_example.dart
=> chore: Fix minor lint issue

doc/flame/flame.md
Fix broken link on flame.md docs
=> docs: Fix broken link on flame.md docs

packages/flame/test/components/position_component_test.dart, packages/flame/test/components/priority_test.dart, packages/flame/test/components/text_box_component_test.dart, packages/flame/test/extensions/vector2_test.dart, packages/flame/test/game/game_widget/game_widget_test.dart
This PR removes all the duplicates tests.
Closes #3356 
=> test: Remove duplicate tests

doc/README.md, doc/flame/structure.md
This updates the getting started documentation to include a starting point for building a game with Flame.
Closes: #3393
=> docs: Add some basic information to the getting started section

melos.yaml, packages/flame/pubspec.yaml, packages/flame_audio/pubspec.yaml, packages/flame_behavior_tree/behavior_tree/pubspec.yaml, packages/flame_behavior_tree/pubspec.yaml, packages/flame_bloc/pubspec.yaml, packages/flame_fire_atlas/pubspec.yaml, packages/flame_forge2d/pubspec.yaml, packages/flame_network_assets/pubspec.yaml, packages/flame_svg/pubspec.yaml
=> chore: Update mocktail to 1.0.4

packages/flame_console/pubspec.yaml
Initial release of flame_console.
=> chore: Release flame_console v0.1.2

packages/flame/benchmark/main.dart, packages/flame/benchmark/render_components_benchmark.dart, packages/flame/benchmark/update_components_benchmark.dart
Add a basic component rendering benchmark.
=> test: Add a basic component rendering benchmark

pubspec.yaml
Currently we need to have a flutter section in the root pubspec.
Tracking it here: https://github.com/dart-lang/pub/issues/4486
=> chore: Add root flutter section to pubspec

.github/workflows/benchmark.yml
Ensure correct permissions for any author on dart_benchmark_action config.
I am not sure if this will actually fix [this issue](https://github.com/flame-engine/flame/pull/3440) but hoping it does. The action just works on mine and @spydon's PRs so hard for me to debug :P
=> test: Ensure correct permissions for any author on dart_benchmark_action config

examples/lib/stories/image/image.dart, packages/flame/lib/src/extensions/color.dart
Previously, .darken(.98) would darken the image by 98%, now it darkens by the inverse by 2%. This restores the original functionality.
=> fix: Darkness increases with higher values

.github/workflows/benchmark.yml
Update dart-benchmark-action to v0.1.14
=> chore: Update dart-benchmark-action to v0.1.14

packages/flame_bloc/pubspec.yaml
Bloc has recently a major version update which doesn't change much. I ran pub upgrade --major-versions.
\-
=> chore(deps): Upgrade bloc dependencies

doc/flame/inputs/pointer_events.md
=> docs: Fix a typo in pointer_events.md

doc/README.md
On https://docs.flame-engine.org/latest/ towards the bottom it says `void onTapUp(TapUpInfo info)`
However, this causes the following error on the latest version of Flame (1.23.0):
```
'Player.onTapUp' ('void Function(TapUpInfo)') isn't a valid override of 'TapCallbacks.onTapUp' ('void Function(TapUpEvent)').dartinvalid_override
tap_callbacks.dart(16, 8): The member being overridden.
```
Changing TapUpInfo to TapUpEvent fixes it.
=> docs: Fix type of the `event` parameter for `onTapUp()`

doc/flame/inputs/other_inputs.md
Fix the link to the gamepads plugin's Github repository.
=> docs: Fix the link to the gamepads plugin's Github repository

examples/lib/stories/camera_and_viewport/follow_component_example.dart, packages/flame/lib/src/components/spawn_component.dart, packages/flame/test/components/spawn_component_test.dart
The `SpawnComponent` accidentally didn't update the range each iteration due to that the `minPeriod` variable wasn't set.
=> fix: SpawnComponent.periodRange should change range each iteration

doc/flame/inputs/tap_events.md
The sentence about the `MultiTapDispatcher` just confuses the user, and its more of an implementation detail, so that part was removed.
=> docs: Clarify long tap config

doc/flame/router.md
=> docs: Re-write sentence about `WorldRoute`

doc/bridge_packages/flame_tiled/flame_tiled.md, doc/bridge_packages/flame_tiled/tiled.md
Update some broken links for flame_tiled, which is now in the monorepo.
=> docs: Update links to flame-tiled to point to monorepo

pubspec.yaml
The links were missing from the last release, this should add them back for the next release.
=> chore: Melos config for linking changelog entries to PRs

packages/flame_test/lib/flame_test.dart, packages/flame_test/lib/src/close_to_matrix4.dart, packages/flame_test/test/close_to_matrix4_test.dart
Add closeToMatrix4 test matcher
=> feat: Add closeToMatrix4 test matcher

packages/flame_3d/lib/src/components/line_3d.dart, packages/flame_3d/test/components/line_3d_test.dart
=> feat: Add Line3D mesh component [flame_3d]

packages/flame_texturepacker/lib/src/texture_packer_atlas.dart
This PR removes the a line where `texture_packer` forces devs to put their atlases under a folder named `/images/`. In Flame, devs can change prefixes of both `AssetCache` and `Images`, but `Future<_TextureAtlasData> _parse()` does not respect this change. This change would make it respect that change.
Simply remove the "/images/" line from any atlas Strings.
=> fix: Remove forced location of the atlas file.

doc/flame/effects.md, doc/flame/examples/lib/anchor_by_effect.dart, doc/flame/examples/lib/anchor_to_effect.dart, doc/flame/examples/lib/color_effect.dart, doc/flame/examples/lib/main.dart, doc/flame/examples/lib/move_along_path_effect.dart, doc/flame/examples/lib/move_by_effect.dart, doc/flame/examples/lib/move_to_effect.dart, doc/flame/examples/lib/opacity_by_effect.dart, doc/flame/examples/lib/opacity_effect_with_target.dart, doc/flame/examples/lib/opacity_to_effect.dart, doc/flame/examples/lib/rotate_around_effect.dart, doc/flame/examples/lib/rotate_by_effect.dart, doc/flame/examples/lib/rotate_to_effect.dart, doc/flame/examples/lib/scale_by_effect.dart, doc/flame/examples/lib/scale_to_effect.dart, doc/flame/examples/lib/size_by_effect.dart, doc/flame/examples/lib/size_to_effect.dart, examples/lib/stories/effects/effects.dart, examples/lib/stories/effects/rotate_around_effect_example.dart, packages/flame/lib/effects.dart, packages/flame/lib/src/effects/rotate_around_effect.dart, packages/flame/test/effects/rotate_around_effect_test.dart
[Screencast from 2025-02-16 23-28-40.webm](https://github.com/user-attachments/assets/b8cc3208-5b03-48d4-b54e-f451e1dec418)
Introduces the `RotateAroundEffect` which rotates your component around a pivot point.
=> feat: Add `RotateAroundEffect`

packages/flame/lib/src/components/core/component.dart
Makes it clear that `onRemove()` can be called several times.
=> docs: Make onRemove() behavior more clear in API doc

packages/flame_audio/pubspec.yaml
Update audioplayers to benefit from latest setAudioContext fix
=> chore: Update audioplayers to benefit from latest setAudioContext fix

packages/flame_texturepacker/lib/src/texture_packer_atlas.dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Unable to load asset: "assets/images/!/atlasMap.atlas".
Fixes:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Unable to load asset: "assets/images/!/atlasMap.atlas".
The asset does not exist or has empty data.
```
=> fix: Unhandled Exception: Unable to load asset. Introduced on Texturepacker 4.16

.github/.cspell/words_dictionary.txt, examples/lib/stories/experimental/experimental.dart, examples/lib/stories/experimental/layout_component_example.dart, packages/flame/lib/experimental.dart, packages/flame/lib/src/experimental/column_component.dart, packages/flame/lib/src/experimental/layout_component.dart, packages/flame/lib/src/experimental/row_component.dart, packages/flame/test/experimental/layout_component_test.dart
Laying out of game UI elements in a column or a row is fairly common, such as for menus, or even HUD buttons.
This PR attempts to create basic layout components that fulfill this purpose.
Closes #1944
=> feat: Layout Components

.github/.cspell/people_usernames.txt, packages/flame_audio/lib/flame_audio.dart
Take advantage of the changes in https://github.com/bluefireteam/audioplayers/pull/1890
=> refactor(flame_audio): Set AudioContext for AudioPool only

examples/lib/stories/experimental/layout_component_example.dart, packages/flame/lib/src/experimental/column_component.dart, packages/flame/lib/src/experimental/layout_component.dart, packages/flame/lib/src/experimental/row_component.dart, packages/flame/test/experimental/layout_component_test.dart, packages/flame/test/experimental/layout_component_test_helpers.dart
Implements shrink wrapping of the LayoutComponents, such that instead of a top-down influence of size, the LayoutComponent's size is dictated by the sizes of the children.
Closes #3509
=> feat: Layout shrinkwrap

packages/flame_texturepacker/lib/flame_texturepacker.dart, packages/flame_texturepacker/lib/src/texture_packer_atlas.dart, packages/flame_texturepacker/test/flame_texturepacker_test.dart
The loading of images and assets from texture packer didn't default to the game caches, but to the static ones.
Found when investigating #3521 
=> fix: Use game's asset cache for texture packer

examples/lib/stories/router/router_world_example.dart, examples/web/index.html, packages/flame/lib/src/components/router/router_component.dart
To get the `WorldRoute` and `world` to work well with other components, the `RouterComponent` needs to be on top.
This also fixes a small deprecation in the index.html file for the examples.
Closes: #3518 
=> fix: RouterComponent should be on top

.github/workflows/gh-pages.yml
Since flame_spine is using ffi we can't compile the examples to wasm.
=> chore: Don't compile examples to wasm

packages/flame/lib/events.dart, packages/flame/lib/src/events/component_mixins/pointer_move_callbacks.dart, packages/flame/lib/src/events/flame_game_mixins/double_tap_dispatcher.dart, packages/flame/lib/src/events/flame_game_mixins/multi_drag_dispatcher.dart, packages/flame/lib/src/events/flame_game_mixins/multi_tap_dispatcher.dart, packages/flame/lib/src/events/flame_game_mixins/pointer_move_dispatcher.dart, packages/flame/test/events/component_mixins/double_tap_callbacks_test.dart, packages/flame/test/events/component_mixins/drag_callbacks_test.dart, packages/flame/test/events/component_mixins/hover_callbacks_test.dart, packages/flame/test/events/component_mixins/ignore_events_test.dart, packages/flame/test/events/component_mixins/pointer_move_callbacks_test.dart, packages/flame/test/events/component_mixins/tap_callbacks_test.dart, packages/flame/test/game/flame_game_test.dart, packages/flame_forge2d/test/body_component_test.dart
It is quite handy to inject your own dispatcher if you want to override how events are handled, so this PR exposes the previously internal dispatcher classes.
=> fix: Expose event dispatcher classes

doc/flame/effects.md, examples/lib/stories/effects/effects.dart, examples/lib/stories/effects/function_effect_example.dart, packages/flame/lib/effects.dart, packages/flame/lib/src/effects/function_effect.dart, packages/flame/test/effects/function_effect_test.dart
The `FunctionEffect` is super simple, but very powerful.
It makes it possible to run any function over time as an effect without having to create a new effect.
This is very useful when for example doing state changes over time.
=> feat: The `FunctionEffect`, run any function as an `Effect`

doc/tutorials/klondike/step4.md
Update event.delta to event.localDelta in step 4 of the klondike tutorial, since the former is being deprecated
=> docs: Update event.delta to event.localDelta

packages/flame/lib/src/events/messages/displacement_event.dart, packages/flame_forge2d/lib/forge2d_game.dart, packages/flame_isolate/lib/flame_isolate.dart, packages/flame_texturepacker/lib/flame_texturepacker.dart
This removes deprecations that should have been removed a long time ago.
=> fix: Remove outdated deprecations

packages/flame_rive/example/.metadata, packages/flame_rive/example/pubspec.yaml, packages/flame_rive/pubspec.yaml, packages/flame_rive/test/flame_rive_test.dart
Since https://github.com/rive-app/rive-flutter/issues/354 doesn't seem to be getting solved any time soon I suggest that we skip the tests for now and bump the Rive version.
Closes #3543 
=> fix: Bump Rive version and skip tests

packages/flame/lib/src/components/isometric_tile_map_component.dart, packages/flame_3d/bin/build_shaders.dart, packages/flame_jenny/jenny/lib/src/function_storage.dart, packages/flame_jenny/jenny/lib/src/parse/parse.dart, packages/flame_jenny/jenny/lib/src/structure/commands/if_command.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/functions/bool.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/functions/number.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/functions/plural.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/functions/random_range.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/functions/string.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/_common.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/and.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/divide.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/greater_or_equal.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/greater_than.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/less_or_equal.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/less_than.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/modulo.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/multiply.dart, packages/flame_jenny/jenny/lib/src/structure/expressions/operators/xor.dart, packages/flame_lint/pubspec.yaml
This bumps to the new lint version, and fixes all issues.
It's a feat due to the implicit changes to flame_lint.
Jenny has to be manually versioned though, since it isn't a feat from the jenny perspective.
=> feat: Bump to new lint package

.github/workflows/title-validation.yml
This enables us to start PR titles with other characters than capital ones.
=> chore: Loosen up constraints on PR title

doc/flame/other/widgets.md, packages/flame/lib/src/widgets/sprite_button.dart
This adds support for the disabled state for the `SpriteButton`, just like with Flutter buttons the disabled state is activated by setting `onPressed` to `null`. When disabled the button won't change sprites when pressed, and if the disabled sprite is provided that will be shown instead.
=> feat: Support for disabled state for `SpriteButton`

doc/flame/components.md, doc/flame/inputs/other_inputs.md, examples/games/rogue_shooter/lib/components/bullet_component.dart, examples/games/rogue_shooter/lib/components/enemy_creator.dart, examples/games/rogue_shooter/lib/components/explosion_component.dart, examples/games/rogue_shooter/lib/components/player_component.dart, examples/games/rogue_shooter/lib/components/star_background_creator.dart, examples/games/rogue_shooter/lib/components/star_component.dart, examples/lib/stories/camera_and_viewport/follow_component_example.dart, examples/lib/stories/collision_detection/collidable_animation_example.dart, examples/lib/stories/components/composability_example.dart, examples/lib/stories/input/joystick_player.dart, packages/flame/lib/components.dart, packages/flame/lib/src/components/core/component.dart, packages/flame/lib/src/components/mixins/has_game_ref.dart, packages/flame/test/components/mixins/has_game_ref_test.dart, packages/flame/test/game/flame_game_test.dart
This deprecates `HasGameRef` and suggests users to use `HasGameReference` instead.
=> fix: Deprecate `HasGameRef` in favor of `HasGameReference`

packages/flame/lib/src/geometry/line_segment.dart, packages/flame/test/geometry/line_segment_test.dart
Add helper methods on LineSegment (translate, inflate, deflate, spread)
=> feat: Add helper methods on LineSegment (translate, inflate, deflate, spread)

doc/bridge_packages/flame_console/flame_console.md
Fix class name in the docs of flame console.
=> fix: Class name at flame_console.md

packages/flame/lib/src/components/core/component.dart, packages/flame/lib/src/components/core/component_tree_root.dart, packages/flame/test/components/component_test.dart
After #3554 we can reflect the priority change directly on the component.
=> fix: Priority change should be reflected directly

packages/flame/lib/src/device.dart
Replaces `dart:io`'s platform checking logic with `defaultTargetPlatform` and `TargetPlatform`
closes #3566 
=> refactor: Replace dart:io usage with defaultTargetPlatform

packages/flame_texturepacker/lib/src/texture_packer_atlas.dart, packages/flame_texturepacker/pubspec.yaml
Replaces `dart:io`'s `File` usage with `cross_file`'s `XFile` to support the package on web platform.
closes #3568
=> feat: Use `XFile` to support web platform

doc/flame/other/performance.md
Fix a typo in the performance, while preserving the original intention
=> docs: Fix typo in performance.md

doc/tutorials/space_shooter/step_2.md
Replace deprecated `HasGameRef` with `HasGameReference` in Space Shooting tutorial documentation page.
Closes #3571 
=> docs: Update outdated code in Space Shooter

.github/.cspell/gamedev_dictionary.txt, doc/flame/examples/lib/post_process.dart, examples/games/crystal_ball/lib/src/game/post_processes/ball_glow.dart, examples/games/crystal_ball/lib/src/game/post_processes/firefly.dart, examples/games/crystal_ball/lib/src/game/post_processes/foreground_fog.dart, examples/games/crystal_ball/lib/src/game/post_processes/water.dart, examples/games/crystal_ball/pubspec.yaml, packages/flame/lib/extensions.dart, packages/flame/lib/post_process.dart, packages/flame/lib/src/extensions/fragment_shader.dart
This adds the fragment shader extension from flutter_shaders.
It allows for setting uniforms in a more convenient way.
=> fix: Add fragment shader extension from flutter_shaders

doc/flame/overlays.md, packages/flame/lib/src/game/overlay_manager.dart, packages/flame/test/game/overlays_manager_test.dart
=> feat: Add method to toggle overlays

packages/flame/test/camera/behaviors/follow_behavior_test.dart
Fixes the intermittently failing test: https://github.com/flame-engine/flame/actions/runs/14451208585/job/40524118828#step:5:492
This just adds the tolerances together for both the target and pursuer.
Related PR: https://github.com/flame-engine/flame/pull/3515
=> test: Increase tolerance on camera follow behavior test to allow for difference on both sides.

packages/flame_console/pubspec.yaml
Bumps terminui dependency on flame_console.
=> chore: Bumping terminui on flame_console

doc/_sphinx/theme/layout.html
Currently chrome sometimes crashes on some of our docs pages to to that we initialize too many webgl contexts, this script should solve that.
https://github.com/greggman/virtual-webgl?tab=readme-ov-file#how-to-use
=> docs: Use virtual webgl

doc/bridge_packages/flame_audio/audio_pool.md
Improved `AudioPool` documentation with description and usage examples.
=> docs: Improved AudioPool documentation with detailed usage examples

examples/games/crystal_ball/lib/src/game/game.dart
Due to a race (I'm guessing) sometimes the crystal ball game will try to access the game after it has been changed to another example, thus making the examples app crash since the crystal ball game has the `SingleGameInstance` mixin on the game.
Closes #3597 
=> docs: Remove `SingleGameInstance` mixin from crystal ball example

doc/flame/flame.md, doc/flame/game.md, doc/flame/inputs/hardware_keyboard_detector.md, doc/flame/inputs/inputs.md, doc/flame/layout/column_component.md, doc/flame/layout/row_component.md, packages/flame/lib/src/experimental/column_component.dart, packages/flame/lib/src/experimental/row_component.dart
This fixes some structural issues with the docs, like order and missing sections.
It also adds the docs for the `ColumnComponent` and `RowComponent`.
=> docs: Update structure and add RowComponent + ColumnComponent docs

examples/assets/yarn/command_lifecycle.yarn, examples/lib/stories/bridge_libraries/flame_jenny/components/command_lifecycle_dialogue_controller.dart, examples/lib/stories/bridge_libraries/flame_jenny/jenny.dart, examples/lib/stories/bridge_libraries/flame_jenny/jenny_command_lifecycle_example.dart, packages/flame_jenny/jenny/lib/src/dialogue_runner.dart, packages/flame_jenny/jenny/lib/src/dialogue_view.dart, packages/flame_jenny/jenny/test/dialogue_view_test.dart
Add onCommandFinish lifecycle method to DialogueView
Closes #3596
=> feat(Jenny): Add onCommandFinish lifecycle method to DialogueView

packages/flame/lib/src/post_process/post_process.dart
=> fix: Dispose picture is postprocess 

doc/flame/post_processing.md, examples/games/crystal_ball/lib/src/game/post_processes/ball_glow.dart, packages/flame/lib/src/post_process/post_process_component.dart, packages/flame/test/components/post_process_component_test.dart, packages/flame_tiled/lib/src/tile_atlas.dart
The `PostProcessComponent` now updates its size if the children list changes.
This only applies if it doesn't have an explicit size.
=> fix: PostProcessComponent should size dynamically

packages/flame/lib/src/geometry/line_segment.dart, packages/flame/lib/src/geometry/shape_intersections.dart, packages/flame/test/collisions/collision_detection_test.dart, packages/flame/test/geometry/line_segment_test.dart
Since we moved to 32-bit Vector2 we need to make the epsilon larger for line segment intersections.
Closes: #3587 
=> fix: Angled line intersections should work with 32-bit vectors

.github/.cspell/gamedev_dictionary.txt, doc/flame/rendering/images.md, packages/flame/lib/components.dart, packages/flame/lib/src/components/raster_sprite_component.dart, packages/flame/lib/src/components/sprite_component.dart, packages/flame/lib/src/sprite.dart, packages/flame/lib/src/widgets/sprite_widget.dart, packages/flame/test/raster_sprite_test.dart, packages/flame/test/sprite_test.dart, packages/flame_texturepacker/lib/src/texture_packer_sprite.dart
Adds features to easily help users to get rid of "ghost lines" and "texture leak artifacts":
- Bleed support on sprites
- Ability to raster Sprite into memory.
=> feat: Implement measure to fix ghost lines and graphical artifacts in Sprites

packages/flame/test/camera/camera_component_test.dart, packages/flame/test/camera/viewports/circular_viewport_test.dart, packages/flame/test/camera/viewports/fixed_aspect_ratio_viewport_test.dart, packages/flame/test/camera/viewports/fixed_size_viewport_test.dart, packages/flame/test/components/advanced_button_component_test.dart, packages/flame/test/components/clip_component_test.dart, packages/flame/test/components/mixins/has_decorator_test.dart, packages/flame/test/components/mixins/has_visibility_test.dart, packages/flame/test/components/mixins/snapshot_test.dart, packages/flame/test/components/route_test.dart, packages/flame/test/components/text_box_component_test.dart, packages/flame/test/layout/align_component_test.dart, packages/flame/test/nine_tile_box_test.dart, packages/flame/test/raster_sprite_test.dart, packages/flame/test/rendering/paint_decorator_test.dart, packages/flame/test/rendering/rotate3d_decorator_test.dart, packages/flame/test/rendering/shadow3d_decorator_test.dart, packages/flame/test/sprite_batch_test.dart, packages/flame/test/sprite_test.dart, packages/flame/test/text/sprite_font_renderer_test.dart, packages/flame/test/text/text_layouting_test.dart, packages/flame_sprite_fusion/test/sprite_fusion_tilemap_component_test.dart, packages/flame_test/lib/src/test_golden.dart, packages/flame_test/test/debug_text_formatter_test.dart, packages/flame_test/test/golden_test.dart
Sometimes one needs to use the `WidgetTester` to prepare the tests, which today isn't possible.
With this PR we pass the tester instance along in the prepare function.
Add the tester argument to your prepare functions.
Before:
```dart
testGolden(
'Rendering effect can be removed',
(game) async {
```
After:
```dart
testGolden(
'Rendering effect can be removed',
(game, tester) async {
```
=> feat!: Pass `WidgetTester` for `testGolden` prepare function

packages/flame/lib/src/game/game_widget/game_widget.dart, packages/flame/lib/src/widgets/animation_widget.dart, packages/flame/lib/src/widgets/nine_tile_box.dart, packages/flame/lib/src/widgets/sprite_widget.dart
This fixes so that `super.onDispose` is called last and checks `mounted` before `setState`.
(Reported by incendial)
=> fix: Call `super.onDispose` last and check `mounted` before `setState`

doc/flame/components.md, packages/flame/lib/src/components/spawn_component.dart, packages/flame/test/components/spawn_component_test.dart
This adds the `target` argument to `SpawnComponent` which will control which parent that the spawned components will have.
Partially fixes: https://github.com/flame-engine/flame/issues/3632
=> feat: Add `target` argument to `SpawnComponent`

packages/flame/lib/src/experimental/column_component.dart, packages/flame/lib/src/experimental/layout_component.dart, packages/flame/lib/src/experimental/row_component.dart, packages/flame/lib/src/layout/align_component.dart
The `Align`,`Row`, `Column` and `Layout` components where missing the `priority` attribute in their constructors.
=> feat: Adding priority to layout components

packages/flame/lib/src/components/position_component.dart, packages/flame/lib/src/geometry/polygon_component.dart, packages/flame/test/collisions/collision_detection_test.dart, packages/flame/test/extensions/vector2_test.dart
We broke vertically flipped hitboxes in #3629, this fixes it up so that it works like it used to.
=> fix: Hitboxes with vertically flipped ancestor should not reflect angle for vertices

packages/flame/lib/src/components/sprite_batch_component.dart
Adds children and priority to SpriteBatchComponent. Priority is absolutely needed to ensure proper rendering order.
=> feat: Add children and priority to SpriteBatchComponent

examples/lib/stories/bridge_libraries/flame_jenny/jenny_command_lifecycle_example.dart, examples/lib/stories/experimental/layout_component_example.dart, packages/flame/lib/src/experimental/column_component.dart, packages/flame/lib/src/experimental/layout_component.dart, packages/flame/lib/src/experimental/row_component.dart, packages/flame/test/experimental/layout_component_test.dart
Removes the `shrinkWrap` property from `LayoutComponent` and its subclasses, and make the `size` setter nullable. Setting the `size` to null causes the `LayoutComponent` to behave as if it were `shrinkWrap`ed.
In all cases with `shrinkWrap=true`, simply remove it and ensure `size` is either set to null, or not set at all.
Closes #3657
=> refactor!: Remove shrinkwrap

packages/flame_3d/example/lib/components/player.dart
Add ability to run on flame_3d example
=> feat: Add ability to run on flame_3d example

doc/flame/effects/effects.md
In the last PR I forgot to create the index for the effects.
=> docs: Fix effects index

doc/flame/effects/anchor_effects.md, doc/flame/effects/color_effects.md, doc/flame/effects/effects.md, doc/flame/effects/move_effects.md, doc/flame/effects/remove_effect.md, doc/flame/effects/rotate_effects.md, doc/flame/effects/scale_effects.md, doc/flame/effects/sequence_effect.md, doc/flame/effects/size_effects.md
The examples source should be relative to the sphinx directory, not the markdown file itself.
=> docs: Fix effects examples

packages/flame_3d/lib/src/resources/mesh.dart, packages/flame_3d/lib/src/resources/mesh/cone_mesh.dart, packages/flame_3d/test/mesh/cone_mesh_test.dart
=> feat: Introduce cone mesh

packages/flame_3d/lib/src/parser/obj_parser.dart
Cleanup and make OBJ parser more resilient.
In particular, this makes it work with simpler OBJ files that have no texels, no normals and/or no materials.
=> fix: Cleanup and make OBJ parser more resilient

.github/.cspell/flame_dictionary.txt, doc/flame/platforms.md
Newer versions of Flutter (3.27+ according to the last link below) default to the CanvasKit renderer, and following the instructions in that documentation section to pass the `--web-renderer` results in the following error (on Flame 1.32 & Flutter 3.35.2 which are the latest versions as of this writing):
```
$ flutter build web --release --web-renderer canvaskit
Could not find an option named "--web-renderer".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```
Since this section only talked about this quirk I think it's better to remove it altogether. If there's a reason to keep it and  for users of older versions of Flutter, a note on this can be added instead.
Addresses https://github.com/flame-engine/flame/issues/3706
See Also:
- …
=> docs: Remove the "Flame web" section in platforms.md

packages/flame_forge2d/lib/body_component.dart, packages/flame_forge2d/test/body_component_test.dart
If the world is changed the `BodyComponent` tries to use the new world instead of the one that it is attached to, this PR makes sure that we use the correct world in `onRemove`.
Fixes #3712 
=> fix: Use correct `Forge2DWorld` in `onRemove`

packages/flame_forge2d/pubspec.yaml
Simply bumps forge2d to v0.14.2
=> chore: Bump forge2d to v0.14.2

.github/workflows/cicd.yml, packages/flame_3d/example/lib/commands/commands.dart, packages/flame_3d/example/lib/commands/destroy_command.dart, packages/flame_3d/example/lib/commands/reset_command.dart, packages/flame_3d/example/lib/commands/setup_command.dart, packages/flame_3d/example/lib/components/player.dart, packages/flame_3d/example/lib/components/simple_hud.dart, packages/flame_3d/example/lib/example_camera_3d.dart, packages/flame_3d/example/lib/example_game_3d.dart, packages/flame_3d/example/lib/main.dart, packages/flame_3d/example/lib/scenarios/boxes_scenario.dart, packages/flame_3d/example/lib/scenarios/colors_scenario.dart, packages/flame_3d/example/lib/scenarios/game_scenario.dart, packages/flame_3d/example/lib/scenarios/models_scenario.dart, packages/flame_3d/example/pubspec.yaml, pubspec.yaml
* The root package should be named `_` in pub workspaces that doesn't have an actual app or package in the root.
* Melos needs to be updated to support this.
* The flame_3d example should be named flame_3d_example to follow the convention.
- [x ] I have updated/added relevant examples in `examples` or `docs`.
=> chore: Correctly name packages

CONTRIBUTING.md
Simplify the CONTRIBUTING file by suggesting the usage of the script to run cspell.
=> docs: Simplify the CONTRIBUTING file by suggesting the usage of the script to run cspell

.github/workflows/title-validation.yml
Update version of the `amannn/action-semantic-pull-request` to the latest, v6.
=> ci: Update version of the amannn/action-semantic-pull-request to v6

CONTRIBUTING.md
Enhance language on `CONTRIBUTING.md`
=> docs: Enhance language on CONTRIBUTING.md

packages/flame/lib/src/camera/camera_component.dart, packages/flame/lib/src/components/core/component_key.dart
This prints the hash in `ComponentKey.toString` so that users can differentiate between keys when debugging.
Closes #3457
=> fix: Unique `ComponentKey` toString

doc/bridge_packages/bridge_packages.md, doc/bridge_packages/flame_3d/basic_concepts.md, doc/bridge_packages/flame_3d/flame_3d.md, doc/bridge_packages/flame_3d/getting_started.md, doc/flame/diagrams/flame_3d_components.md
Start documentation for flame_3d.
This is just a barebones start - we can expand as we go. Notably this adds a diagram for the hierarchy.
=> docs: Start documentation for flame_3d
